### ISSUE TITLE
How to scrap sites which requires login?

### ISSUE THREAD

**Issue by ekanna** [cheeriojs/cheerio#10]
Hi Matt Mueller,

How to scrap sites which requires login?

Can you post some example code todo this?

Thanks

Koti

**Comment by yortrosal** [comment]
Try using [osmosis ](https://github.com/rchipka/node-osmosis) module. It has login feature. But is limited to the given generic login selector. But it should work in most cases. You can do post request if you want. 

Another option you have is to use a headless browser. Try using [CasperJs ](http://casperjs.org/)or PhantomJs. It lets you manipulate the DOM and input some fields.

**Comment by oseisaac** [comment]
any luck?

**Comment by adrian110288** [comment]
@oseisaac there are a few options mentioned here https://stackoverflow.com/questions/8726079/how-can-i-scrape-sites-that-require-authentication-using-node-js. Hope it helps
