### ISSUE TITLE
How to select <?xml-stylesheet type="text/xsl" href="my.xsl"?>

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [cheeriojs/cheerio#1005]
Hello. I have found a lot of examples of parsing tags of HTML and XML. I really  can't find the way to select this this description of XSL transform and change it.

**Comment by DianeLooney** [comment]
Almost all of the functions in the cheerio api have a check to make sure it only considers tag elements, so you if you want to use cheerio to modify these elements you'll need to navigate to their parent, and then find the directive directly from the parent's children array.

For example:

```js
var cheerio = require('cheerio');
var data = `
<?xml-stylesheet type="text/xsl" href="my.xsl"?>
<xml></xml>
`;
var $ = cheerio.load(data);
var preamble = $.root()[0].children.filter(x=>x.type==='directive');
console.log(preamble[0].data);
```

**Comment by SuperMasterBlasterLaser** [comment]
@DianeLooney  That is great. I think this should be added to README.
