### ISSUE TITLE
tbody is not recognised

### ISSUE THREAD

**Issue by balazserdos** [cheeriojs/cheerio#1010]
The following line gives an empty string back to me:
`$("table table tbody tr:not(:first-child)").text();`

but this one gives the expected result:
`$("table table tr:not(:first-child)").text();`

**Comment by Vladislao** [comment]
I think element *\<tbody\>* is missing in the initial markup, but automatically included in the DOM when you try to browse code. You can read more about it [here](http://stackoverflow.com/questions/938083/why-do-browsers-insert-tbody-element-into-table-elements)

**Comment by Vladislao** [comment]
Check document source (CTRL+U in chrome)

**Comment by balazserdos** [comment]
yep, you are right. I didn't notice it. Thank you :)

**Comment by fb55** [comment]
Fixed with rc0
