### ISSUE TITLE
Cheer.io doesn't seem to scrape/work

### ISSUE THREAD

**Issue by siriate** [cheeriojs/cheerio#1012]
```
var request = require('request'),
	cheerio = require('cheerio'),
	fs = require('fs'),
	urls = [];

request('https://www.twitch.tv/directory/game/Counter-Strike:%20Global%20Offensive/clips', function(err,resp,body) {
	if(!err && resp.statusCode == 200) {
		var $ = cheerio.load(body);
		$('h3.cn-card__title a', 'ember2812').each(function() {
			var url = $(this).attr('href');
    		urls.push(url);
		});

  		console.log(urls);
 	}
});﻿
```

Can someone fix or tell me why this code doesn't work and just leaves urls array empty?

**Comment by jugglinmike** [comment]
It looks like you are trying to scrape content that is generated dynamically
with JavaScript. Cheerio is an HTML traversal/manipulation library; it does not
render documents, fetch external resources, or execute JavaScript. In your
example, if the variable named `body` does not contain the information you are
looking for, then you won't be able to use Cheerio to find it. If that's the
case, you might consider using projects like PhantomJS or JSDom.
