### ISSUE TITLE
Cannot install cheerio

### ISSUE THREAD

**Issue by ModestBouse5** [cheeriojs/cheerio#1014]
Hi, I try to npm cheerio, but I keep running into errors.

This is the terminal output below:

Rickys-Air:~ Ricky$ npm install cheerio
npm WARN checkPermissions Missing write access to /Users/Ricky/node_modules
/Users/Ricky
└─┬ cheerio@0.22.0 
  ├─┬ css-select@1.2.0 
  │ ├── boolbase@1.0.0 
  │ ├── css-what@2.1.0 
  │ └─┬ nth-check@1.0.1 
  │   └── boolbase@1.0.0  deduped
  ├── lodash.assignin@4.2.0 
  ├── lodash.bind@4.2.1 
  ├── lodash.defaults@4.2.0 
  ├── lodash.filter@4.6.0 
  ├── lodash.flatten@4.4.0 
  ├── lodash.foreach@4.5.0 
  ├── lodash.map@4.6.0 
  ├── lodash.merge@4.6.0 
  ├── lodash.pick@4.4.0 
  ├── lodash.reduce@4.6.0 
  ├── lodash.reject@4.6.0 
  └── lodash.some@4.6.0 

npm WARN enoent ENOENT: no such file or directory, open '/Users/Ricky/package.json'
npm WARN Ricky No description
npm WARN Ricky No repository field.
npm WARN Ricky No README data
npm WARN Ricky No license field.
npm ERR! path /Users/Ricky/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/Ricky/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/Users/Ricky/node_modules'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/Ricky/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Ricky/.npm/_logs/2017-04-30T07_47_25_790Z-debug.log
Rickys-Air:~ Ricky$ 

I would appreciate any assistance on the matter

**Comment by jugglinmike** [comment]
This is more of a support request for npm, but I'm happy to help troubleshoot.

It looks like your user account does not own the `node_modules` directory. I
think this should fix it:

    sudo chown -R Rickey /Users/Ricky/node_modules

This assumes your operating system is OSX/macOS, your current user account is
named "Ricky", and that you have administrative access.
