### ISSUE TITLE
nth-child counts unselected blocks

### ISSUE THREAD

**Issue by CoryGH** [cheeriojs/cheerio#1017]
I'm attempting to parse the following code:

```
<list id="c" view="vw_project_content" where="`project` = %%2%%">
    <item>
        <b>$$title$$</b><br />
        $$message$$
        <br />
    </item>
</list>
<br />
Discussion:
<list id="p" view="vw_project_posts" where="`project` = %%2%%" limit="100">
    <item>
        <b>$$poster_id$$</b><br />
        $$message$$
        <br />
    </item>
</list>
```

via `list:nth-child(' + index.toString() + ')` - which works great, except for the `<br />` tag between the two `list` blocks, which seems to increment the index by 1 in an undetectable manner.  For instance, selecting the 1st child will return the `list` with id `c` whereas selecting the 2nd child will return the `br` block and selecting the 3rd child will return the `list` with id `p`.  Is there any way around this issue?

**Comment by fb55** [comment]
Try `nth-of-type`
