### ISSUE TITLE
cannot install cheerio successfully

### ISSUE THREAD

**Issue by thelaurelyy** [cheeriojs/cheerio#1022]
well,I've tried several methods ,but I still cannot install cheerio successfully.  the latest warn info is that :
    npm WARN http@1.0.0 No description
    npm WARN http@1.0.0 No repository field.
I don't know how to solve this question ,so is there anyone who can help me ?

**Comment by DianeLooney** [comment]
Those npm warnings look like you are missing a package.json, or that your package.json doesn't have those fields set in it. They shouldn't impact npm's ability to install modules, but that's what those errors mean.

Whats the full output of `npm install cheerio`, then `node`, and `require('cheerio')`?

**Comment by luanmuniz** [comment]
None of the `cheerio` dependences use this `http` module.
More weird is that the `http@1.0.0` doesn't even exist in npm

**Comment by thelaurelyy** [comment]
@DianeLooney

**Comment by thelaurelyy** [comment]
@DianeLooney   Thank you very much for your answer .This helped me to modify my package.json and the full output of the instructions is as follows :
![image](https://cloud.githubusercontent.com/assets/27723220/26516873/4a7019ae-42c0-11e7-982f-8c30318597d0.png)

**Comment by thelaurelyy** [comment]
@DianeLooney  and it still has no response when I run the crawler program,just like this:
![image](https://cloud.githubusercontent.com/assets/27723220/26517009/8c0d0668-42c2-11e7-8110-b7c2024e8db8.png)

**Comment by thelaurelyy** [comment]
@DianeLooney  and it still has no response when I run the crawler program,just like this:
![image](https://cloud.githubusercontent.com/assets/27723220/26517028/e86503b6-42c2-11e7-8986-e425e556bee4.png)

**Comment by DianeLooney** [comment]
Hmm

Well since you got a function back from `require('cheerio')` I'd be somewhat surprised to find out this was a problem with cheerio instead of a problem with the code using cheerio. How are you using it,? Have you used it on a smaller scale before?

**Comment by thelaurelyy** [comment]
@DianeLooney  No~ in fact ,this is the first time I use cheerio and the test program is just a small crawler one.  this is the code url : https://codepen.io/laurelfreecodecamp/pen/OmGGZw?editors=1010

**Comment by DianeLooney** [comment]
Oh friend, I think you just needed a fresh set of eyes. =)

I suggest changing `var $ = cheerio.load('html');` to `var $ = cheerio.load(html);`

**Comment by thelaurelyy** [comment]
@DianeLooney    (˘•ω•˘) God, I've made such a stupid mistake and your suggestion solved my problem very well.  (＾▽＾)  Thank you very much for your help.

**Comment by jugglinmike** [comment]
Glad we got to the bottom of that :)
