### ISSUE TITLE
Forcibly wrapped in <html></html>

### ISSUE THREAD

**Issue by Tsuguya** [cheeriojs/cheerio#1024]
Hi, I tried 1.0.0-rc.1.  
Not attached tag `<html><head></head><body></body></html>` is attached.  
Is this the default?

```js
const cheerio = require('cheerio')
const $ = cheerio.load('<h2 class="title">Hello world</h2>')

$('h2.title').text('Hello there!')
$('h2').addClass('welcome')

$.html()
//=> <h2 class="title welcome">Hello there!</h2>
```

output: `<html><head></head><body><h2 class="title welcome">Hello there!</h2></body></html>`

**Comment by stevenvachon** [comment]
`load()` is the document, which, like a real web browser, would insert such necessary elements. This new version behaves even more like real jQuery.

Try this:
```js
$('body').html()
```

**Comment by Tsuguya** [comment]
thanks.  
It went well.
