### ISSUE TITLE
Question: can we check for repeated attributes within an element.

### ISSUE THREAD

**Issue by pgarciacamou** [cheeriojs/cheerio#1026]
In our projects, HTML elements tend to be very long, e.g.

```
<div class="some-class" id="some-id" data-selectable data-name="some name" data-type="some type" spellcheck="false" contenteditable="true" data-max-length="123" draggable="true" data-hidden="true">some text</div>
```

is there a way to see if an attribute was repeated? e.g. `class` attribute.

```
<div class="some-class" id="some-id" data-selectable data-name="some name" data-type="some type" spellcheck="false" class="another-class" contenteditable="true" data-max-length="123" draggable="true" data-hidden="true">some text</div>
```

**Comment by fb55** [comment]
The first instance will always take precedent, so sadly there is no way to check this.

**Comment by pgarciacamou** [comment]
@fb55 thanks

**Comment by pgarciacamou** [comment]
Just for anyone that is looking into this, I posted a question in stackoverflow and the answer works https://stackoverflow.com/questions/44336016/how-to-check-if-an-element-has-duplicated-attributes-with-cheerio-js

CC: @fb55
