### ISSUE TITLE
Can not select contains with minus (-) operator.

### ISSUE THREAD

**Issue by chen86860** [cheeriojs/cheerio#1028]
When I using cheerio to select a span which class name contain with `-`,but it not work?
```
var $ = cheerio.load(data)
 var viewsCount = $('span[class="views-count"]').text()
```
Does anyone know how to fix? (⊙ˍ⊙)

**Comment by fb55** [comment]
Are there other class names on the element as well? You might want to use the `.classname` selector in that case (`span.views-count` in this case). Another option would be to use `[class~="views-count"]`, which is semantically equivalent.
