### ISSUE TITLE
New release with empty attribute fix?

### ISSUE THREAD

**Issue by arthurevans** [cheeriojs/cheerio#1032]
The issue reported in #702 still exists in the current release, although the bug is closed. There's a fix in the master branch of dom-serializer, but it hasn't been published to npm so cheerio doesn't get the fix.

It looks like there's a 1.0 in the offing—any chance to fix this issue?

Thanks!

**Comment by fb55** [comment]
Have you tried whether this still is an issue with the current rc?

**Comment by arthurevans** [comment]
@fb55 Sorry for the slow response, I wanted to make sure I had tested this correctly.

Yes, this is still an issue with the current RC. I have a minimal repro that just uses gulp-highlight, cheerio@1.0.0-rc.1, and their dependencies. I can upload that if you'd like.

It appears that 1.0.0-rc.1 doesn't add the `=""` for a certain list of whitelisted attributes, but it does for arbitrary attributes. For example, given:

```
  <input disabled>
  <div starred>Hello!</div>
```

The output is:

```
  <input disabled>
  <div starred="">Hello!</div>
```

**Comment by arthurevans** [comment]
Here's the minimal reproduction case, requiring only cheerio:

```
const cheerio = require('cheerio')
const $ = cheerio.load('<input disabled><div starred>Hello!</div>');
console.log($.html())
```

**Comment by arthurevans** [comment]
Verified that this same code produces the correct output when I use the master branch of dom-serializer instead of the current stable release, 0.1.0.

**Comment by arthurevans** [comment]
@fb55 Tested against 1.0.0-rc.2, this is still an issue, minimal repro as reported above (https://github.com/cheeriojs/cheerio/issues/1032#issuecomment-309836862). 

Works with `dom-serializer` master, but the fix has never been released on npm. Any chance of an updated `dom-serializer`?

**Comment by inikulin** [comment]
What's the difference? From HTML grammar standpoint `starred` is just a shortcut for `starred=""`.

**Comment by borislemke** [comment]
@inikulin this could save a lot in file size when having many empty attributes. This is crucial for me as I'm building a CMS.

**Comment by inikulin** [comment]
@borislemke Have you made any measurements? I doubt where will be any significant difference with gzip enabled.

**Comment by borislemke** [comment]
@inikulin yes. Our CMS utilises component "hoisting" by appending unique attributes to each section / component, something like `data-host-xyz1` to all elements to avoid style leak between components. In this scenario, this can be critical. We save an additional ~2.4KB per page by manually removing all occurrences of `=""` before serving the rendered page (after minifying). Of course the rendered template is saved to `redis` but at 5000+ page visits a day this can save quite a bit of bandwidth.

**Comment by fb55** [comment]
Cheerio isn't a minifier — if you want minified HTML there are libraries that do that. Modifying cheerio just for the sake of skipping one operation doesn't seem worth it, especially as there are tools that also operate on top of the htmlparser2 dom.

**Comment by arthurevans** [comment]
@fb55 For what it's worth, I'm not interested in minification. I'm trying to do build-time code highlighting using gulp-highlight, which uses cheerio internally. And this transforms the output so it doesn't match our code style.

Given that empty quotes or no empty quotes is a style choice, it would be nice if Don-serializer at least offered the option to serialize without quotes. And based on the comments on the original issue, I am not alone in wanting it.

**Comment by mankins** [comment]
In case anyone wants a temporary fix for this until npm is updated, I forked and made the modifications in package.json: https://github.com/mankins/cheerio

**Comment by fb55** [comment]
This should be resolved with the latest release.

**Comment by dpw1** [comment]
Any updates on this?

**Comment by 5saviahv** [comment]
It should be fixed for now, all attributes are in form `...=""` and it is according to spec.

**Comment by dpw1** [comment]
> It should be fixed for now, all attributes are in form `...=""` and it is according to spec.

Hi, thank you for your reply. On my end it does not seem to be fixed (currently on cheerio 1.0.0-rc.5). All of my data-attributes used are receiving a ="" at the end. 

input:

`<div data-info></div>`

output:

`<div data-info=""></div>`

I wouldn't like this to happen. Is there anyway I can have control of this? Or, perhaps, can I use some external library to trim those out? Any help is greatly appreciated. 

Thank you yet again!

**Comment by 5saviahv** [comment]
No, not sure, but it is highly dabated matter actually. There are least 10 issues with this matter.

I tried wrote simple serializer for html5 boolean attributes . [Gist](https://gist.github.com/5saviahv/c856bdaaabbc5e0b3562f5658069a673)
It tries target specific attributes, It was not intended for public usage, it was mainly for idea testing.
But maybe it helps

``` js
const cheerio = require('cheerio');
const seri = require('../lib/serializer');

const $ = cheerio.load(html);
const ghtml = seri.render($, { boolAttr: { '*': ['data-info'] } });
```
it is based upon parse5 serializer.

**Comment by virskor** [comment]
THIS BUG STILL EXISTING

**Comment by domino86** [comment]
Guys, to solve this problem modify your html second time  - i.e. -  let result = $.html().replace(/=""/g, '');
