### ISSUE TITLE
Cannot remove elements from a webpage

### ISSUE THREAD

**Issue by lpeppe** [cheeriojs/cheerio#1037]
Hi guys, I'm doing some scraping on a website and I can't manage to get remove() working properly.

Here is my code:

```
app.get('/page', function(req, res) {
  request(req.query.link, function(error, response, body) {
    console.log('error:', error); // Print the error if one occurred
    console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
    var cheerio = require('cheerio');
    $ = cheerio.load(body);
    res.send($("div#block-system-main div.region-inner.clearfix").remove("h2.field-label").html());
  });
});
```

The result I get is the same whether or not I omit the remove("h2.field-label") call (the h2 element is always present on the page).

Just for reference, this is the page I'm working on:

http://www.quattrocalici.it/denominazioni-agroalimentari/pomodoro-di-san-marzano-dell-agro-sarnese-nocerino-dop

What I'm doing wrong?

**Comment by Dreamiko** [comment]
`$('h2.field-label').remove()` - This would work for you.

I'm guessing it has something to do with the selectors name (remove function can't handle space?)

**Comment by lpeppe** [comment]
thanks a lot man, it works!
