### ISSUE TITLE
has not return a Boolean

### ISSUE THREAD

**Issue by maicss** [cheeriojs/cheerio#1038]
```
// some very old HTML
let text = `
	<tr class="tr3 t_one tac">
	<td><a title="ll" href="ll" target="_blank">ll</a></td>
	<td class="tal" style="padding-left:8px" id=""> 

		↑13

	

	<h3><a href="ll" target="_blank" id=""><b><font color=blue>ll</font></b></a></h3>  

	

	</td>
	<td><a href="ll" class="bl">ll</a><div class="f10">ll</div></td>
	<td>15</td>
	<td><a href="ll" class="f10">ll </a><br />ll0</td>
	</tr>`;

let td = cheerio.load(text)('td.tal');
console.log(td.has('a')); // initialize {/**/}
console.log(JSON.stringify({has: td.has})) // {}, that means has is undefined.
console.log(td.has) // [Function]
console.log(td.find('font').length) // 0
```

And I checked the source code:
```
exports.has = function(selectorOrHaystack) {
  var that = this;
  return exports.filter.call(this, function() {
    return that._make(this).find(selectorOrHaystack).length > 0;
  });
};
```
It should return a Boolean.
Seems very confused.
I write something wrong or that a bug?
Thanks.

**Comment by Dreamiko** [comment]
Hi,

I think that is a bug, I tried it out myself, its returning the cheerio object instead of a boolean value. 

`exports.has = function(selectorOrHaystack) {
  var that = this;
  return exports.filter.call(this, function() {
    return that.find(selectorOrHaystack).length > 0 // modified code
  });
};`

This works, however the cheerio object is still being returned. (Being returned from the .find() function I think)

**Comment by Dreamiko** [comment]
Hi,

It does look like a bug, I tried it out, get same results.

**Comment by maicss** [comment]
![image](https://user-images.githubusercontent.com/9784767/27258500-b8f87608-542e-11e7-8c34-b71714130dcf.png)

yes, you are right, it returns an object.

I should use `console.log(td.has('a').length > 0)`

Thanks very much.
