### ISSUE TITLE
Add option to be able to manipulate `<script />` tags when using `.load()`

### ISSUE THREAD

**Issue by sampi** [cheeriojs/cheerio#1042]
When trying to `.append()` or `.text()` `<script />` tags, they just get ignored in v1.0.0.
I assume `<style />` tags have reached the same fate.

I'd like to have the option to still handle these tags, because we're using cheerio to build our static GitHub pages and we rely on injecting `<script />` tags to the `<head />`, and reading `<script />` tags' contents to transform them into editable code fields.

something like this could work, I saw that `.parseHTML()` already has a similar feature:

```javascript
cheerio.load(html, { includeScripts: true });
```

PS: Doing `html.replace(/script/g, 'skript')` won't work, because then the text contents of the element get escaped to html entities =/

**Comment by fb55** [comment]
Looks like this is fixed: https://github.com/cheeriojs/cheerio/commit/7d252a27792183c6fb6e10686769074bdb4abc81
