### ISSUE TITLE
Big file makes Cheerio fail

### ISSUE THREAD

**Issue by EhsaanF** [cheeriojs/cheerio#1043]
I have a ~20 MB HTML file. Here is my code:
```
var cheerio = require( 'cheerio' ),
    content = require( 'fs' ).readFileSync( 'in.html', { encoding: 'utf8' } ),
    $ = cheerio.load( content );

var data = [];
$( 'td.CTDData' ).each( function( i, elem ) {
    if ( /[0-9]{7}/.test( $( elem ).text() ) ) {
        var code = parseInt( $( elem ).text() );
        var title = $( elem ).next().text();

        data.push( { code: code, title: title } );
    }
} );

console.log( data );
```
But I'm getting an empty array. When I execute this code with a smaller file (~400 KB) it works.
How can I parse the big file?

**Comment by PedramMarandi** [comment]
Same here.

**Comment by fb55** [comment]
20MB is a pretty huge file. You could try using something like [cornet](https://github.com/fb55/node-cornet) to select elements within the page first, then use cheerio on those subsets.
