### ISSUE TITLE
Submit HTML Form

### ISSUE THREAD

**Issue by gencaysahinn** [cheeriojs/cheerio#1044]
Hello, thanks for great lib.
Is it possible to submit html form that got from cheerio?

**Comment by bluzi** [comment]
No, it is not possible using Cheerio. 
Cheerio is only designed to manipulate HTML, and it cannot apply browser functionality (such as form submission) on it.

**Comment by fb55** [comment]
We have some functionality for serialising forms, which should be a good starting point for implementing this yourself. Cheerio doesn't perform any http requests though.
