### ISSUE TITLE
Stringify behaviour differs between cheerio and jQuery

### ISSUE THREAD

**Issue by stevenvachon** [cheeriojs/cheerio#1045]
jQuery fragment `html()`:
```js
$("<html></html>").html()
//-> ""
```
cheerio fragment `html()`:
```js
const $ = cheerio.load("")

$("<html></html>").html()
//-> <html><head></head><body></body></html>
```

---

jQuery `toString()`:
```js
$(":root").toString()
//-> [object Object]
```
cheerio `toString()`:
```js
const $ = cheerio.load("")

$(":root").toString()
//-> <html><head></head><body></body></html>
```

@inikulin @fb55

**Comment by jcrben** [comment]
@fb55 @inikulin this could use the label jQuery Differences https://github.com/cheeriojs/cheerio/issues?q=is%3Aopen+is%3Aissue+label%3A%22jQuery+Differences%22

**Comment by fb55** [comment]
Thanks @jcrben!

**Comment by fb55** [comment]
I believe Cheerio's behaviour is more useful in a server context, so closing this as a won't fix.
