### ISSUE TITLE
How can I get a screenshot when I using cheerio。

### ISSUE THREAD

**Issue by ColinCLL** [cheeriojs/cheerio#1048]
I want some  screenshots with dom.

just like: 
< div class="screenshot"  >
   //some  html
< div >
< div class="screenshot" >
   //some  html
< div  >

Ask for help,thanks!

**Comment by josecarneiro** [comment]
I'm not exactly sure what you mean, but taking screenshots of your webpage can't be achieved with cheerio.

Please look into PhantomJS, Nightwatch.js, google-chrome headless mode or wkhtmltoimage.

**Comment by ColinCLL** [comment]
I mean that  I want to take screenshots of  selector(".class") .
I'm sorry for my English.And thinks for you answer.
