### ISSUE TITLE
Selector byte locations

### ISSUE THREAD

**Issue by cdibbs** [cheeriojs/cheerio#1049]
Odd ball request, but my hope is that its implementation would be straightforward. Is there any way to get byte locations in the original document? If I select `$("body>#something>table td")`, can I find out where td was in the original document?

In essence, serialization isn't enough, for me; I need to make changes without altering even the original white space. Thanks!

**Comment by dilantha111** [comment]
Is some one working on this feature ? If not I would like to start working on.

**Comment by cdibbs** [comment]
@dilantha111 I cannot speak for the project maintainers, but I am not working on this. @jugglinmike what do you think? This isn't urgent for me. It would just facilitate a "some day" feature in a project of mine.

**Comment by cdibbs** [comment]
@jugglinmike thought I'd check in, just in case there's been progress but this issue got lost in the shuffle. Any word on this? Does it seem feasible given the underlying frameworks? Thanks!

**Comment by fb55** [comment]
You can enable location information for either parser. Have a look at the parser options to see where you can turn this on. For `htmlparser2`, the options would be [here](https://github.com/fb55/domhandler#option-withstartindices).
