### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by oleersoy** [cheeriojs/cheerio#1051]
I created the documentation here as I first thought this was a nunjucks issue:
https://github.com/mozilla/nunjucks/issues/1011

``` console
RangeError: Maximum call stack size exceeded
    at uniqueSplice (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/api/manipulation.js:106:23)
    at /home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/api/manipulation.js:130:3
    at initialize.<anonymous> (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/api/manipulation.js:49:7)
    at exports.domEach (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/utils.js:52:24)
    at initialize.append (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/api/manipulation.js:39:12)
    at Object.<anonymous> (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/@superflycss/task-test/src/main/js/index.js:46:105)
    at initialize.exports.each (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/api/traversing.js:300:24)
    at /home/ole/Junk/@superflycss/utilities-fonts/node_modules/@superflycss/task-test/src/main/js/index.js:41:32
    at DestroyableTransform._transform (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/gulp-cheerio/lib/index.js:18:9)
    at DestroyableTransform.Transform._read (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/gulp-cheerio/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/gulp-cheerio/node_modules/readable-stream/lib/_stream_transform.js:172:12)
```

**Comment by oleersoy** [comment]
After the nunjucks loop runs, cheerio is used to take the content and copy it another section of the document.  If I remove literals from the loop it runs, but very very slowly.

**Comment by oleersoy** [comment]
This is the cheerio gulp task code:
https://github.com/superfly-css/superfly-css-task-test/blob/master/src/main/js/index.js

**Comment by oleersoy** [comment]
This is the line of code that the stack says causes the error:
``` js
  return array.splice.apply(array, spliceArgs);
```

**Comment by oleersoy** [comment]
I logged the size of the array and the spliceArgs when the exception is triggered:

``` console
SPLICE ARGS LENGTH:  4
ARRAY LENGTH:  5
SPLICE ARGS LENGTH:  132519
ARRAY LENGTH:  0
/home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/api/manipulation.js:109
  return array.splice.apply(array, spliceArgs);
                      ^

RangeError: Maximum call stack size exceeded
    at uniqueSplice (/home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/api/manipulation.js:109:23)
    at /home/ole/Junk/@superflycss/utilities-fonts/node_modules/cheerio/lib/api/manipulation.js:133:3
```

Thoughts?

**Comment by oleersoy** [comment]
Also asked for feedback on [SO](https://stackoverflow.com/questions/44959025/rangeerror-maximum-call-stack-size-exceeded-caused-by-array-splice-apply)

**Comment by oleersoy** [comment]
With this test there is only a single element that Cheerio is selecting and then moving to a different part of the document.  In order to do this it adds over 100,000 array entries to spliceArgs ... which seem to be very heavy objects, and that causes node to blow up.

**Comment by henry-luo** [comment]
There are many [SO](https://stackoverflow.com/questions/18308700/chrome-how-to-solve-maximum-call-stack-size-exceeded-errors-on-math-max-apply) questions on similar problem.

I think the code is hitting the limit of the JavaScript engine, which has a limit on the size of function arguments. Instead of calling array.splice.apply, can just rewrite the code and use a simple for-loop to implement what the array.splice is doing. I think it won't be too hard.

**Comment by oleersoy** [comment]
I agree - it seems pretty straightforward ... the second part that I'm wondering about is why is cheerio creating so many "Heavy" objects.  The tasks takes several minutes to complete, if I remove one of the loops so that it can complete, and all it is doing is finding one selector and appending a copy of the content in that element to another element ...

**Comment by oleersoy** [comment]
I noticed that the size of the array that we are using in `  return array.splice.apply(array, spliceArgs);
` is zero at the time the exception occurs, and spliceArgs has 132000 entries.  So instead of splicing, I just returned spliceArgs like this:

``` js
  if (array.length == 0) {
    return spliceArgs;
  }
```
Now V8 runs out of memory:

``` console

<--- Last few GCs --->

[10392:0x247c600]    39418 ms: Mark-sweep 1404.6 (1451.9) -> 1404.4 (1428.9) MB, 2448.2 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2448 ms) last resort 
[10392:0x247c600]    41855 ms: Mark-sweep 1404.4 (1428.9) -> 1404.4 (1428.9) MB, 2436.3 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x11ea432a9891 <JS Object>
    2: processKeywords [/home/ole/Junk/@superflycss/utilities-fonts/node_modules/highlight.js/lib/highlight.js:~366] [pc=0x39e06d9a7a8e](this=0x2b357c11c01 <JS Global Object>)
    3: processBuffer [/home/ole/Junk/@superflycss/utilities-fonts/node_modules/highlight.js/lib/highlight.js:~415] [pc=0x39e06d9a9cf9](this=0x2b357c11c01 <JS Global Object>)
    4: processLexeme [/home/ole/Junk/@superflyc...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [gulp]
 2: 0x13647ec [gulp]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [gulp]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [gulp]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [gulp]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 7: 0x39e06ce8437d
Aborted (core dumped)
```

**Comment by oleersoy** [comment]
BTW - Just returning spliceArgs might be a good optimization to apply when array.length is zero?

**Comment by oleersoy** [comment]
This is not a cheerio issue.  I tried implementing it in JSDom as well, and it also runs out of memory.  I'm generating 9X9X816 html blocks with nunjucks loops within the html document and also importing a lot of other css from other modules, and it's probably just too much for node and jsdom to handle.  Even tried it with 6GB or ram to see if it could handle it, and it can't.

``` console
node --max-old-space-size=6000 ./node_modules/.bin/gulp test:css
```

I'll leave the issue open in case you want to add the `array.length` optimization I mentioned above.

**Comment by fb55** [comment]
Great writeup! Closing this as it seems unrelated to this project.

**Comment by fb55** [comment]
@Turbine1991 A fix for this is really hard to implement, and (as seen above) would quickly be substituted for running out of memory. Please consider using a streaming processor like `cornet` if you have to deal with massive datasets.
