### ISSUE TITLE
Arrow functions bug for .each() method

### ISSUE THREAD

**Issue by trevorfrese** [cheeriojs/cheerio#1056]
Hi there,

It looks like there is some bug in processing arrow functions inside of a .each() iteration for a cheerio object.
E.g.
**This will not work:**
` elements.each((i, element) => {
      console.log($(this).text());
    });`

**Whereas, this works:**
`elements.each( function (i, element) {
      console.log($(this).text());
    });`

Anyone have any feedback on this? If this is a known issue I apologize, I'm relatively new to the cheerio community :)

**Comment by jugglinmike** [comment]
Hi there! The behavior you have reported is not directly related to Cheerio. Instead, it concerns the JavaScript language itself. Unlike "traditional" functions such as those defined with the `function` keyword, so-called "arrow functions" have a `this` value which is lexically-scoped. You can learn more about arrow functions at [this page on the Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

**Comment by trevorfrese** [comment]
@jugglinmike is there a way to access the `this` value that Cheerio is using in the "traditional" function, while still using the "arrow function"?

**Comment by gforceg** [comment]
@trevorfrese 

Would `element` be a reference to `this`?

e.g., 
```javascript
elements.each((i, element) => { console.log($(element).text()); });
```

**Comment by trevorfrese** [comment]
@gforceg that works! I'm not sure why it didn't work before, that was definitely the first thing I tried. We can mark this as resolved 👍
