### ISSUE TITLE
How do I use `cheerio` in `react native`?

### ISSUE THREAD

**Issue by Lizhooh** [cheeriojs/cheerio#1058]
I like the `cheerio` library. I want to use `cheerio` in `react native`, but it didn't work

```js
import cio from 'cheerio';
```

```js
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `events` from `G:\React-Native\test\node_modules\htmlparser2\lib\Parser.js`: Module dop or in these directories:
```

**Comment by niocncn** [comment]
Same issue

**Comment by vvo** [comment]
Can you try to:

```js
npm install events
```

I know this seems counter intuitive, in Node.js this is available by default, maybe not in react native?

**Comment by niocncn** [comment]
Not work for me, next error appear `Unable to resolve module `stream`` =((

**Comment by vvo** [comment]
Seems like a recurrent issue in the react-native repository, ask the question here and provide a reproduction repository. This is not specific to cheerio.

**Comment by Lizhooh** [comment]
I found the problem.
htmlparser2 useing nodejs API.
cause to be unable to work on react native.


> https://github.com/fb55/htmlparser2/issues/199
> https://github.com/oyyd/htmlparser2-without-node-native

**Comment by niocncn** [comment]
it works in my other project on RN 0.42 )

**Comment by niocncn** [comment]
@Lizhooh have you fix the problem?

**Comment by niocncn** [comment]
after installing 'react-native-fence-html' problem disappear, it seems to me it includes all required dependencies )

**Comment by Lizhooh** [comment]
@niocncn One of the libraries helped me, look https://github.com/oyyd/cheerio-without-node-native

No errors, can correctly parse.

```js
import React, { Component } from 'react';
import { StyleSheet, View, Text } from 'react-native';
import cio from 'cheerio-without-node-native';

export default class App extends Component {
    constructor(props) {
        super(props);
        this.$ = cio.load('<p class="hello" style="color: red">Hello world</p>');
    }
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.text}>{this.$('.hello').text()}</Text>
                <Text style={styles.text}>{this.$('.hello').attr('style')}</Text>
            </View>
        );
    }
}
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    text: {
        fontSize: 30
    }
});
```

**Comment by fb55** [comment]
You can install the missing packages from npm (`events`, `stream` and `utils` afaict) and they will be automatically picked up.

I would not recommend the usage of a fork as it will make it difficult to track down issues and will delay, if not prevent, patches for bugs.

**Comment by mhsjlw** [comment]
What about `net` and `url` that are required by tough-cookie?

**Comment by dantman** [comment]
@fb55 The hack of requiring `stream` (a 2 year old abandoned hack) doesn't work with the new `parse5` dependency in `1.0.0-rc.2`.

**Comment by Noitidart** [comment]
Thanks very much for this topic. I had the same issue it was great to see solution right away on search.

**Comment by czy0729** [comment]
@Lizhooh 世界上最远的距离就是我不知道轮子的存在

**Comment by regalstreak** [comment]
Install these packages:
```yarn add buffer events stream util``` 

Fixes for me on `react-native` 0.62 and cheerio 1.0.0-rc3

**Comment by vnadai** [comment]
try:
npm install react-native-cheerio

**Comment by LeoAso** [comment]
You can install `react-native-cheerio` but pretend that it's `cheerio`.

    yarn add cheerio@npm:react-native-cheerio && yarn add --dev @types/cheerio

If you are using NPM instead of Yarn, I think newer versions of NPM also support this.

**Comment by lilraja-x** [comment]
> You can install `react-native-cheerio` but pretend that it's `cheerio`.
> 
> ```
> yarn add cheerio@npm:react-native-cheerio && yarn add --dev @types/cheerio
> ```
> 
> If you are using NPM instead of Yarn, I think newer versions of NPM also support this.

It gives me error "  Error: ENOENT: no such file or directory, lstat 'C:\Users\UZAIR\FYP\node_modules\cheerio-select' "
