### ISSUE TITLE
Cheerio keeps returning undefined for attr of element

### ISSUE THREAD

**Issue by ishan-marikar** [cheeriojs/cheerio#1060]
Hi there.
I don't know if this is a bug or a mistake from my end, but the following line keeps returning 'undefined'.

``` js

    const request = require('axios');
    getImage(link) {
        return new Promise((resolve, reject) => {
            request
                .get(link)
                .then((response) => {
                    let html = response.data;
                    let $ = cheerio.load(html);
                    let base64Image = $('img.vacancy-img').attr('src');
                    console.log('image -->', base64Image);
                    let imageBlob = new Buffer(base64Image, 'base64');

                    return resolve(imageBlob);
                })
                .catch((error) => reject(error));
        });
    }
```
HTML: http://topjobs.lk/employer/advertismentpreview.jsp?jc=0000450465&rid=39&ac=DEFZZZ&ec=DEFZZZ

Using jquery on the site, the function returns the expected data, but not via cheerio.

**Comment by fb55** [comment]
Could you provide a minimal example that contains the relevant HTML?

**Comment by MCTaylor17** [comment]
Looking at the link you provided, the image you're targeting is loaded dynamically.  I would guess that at the time you're trying to access it's `src`, it hasn't been loaded.

I would suggest adding a delay loop that checks if the image exists.

Note: The image doesn't load as a dataURI.  The one on the page you linked first appears like this:

```html
<img alt="" src="/logo/DEFZZZ/6493c8.jpg" style="border-style:solid; border-width:3px; height:984px; width:672px" class="vacancy-img">
```

This means you have to check for not only the existence of the image, but some other check like a minimum length of the `src` attribute.

**Comment by ishan-marikar** [comment]
@MCTaylor17 Thank you, I'll look into adding some sort of delay to check if the image exists and let you know when/if it works c:

**Comment by MCTaylor17** [comment]
I don't use Cheerio for scraping so I'm not up to speed on best practices, but I'm guessing you'll need to use Phantomjs or some other headless browser to render the page before scraping it.

**Comment by fb55** [comment]
What @MCTaylor17 said :)
