### ISSUE TITLE
Cheerio objects/html

### ISSUE THREAD

**Issue by WAINGOR** [cheeriojs/cheerio#1062]
Hi all, I have a few questions on Cheerio/JQuery. 
- First of all: why does cheerio treat html elements differently depending on how you call them? 
Suppose a page has 8 divs with class "cars". If I go console.log($("cars")); is will log plain html text. Then again, if I use .each on the same selector it will show me the element as an object! 
- Suppose I wanted to loop through all of these, and store information about this div according to it's content. Lets say I wanted to store it's grandchild's anchor href attribute only if the word "mustang" was present within the child p element of one of the "cars" divs. I would know how to do all this, except I wouldnt know how to reach a child element during a .each iteration.. Can anybody help?
```
<div class="cars">
<div class="childdiv">
<a href="www.cars.com/cars">Check this car out</a>
<p>it's a 1964 mustang!</p<
</div>
</div>
```

**Comment by jugglinmike** [comment]
> First of all: why does cheerio treat html elements differently depending on
> how you call them?

Cheerio mimics jQuery's behavior in this regard. When iterating over a
collection of nodes, the callback function is invoked with the node itself. The
reason that value is not likewise "wrapped" in a Cheerio object is that
wrapping is an expensive operation that is not always necessary. Just like when
using jQuery, if you would like to interact with the node using the Cheerio
API, you may "wrap" it explicitly (more on this in just a moment).

The behavior of `console.log` that you are reporting is not expected, however.
`console.log($(".cars"))` should log a Cheerio object that contains the result
of the selection operation. Note that I added the leading period (`.`)
character to the selection, since you described "cars" as a class name and not
a tag name.

Can you provide a reduced test case where logging the return value of your `$`
function produces a string value?

> I would know how to do all this, except I wouldnt know how to reach a child
> element during a .each iteration.

You may wrap the element in a Cheerio object:

```js
$('.cars').each(function(idx, el) {
    var $el = $(el);

    var pText = $el.find('p').text();
    // etc.
  });
```

This is a very common pattern for both Cheerio and jQuery, so I recommend
reading tutorials for either library to learn more.

**Comment by WAINGOR** [comment]
Hi jugglinmike, let me start by thanking you for taking your time in giving such a clear explanation, and, perhaps even more importantly, saluting you for being the first programmer I encounter to have an avatar even more awesome than mine.
By wrapping I suppose you mean wrapping inside html tags?

I tried your code out and your logic seems sound. Again, thanks a lot!

**Comment by WAINGOR** [comment]
OK Wait, there is still something I dont get... If we take this page for instance:
https://www.marktplaats.nl/z/muziek-en-instrumenten/piano-s/piano.html?query=piano&categoryId=765&currentPage=1&numberOfResultsPerPage=100
I have set my crawler to find an element with class price-new, and log it's text. 2 things that I just dont get here:
- Why doesnt it give me plain HTML or text? Thats what .text() does right? 
- Also BREAK doesnt get logged :(

```
		console.log($(".cell-group"));				

				$('.cellGroup').each(function(idx, el) {
				    var $el = $(el);
				
				    var pText = $el.find('price-new').text();
				    console.log(pText);
				    console.log("BREAK");
				    // etc.
					
								
			});
```

**Comment by WAINGOR** [comment]
OK Wait, there is still something I dont get... If we take this page for instance:
https://www.marktplaats.nl/z/muziek-en-instrumenten/piano-s/piano.html?query=piano&categoryId=765&currentPage=1&numberOfResultsPerPage=100
I have set a crawler to find an element with class price-new, with a div with class cellgroup. I have checked in the HTML source that this div exists and indeed has a descendant span with class "price-new". Still, when I use the following code it doesnt log anything..

```javascript
		console.log($(".cell-group"));				

				$('.cellGroup').each(function(idx, el) {
				    var $el = $(el);
				
				    var pText = $el.find('price-new').text();
				    console.log(pText);
				    console.log("BREAK");
				    // etc.
					
								
			});
```

**Comment by jugglinmike** [comment]
> By wrapping I suppose you mean wrapping inside html tags?

In this case, I mean "wrapping" with a Cheerio object. If `el` is an element
reference, then `$(el)` is a Cheerio object that contains (or "wraps") that
same element. The element is still available via `$(el)[0]`, but the "wrapped"
object defines all the Cheerio/jQuery methods that make manipulation and
traversal much easier.

> saluting you for being the first programmer I encounter to have an avatar
> even more awesome than mine.

Don't sell yourself short. Jigglypuff is a force to be reckoned with.

> Still, when I use the following code it doesnt log anything..

Because you wrote "a descendant span with class "price-new"", I'm inclined to
suspect that your selector is incorrect. Try making the following change:

```diff
 $('.cellGroup').each(function(idx, el) {
   var $el = $(el);

-  var pText = $el.find('price-new').text();
+  var pText = $el.find('.price-new').text();
   console.log(pText);
   console.log("BREAK");
   // etc.
 });
```

**Comment by WAINGOR** [comment]
Geez, I'm making such nooby mistakes now leaving out that period. Been coding since early morning (it's 22:03 here in Holland) so before I bother you with any more syntax errors I will sleep off this brainfog. Will let U know whats up tomorrow first thing :D Thanks so much for your effort.

**Comment by WAINGOR** [comment]
Allright it's working like a charm :) I do have one more question though... I spent the last 6 months learning all sorts of fancy methods like map, reduce and filter (this must seem very basic to you but for me it was quite awesome) and I see now that cheerio has it's own version of map. To me the vanilla version of map is part of my daily bread and butter and it seems quite wrong that they took such a powerful method, changed the order of it's first 2 parameters and left all the others out. Is there a way to use the dirty old plain .map while "inside" cheerio?

**Comment by jugglinmike** [comment]
Sure, that's another common operation for jQuery code. Use the `toArray` method:

```js
var $mapped = $('.cars').map(function(idx, el) {
    return $(el).find('p')[0];
  });

console.log($mapped.html());

var mapped = $('.cars').toArray().map(function(el, idx) {
    return $(el).find('p')[0];
  });

console.log($(mapped).html());
```

Note that the result will not be a Cheerio-wrapped collection--it will be a native array of the returned values.

**Comment by WAINGOR** [comment]
Well Mike, it seems that I lack a proper understanding of basic JQuery... I did a course on it @ Code Academy as well as FreeCodeCamp, but that didn't touch arrays or OOP. Would you recommend any other sources for me to study? Thanks a lot, I really appreciate all the help you've given. Greets

**Comment by jugglinmike** [comment]
It's been a while since I've looked in to learning resources, but I remember these being good references:

- http://jqfundamentals.com/
- https://learn.jquery.com/

They're both open source, so if you want to help improve them, you're free to do so.

Good luck!

**Comment by WAINGOR** [comment]
Hi Mike, 

I really dont know another way to "contact" you as Github doesnt allow private messaging :( I hope you read this because I'm stuck writing my programme... 
The thing is: I have it working perfectly after putting in blood sweat and tears, only to find out that the node crawler Module doesnt seem to do what it says it does 8*(
I addressed this issue in https://github.com/bda-research/node-crawler/issues/230

I hope you can help me, your recent comments have helped me a lot... By the way did you write this crawler module?

Greets

**Comment by jugglinmike** [comment]
Nope, I haven't contributed to that project (I hadn't heard of it until just
now, actually). GitHub.com lists the contributors for every project. You can see
that project's list here:

https://github.com/bda-research/node-crawler/graphs/contributors

So I'm not really the best person to help. Maintaining a Free/Open Source
project is a lot of work, though, so it may just be that those folks have been
busy over the past two days. Be patient--they may still have some advice for
you :)
