### ISSUE TITLE
Guidelines for error handling in Cheerio?

### ISSUE THREAD

**Issue by hifall** [cheeriojs/cheerio#1065]
Hi,

I am new to Cheerio, and after doing some searching on Cheerio's docs, Google, SO, etc., I can't figure out the proper way to handle potential errors in Cheerio.

For example, how to handle errors while calling `load` on an HTML string? Does `load` throw any exception when it's unable to parse the string, or does it return any error?

Since we use Cheerio in a node.js server, I think it's important to handle errors properly to not crash the server.

Thanks!

**Comment by jugglinmike** [comment]
The `load` method may throw an error under exceptional circumstances, e.g. `cheerio.load(null)`. Parsing string values generally should not throw an error, though, so please let us know if you're experiencing that.
