### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by pastorsj** [cheeriojs/cheerio#1066]
Hello,
I was attempting to retrieve a set of dom elements and get the html using `.each`. I wrote this piece of code, which caused the following error.

``` javascript
const sheets = $('link[rel=stylesheet]').each().html();
```
Error:
```
/Users/redacted/Documents/Programming/Web Application Development/node-gist-html/node_modules/cheerio/lib/api/traversing.js:300
  while (i < len && fn.call(this[i], i, this[i]) !== false) ++i;

TypeError: Cannot read property 'call' of undefined
    at initialize.exports.each (/Users/redacted/Documents/Programming/Web Application Development/node-gist-html/node_modules/cheerio/lib/api/traversing.js:300:23)
    at Request.__WEBPACK_IMPORTED_MODULE_0_request___default [as _callback] (/Users/redacted/Documents/Programming/Web Application Development/node-gist-html/lib/node-gist-html.js:157:58)
    at Request.self.callback (/Users/redacted/Documents/Programming/Web Application Development/node-gist-html/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/redacted/Documents/Programming/Web Application Development/node-gist-html/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/redacted/Documents/Programming/Web Application Development/node-gist-html/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
```

I know that there are Cheerio objects being returned when I run this statement.
``` javascript
 $('link[rel=stylesheet]')
```
so that is not the problem. I also attempted to do something similar to  this:
``` javascript
$('link[rel=stylesheet]').each((index, element) => {
     console.log('html', $(this).html());
});
```
which printed
```
html null
```
several times.
So I am reporting a bug, but I also am having trouble figuring out how to fix the issue above. Thanks!

**Comment by jugglinmike** [comment]
Hi there

>     const sheets = $('link[rel=stylesheet]').each().html();

This line is producing an error because `each` must be invoked with a function
value as the first parameter.

>     $('link[rel=stylesheet]').each((index, element) => {
>          console.log('html', $(this).html());
>     });

This is not working as you intend because in JavaScript, the `this` value of
arrow functions is lexically-scoped. To print the value of each element
contaied by the selection, either define the callback function via a function
expression using the `function` keyword, or replace the reference to `this`
with the value of the second argument--`element` in that example.

**Comment by pastorsj** [comment]
@jugglinmike Thanks for the quick response. That would definitely be the issue. However, when changing the code to 
``` javascript
$('link[rel=stylesheet]').each(function (index, element) {
    console.log('html', $(this).html());
});
```
It produces this output.
```
html
html
html
```
Should I assume that this is my fault now?
Note that I can now get the href attribute using the below code without any problems and it will output the links correctly.
``` javascript
$('link[rel=stylesheet]').each(function (index, element) {
    console.log('html', $(this).attr('href'));
});
```

**Comment by jugglinmike** [comment]
Try not to think of it in terms of "fault" :)

It's difficult to say what the problem is; we'll need to see the input markup before we can say more. As a first guess: does the anchor tag have any content?

**Comment by chr1se** [comment]
>>As a first guess: does the anchor tag have any content?

was just about to ask that, they tend not to <link ../>

**Comment by pastorsj** [comment]
So my understanding was that if I retrieve all link tags and got the html for each of them, I would expect them to be returned regardless of whether they had content or not. A link tag that I am retrieving would look something like this. Am I not able to get this as a string?
``` html
<link rel=stylesheet type=text/css href=https://cdn:something.css />
```

**Comment by chr1se** [comment]
.html() 
returns all 'children' html of the selected element as a string 

in your case the selected element is $('link[rel=stylesheet]')
which has no children hence the empty result

https://github.com/cheeriojs/cheerio#rendering

if you want to print the actual selected element itself along with all its children
then use $.html()
in your case that will return <link rel=stylesheet type=text/css href=https://cdn:something.css />

**Comment by chr1se** [comment]
.html()
returns all 'children' html of the selected element as a string

in your case the selected element is $('link[rel=stylesheet]')
which has no children hence the empty result

https://github.com/cheeriojs/cheerio#rendering

if you want to print the actual selected element itself along with all its children
then use 
$.html('link[rel=stylesheet]')

in your case that will return
<link rel=stylesheet type=text/css href=https://cdn:something.css />

**Comment by chr1se** [comment]
.html()
returns all 'children' html of the selected element as a string

in your case the selected element is $('link[rel=stylesheet]')
which has no children hence the empty result

https://github.com/cheeriojs/cheerio#rendering

if you want to print the actual selected element itself along with all its children
then use
$.html('link[rel=stylesheet]')

in your case that will return
 ...link rel=stylesheet type=text/css ....

**Comment by pastorsj** [comment]
@chr1se Thanks for the help. I will close this issue.
