### ISSUE TITLE
Add new node in xml file (question)

### ISSUE THREAD

**Issue by fedorovmichael** [cheeriojs/cheerio#1069]
Hi, I try to add new node in xml file by append command, my **code**:

var cheerio = require('cheerio');
$ = cheerio.load("my.xml", {xmlMode: true});
$('urlset').append('<url><loc>http://zzzzzz.com/event/5555555/</loc></url>');

what I need to do ?

**Comment by jugglinmike** [comment]
I recommend reading [the project's documentation on the `append` method](https://github.com/cheeriojs/cheerio#append-content-content--). You'll find that the first argument should be the *content* you want to insert, not a URL where the content is hosted.

In this case, you'll want to fetch the content of that URL (this is not a feature offered by Cheerio), and then use the result of that operation when you invoke `append`.

Hope that helps!

**Comment by fedorovmichael** [comment]
Thanks for you answer, I well try to do it.
