### ISSUE TITLE
SCRIPT and LINK tags defined in HEAD incorrectly assigned to BODY

### ISSUE THREAD

**Issue by CoryGH** [cheeriojs/cheerio#1072]
It appears the `script` and `link` tags defined in the `head` section are incorrectly being placed in the `body` DOM tree when using selectors to find them.  On the plus side this doesn't apply to `$('body').html()` text, but it does make using cheerio to build up template pages impossible without either duplicating `script` and `link` tags (i.e. when you're passing the links up and searching for `script` and `link` tags via `body > script` or `body > link`) or adding additional markup to concatenate the `script` and `link` `head` elements (like moving them outside of the head into a `div` contained in the `body`.

This does work in standard jQuery (i.e. you can use `head > link` and `head > script` to obtain either.

**Comment by CoryGH** [comment]
Upon closer inspection this only occurs when you have a custom element preceeding the tags in the `head` tag, for instance:

```
<head>
    <title>title</title>
    <link rel="stylesheet" href="/path/to/mathquill.css"/>
    <header>header</header>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
```

In the example above the `link` tag will show up but the `script` tag gets moved into the body (but not in the `body` HTML.)

**Comment by inikulin** [comment]
If you are using RC, when it's correct behaviour. If you try open this markup in browsers you'll see that what it moves custom element and content that follows to `body`. This is standardised HTML behaviour: `head` has very limited number of tags that it can contain.

**Comment by CoryGH** [comment]
The issue is more in trying to define custom tags on a page which never show up in the body without limiting possible tags in the body (these get parsed out in my case and are just there for page-specific inserts into a template page, but I don't want the requirement of always defining them as the first item in the body or something similar and then omitting or worse reusing a custom tag as a part of some other library which ends up being parsed incorrectly.)  The head is a logical place to put this kind of information, since the entire head content of child pages is parsed via the templating engine and spliced into the parent template(s).

**Comment by inikulin** [comment]
@CoryGH Exactly for this use case `<template>` tag was invented and it lives perfectly in `head`.

**Comment by CoryGH** [comment]
@inikulin Can you add other tags inside of a `<template>` tag?

**Comment by inikulin** [comment]
You can add any tags inside template.
