### ISSUE TITLE
$.clone() method

### ISSUE THREAD

**Issue by MCTaylor17** [cheeriojs/cheerio#1074]
There have been a couple times where it would be convenient to clone the entire cheerio object.

Is it possible to add this?

**Comment by fb55** [comment]
That method is implemented: https://github.com/cheeriojs/cheerio#clone

**Comment by MCTaylor17** [comment]
@fb55 It doesn't work on the root:

```js
var $ = cheerio.load("<DOCTYPE! html><html><body><p>Hello World</p></body></html>");

var $clone = $.clone();
$clone.html()
```
Result:

```
var $clone = $.clone();
               ^

TypeError: $.clone is not a function
```

**Comment by jugglinmike** [comment]
In that example, `$` is a selector function. To access the root, call the static `root` method, as in `$.root()`.

**Comment by danday74** [comment]
the only way I can clone is:

```
const clone = $ => {
  const strHtml = $('body').html()
  return cheerio.load(strHtml)
}
```
this did NOT work:

`$.root().clone()
`
