### ISSUE TITLE
Proposal for breaking change: removing the `root` element

### ISSUE THREAD

**Issue by jugglinmike** [cheeriojs/cheerio#1077]
### Background

Cheerio's `load` method accepts a string of markup and creates a selector
function. This function is "bound" to a document whose contents is a node
structure based on the input markup. This function is intended to behave much
like the global `jQuery`/`$` function provided by the jQuery library (as if the
library had been loaded in a document generated from the same markup by a web
browser).

Historically, Cheerio has always attached the parsed markup to a non-standard
"root" element (i.e. `<root>`). As far as I know, this was implemented to
support the `load` method's behavior when given markup describing a document
fragment--strings like `'<p>1</p><p>2</p>'` could be passed to `load` and still
produce a single top-level element.

Thanks to @inikulin and his Parse5 library, the release candidate for version
1.0.0 normalizes the parsing behavior of `load`. It *always* produces a
complete document--just a like a web browser. The result is much more
predictable, standards-compliant, and "familiar" to web developers. It's a
backwards-breaking change, though, and we hope to ease the upgrade path for
consumers through a concise migration guide.

### Proposal

Since we are already committed to a breaking change for version 1.0, I wanted
to consider making Cheerio's behavior even more browser-like. I'd like to get
rid of the `<root>` element and instead rely on the `<html>` element (which
again, is either described by the consumer's input markup or automatically
created by Parse5).

This would involve removing the Cheerio-specific `$.root()` method from the
API.  Users who previously used it as a basis for traversal could re-write code
like `$.root().find('div')` with `$('html').find('div')`.

However, many use cases involve rendering full documents. For this,
`$('html').html()` is not equivalent because the resultant string does not
include the document element itself. So we'll need to keep another
Cheerio-specific method: `$.html()`.

Other than that, I think it would just be matter of updating Cheerio's
internals to operate without `<root>`. I spent just enough time trying this out
to see that it is not trivial, but I don't believe that there is any technical
reason it can't be done.

I'd love to get feedback from any Cheerio user, but I'm particularly interested
in hearing from @fb55, @matthewmueller, and @inikulin. Do you think this is a
good idea? Do you think it would invalidate any existing use cases? Or is there
any other reason it isn't technically possible? Or more subjectively, do you
think the change would be too jarring for consumers to justify the benefit?

**Comment by matthewmueller** [comment]
@jugglinmike I'm +1 to standardizing as much as possible with the DOM. When I first wrote cheerio, I didn't pay much attention to the internal DOM node structure. I was also a bit new to node at that time.

The internal structure's keys should match the actual DOMs, so nodeName, nodeType, childNodes, etc. We really only need a few of these to make the whole API possible.

I do think having some reference to the top-level node would be good. e.g. having `$.html()` vs `$('html').html()`. If I recall the reason for a $.root() is that we wanted to be able to get the DOCTYPE too. I think it's safe to treat $ as the document like this and attach additional method to the prototype (perhaps use getters and setters too):

<img width="221" alt="screen shot 2017-09-09 at 9 58 29 am" src="https://user-images.githubusercontent.com/170299/30236522-813cadc6-9545-11e7-8280-3e2315d2341c.png">

Additionally, I'd like to just be able to do this:

```
const cheerio = require('cheerio')
const $ = cheerio('some html string')
```

I don't think this would need to be a breaking change though.

**Comment by jugglinmike** [comment]
Ah, directive nodes. I hadn't considered those...

I had mistakenly assumed that the library would *always* produce a single `<html>` element, but to @matthewmueller's point, if you invoke `cheerio.load('<!DOCTYPE html><html>')`, you will get the expected 2 nodes. This means that if we simply replaced the current (Cheerio-provided) `<root>` element with the (Parse5-provided) `<html>` element, we'd be lopping off critical information.

Calling on @inikulin for some information on Parse5: what kind of assumptions can we make about the DOM returned by `parse5.parse` (versus `parse5.parseFragment`)? For instance, I'm thinking if we can say, "it's *always* either an `<html>` element or a directive node and an `<html>` element," then maybe my proposal still has legs. We could remove `$.root` but preserve `$.html`for rendering the entire document (we'd just keep a reference to the directive node if it is produced at document parse time).

> **One more thing**: I'd really like to avoid a transpiling step, so if there's any significant re-write, can we keep it ES5? These old(ish) projects that still work everywhere are like a diamond in the rough 💎

I'm definitely in favor of this!

**Comment by inikulin** [comment]
@jugglinmike parse5 (as well as HTML spec) has root element which is `document` in case of full document parsing and `documentFragment` in case of fragment parsing. `root` sounds like a good umbrella term for `document` and `documentFragment` and it allows you to handle scenarios where you need to modify/render DOCTYPE along with `html` tag, so I believe we should keep it.

**Comment by jugglinmike** [comment]
Thanks for the feedback, @inikulin! I wanted to push for a more
standards-compliant API if only to make the internals more familiar for
contributors. After experimenting some more, though, I've come to realize that
whatever the case, jQuery (and by extension Cheerio) does not offer an API for
working with the owner document.

One day, it would be nice if we could more concretely document and support
direct interaction with Cheerio's DOM. I'm not sure if this is a realistic
goal, though: if the DOM is implemented as a static data structure, then it
will always be dangerous to encourage end-user manipulation--many modifications
could invalidate the document and cause instability in Cheerio's behavior.

So until then, we'll always need a Cheerio-specific API to support this use
case. We might make changes to the underlying structure (for instance, using
a "true" document node as opposed to a Element with tag name "root"), but that
will be a implementation detail that we introduce essentially just for the sake
of conformance; it won't effect the API. In other words: I don't have to block
version 1.0 with my pedantic objections :)

**Comment by ljharb** [comment]
@jugglinmike does this mean that some form of `.root()` will end up in v1?
