### ISSUE TITLE
How to get document.documentElement.innerHTML on server?

### ISSUE THREAD

**Issue by extensionsapp** [cheeriojs/cheerio#1080]
Hello.

I need get to HTML code on server, analog `console.log(document.documentElement.innerHTML)` on browser.

```
var $ = cheerio.load(html, {
    decodeEntities: false
});
```

<img width="834" alt="screenshot_7" src="https://user-images.githubusercontent.com/8192379/30507557-e264c806-9a8e-11e7-8c3d-181f18f9bf5a.png">

<img width="851" alt="screenshot_5" src="https://user-images.githubusercontent.com/8192379/30507561-e8721460-9a8e-11e7-8706-de26fb6ba5b4.png">

<img width="826" alt="screenshot_6" src="https://user-images.githubusercontent.com/8192379/30507772-ca2cac7e-9a91-11e7-9ab9-3f1547b8fdc5.png">

I need Browser code === Cheerio code.
`console.log(document.documentElement.innerHTML)` === `$('html').html()`
Can you help me?

**Comment by fb55** [comment]
Please refer to StackOverflow for this kind of question.
