### ISSUE TITLE
TypeError: $(...).get(...).getAttribute is not a function

### ISSUE THREAD

**Issue by saeedhei** [cheeriojs/cheerio#1082]
**Why I'm Getting This Error?:**
`TypeError: $(...).get(...).getAttribute is not a function`

```
request('https://example.com', function (error, response, html) {
  if (!error && response.statusCode == 200) {
    const $ = cheerio.load(html);
    console.log($("meta").get(1).getAttribute("content")); 
  }
});
```

**Comment by luanmuniz** [comment]
You should use `.eq(1)` and `.attr("content")` as in `console.log($("meta").eq(1).attr("content"));`

`.get()` returns a DOM object as specified https://github.com/cheeriojs/cheerio#get-i-
Cheerio is not a browser, so the DOM api is not available.

**Comment by saeedhei** [comment]
Thank you.
