### ISSUE TITLE
Adjacent sibling selectors broken

### ISSUE THREAD

**Issue by monkeysuffrage** [cheeriojs/cheerio#1095]
Cheerio adjacent sibling selectors aren't working properly. This is the case for both + and ~
```
let html = `
<div class="foo">My List</div>
<ul>
  <li>aaa</li>
  <li>bbb</li>
  <li>ccc</li>
</ul>
`
const cheerio = require('cheerio')

let $ = cheerio.load(html)

let data = $('.foo').get().map(div => {
  return {
    title: $(div).text(),
    list: $(div).find('+ ul li').get().map(li => $(li).text())
  }
})

console.log(data)

// [ { title: 'My List', list: [] } ]
```
Also if anybody knows of any projects that are more faithful to jQuery I'd love to hear about it. Thanks.

**Comment by dbuezas** [comment]
you can use jQuery or Sizzle with JSDom. It is slower but it works great.

**Comment by fb55** [comment]
This should be resolved with the latest release.

**Comment by monkeysuffrage** [comment]
Thanks, that helps me out a lot if true.

**Comment by fb55** [comment]
Actually, this was not fixed yet. I've opened #1583 with a proper fix.
