### ISSUE TITLE
1.0.0.rc2 ignoring lowerCaseAttributeNames option

### ISSUE THREAD

**Issue by tanrikut** [cheeriojs/cheerio#1096]
In version 0.20.0 following code gives me attribute names involving uppercase letters:

`const $ = cheerio.load(htmlContent, {
                        decodeEntities: false,
                        lowerCaseAttributeNames: false
                    });`

But same code with version 1.0.0.rc2 fails.

**Comment by anjmao** [comment]
Same here
```js
const $ = cheerio.load('<div [innerHTML]="test"></div>', { lowerCaseAttributeNames: false });
console.log($('body').html()) // outputs <div [innerhtml]="test"></div>
```

**Comment by fb55** [comment]
Yeah, 1.0 uses a new parser that does not support these extensions. If you enable xml mode this is doable again.

```js
const $ = cheerio.load(htmlContent, { xml: { decodeEntities: false, lowerCaseAttributeNames: false } });
```
