### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ryanZiegler** [cheeriojs/cheerio#1097]
Help！
`var html ='<div><!-- abc -->value<!-- *abc --></div>';`

How to get the value? use the` '<!-- abc --> `'`

**Comment by vvo** [comment]
I am unsure this is doable with cheerio because with CSS selectors there's no way to target comments.

```
> node
> var $ = require('cheerio').load('<div><!-- abc -->value<!-- *abc --></div>');
undefined
> $('div').text()
'value'
>
```

This works for me

**Comment by fb55** [comment]
Thanks @vvo!
