### ISSUE TITLE
How to select using xpath?

### ISSUE THREAD

**Issue by miguelmota** [cheeriojs/cheerio#1098]
Is selecting elements using xpath selector supported? If not, what are some alternatives? Thanks

**Comment by fb55** [comment]
Not supported

**Comment by Bowlingtoolkit** [comment]
anyway to get selector more accurate ?

**Comment by softmarshmallow** [comment]
https://github.com/cheeriojs/cheerio/issues/152#issuecomment-658512082
i thing cheerio should support xpath by default

**Comment by mattfysh** [comment]
hi @fb55 - I've had some success getting the xpath library working with the htmlparser2 tree format, see this gist: https://gist.github.com/mattfysh/92e160e5f2a4cf7d569f3c2bf012c217

feel free to add in cheerio if you think it could be useful! cheers
