### ISSUE TITLE
$().text()的html实体符号

### ISSUE THREAD

**Issue by Febby315** [cheeriojs/cheerio#1100]
通过选择得到一个元素该元素的文本内容是'a &nbsp;&gt;&nbsp;b',而通过.text()得到的元素的文本却是'a&amp;nbsp;&amp;gt;&amp;nbsp;'

**Comment by shinima** [comment]
`cheerio.load('...', { decodeEntities: true })`

**Comment by Febby315** [comment]
@shinima 谢谢

**Comment by fb55** [comment]
I assume this is resolved, thanks @shinima
