### ISSUE TITLE
Improve documentation about properties of generated elements

### ISSUE THREAD

**Issue by iabw** [cheeriojs/cheerio#1103]
I think Cheerio's docs could be more clear about the properties of the elements it generates, through some combination of
- moving the [properties list](https://github.com/cheeriojs/cheerio#the-dom-node-object) to the top of the API docs
- linking to those properties from the [caveats of what Cheerio can do](https://github.com/cheeriojs/cheerio#cheerio-is-not-a-web-browser)
- changing the 2nd sentence in that caveat from "It does not interpret the result as a web browser does" to "It does not interpret the result as a web browser does, and [generated elements will not have the full DOM api](https://github.com/cheeriojs/cheerio#cheerio-is-not-a-web-browser)"

The sentence after that starting "Specifically" made me think those were the ONLY caveats, and I was then momentarily surprised to discover the missing DOM apis, since everything else about using cheerio feels so much like using jQuery in a browser.

Cool lib, thanks for all the great work. 👍

**Comment by fb55** [comment]
Happy to accept PRs for this :)

**Comment by fb55** [comment]
This has improved a lot with the last release — closing this issue.
