### ISSUE TITLE
Do not change attributes formatting

### ISSUE THREAD

**Issue by anjmao** [cheeriojs/cheerio#1104]
When I have formatted html like this
``` js
const templateHtml = `
<div id="test"
        class="main"
        data-x="x">
</div>`;
const $ = cheerio.load(templateHtml, { lowerCaseAttributeNames: false });
```

after i load it with cheerio and output its html after some modifications I get all attributes formatted to one line like this

```
console.log($.html());
```
outputs
```html
<div id="test" class="main" data-x="x">
</div>
```

I'm not sure if this is htmlparser2 or cheerio issue. Do you know if it is possible to keep attributes formatting as it was in original input, because this is very important for my use case?

**Comment by ceremcem** [comment]
Thanks for the `{ lowerCaseAttributeNames: false }` bit, it helped me solving an issue. 

On the other hand, I this issue's point is hard to get at the first sight (for me, at least). I guess you want Cheerio to output: 

```
<div id="test"
        class="main"
        data-x="x">
</div>
```

instead of 

```
<div id="test" class="main" data-x="x">
</div>
```
which is just the same thing with the current behavior plus the newlines are kept. Is that correct?

**Comment by anjmao** [comment]
I’m creating webpack plugin which can highlight code snippets in html markup, this is why it is important to keep html with original newlines. I solved my issue by not using cheerio and simply parsing html by myself, but nee setting like ‘preserveNewLines’ could be a solution if it make sense :)

**Comment by fb55** [comment]
We decided before that this is out of scope for cheerio. Thanks for the input though!
