### ISSUE TITLE
Can't reach anything under noscript tag

### ISSUE THREAD

**Issue by rightaway** [cheeriojs/cheerio#1105]
I've got `cheerio.load(pageContent, { decodeEntities: false })`, but then when I try to match an element that's under a `noscript` tag it doesn't work. I thought setting `decodeEntities` to `false` would allow this. How do I match that element?

**Comment by VulcanRav** [comment]
try cheerio.load(pageContent, [ xmlMode: true});

**Comment by monkeysuffrage** [comment]
I'm seeing this too. This should not have been closed.

**Comment by fb55** [comment]
Enabling xml mode fixes this, otherwise parse5 will always strip `noscript` tags.

**Comment by monkeysuffrage** [comment]
Right, but it's still an issue, right? It should stay open until it gets resolved.

**Comment by mitin001** [comment]
Try to match the noscript tag itself, get the html by calling .html() and then load that html with cheerio again. That way you'll be able to match any element under the noscript tag.

**Comment by paulsmithkc** [comment]
This is definitely still a bug with cheerio, as cheerio is essentially a browser without JavaScript support. The noscript tag is intended to provide content for browsers that do not support javascript (which would include search engines, web crawlers, and web scrapers).

"xmlMode: true" has several other side effects (see documentation) which can cause most pages, and especially those in question to fail to parse.

**Comment by joeybaker** [comment]
Quickly looking through, it seems like https://github.com/cheeriojs/cheerio/blob/208bce1ee8ed921dbd0fc2988644fd3a68bf8bd1/lib/parse.js needs to be updated to turn `scriptingEnabled: false` https://github.com/inikulin/parse5/blob/master/packages/parse5/docs/options/parser-options.md 

I'm not sure if there are security implications of doing that though.

**Comment by paulsmithkc** [comment]
<noscript> tags should be parsed as HTML as that is what they contain, not text/javascript.

**Comment by dsmmcken** [comment]
This is the first google result for "cheerio noscript". If you are attempting to parse html inside a noscript tag with cheerio, see the doc page linked below.

Set the [`scriptingEnabled`](https://cheerio.js.org/interfaces/Parse5Options.html) option to `false`.

```
const $ = cheerio.load(data, { scriptingEnabled: false });
```

**Comment by ggorlen** [comment]
[`xmlMode`](https://cheerio.js.org/interfaces/CheerioOptions.html#xmlMode) is deprecated in favor of [`xml`](https://cheerio.js.org/interfaces/CheerioOptions.html#xml).

**Comment by rishi-raj-jain** [comment]
https://rishi.app/blog/parsing-noscript-elements-using-cheerio-in-node-js/ is also another solution.
