### ISSUE TITLE
Parsing returns null if first line is carriage return

### ISSUE THREAD

**Issue by WickyNilliams** [cheeriojs/cheerio#1107]
Spent a while scratching my head about this, only to realise it's the empty first line which was causing issues. Here's some code to reproduce:

```js
const html =`
<p>
  hello world
</p>`;

const $ = cheerio(html);
console.log($.html()); // null
```

Version: `1.0.0-rc.2`

**Comment by fb55** [comment]
This was a fun one to understand: The issue is that the document should be loaded with `cheerio.load`. Otherwise, you get a collection of elements, with the first one being a text node. `.html` is only supported on elements with children, otherwise `null` is returned — as experienced here.
