### ISSUE TITLE
Changing attribute or tag name to lowercase should be turned off by default

### ISSUE THREAD

**Issue by ceremcem** [cheeriojs/cheerio#1108]
While using template libraries, attributes are converted to variables and tag names are searched in a global definition table. If attributes or tag names are converted to lowercase, they are found, thus application is not working. 

This kind of "improvements" should be turned off by default.

**Comment by fb55** [comment]
This is part of the HTML spec. There are options to disable this for htmlparser2, the default is to adhere to the spec though.
