### ISSUE TITLE
Feature Request: Allow access to line number for matched tag

### ISSUE THREAD

**Issue by tw3** [cheeriojs/cheerio#1109]
I am using cheerio to scan HTML template files for tags with a particular attribute (i18n).  My node js script works great, I open the files, extract the text, pass the text to cheerio, query for the tags and output something like:

`file1.html: Tag found <div i18n>Foobar</div>`

It would be great if my script could output the line number, e.g.:

`file1.html, line 45: Tag found <div i18n>Foobar</div>`

Unfortunately it doesn't seem like cheerio stores the line number associated with a queried tag.

Is it possible to to store the line number for tag lookups?  I realize this may be beyond the scope of this project.

**Comment by keyndark** [comment]
Hi tw3. Did you find working solution?

**Comment by b4dnewz** [comment]
there is a solution for this? I need this feature too and I'm deciding to use cheerio based on this feature, there's nothing mentioned in the documentation
