### ISSUE TITLE
.html() adds a wrapper

### ISSUE THREAD

**Issue by horprogs** [cheeriojs/cheerio#1114]
First, thank you for cheerio!

I have a bug this `.html()`.

Code:
```
const ch = cheerio.load('<div id="cheerio">test</div>');
ch.html(); // => <html><head></head><body><div id="cheerio">test</div></body></html>
```

Why cheerio adds a html-body wrapper to my div?

**Comment by PierreRAFFA** [comment]
+1

**Comment by PierreRAFFA** [comment]
try `cheerio.load('<div id="cheerio">test</div>', {xmlMode: true});`

**Comment by horprogs** [comment]
Thanks! Its working!

**Comment by 1mike12** [comment]
Could I add {xmlMode: true} to the docs? I came across people suggesting to do $("body).html() to get around this but it throws away the xml header. Would be much better if this useful feature was mentioned.

**Comment by popey456963** [comment]
@1mike12 If I remember correctly, it's mentioned that you can use htmlparser2 configuration options, which include `xmlMode`.
