### ISSUE TITLE
Any Way To Use Malformed HTML?

### ISSUE THREAD

**Issue by CoryGH** [cheeriojs/cheerio#1116]
I'm using cheerio to parse HTML in a node.js templating engine, and I know from past experience that cheerio does some preprocessing to "see what the browser sees" - but is there a way to shut this off either temporarily (i.e. get something that an element maps to) or in while (across the whole page being parsed?)  The specific issue I'm having can be demonstrated with the malformed HTML below used in my templating engine:

    <table class="editable" fixedcolumnsleft="1">
        <tr>
            <th>Pin</th>
            <th>Type</th>
            <th>Label</th>
            <th>Description</th>
        </tr>
        <list id="xs" view="vw_public_board_component_pins" where="`parent` = 2" inline="true">
            <item>
                <tr>
                    <td>$$name$$</td>
                    <td>$$type_name$$</td>
                    <td>$$label$$</td>
                    <td>$$description$$</td>
                </tr>
            </item>
        </list>
    </table>

When the `list` element is off on it's own all is well and good, but when I put it inside a table things go haywire and nothing I do within node.js seems to allow me to get the content of the `item` tag.  If I were able to see the HTML within the tags as expected this would parse into something like the following:

    <table class="editable" fixedcolumnsleft="1">
        <tr>
            <th>Pin</th>
            <th>Type</th>
            <th>Label</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>name 1</td>
            <td>type 1</td>
            <td>label 1</td>
            <td>description 1</td>
        </tr>
        <tr>
            <td>name 2</td>
            <td>type 2</td>
            <td>label 2</td>
            <td>description 2</td>
        </tr>
        <tr>
            <td>name 3</td>
            <td>type 3</td>
            <td>label 3</td>
            <td>description 3</td>
        </tr>
        ...
    </table>

**Comment by fb55** [comment]
Cheerio only operates on HTML and a subset of XML.
