### ISSUE TITLE
Why is Cheerio adding unicode byte order mark?

### ISSUE THREAD

**Issue by enricopolanski** [cheeriojs/cheerio#1117]
Sample code:

```
var fs = require("fs");

var cheerio = require("cheerio");

input_file = fs.readFileSync("./my.xml", "utf8");

console.log(input_file.substring(0,100));
```

Output:

`<?xml version="1.0" encoding="utf-8" standalone="yes"?><w:document xmlns:wpc="http://schemas.micros`

```
var $ = cheerio.load(input_file, {xmlMode:true});

console.log($.xml().substring(0,100));
```

Output:

`&#xFEFF;<?xml version="1.0" encoding="utf-8" standalone="yes"?><w:document xmlns:wpc="http://schemas`

Don't really understand how to get rid of the of the order-mark with Cheerio, I mean, I can just remove it with a string manipulation, but I find it odd that it's here and can't really understand if it is Windows related (don't have access to osx/linux machine right now).

**Comment by fb55** [comment]
This should be resolved with the latest release.

**Comment by joneldiablo** [comment]
x2
