### ISSUE TITLE
How to find all element use *, wrap and unwrap in cheerio?

### ISSUE THREAD

**Issue by quangvinh1305** [cheeriojs/cheerio#1123]
I hav a jquery code like bellow. I would like to implement the same function in jquery. Seem that the function find('*') and unwrap doesn't exist. How can i implement this in cheerio. 

```
var contentInHtml = $('<div>' + searchTerm + '</div>');
contentInHtml.find('*').contents().unwrap().wrap('<p/>');
```
Thanks,

**Comment by dbuezas** [comment]
Try something like this: (not tested)
```javascript
const contentInHtml = cheerio.load('<div>' + searchTerm + '</div>');
contentInHtml('*').each((i, el) => {
   const $el = $(el);
   $el.contents.wrap('<p></p>');
   $el.replaceWith($el.contents)
})
console.log($.html());
```

Maybe you could define what is your intended result (e.g. wrap all new lines with <p> tags) and input (e.g. `searchTerm` is just text or also HTML).

If that is exactly what you want to do, I'd rather do:
```javascript
const wrapped = '<p>' + searchTerm.split('\n').join('</p><p>') + '</p>';
```
But be aware that if has HTML inside, this will break and is even a potential security issue.

Something like this should be OK:
```javascript
const contentNode = $('<div></div>');
searchTerm.split('\n').forEach(line => {
  const p = $('<p></p>');
  p.text(line);
  contentNode.append(p);
});
console.log(contentNode.html());
```
cheerio should handle escaping the html tags in the text

**Comment by fb55** [comment]
Thanks @dbuezas!

**Comment by quangvinh1305** [comment]
@dbuezas Many Thanks you my issues are resolved.
