### ISSUE TITLE
should .html() decode entities?

### ISSUE THREAD

**Issue by GHolk** [cheeriojs/cheerio#1124]
when i use `{decodeEntities: true}` option and use `$('body').html('&lt;')` ,
it cause `<body><</body>` but not `<body>&lt;</body>` ,
is this behavior expect?

because my language out of ascii,
without option `{decodeEntities: false}` the output of html
would from `<h1>你好</h1>` become `<h1>&#x4F60;&#x597D;</h1>` ,
which is totally not human readable.
so i need  `{decodeEntities: false}` prevent chinese to be escape.

is this a bug?
or any suggestion?

**Comment by fb55** [comment]
This disables entity decoding, so this is expected.

**Comment by team6612** [comment]
I think the problem is that Chinese characters should not be decoded, same problem in #866
