### ISSUE TITLE
Modify randomly attributes

### ISSUE THREAD

**Issue by roninteger** [cheeriojs/cheerio#1125]
I am trying to modify the values of class, ID values, randomly without knowing the elements of my html content. That is, cheerio loads a html that have different content and I want to modify the content of these tags with random values of an array (classone, classnine, classtwo, id01, id05). I do not know if there are 5 divs, or 20 span, or 1 form. I have tried it in a thousand ways :

mycheerio('*').attr('class', rclass.random()).html()
mycheerio('div').attr('class', rclass.random()).html()
mycheerio('div').attr('id', rid.random()).html()

output must be:

<div id="id09">
<div id="01">
<span class="classnine"></span>
<table id="04" class="classtwo">...</span>
</div>
</div>

the help is appreciated

**Comment by fb55** [comment]
Please use stackoverflow for this kind of help.

**Comment by agarciagonzalez** [comment]
I'm also interested in this, I've been following the stackoverflow issue that has no answers. Please consider to open the issue here so people like @roninteger , me and others could solve it.
