### ISSUE TITLE
Release candidates should preferably not be default on NPM

### ISSUE THREAD

**Issue by popey456963** [cheeriojs/cheerio#1131]
Running `npm i cheerio` at the moment downloads `1.0.0-rc-2`, which seems odd to me considering it's a release candidate.  In my opinion running the command should still download `0.22.0`, whilst the latest are marked as beta.

**Comment by fb55** [comment]
New users should use the release candidate, there aren't any associated shortcomings.

**Comment by popey456963** [comment]
@fb55 I think one of the main issues is that 99% of the rest of the internet has code snippets based on the old Cheerio, not the release candidate.  For people who have already been using Cheerio, it's pretty easy to fix all the changes, but for people who are new, it can cause some confusion ("this Stackoverflow question has 400 upvotes, why isn't the code working?").

I might suggest you may be using the wrong terminology with release candidate, not sure about other people but I generally do not think of a release candidate being something you should be using for a production application.

**Comment by jwhitmarsh** [comment]
Apologies to comment on a closed issue, but I was just going through the issues to find guidance on whether we should be using the RC or not. @fb55 if the recommendation is that new users should use the RC can I suggest that the README is updated as such, or even that it's moved out of RC and is released as the full major - I'd agree with @popey456963 that an RC version is generally not a version you'd use in production.
