### ISSUE TITLE
应用案例(a example for job)

### ISSUE THREAD

**Issue by liujunjiun** [cheeriojs/cheerio#1138]
const $ = cheerio.load(data.toString());
                        isDev 
                        ? $('script[class="build"]').replaceWith(`<script src="dist/${item.index}.dev.js" class="build"></script>`)
                        : $('script[class="build"]').replaceWith(`<script src="dist/${res.assetsByChunkName[item.index][0]}" class="build"></script>`)

**Comment by fb55** [comment]
Please provide more context.
