### ISSUE TITLE
`baseURI` option

### ISSUE THREAD

**Issue by bluelovers** [cheeriojs/cheerio#1140]
a.attr('href') return att href

but a.prop('href') should can return full url when baseURI is set

**Comment by starzou** [comment]
+ 1

**Comment by starzou** [comment]
[**I found a way, hope it can help you.**](https://nodejs.org/api/url.html#url_url_resolve_from_to)

```javascript
const url = require('url');
url.resolve('/one/two/three', 'four');         // '/one/two/four'
url.resolve('http://example.com/', '/one');    // 'http://example.com/one'
url.resolve('http://example.com/one', '/two'); // 'http://example.com/two'
```

**Comment by bluelovers** [comment]
@starzou https://github.com/cheeriojs/cheerio/pull/1141
