### ISSUE TITLE
How to handle a child with a text and element combination

### ISSUE THREAD

**Issue by lesterjanpearson** [cheeriojs/cheerio#1142]
How to access both the text and the span inside the text seperately?

`<a>TEXT <span>SPANTEXT</span></a>`

**Comment by dbuezas** [comment]
I think stackoverflow should be a better place for questions. Anyway:

As far as I know there is no way of accessing the text nodes via a css query, but you can get them from the representation of their parent:

```javascript
const $ = cheerio.load(htmlString);
const $parent = $('a')
const textNodes = $parent[0].children.filter((node => node.type === 'text'));
const $elements = $parent.children();
```

it should be then possible to then wrap the text nodes again in a cheerio object `const $textNodes = $(textNodes);` if needed.

**Comment by fb55** [comment]
Thanks @dbuezas!
