### ISSUE TITLE
Why parse5 is half as slow as jsdom

### ISSUE THREAD

**Issue by harryhays** [cheeriojs/cheerio#1144]
Why is the version with 'jsdom' (0.20.0) twice (2x) faster than the new version with 'parse5' (1.0.0-rc.2)?

**Comment by KakolIsSomewhatGay** [comment]
@harryhays How exactly is this related to Cheerio?

**Comment by fb55** [comment]
jsdom was never used by cheerio and uses parse5 under the hood.
