### ISSUE TITLE
Changing document title and metatags [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [cheeriojs/cheerio#1147]
I'm using Cheerio to manipulate an html template on Node (I'm writing a webpack plugin) and I'll be manipulating (adding) mainly `<meta>`, `<script>` and `<link>` in the header.

Surprisingly I didn't find a way to set the document title: how can this be achieved? I tried:

```
    const file = fs.readFileSync(input);
    const $ = cheerio.load(file);
    $.prop('title', title);
```

It doesn't work and I don't know how to access the "document" object.

**Comment by fb55** [comment]
There is no document object. Instead, you'll need to query for a `title` tag and update it yourself.
