### ISSUE TITLE
https://cheerio.js.org/-URL not working (404)

### ISSUE THREAD

**Issue by eklem** [cheeriojs/cheerio#1154]
Seems the site is down. Waybackmachine has a last working version 25. November, 2017:
https://web.archive.org/web/20171125123909/https://cheerio.js.org/

**Comment by fb55** [comment]
Thanks for flagging — I removed some branches the other day, which apparently accidentally included the `gh-pages` branch. The website was out of data anyway, so I've replaced it with a page generated from our readme.

The TOC isn't displaying correctly, which should be fixed eventually.
