### ISSUE TITLE
Can we make automatically on dom click

### ISSUE THREAD

**Issue by vishnusinghchauhan** [cheeriojs/cheerio#1180]
Can we make automatically on dom click
it is possible like  this ??

$('.navigation.vertical-navigation li:nth-child(1) a').click();

$('.navigation.vertical-navigation li:nth-child(1) a').trigger('click');

**Comment by fb55** [comment]
cheerio doesn't execute JS

**Comment by jugglinmike** [comment]
For future reference, be sure to check the project's README file:

> ## Cheerio is not a web browser
>
> Cheerio parses markup and provides an API for traversing/manipulating the resulting data structure. It does not interpret the result as a web browser does. Specifically, it does *not* produce a visual rendering, apply CSS, load external resources, or execute JavaScript. If your use case requires any of this functionality, you should consider projects like [PhantomJS](http://phantomjs.org/) or [JSDom](https://github.com/tmpvar/jsdom).
