### ISSUE TITLE
find() allows to select parent element

### ISSUE THREAD

**Issue by martinsbalodis** [cheeriojs/cheerio#1181]
CSS selector passed to `find()` can also select parent element. jQuery `find()` only works with child elements.

Here is an example:
```javascript
const cheerio = require('cheerio');
const $ = cheerio.load('<div class="root"><span>no</span><div><span>yes</span></div></div>');

const childElements = $('.root').find("div span");

childElements.each(function(){
	console.log($(this).text());
});

// output:
no
yes

// expected output:
yes
```

**Comment by vsDizzy** [comment]
closest()

**Comment by hyurl** [comment]
My program encountered this problem too, definitely a BUG.
My current solution is using `find("div").find("span")` instead of `find("div span")`.

**Comment by tactyc** [comment]
You can just use a proper selector as well.
`find("div > span")` -> finds span under a div tag

**Comment by fb55** [comment]
This should be solved with the latest release!

**Comment by Nawfal07** [comment]
> closest()
Thanks that helped me
