### ISSUE TITLE
v1.0: Omitting the root element when rendering markup

### ISSUE THREAD

**Issue by jugglinmike** [cheeriojs/cheerio#1185]
As part of [the effort to normalize the API and promote consistency with jQuery](https://github.com/cheeriojs/cheerio/issues/1122), I'd like to deprecate the static `html` method of the "loaded" Cheerio factory function.

This conflicts with the documentation for 1.0, which reads:

> ### Rendering
> When you're ready to render the document, you can use the `html` utility function:
>
> ```js
> $.html()
> //=>  <ul id="fruits">
> //      <li class="apple">Apple</li>
> //      <li class="orange">Orange</li>
> //      <li class="pear">Pear</li>
> //    </ul>
> ```
>
> If you want to return the outerHTML you can use `$.html(selector)`:
>
> ```js
> $.html('.pear')
> //=> <li class="pear">Pear</li>
> ```

Instead, I would like to recommend the use of the `load` method exported by the Cheerio module, as in:

```js
var $ = cheerio.load('<h1>Hi</h1>');
$.html($.root());
```

This usage limits the Cheerio-specific API to the `root` function, which we have no intention of removing. Unfortunately, the pseudo-element `<root>` shows up in the rendered output:

    $ node -p 'cheerio = require("./"); $=cheerio.load("<h1>hi</h1>"); cheerio.html($.root())'
    <root><html><head></head><body><h1>hi</h1></body></html></root>

@fb55 Do you think we can omit `<root>` from the rendered output?

**Comment by yPangXie** [comment]
Is there any progress on this issue mentioned by the last sentence?

> This usage limits the Cheerio-specific API to the root function, which we have no intention of removing. Unfortunately, the pseudo-element <root> shows up in the rendered output:
> ```javsacript
> $ node -p 'cheerio = require("./"); $=cheerio.load("<h1>hi</h1>"); cheerio.html($.root())'
> <root><html><head></head><body><h1>hi</h1></body></html></root>```

**Comment by jugglinmike** [comment]
Actually, this doesn't appear to be an issue.

Quick recap: for code like

    $.html()

I was trying to suggest a replacement with the `html` static method::

    cheerio.html($.root())

As I recall, I was trying to accommodate use cases that required the doctype be present in the output. (We had recognized that invocations such as `cheerio.html($('html'))` would never include the doctype.) The solution was flawed, though, and I was struggling to handle the presence of the `<root>` element.

Six months later, the answer seems obvious.

Our recommendation should instead be to call the `html` *instance* method on the root selection:

    $.root().html()

Applying that to the example above shows that (logically) there is no `<root>` element in the rendered output:

    $ node -p 'cheerio = require("./"); $=cheerio.load("<h1>hi</h1>"); $.root().html()'
    <html><head></head><body><h1>hi</h1></body></html>

This also captures the element doctype (where present):

    $ node -p 'cheerio = require("./"); $=cheerio.load("<!DOCTYPE html><html><h1>hi</h1></html>"); $.root().html()'
    <!DOCTYPE html><html><head></head><body><h1>hi</h1></body></html>

This seems obvious to me now. I can't tell if I'm missing something that I took for granted back then or if I was just being a little thick.

If this is right, then no code change is necessary--just an update to the docs. We might even consider deprecating `cheerio.html` and `cheerio.text` (that is, in *addition* to deprecating `$.html` and `$.text`) in 1.0. That would be great since it would further shrink the Cheerio-specific API (especially helpful given the conflating names).

But I'm getting ahead of myself. @yPangXie does that work for you? @fb55 do you think that's sufficient in general?

**Comment by fb55** [comment]
Love this idea. Simple solution for a complex issue. Also all for shrinking the API surface.

**Comment by jugglinmike** [comment]
Between @fb55's support and @yPangXie's silence, I'm inclined to think that this is a non-issue, after all. Happy to close accordingly :)
