### ISSUE TITLE
Expose the CSSselect object

### ISSUE THREAD

**Issue by chocolateboy** [cheeriojs/cheerio#1186]
I have a couple of custom pseudo-classes I'd like to use in Cheerio and make available as modules i.e. Cheerio selector plugins. [css-select](https://github.com/fb55/css-select) provides an easy way to add, modify, or remove pseudo-classes via `CSSselect.filters` and `CSSselect.pseudos`, but Cheerio doesn't expose its `CSSselect` object (function) or take it as a parameter, so there's no way to access that functionality.

I guess the easiest way would be to make it available on the Cheerio export e.g.:

```javascript
import Cheerio, { select } from 'cheerio'

console.log(select.filters) // { has: ..., not: ..., ... }
console.log(select.pseudos) // { empty: ..., visited: ..., ... }
```

Then plugins could easily work with Cheerio, or css-select, or both e.g.:

```javascript
function register (target) {
    const cssSelect = target.select || target

    Object.assign(cssSelect.filters, { ... })
    Object.assign(cssSelect.pseudos, { ... })
}
```

**Comment by fb55** [comment]
As a temporary solution:

This is a bit finicky based on your package manager, but as one option: You can `require` css-select from your code, and should get the version that cheerio uses.

Ultimately I agree that we should expose these through cheerio. I'll keep this open as a feature request.
