### ISSUE TITLE
replaceWith makes attributes small casing

### ISSUE THREAD

**Issue by reddyrenuka** [cheeriojs/cheerio#1187]
I am trying to replace a span element with another html tag using replaceWith.

However, the attributes in the new html tag are converted to small casing. Expected behaviour is to have attributes casing to be unchanged.

e.g. <span id = "123>apple</span> when being tried to replace with <test contextRef="123">Changed</test>

Output changes to <test contextref="123">Changed</test>

**Comment by fb55** [comment]
You need to enable xml mode to make this possible.
