### ISSUE TITLE
Support for...of and entries iteration?

### ISSUE THREAD

**Issue by papandreou** [cheeriojs/cheerio#1191]
Hi!

I wanted to do some quick scraping and found `$(...).each(() => {...})` a bit uncomfortable now that we have `for ... of` in ES6. Basically I'd like to do the following:

```js
const cheerio = require('cheerio');
const $ = cheerio.load(myHtml);
for (const element of $('.someClass')) {
  // ...
}

for (const [index, element] of $('.someOtherClass').entries()) {
  // ...
}
```

I whipped up a quick patch that allows the above syntax:

```js
const cheerio = require('cheerio');

cheerio.prototype[Symbol.iterator] = function* () {
  for (let i = 0; i < this.length; i += 1) {
    yield this[i];
  }
};

cheerio.prototype.entries = function* () {
  for (let i = 0; i < this.length; i += 1) {
    yield [i, this[i]];
  }
};
```

LMK if this is out of scope -- if not I'll whip up a PR.

**Comment by fb55** [comment]
I think this would be a pretty cool feature, even though we would loose compatibility with old node versions.

**Comment by papandreou** [comment]
I think we'd have a shot at making it backwards compatible.

**Comment by jugglinmike** [comment]
Agreed--we can and should maintain backwards compatibility just as jQuery did when [it introduced this
feature](http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/). Let's skip introducing an `entries` method since [that doesn't exist in jQuery](http://api.jquery.com/?s=entries).

**Comment by papandreou** [comment]
Hah, I didn't even know that jQuery supported this :)

I can certainly live without `entries`, I mostly put it in for completeness sake.

**Comment by papandreou** [comment]
Opened a PR: #1197

**Comment by tuzmusic** [comment]
As a user is there anything I need to do to use this functionality? I'm still getting an error on:
```nodejs
const metaNodes = $('meta');

const properties = {};
for (const { attribs } of metaNodes) {
    if (attribs.property) {
        properties[attr.property.split(':')[1]] = attr.content;
    }
}
```

**Comment by papandreou** [comment]
No, it should just work. “An error”? Can you be a bit more specific? 😅

**Comment by fb55** [comment]
This hasn't been published yet. The next release will include iterator support.

**Comment by tuzmusic** [comment]
> This hasn't been published yet. The next release will include iterator support.

Even though it's merged, as this page shows? I guess I'm not familiar with the process and this may be more of an off-topic question.

**Comment by fb55** [comment]
The process is (1) code is merged to the repo, then (2) a number of changes are bundled up and released to npm. This change has only made it past (1) right now.

**Comment by tuzmusic** [comment]
Ah, of course, very clear! Thank you!
