### ISSUE TITLE
attributes in capital letter

### ISSUE THREAD

**Issue by ampgular** [cheeriojs/cheerio#1196]
Hi everybody, I am manipulating some angular code with cheerio and I will like to add *ngIf="loadReady" as an attribute for a div.
So far so good, nevertheless the result look like *ngif="loadReady" with the I of the attribute in lower case.
This give a problem in my angular code.
Is there a way to pas the attribute in capital letters?
Thanks in advance!!

**Comment by okashirin** [comment]
Try it
```
var $ = cheerio.load(html, { 
  xmlMode: true,
})
```
