### ISSUE TITLE
No lockfile?

### ISSUE THREAD

**Issue by bencooper222** [cheeriojs/cheerio#1199]
This package doesn't contain a `yarn.lock` or `package-lock.json`. Is there any design reason for this? Lockfiles should generally be pushed because they give more [consistent builds](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/).

**Comment by fb55** [comment]
The last release was before npm introduced `package-log.json` files. Future releases will probably feature them, just hasn't been a priority so far.
