### ISSUE TITLE
style property becames garbled

### ISSUE THREAD

**Issue by FernandoCesarS** [cheeriojs/cheerio#1201]
After parsing an html file the following div tag

`<div style="text-align:center; font-family:" Gill Sans ", "Gill Sans MT ", "Myriad Pro ", "DejaVu Sans Condensed ", Helvetica, Arial, sans-serif; font-size:12px;">`

changed to

`<div style="text-align:center; font-family:" gill="" sans ",=" " "gill="" sans="" mt ",=" " "myriad="" pro ",=" " "dejavu="" condensed ",=" " helvetica,=" " arial,=" " sans-serif;=" " font-size:12px;"="">`

'=' signs and comas were added. This is not standard HTML/CSS.

**Comment by fb55** [comment]
That div tag is also not valid html.
