### ISSUE TITLE
? .classname:nth-child(n) doesn't work, but  td:nth-child(n) does?

### ISSUE THREAD

**Issue by nowherenearithaca** [cheeriojs/cheerio#1202]
I just noticed that a selector of the form $(".classname:nth-child(n)") didn't work, but $("td:nth-child(n)").  Is this by design according to the css spec?

**Comment by LoganDark** [comment]
No, it is not.

**Comment by fb55** [comment]
Please add more context. This is supposed to work, everything else would be a bug.

**Comment by nowherenearithaca** [comment]
thanks - that info is useful to know
