### ISSUE TITLE
Tips for improving performance when using cheerio?

### ISSUE THREAD

**Issue by nowherenearithaca** [cheeriojs/cheerio#1205]
btw - I checked on stackoverflow first

I am curious if there are some basic tips based on how cheerio is built that could improve performance.  

Maybe some tips from those of you have been using cheerio for a while?

Or has it never been an issue for you?

**Comment by fb55** [comment]
The biggest one is going to be that cheerio doesn't save intermediate results. This is a performance optimization that jQuery does that cheerio has a hard time doing as it runs into memory issues much sooner (as there could be hundreds of loaded pages at a time).

**Comment by nowherenearithaca** [comment]
I could maybe look at playing with that, by doing a quick enable if possible and bumping up memory for node if possible - what I am wondering about is saving the parsed structure for later reloading that might have some performance benefit since you wouldn't need to parse it but once.

**Comment by fb55** [comment]
Assuming this has been resolved.
