### ISSUE TITLE
el.prop("tagName") throws error when el is a text node?

### ISSUE THREAD

**Issue by nowherenearithaca** [cheeriojs/cheerio#1206]
Text nodes don't seem to have a "name" property, so this line throws an error since there is check for that (at least it did for me)

https://github.com/cheeriojs/cheerio/blob/master/lib/api/attributes.js#L126

```
     case 'tagName':
     case 'nodeName':
     property = this[0].name.toUpperCase();
```

**Comment by fb55** [comment]
This was fixed in a recent release.
