### ISSUE TITLE
Feature request: The options to have .each() passes in cheerio object rather than element?

### ISSUE THREAD

**Issue by Kotsuha** [cheeriojs/cheerio#1207]
Actually I am not sure if this is a proper request or is there workarounds or something. I've asked this [question](https://stackoverflow.com/questions/50788225/is-there-a-way-to-avoid-having-to-pass-both-and-foo-when-using-each-inside) on SO and currently waiting for replies. After I asked the question and kind of changed how my functions work, I thought the need is gone. But today I encounter another use case which again makes me wish there's the opportunity to have .each() gives me a cheerio object rather than a normal element, so I don't need to $() wrap again. So here I am... :)

Is there possibilities for this?

**Comment by fb55** [comment]
This would be a severely breaking change, so unfortunately this won't be possible.
