### ISSUE TITLE
data(k,v) does not look to be implemented (while attr(k,v) does)

### ISSUE THREAD

**Issue by kaemu** [cheeriojs/cheerio#1210]
Hello Cheerio
According the doc, we should assign a value to a data prefixed attribute with .data(key, val), but it does not look to work. Do I make a mistake somewhere or is it a bug?

```
const $ = require('cheerio').load("<p data-a>Foo</p>", {encoding: 'utf-8', decodeEntities: false });

// Doesn't work:
$('[data-a]').data('a','Boo');
console.log($.html());

// Works:
$('[data-a]').attr('data-a', 'Boo');
console.log($.html());
```

**Comment by fb55** [comment]
This is intentional behavior. Data changes are not forwarded to the final html.
