### ISSUE TITLE
cheerio can not handle `<img src="">` and `<custom-element/>` accurately at the same time(use xmlMode or not)

### ISSUE THREAD

**Issue by lovetingyuan** [cheeriojs/cheerio#1215]
when set `xmlMode` true, cheerio can not handle `<img src="">` (without trailing slash '/' as '/>') correctly,
but if not use xmlMode, cheerio can not handle `<custom-element />` correctly,
so how can I handle this?
```html
<div id="container">
  <img  src=""/>
  <img src="">
  <p></p>
  <my-component title="this tag is invalid in html5, it will wrap reset elements" />
  <my-component></my-component>
  <p></p>
</div>
```
I hope the result of `$('#container').children().length === 6` could be true

**Comment by FredLavoie** [comment]
@lovetingyuan did you ever find a solution for custom elements?

**Comment by lovetingyuan** [comment]
> @lovetingyuan did you ever find a solution for custom elements?

I forget this. But Custom elements cannot be self-closing. So It is not cheerio's issue.
Maybe you can try to use `happy-dom`. It is better than jsdom, but not support jquery like api.

**Comment by FredLavoie** [comment]
@lovetingyuan I'm curious if you have successfully targeted the children of custom elements, is it possible with Cheerio?

Example:
```html
<div>
  <my-custom-element>
    <h3>Hello!</h3>
  </my-custom-element>
</div>
```

Using Cheerio JS, I cannot seem to target the inner h3, I can only go as deep as the custom element. Cheerio tells me this custom element has no children.

**Comment by lovetingyuan** [comment]
> @lovetingyuan I'm curious if you have successfully targeted the children of custom elements, is it possible with Cheerio?
> 
> Example:
> 
> ```
> <div>
>   <my-custom-element>
>     <h3>Hello!</h3>
>   </my-custom-element>
> </div>
> ```
> 
> Using Cheerio JS, I cannot seem to target the inner h3, I can only go as deep as the custom element. Cheerio tells me this custom element has no children.

I can not reproduce your case.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/7310471/216496084-944ecc93-f7ed-4ffb-9590-145dea4dd7d0.png">
