### ISSUE TITLE
Structure of DOM "node"

### ISSUE THREAD

**Issue by RevealedFrom** [cheeriojs/cheerio#1218]
Has the [DOM Node object](https://github.com/cheeriojs/cheerio#the-dom-node-object) been changed?

What I am seeing is (sample img tag) is:

     { type: 'tag',
       name: 'img',
       namespace: 'http://www.w3.org/1999/xhtml',
       attribs: { src: '...', data: 'dfd' },
       'x-attribsNamespace': { src: undefined, data: undefined },
       'x-attribsPrefix': { ... },
       children: [],
       parent: ... ,
       prev: ... ,
       next: ... 
    }

**Comment by fb55** [comment]
The properties exist, but are part of the object's prototype, which you won't see by default when rendering it like this.
