### ISSUE TITLE
Escaped html transformed to unescaped html

### ISSUE THREAD

**Issue by ViktorQvarfordt** [cheeriojs/cheerio#1219]
I found a nasty bug that affects `.html`, `.replaceWith` and possibly more.

**Minimal reproducing example:**

```js
$ = cheerio.load('', { decodeEntities: false })
$('body').html('&lt;')
console.log($('body').html())
// Prints <
// Meaning that escaped html got turned into unescaped html
```

cheerio version 1.0.0-rc.2

This is very problematic if you have nicely escaped characters that you want to insert into your DOM, then the result will become invalid html.

**Comment by AlynxZhou** [comment]
The same, if you set `decodeEntities` to `true`, you will get CJK characters escaped, but if false, cheerio will replace user escaped characters wrongly.

**Comment by rdmclin2** [comment]
same issue, any solutions?

**Comment by fb55** [comment]
This should be resolved with the latest release.
