### ISSUE TITLE
Html format exception

### ISSUE THREAD

**Issue by channg** [cheeriojs/cheerio#1221]
```
const cheerio = require('cheerio')
const fs = require('fs')
let $ = cheerio.load(fs.readFileSync('./index.html'))
fs.writeFileSync('./cheerio.html',$.html())
```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
```
cheerio.html
```
<!DOCTYPE html><html lang="en"><head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


</body></html>
```

I didn't do anything, but the format changed.

Both mac and windows will appear
```
"cheerio": "^1.0.0-rc.2"
```

**Comment by fb55** [comment]
Cheerio doesn't guarantee whitespace to stay the same. Our goal is to make documents behave the same in your browser after using cheerio. You might want to look into using a tool like `prettier` that specializes in pretty-printing HTML.
