### ISSUE TITLE
Terminate statements in example code with a semicolon

### ISSUE THREAD

**Issue by Lukenickerson** [cheeriojs/cheerio#1222]
Examples in the readme should end their statements with a semicolon.

As per the code style guide https://github.com/cheeriojs/cheerio/blob/master/CONTRIBUTING.md#code-style ... 

> Terminate every statement with a semicolon

...but in the examples in https://github.com/cheeriojs/cheerio/blob/master/Readme.md very few of the statements end with a semicolon. This can be especially confusing to new developers, who are most likely to need to follow the examples.

**Comment by fb55** [comment]
This has been resolved after using Prettier to format everything.
