### ISSUE TITLE
The slash in url in inline styles are removed

### ISSUE THREAD

**Issue by chiqui3d** [cheeriojs/cheerio#1223]
When in the document there is some inline style of the type:
`<div style="background-image: url("//domain.com/assets/image.jpg");"></div>`
The slash are remove

leaving the result with spaces:

`<div style="background-image: url("domain.com assets image.jpg");"></div>`

**Comment by Mialur** [comment]
Actually quotes inside double quoted attribute value won't work.
Missing slashes are consumed by parser, with attempt to find self closing tag.

**Comment by 5saviahv** [comment]
Attribute format is invalid:
``` html
<div style="background-image: url("//domain.com/assets/image.jpg");"></div>
           ^                      ^                             ^  ^
```
You can resolve it either: 

1. Use mixed quotes - use single quotes either internally or externally
``` html
<div style="background-image: url('//domain.com/assets/image.jpg');"></div>
                                  ^                             ^   
<div style=`background-image: url("//domain.com/assets/image.jpg");`></div>
           ^                                                       ^
```
2. Escape internal quotes with `&quot;`
``` html
<div style="background-image: url(&quot;//domain.com/assets/image.jpg&quot;);"></div>
                                  ^^^^^^                             ^^^^^^
```

**Comment by fb55** [comment]
Great answer @5saviahv, and happy to see you get started 💯
