### ISSUE TITLE
All examples are broken for v1.0.0 (rc2) - cheerio outputs html-tags

### ISSUE THREAD

**Issue by tyranteon** [cheeriojs/cheerio#1239]
Running the example
```js
const cheerio = require('cheerio')
const $ = cheerio.load('<h2 class="title">Hello world</h2>')

$('h2.title').text('Hello there!')
$('h2').addClass('welcome')

$.html()
//=> <h2 class="title welcome">Hello there!</h2>
```

it's supposed to print out `<h2 class="title welcome">Hello there!</h2>`, however, it prints `<html><head></head><body><h2 class="title welcome">Hello there!</h2></body></html>`

This breaks my workflow, because I'm using it to preprocess vue.js templates (i.e. html snippets) and putting <html> tags there inside of the `<template>` tags breaks everything.

repro: https://repl.it/repls/ImmediateWittyAnalysts

**Comment by weyusi** [comment]
See https://github.com/cheeriojs/cheerio/issues/1031

**Comment by fb55** [comment]
Thanks @curbengh
