### ISSUE TITLE
.data updates not rendered

### ISSUE THREAD

**Issue by tgandrews** [cheeriojs/cheerio#1240]
Changes to data attributes are updated but not rendered back out.

```
const cheerio = require("cheerio");

const $ = cheerio.load('<div data-a="1" />')
const $el = $("div");
$el.data("a", "2");
console.log($el.data("a"))
console.log($.html($el));
```
[Running Example](https://repl.it/repls/ShimmeringUnselfishDebuggers)

Expected:
```
2
<div data-a="2" />
```
Result:
```
2
<div data-a="1" />
```

Making the following changes resolve it
```patch
-- $el.data("a", "2");
++ $el.attr("data-a", "2")
```

**Comment by fb55** [comment]
This is intentional behavior. Data changes are not forwarded to the final html.
