### ISSUE TITLE
A selector relative to the parent selector does not work (different behaviour from jQuery)

### ISSUE THREAD

**Issue by gajus** [cheeriojs/cheerio#1244]
```js
const subject = `
<div>
  <p class='a'>FOO</p>
  <p class='b'>BAR</p>
</div>
`;

const $ = cheerio
  .load(subject, {
    xmlMode: false
  })
  .root();

console.log($.find('.a').find('+.b').length);

```

Actual result: 0
Expected result: 1

If you try the same in jQuery, you will get the expected result. https://codepen.io/anon/pen/WaqdEN

Scoped search with a predefined context does not work either:

```js
const subject = `
<div>
  <p class='a'>FOO</p>
  <p class='b'>BAR</p>
</div>
`;

const $ = cheerio
  .load(subject, {
    xmlMode: false
  })
  .root();

console.log($.find('+.b', $.find('.a')).length);

```

Actual result: 0
Expected result: 1

Again, it works in jQuery. https://codepen.io/anon/pen/oarpod

**Comment by gajus** [comment]
@jugglinmike am I overlooking something obvious?

**Comment by gajus** [comment]
Related:

* https://github.com/cheeriojs/cheerio/issues/867
* https://github.com/fb55/css-select/issues/42

@fb55 Has this been fixed?

**Comment by gajus** [comment]
Tested https://github.com/cheeriojs/cheerio/tree/v1.0.0 branch with the latest https://github.com/fb55/css-select/issues/42 changes. Same issue persists.

**Comment by fb55** [comment]
Has not been fixed yet, generally a pretty gnarly issue. Happy to accept PRs for this!

**Comment by gajus** [comment]
> Has not been fixed yet, generally a pretty gnarly issue. Happy to accept PRs for this!

Is there a workaround that you propose at the moment?

Some meta selector such as `:scope` or whatever.

**Comment by fb55** [comment]
`:scope` is implied when the selector starts with `>`. This very much seems like a bug when passing contexts.
