### ISSUE TITLE
don't automatically adding <html><head><body> 

### ISSUE THREAD

**Issue by xianghongai** [cheeriojs/cheerio#1247]
file stream is a file stream,

browser environment is browser environment,

complete the expected operation, no extra addition, even though the target might have been a risk, that risk, the target owner controls it. maybe it was meant to be that way, not a risk.

#1031

**Comment by jugglinmike** [comment]
We'll track this via the existing issue. Feel free to add any new perspective to that discussion thread

**Comment by timthedev07** [comment]
Is this still not available as an extra option?

**Comment by 5saviahv** [comment]
No there is no extra option for that but at the end of connected issue #1031 has [comment](https://github.com/cheeriojs/cheerio/issues/1031#issuecomment-748677236) what may help you !

basically if you load document as fragment - elements like _html_, _body_ and _head_ will not be added.

**Comment by timthedev07** [comment]
Thanks!
