### ISSUE TITLE
How to find a part of javascript code?

### ISSUE THREAD

**Issue by Mustafax06** [cheeriojs/cheerio#1250]
I want to find `window.$zopim` keyword or `v2.zopim.com` in the parsed html's scripts. the full code seems like this;

    window.$zopim || (function (d, s) {
        var z = $zopim = function (c) { z._.push(c) }, $ = z.s =
            d.createElement(s), e = d.getElementsByTagName(s)[0]; z.set = function (o) {
                z.set.
                _.push(o)
            }; z._ = []; z.set._ = []; $.async = !0; $.setAttribute("charset", "utf-8");
        $.src = "https://v2.zopim.com/?50MofDmMQgUTFjmn2Jyq7lMMFEAqicg6"; z.t = +new Date; $.
            type = "text/javascript"; e.parentNode.insertBefore($, e)
    })(document, "script");`

I  have almost 250 web sites need to search. Can any body help to do that please? Does cheerio support this?

**Comment by fb55** [comment]
This seems to depend on execution of JS code, which cheerio does not support.
