### ISSUE TITLE
Aliexpress crawling issue nodejs please help 

### ISSUE THREAD

**Issue by ouahibAbdou** [cheeriojs/cheerio#1258]
Issue: sometimes it works and gives a list of categories but other not work
Image:
![image](https://user-images.githubusercontent.com/30089652/49789503-13583d00-fd24-11e8-8452-574580641346.png)
Code:
import Crawler from "crawler";

let c = new Crawler({
    maxConnections: 10,
    // This will be called for each crawled page
    callback: (error, res, done) => {
        if (error) {
            console.log(error);
        } else {
            let $ = res.$;

            let categories = []

            $('.cg-main .item').map((tid, ntype) => {

                let rtype = { name: $(ntype).find('.big-title').text().trim(), sub: [] }

                $(ntype).find('.sub-item-cont a').map((sid, subs) => {
                    rtype['sub'].push("" + subs + "")
                })
                categories.push(rtype)

            })
            console.log(categories) 

        }
        done();
    }
});

c.queue('https://www.aliexpress.com/all-wholesale-products.html');

**Comment by fb55** [comment]
I assume @luanmuniz's response fixed this :)
