### ISSUE TITLE
Parse failure

### ISSUE THREAD

**Issue by dandavison** [cheeriojs/cheerio#126]
Cheerio seems to fail to parse this HTML: http://pastebin.com/iEurSsVW obtained from http://www.politico.com/

I believe the problem lies with the javascript in the script tag starting at line 1575. The JS  contains an embedded script tag itself, which may be badly escaped. I'm not very experienced with this style of HTML, perhaps this is a WontFix for cheerio?

That parsing has failed is shown by the fact that queries like `$('#secondaryContent')` are successful when referring to elements prior to line 1575 but not afterwards (e.g. `$('#popularMostRead')`).

Thanks very much for cheerio, I switched to it yesterday when I couldn't get jsdom to run on heroku.

**Comment by jimmywarting** [comment]
+1 parse5

**Comment by fb55** [comment]
Fixed on the 1.0.0-RC versions.
