### ISSUE TITLE
class selector only returns first result with .html()

### ISSUE THREAD

**Issue by Cepheid-UK** [cheeriojs/cheerio#1262]
I'm scraping a page that I am 100% certain has 4 elements with the same class, but when I do 

`$('.className').html()`

It only returns the first instance of a class with <class = className>

if I do 

`$('.className').text()`

I see all the data within the elements correctly.

It seems that: 

`$.html($('.className'));`

correctly returns what I was expecting from .html(), is this intentional?

**Comment by Gei0r** [comment]
That's expected behavior. From the [docs](https://github.com/cheeriojs/cheerio#html-htmlstring-):

> Gets an html content string from the first selected element.

It's the same behavior in [jquery](http://api.jquery.com/html/).

**Comment by dhruvgajwa** [comment]
You should use each((i, ele)=> {
})  callback

eg.
```
$('.browse-events-wrp').children('.event-card-wrp').each((i, ele)=> {
  
  try {
    const tags =  $(ele).attr('data-tags');
    
  }
  catch(e) {
      console.log(e);
  }

});
```

**Comment by fb55** [comment]
Thanks @Gei0r!
