### ISSUE TITLE
Fastest possible way to see if an element exists

### ISSUE THREAD

**Issue by peterbe** [cheeriojs/cheerio#1265]
I'm sorry if this isn't a feature request or bug but I'm hunting for a way to use cheerio in the fastest possible way and my use case is simple. I just want to find out if an element *exists*. I don't need the element or know how many there are.

What I'm currently doing is something like this:

```javascript
const $ = cheerio.load(htmlString)
cssselectors.forEach(selector => {
  if ($(selector).length) {
    console.log('It exists!')
  } else {
    console.log('Does not exist')
  }
}
```
In my [use case](https://github.com/peterbe/minimalcss/issues/287) I have hundreds or thousands of CSS selectors and I just want to find out, for each one, if there exists an element at all.

**Comment by fb55** [comment]
First thing that comes to mind is to use `css-select` directly (`cheerio` uses `css-select` as its selector engine). Something like this:

```js
const {selectOne} = require('css-select')

const $ = cheerio.load('<document>')
const doesElementExist = !!selectOne('.someSelector', $.root().get(), $._options)
```

This way, each search terminates as soon as an element was found.

**Comment by fb55** [comment]
Another option would be to use 

```js
$.root().filter(`:scope:has(${mySelector})`)
```
