### ISSUE TITLE
.text() donot work in version 1.0.0-rc.2

### ISSUE THREAD

**Issue by milu2003** [cheeriojs/cheerio#1267]
version  1.0.0-rc.2：

```
let text = `<title><span>标题</span></title>`;
let res = $c('title').text(); 

```

The result is  

```
<span>标题</span> 

```
 The result I expect is  
```
标题
```

0.22.0 version No problem.

**Comment by fb55** [comment]
`title` tags in HTML are special and can only have text contents. Use `xmlMode: true` to parse this as XML.
