### ISSUE TITLE
Ur old friend "Cannot read property 'prototype' of undefined"

### ISSUE THREAD

**Issue by ExplodingBanana** [cheeriojs/cheerio#1268]
_I've already looked for some other solutions, but unsucessfully._

There's my project, that I've just started. Simple express app (also, there's underscore.js ¯\_(ツ)_/¯)
[project.zip](https://github.com/cheeriojs/cheerio/files/2760119/project.zip)

Oh, if u curious about error:
 `bundle.js:4856 Uncaught TypeError: Cannot read property 'prototype' of undefined`
    `at Object.<anonymous> (bundle.js:4856)`
    `at Object.29../utils (bundle.js:5953)`
    `at o (bundle.js:1)`
    `at bundle.js:1`
    `at Object.25../application (bundle.js:4102)`
    `at o (bundle.js:1)`
    `at bundle.js:1`
    `at Object.23../lib/express (bundle.js:3430)`
    `at o (bundle.js:1)`
    `at bundle.js:1`

**Hate my English. Cheers from Belarus**

**Comment by fb55** [comment]
It would be great if this could be reduced to an isolated issue. Right now, this is extremely hard to debug from the outside.
