### ISSUE TITLE
Find a "scri'+'pt" tagName into normal <script> | by $(elem).find('*')

### ISSUE THREAD

**Issue by denisx** [cheeriojs/cheerio#1287]

**Comment by jugglinmike** [comment]
This report lacks the information we need to help. If it is a bug report, can you please share a minimal code example, what you expect that example to do, and what it actually does? If it's a feature request, can you describe the desired functionality in general terms and include an example of how it should work?

**Comment by denisx** [comment]
it's a bug. parse this html view-source:https://alfabank.ru/press/news/2019/3/14/50834.html and you can see wrong tag

**Comment by fb55** [comment]
Closing as this is still very hard to replicated.
