### ISSUE TITLE
Parse element <post>

### ISSUE THREAD

**Issue by ElectroMyStyle** [cheeriojs/cheerio#1289]
Hello, I did not find my problem in this thread. The problem is this: on some sites there is a DOM element - <post>, which serves to embed from facebook.

`<post href="https://www.facebook.com/TeamCX/photos/a.150063808441121/2057430031037813/?type=3&amp;theater" data-width="552"></post>`

Cheerio finds this element and converts to @name="fb:post"

![Cheerio_post_embed](https://user-images.githubusercontent.com/5159210/54401842-8a61f080-46da-11e9-919f-2d71f1b89dfd.png)

It is not quite clear how to find it using the find() function if it is already impossible to specify the name of the DOM element in the function (find('post') or find('fb:post')), since the colon is recognized by the cheerio mechanism as an erroneous pseudo-class and displays an error, and the (find('post')) option does not find anything

`UnhandledPromiseRejectionWarning: SyntaxError: unmatched pseudo-class: post`

I understand that this is not a global error and maybe not at all an error, but I would like to understand why this happens and how this element can be found in the DOM after such a conversion

**Comment by fb55** [comment]
This should be part of the HTML that you receive. The way to query for this is by escaping the colon: `'fb\\:post'`.
