### ISSUE TITLE
Cannot append or prepend <style> tags

### ISSUE THREAD

**Issue by danielepolencic** [cheeriojs/cheerio#1294]
I have an SVG and I wish to append a `<style></style>` element with Cheerio.

Code:

```ts
const $ = cheerio.load(svg, { decodeEntities: false, xmlMode: true})
$('svg').prepend(`<style>body {color: red}</style>`)
```

The SVG contains a `<style/>` tag with no content.
Expected behaviour: a style tag such as `<style>body {color: red}</style>`

**Comment by danielepolencic** [comment]
Just noticed that `<script />` suffers from the same limitation.
https://github.com/cheeriojs/cheerio/issues/1042

**Comment by fb55** [comment]
Unable to replicate — looks like this is fixed.
