### ISSUE TITLE
How to access to a specific script type application/ld+json in cheerio?

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [cheeriojs/cheerio#1295]
Regards,

My problem is that I'm scraping a page, but I'm surprised that it has 3 script data structure type application / ld + json.

This is the way I'm accessing the structure:

 
     ```$('script[type="application/ld+json"]').each((index, item) => {```

My question is, how can I access the second structure using cheerio?

**Comment by xamgore** [comment]
1. Seems that you need `:nth-[last-]child[-of-type]` ([the full list of supported CSS selectors](https://github.com/fb55/css-select#supported-selectors))

2. The other option is `toArray` method:
    ```js
    $('li').toArray()
    //=> [ {...}, {...}, {...} ]
    ```

**Comment by ChrisMichaelPerezSantiago** [comment]
Thank you.

I had already solved the problem, using the same examples that you communicated to me.
