### ISSUE TITLE
Location info is not supported for parse5 in 1.0.0-rc3

### ISSUE THREAD

**Issue by halfzebra** [cheeriojs/cheerio#1296]
Hello friends!
Thanks for Cheerio, I'm happy to be able to use such a nice library. 👍 

I'd like to know what is the reasoning behind not supporting the `locationInfo` for parse5?
As far as I can see this has been possible before:
https://github.com/cheeriojs/cheerio/pull/1155/files#diff-9f97a9c36fbbfb0d19068d6fae3bb84eR26

I'm pretty interested in getting this, so I'm up for doing a PR if there are no objections.

**Comment by fb55** [comment]
@halfzebra Would love a PR!

**Comment by halfzebra** [comment]
Hi Felix!

Any chance you'll have time to have a look at the PR @fb55?

**Comment by fb55** [comment]
Done!

**Comment by halfzebra** [comment]
Thanks for merging! 👍
