### ISSUE TITLE
Removing text nodes has no effect

### ISSUE THREAD

**Issue by alexreg** [cheeriojs/cheerio#1304]
Removing a text node (non-element) by calling `node.remove()` has no effect whatsoever.

**Comment by alexreg** [comment]
Sorry, my mistake. The issue was actually caused by an html beautifier behaving incorrectly.

**Comment by cawa-93** [comment]
@alexreg May you provide example  how remove text nodes? I need to clear the string from top-level text but can't figure out how to do it
