### ISSUE TITLE
Missing whitespace in tag text between child elements

### ISSUE THREAD

**Issue by ankitkariryaa** [cheeriojs/cheerio#1306]
If an element contains children then their text is concatenated without any white space in between, whereas it is expected that they would be separated by a space. For example:
```
const cheerio = require('cheerio');
const ch = cheerio.load('<body><div id="1">Some text in the div.</div><div id="2">There should be a space before this line.</div></body>');
ch('body').text();
```

Results in:
`'Some text in the div.There should be a space before this line.'`

But in many cases, the text should be separated resulting in:
`'Some text in the div. There should be a space before this line.'`

text() should provide an option to compulsorily separate children with a space.

**Comment by fb55** [comment]
This behavior is equivalent to jQuery.

**Comment by misner** [comment]
So what was the solution ?

**Comment by eurlexa** [comment]
> .

I  am not sure if you are right. See official docs and example https://api.jquery.com/text/  

I tested it by myself and JQuery text() method keeps whitespaces between the text parts. This is very useful. Cheerio on the other hand messes text parts alltogther withou no spaces which is a pain.

**Comment by eurlexa** [comment]
> This behavior is equivalent to jQuery.

I  am not sure if you are right. See official docs and example https://api.jquery.com/text/  

I tested it by myself and JQuery text() method keeps whitespaces between the text parts. This is very useful. Cheerio on the other hand messes text parts alltogther without no spaces which is a pain.

E.g. from this ```
TITLE>
<TI>
<P>PART ONE</P>
</TI>
<STI>
<P>
<HT TYPE="BOLD">GENERAL PROVISIONS</HT>
</P>
</STI>
</TITLE>
```

I need and expect to have this text `PART ONE GENERAL PROVISIONS` but I have `PART ONEGENERAL PROVISIONS`
