### ISSUE TITLE
Keep &euro; instead of &#x20AC;

### ISSUE THREAD

**Issue by CTimmerman** [cheeriojs/cheerio#1308]
Using 1.0.0-rc.3, cheerio does not preserve things like `&euro;`, in that case `fs.writeFileSync(path, doc.html(), {'encoding': 'utf-8'})` will contain `&#x20AC;` instead. Is there a way to keep the name?

**Comment by CTimmerman** [comment]
Workaround in https://gist.github.com/CTimmerman/cf0e5f4339cd8f7922515b95d875b3b1

**Comment by fb55** [comment]
This should be resolved with the latest release.
