### ISSUE TITLE
 recognizeSelfClosing fails to process self-closing div 

### ISSUE THREAD

**Issue by idahogurl** [cheeriojs/cheerio#1312]
When I load my HTML in Cheerio, the sibling elements of a **self-closing div** become its children. I have tried both **recognizeSelfClosing** and **xmlMode**. Neither one fixes the problem. I have created an example on https://codesandbox.io/s/np4vq

**Comment by misner** [comment]
Did you find a solution ? Having roughly the same issue

**Comment by idahogurl** [comment]
@misner Unfortunately not. I'm thinking about doing some RegExp to find the self-closing div and put some dummy data as the innerHTML. I am also considering looking for a different library. It appears this project is really slow in addressing issues.

**Comment by tomjw64** [comment]
@idahogurl Sure this is still an issue? See https://codesandbox.io/s/objective-noether-tb2ct

**Comment by idahogurl** [comment]
@tomjw64 Yes

**Comment by 5saviahv** [comment]
Just for mentioning for HTML, one option would be also use **_useHtmlParser2** option, it will switch into htmlParser2 parser, but uses it in HTML mode, not in XML mode like **xmlMode** does it.

`const $ = cheerio.load(html, { recognizeSelfClosing: true, _useHtmlParser2: true });`

**recognizeSelfClosing** has no effect unless **xmlMode** or **_useHtmlParser2** is also used

**Comment by idahogurl** [comment]
This is no longer an issue for us. We found it was because we were using different parsing options in prior calls that it failed here.

**Comment by george-norris-salesforce** [comment]
Same here
```
const $ = cheerio.load(htmlStr, {
    decodeEntities: false,
    recognizeSelfClosing: true
  });
```

Nothing is self closed
