### ISSUE TITLE
$.each() not working

### ISSUE THREAD

**Issue by praveenkutty** [cheeriojs/cheerio#1313]
Hi,
I tried to loop through tags using $.each, but in my case it throws an error

This is my code,
```
let $=cheerio.load(HTML_FILE)
$("div").each(function() {
        	$.each(this.attributes,function(i,a){
            	console.log(i,a.name,a.value)
            })
	    })
```
$.each(this.attributes,function(i,a) line hits an error as below

TypeError: $.each is not a function
    at Node.<anonymous> (/home/ubu/check.js:41:18)
    at initialize.exports.each (/home/ubu/scrape2/node_modules/cheerio/lib/api/traversing.js:300:24)
    at nextAttributes (/home/ubu/check.js:36:11)
    at checkNext (/home/ubu/check.js:7:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by BernhardWebstudio** [comment]
The problem is you inner $.each, which indeed is not a function. If you just want to loop all attributes, I would suggest to do approximately like so:

```
let $=cheerio.load(HTML_FILE)
    $("div").each(function(i, div) {
         var allAttr = div.attributes;
         for (var i = 0; i < allAttr.length; ++i) {
             var a = allAttr[i]:
             console.log(i,a.name,a.value)
     })
})
```

**Comment by fb55** [comment]
Thanks @BernhardWebstudio!
