### ISSUE TITLE
Extract an element from a webpage

### ISSUE THREAD

**Issue by AjaiGanesh** [cheeriojs/cheerio#1314]
First of all its a big ask, but I really need this. I'm trying to achieve the following. 

I want to get(return) the element from an html page which has an attribute value of xyzzz, i do not want to iterate based on attribute name or the tag, and I also want to achieve this with minimal loops say 1 or 2 or no loops.

**Comment by fb55** [comment]
Please refer to StackOverflow for questions like this :)
