### ISSUE TITLE
Update parse5 version in 1.0.0-rc3

### ISSUE THREAD

**Issue by airarrazaval** [cheeriojs/cheerio#1317]
cheerio@1.0.0-rc.3 (cheerio@latest) currenlty bundles parse5@3.0.3 (^3.0.1).  This version of parse5 declared `@types/node` as dependency which adds around an extra 600KB (even in none typescripts implementations).  Currently, parse5 fixed this in parse5@4.0.0.

Please refer to https://github.com/inikulin/parse5/issues/235.

**Comment by osdiab** [comment]
Agreed. It also is forcing me to have `@types/node` available in my frontend web app, which is dangerous because now the TypeScript compiler is telling me it's OK to use Node builtins and libraries even though my app runs in a browser, where those things aren't present.

**Comment by fb55** [comment]
Fixed in the `v1.0.0` branch.
