### ISSUE TITLE
any idea to fix this ?

### ISSUE THREAD

**Issue by minanagehsalalma** [cheeriojs/cheerio#1318]
https://stackoverflow.com/questions/56516182/how-can-i-inspectdocument-body-in-js-while-loading-the-page-using-object

**Comment by fb55** [comment]
Looks like this was solved on StackOverflow

**Comment by minanagehsalalma** [comment]
@fb55  not really 
https://stackoverflow.com/questions/56744800/why-alert-didnt-work-in-a-http-onload-from-an-xmlhttprequest 

i am falling really hard in making it make sure that it worked !!
