### ISSUE TITLE
Element Attribute without Value and without Wrapping <html> and <body> Tags

### ISSUE THREAD

**Issue by joeosburn** [cheeriojs/cheerio#1320]
I have a string of html content that I'm trying to modify via cheerio that doesn't have wrapping `<html>` or `<body>` tags, and also has attributes on some of the DOM elements which don't have values. My problem is with the html that gets created when running the `html()` function. If I use `xmlMode: true`, it forces the attributes to have a blank value, but if I use `xmlMode: false`, it wraps the content with `<html>` and `<body>` tags.

See my example below:

```
> cheerio.load('<input checked>', {xmlMode: true}).html();
'<input checked=""/>'
> cheerio.load('<input checked>', {xmlMode: false}).html();
'<html><head></head><body><input checked></body></html>'
```

My ideal output would be:

```
> cheerio.load('<input checked>', {xmlMode: false}).html();
'<input checked>'
```

Is there some way to have cheerio not force the content to be wrapped by `<html>` and `<body>` tags and also not force element attributes to have a blank value?

**Comment by fb55** [comment]
You could get the inner HTML of the body element.

**Comment by joeosburn** [comment]
@fb55 Thanks for responding.

I didn't include this in the original post, but that won't work for me because I have other scenarios where the input I'm using *may* include html, body and/or head tags. And in those cases, I would like to keep those tags.

However, I was able to solve this by using some regexes to eliminate the attributes with blank values getting added.

**Comment by LeeLejia** [comment]
I had the same problem!
