### ISSUE TITLE
Discrepancy between Jquery and Cheerio

### ISSUE THREAD

**Issue by mayeaux** [cheeriojs/cheerio#1323]
Via Jquery run via the console I can easily select my element as : 

`$('.column')[0].children[0].children[1];`

However running this same code via Cheerio I receive:

`TypeError: Cannot read property '1' of undefined`

I thought Cheerio implemented DOM traversal via the same API as Jquery, but then how could this discrepancy happen? Thanks

**Comment by mayeaux** [comment]
Can confirm it's because Cheerio is inserting a :  
```
{ type: 'text',
  data: '\n      ',
...
}
```

div. However if I use the normalizeWhitespace option this has no effect. Which options can I use to have these newlines which are not recognized by Jquery on the clientside ignored by Cheerio?

**Comment by fb55** [comment]
Fixed on the 1.0.0-RC versions.
