### ISSUE TITLE
CSS selector is not working for attributes with square brackets

### ISSUE THREAD

**Issue by mertdeg2** [cheeriojs/cheerio#1328]
**Repro:**
1. `npm install cheerio`
2. `node`
3. `const cheerio = require('cheerio');`
4. `const $ = cheerio.load('<div [test]="value"></div>');` // This is a valid Angular HTML template
5. `$('[[test]]').length`

**Expected:**
Cheerio is able to find the div element. Other libraries that work with HTML (like JSoup) support this use case.

**Actual:**
SyntaxError: Malformed attribute selector: [test]]

**Comment by fb55** [comment]
The attribute name needs to be escaped.
