### ISSUE TITLE
Using Cheerio in Angular 7

### ISSUE THREAD

**Issue by vicatcu** [cheeriojs/cheerio#1332]
`npm install cheerio` didn't work for me in an Angular 7 project. Granted there are other things in the project, but `npm run build` was failing with an error like this:

```
ERROR in ./node_modules/cheerio/node_modules/parse5/lib/parser/parser_stream.js
Module not found: Error: Can't resolve 'stream' in '/home/vic/dev/my-project/node_modules/cheerio/node_modules/parse5/lib/parser'
ERROR in ./node_modules/cheerio/node_modules/parse5/lib/sax/index.js
Module not found: Error: Can't resolve 'stream' in '/home/vic/dev/my-project/node_modules/cheerio/node_modules/parse5/lib/sax'
ERROR in ./node_modules/cheerio/node_modules/parse5/lib/sax/dev_null_stream.js
Module not found: Error: Can't resolve 'stream' in '/home/vic/dev/my-project/node_modules/cheerio/node_modules/parse5/lib/sax'
ERROR in ./node_modules/cheerio/node_modules/parse5/lib/serializer/serializer_stream.js
Module not found: Error: Can't resolve 'stream' in '/home/vic/dev/my-project/node_modules/cheerio/node_modules/parse5/lib/serializer'
```

I had to follow the advice in this Blog Post as a workaround: https://blog.lysender.com/2018/07/angular-6-cannot-resolve-crypto-fs-net-path-stream-when-building-angular/

I also did `npm install parse5@^3.0.0 --save` in the root of my project.

That seems really brittle to me, and I'm not sure this is something that cheerio.js can address. But I think it might be useful / helpful to have this issue here for other developers to follow the breadcrumbs, and maybe a mention in the README.md.

**Comment by gajus** [comment]
Angular is a client-side framework. Cheerio is a Node.js script. They are for the most part incompatible.

What is your use case?

**Comment by vicatcu** [comment]
I want to deliver some HTML from the server to my app, parse it into a structure that I can manipulate, make some changes to it, and then attach the transformed content to the innerHTML of a div. I'm doing so quite successfully actually. Except I have to put in that workaround. So it's not _really_ incompatible, but it's unfortunate that you have to patch in this workaround to "get it to work."

**Comment by wsw87201326** [comment]
i run `npm i cheerio --save` and `npm i @types/cheerio --save`,then `import * as cheerio from 'cheerio';` in my component. paste
 `const $ = cheerio.load('<h2 class="title">Hello world</h2>')
    $('h2.title').text('Hello there!');
    $('h2').addClass('welcome');
    $.html();` in ngOnInit.
An error occurred ： 
Uncaught ReferenceError: global is not defined
    at Object../node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/safe-buffer/index.js (index.js:2)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:55)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/readable-stream/readable-browser.js (readable-browser.js:1)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/stream-browserify/index.js (index.js:28)
    at __webpack_require__ (bootstrap:79)

**Comment by cnscorpions** [comment]
@wsw87201326 global in Node.js is the counterpart of window in javascript. So it may be improper to use ng with cheerio together. You can include cheerio in a node.js app.

**Comment by vicatcu** [comment]
@cnscorpions "improper" or not... am I unclear that it _works_ if I patch webpack. The fact is I have a practical use case for it, and it's possible to support the browser, so why not?

**Comment by ihsanberahim** [comment]
i agree with @vicatcu .

I found that this error resolved by doing these, thanks to @wsw87201326 for the hint

1.
```
npm i @types/cheerio --save
```

2.
then replace `import cheerio from 'cheerio'` to `import * as cheerio from 'cheerio'`

error related to `global` is different issue.

**Comment by ihsanberahim** [comment]
`npm i stream`

it works for me.

reference https://stackoverflow.com/a/55601717/2342289

**Comment by vicatcu** [comment]
Just to update the breadcrumb trail, the browser.js file that needs patched in the webpack config is located in node_modules/@angular-devkit/build-angular/src/webpack/configs as of Angular 11

**Comment by fb55** [comment]
The latest release should have removed all native dependencies
