### ISSUE TITLE
Whitespace removed between <html> and <head>

### ISSUE THREAD

**Issue by graue** [cheeriojs/cheerio#1336]
In cheerio@1.0.0-rc3, whitespace between the opening `<html>` and `<head>` is getting removed. Here's an example in the Node REPL:

```
> const cheerio = require('cheerio')
undefined
> const $ = cheerio.load('<html>\n\n<head>\n<title>Foo</title>\n\n<body>\n\n</body>\n</html>')
undefined
> $.html()
'<html><head>\n<title>Foo</title>\n\n</head><body>\n\n\n</body></html>'
```

My understanding based on the readme is that `normalizeWhitespace` defaults to `false`, so this shouldn't be happening. It's presenting a challenge for my use case because I need accurate line numbers in JavaScript error stacks for code embedded in the transformed HTML.

**Comment by fb55** [comment]
This should be resolved with the latest release.
