### ISSUE TITLE
HTML Encoded Line Feed characters being removed - &#xA; 

### ISSUE THREAD

**Issue by gitnan** [cheeriojs/cheerio#1349]
Hi All,

Has anyone else encountered line feed characters being removed? The hex value: `&#xA;` is being removed after parsing and this is causing issues once rebuilding the file.

**Comment by fb55** [comment]
```
> cheerio.load('&#xA;').html()
'<html><head></head><body></body></html>'
> cheerio.load('<p>&#xA;').html()
'<html><head></head><body><p>\n</p></body></html>'
```

It looks like they are removed only in a context that doesn't allow whitespace, and otherwise are replaced with the decoded character, which is valid in HTML documents.
