### ISSUE TITLE
Cant install cherrio(npm ERR! 404 Not Found: cherrio@latest)

### ISSUE THREAD

**Issue by Fufican** [cheeriojs/cheerio#1351]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'cherrio' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose npm-session d94a9ae140f8cd5f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/cherrio 1090ms
8 silly fetchPackageMetaData error for cherrio@latest 404 Not Found: cherrio@latest
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 1388ms
11 verbose stack Error: 404 Not Found: cherrio@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
11 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
11 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at processImmediate (timers.js:632:19)
12 verbose cwd C:\Users\User\Desktop\Discord Bot
13 verbose Windows_NT 10.0.18362
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "cherrio"
15 verbose node v11.6.0
16 verbose npm  v6.5.0-next.0
17 error code E404
18 error 404 Not Found: cherrio@latest
19 verbose exit [ 1, true ]

Thats the log

**Comment by OkancanCosar** [comment]
maybe try 
`yarn add cheerio`
without @latest. Becasuse yarn add cheerio work for me
