### ISSUE TITLE
Minor Docs CSS Bug

### ISSUE THREAD

**Issue by KyleMit** [cheeriojs/cheerio#1354]
The details > summary elements in the table of contents dumps in an entire text element, which formats all on the same line once the whitespace is stripped out

Here's how the home page looks in the browser:

![image](https://user-images.githubusercontent.com/4307307/67253457-b221ef80-f445-11e9-9574-1a9da81cbaed.png)

But here's the intended formatting from the source code:

![image](https://user-images.githubusercontent.com/4307307/67253473-c8c84680-f445-11e9-9652-94191e94a383.png)

If your documentation page is open source and you can point me toward the TOC builder, I'd be happy to patch together a commit, but I can't seem to find what builds the html and inserts the TOC

**Comment by fb55** [comment]
Thanks @KyleMit for reporting this! We have removed the TOC from the README, which resolves this 😄
