### ISSUE TITLE
What is the 1.0.0-rc3 release?

### ISSUE THREAD

**Issue by gajus** [cheeriojs/cheerio#1358]
There are no release notes for 1.0.0-rc3.

**Comment by pengmujing** [comment]
When will the 1.0 official version be released？

**Comment by cheshrkat** [comment]
Over a year since the last release... it'd be good to hear what the intention is regarding a 1.0, or even just a general project status.

**Comment by fb55** [comment]
There is currently not a lot of activity, but there is still interest in getting a 1.0 out eventually. Cheerio is still an incredibly useful project, and I'd love to see it pick up pace again.

**Comment by cheshrkat** [comment]
@fb55 Thanks for the update.
