### ISSUE TITLE
this.children is undefined in custom plugin

### ISSUE THREAD

**Issue by jabarihunt** [cheeriojs/cheerio#1365]
**Cheerio Version:** 1.0.0-rc.3

I'm attempting to create a custom plugin that will return the first child of an element:

```
$.prototype.firstChild = () => {
    return this.children().first();
};
```

I'm getting the following error:
> TypeError: this.children is not a function at initialize.$.firstChild...

**Comment by KazimirPodolski** [comment]
You probably want `function` instead of lambda for `this` to work as you need.
