### ISSUE TITLE
.html() leaving script attributes w/ out assigned value

### ISSUE THREAD

**Issue by mjyocca** [cheeriojs/cheerio#1366]
Cheerio Version: 1.0.0-rc.3

Would like to be able have .html() function leave script tag attributes w/ out assigning an empty value
```js
const $ = cheerio.load('<script defer type="text/javascript" src="bundle.js"></script>')
// result
$.html(); // => <script defer="" type="text/javascript" src="bundle.js" />
// what I would like to happen
$.html() // => <script defer type="text/javascript" src="bundle.js" />
```

**Comment by glaubermagal** [comment]
I have the same issue

**Comment by 5saviahv** [comment]
This behavior dont come directly from cheerio, but from parse5 serializer.

**Comment by fb55** [comment]
Thanks @5saviahv!

**Comment by fb55** [comment]
@5saviahv Don't have a good way to reach you, so adding this here: Thanks for helping with so many issues! I've invited you with _Triage_ permissions, so you can close issues like this yourself.
