### ISSUE TITLE
What is the milestone for 1.0.0?

### ISSUE THREAD

**Issue by micky2be** [cheeriojs/cheerio#1367]
The current dependencies of cheerio@1.0.0-rc3 have old dependencies like `css-select` with improper license.
While the new version (already set in the v1.0.0 branch) seems fine.

It's been 9 months since the RC3 so is there any blocker for releasing the final 1.0.0?

**Comment by cheshrkat** [comment]
You may be interested in this comment - https://github.com/cheeriojs/cheerio/issues/1358#issuecomment-625392658

**Comment by brettz9** [comment]
I don't know if this is still currently but https://github.com/cheeriojs/cheerio/projects/1 indicates 4 remaining issues toward release 1.

**Comment by eklem** [comment]
Seems there are some security fixes in v1.0.0 that could be good getting out. Any take on this or backporting security fixes for rc3 @matthewmueller ?

**Comment by fb55** [comment]
The latest release contains everything I wanted to include in the 1.0.0 release. I want to wait for a couple of weeks to see if there are any additional issues here. If not, a proper 1.0.0 release should be imminent.

**Comment by eklem** [comment]
Thank you, @fb55 😊 Greatly appreciated!
