### ISSUE TITLE
Prop not working in many cases 

### ISSUE THREAD

**Issue by heshaShawky** [cheeriojs/cheerio#1369]
If I'm right cheerio is like the twin brother of jQuery but for the server-side, I'm using cheerio prop to access the properties of the elements but in many cases, I can't! 

It just returns `undefined` and I'm sure that my function works as I try all my functions on a google chrome console using jquery and it works!! 

Now I'm working in a project and I'm trying to access table properties on the browser I could, but Nodejs using cheerio I couldn't 

The code ( the code works with jquery on browser buy not with nodejs )
```javascript
 Array.from($('table:nth-child(2) tr:first-child td:first-child table').prop('rows'), function(data) {
            return Array.from($(data).prop('cells'), (cells) => $(cells).prop('innerText') )
        })
        .filter( array => array.length == 7 )
```

**Comment by fb55** [comment]
This issue is a bit nondescript. Which props should be added? Feel free to open additional issues with the needed props.
