### ISSUE TITLE
$.html() decodes entities in 1.0.0

### ISSUE THREAD

**Issue by ErisDS** [cheeriojs/cheerio#1370]
I think this may be related to https://github.com/cheeriojs/cheerio/issues/319.

The source HTML:

```
...
<div>
  <h3>A Subheading</h3>
   <p>Text contains a link with the text being an encoded script tag <a href="http://www.w3schools.com/tags/tag_script.asp" rel="noopener" target="_blank">&lt;script&gt;</a>. The End.</p>
</div>
...
```

I read this in using:

```
const $content = $.load(html, {
        decodeEntities: false
});
```

Perform some processing which doesn't affect this particular block, and then render it back to html:

`$content.html()`

The output is:

```
...
<div>
  <h3>A Subheading</h3>
   <p>Text contains a link with the text being an encoded script tag  <a href="http://www.w3schools.com/tags/tag_script.asp" rel="noopener" target="_blank"><script></a>. The End.</p>
</div>
...
```
This is not the same intended meaning as the original source HTML and is invalid. Subsequent parsing fails. 

This behaviour is present in 1.0.0 rc2 and rc3, but not 0.22.0. I've not checked other versions.

**Comment by drewbaker** [comment]
This is breaking with me too. My CMS outputs a web component, like `<gallery images="encodedJsonBlob"></gallery>` and the `encodedJsonBlob` is decoded by `.html()` on output and breaks the page, instead of rendering the web component (which is the built by Vue into a gallery component).

**Comment by drewbaker** [comment]
Do this:

```php
<?php
$data = array("One", "Two");
$data = htmlspecialchars(json_encode($data), ENT_QUOTES, 'UTF-8');

$html = '<div data-test="'. $data . '">Foo</div>'
?>
<script>
            const $ = cheerio.load(<?php echo $html; ?>);
            output = $("body").html();
            document.body.innerHTML = output;
</script>
```

You'll see `output` is `<div data-test="["One", "Two"]">Foo</div>` which breaks the HTML output due to quotes inside the HTML attribute.

**Comment by drewbaker** [comment]
I manged to work around this by using single quotes inside my double-quotes in PHP, like so:

```
$html = "<div data-test='". $data . "'>Foo</div>";
```

Still a bug in Cheerio I think.

**Comment by fb55** [comment]
Cheerio is now using `parse5` as the default parser, which doesn't have an option to disable parsing entities. You can restore the old behavior by specifying the `_useHtmlparser2` option:

```js
const $content = $.load(html, {
        _useHtmlparser2: true,
        decodeEntities: false
});
```
