### ISSUE TITLE
.html() trims empty html attributes (class="" becomes class)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [cheeriojs/cheerio#1372]
**Version:** 1.0.0-rc.3

**Input:**
```js
require('cheerio').load('<div class=""></div>').html();
```
**Expected:**
```js
'<html><head></head><body><div class=""></div></body></html>'
```
**Actual:**
```js
'<html><head></head><body><div class></div></body></html>'
```

**jQuery Comparison:**
```js
$($.parseHTML('<div><div class=""></div></div>')).html();
// '<div class=""></div>'
```

* * *

I actually prefer the attributes being trimmed when empty. However, I am using Cheerio in a [Jest Snapshot serializer](https://github.com/tjw-lint/jest-serializer-vue-tjw), and would prefer it to have the least disruption as possible for my end users. So ideally it would have a setting to output `attribute` or `attribute=""` with the default being `attribute=""`, to match jQuery's `.html()`. This would allow me to pass along this option to my end users so they can pick based on preference.

* * *

Same outcome occurs when paired with `htmlparser2`.

**Comment by 5saviahv** [comment]
Newer parse5 versions (I tested v5) generate `=""` for every attribute even for boolean attributes.

Same time, people doesn't like if it is added for boolean attributes like `async` or `defer`. [parse5#184](https://github.com/inikulin/parse5/issues/184)

**Comment by fb55** [comment]
Closing as out-of-scope for Cheerio – please refer to one the serializers.

**Comment by TheJaredWilcurt** [comment]
> please refer to one the serializers.

@fb55 Can you give more details, this isn't even a complete sentence. So I'm not sure what I should be referring to.

**Comment by fb55** [comment]
Cheerio uses two serializers under the hood. For HTML, it is usually `parse5`'s serializer. I'm happy to pull in changes to the serializer, but it is out of scope for cheerio to solve this.

**Comment by dschmidt** [comment]
Aaaah, found it: https://github.com/cheeriojs/cheerio/issues/1031#issuecomment-748677236
