### ISSUE TITLE
Self closing tag space issue in xml. (Urgent help)

### ISSUE THREAD

**Issue by leninpmj93** [cheeriojs/cheerio#1383]
My issue is not preserving the space in the XML close tag during the cheerio parse.

```js
const xmlstr = `<plugin>
<testId />
<classId />
<goalsone>
    <goals />
    <info>new</info>
</goalsone>
</plugin>`;


const $one = cheerio.load(xmlstr, { xmlMode: true });

console.log( $one.xml() );
```

returns

```js
`<plugin>
<testId/>
<classId/>
<goalsone>
    <goals/>
    <info>new</info>
</goalsone>
</plugin>`
```

here the output comes for `<testId/>` and `<classId/>` but the initial state was  `<testId />` with one space at the end of close tag, same case with `<classId />`. I want to preserve the self-closing tag space with tag. Please help me, it's very urgent. I don't want to change the XML current format.

**Comment by fb55** [comment]
The output is valid XML, you will need a custom serializer to change this. Feel free to fork `dom-serializer`.
