### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by micheilsgrey** [cheeriojs/cheerio#1385]
I decide to use cheerio for parsing html in `react-native` project. I am getting error if i use debug in browser or not using debug mode at all. But if i use debug mode in IDE Visual Studio Code everything working fine. How to fix this issue with `ReferenceError: Buffer is not defined`. If i comment all code with cheerio everything working fine.

libs i already install: 

```
    "axios": "^0.19.2",
    "buffer": "^5.5.0",
    "cheerio": "^1.0.0-rc.3",
    "events": "^3.1.0",
```
Code:

```Typescript
const parseNews = (html: string) => {
    const $ = cheerio.load(html);
    const nodes = $('#news').find('.post-outer');
    const newsArray: News[] = Array();
    nodes.each((index, node) => {
        const news: News = { type: 'newsType' };
        const n = $(node);
        const h1 = n.find('.news-title');
        const newsUrl = h1.children().attr('href');
        news.newsUrl = newsUrl;
        const newsTitle = h1.children().text();
        news.title = newsTitle;
        const span = n.find('.news-date');
        let date = span.children().text();
        date = date.trim();
        date = date.replace(/\n/g, " ");
        const dateMoment = moment(date, 'MMMM DD, YYYY h:mm A')
        news.date = dateMoment.toDate();
        const div = n.find('.news-content');
        let newsSubtitle = div.text();
        newsSubtitle = newsSubtitle.replace(/(\r\n|\n|\r)/gm, '');
        news.subtitle = newsSubtitle;
        const imageSrc = div.find('img').attr('src');
        news.imageUrl = imageSrc;
        newsArray.push(news);
    })
    return newsArray;
}

```

Here error in debug mode: 
![React Native Debugger - Google Chrome 2020-03-27 1](https://user-images.githubusercontent.com/8958040/77769731-44fa3200-7055-11ea-9c37-e3f99ec0a29b.png)

Same issue without debug mode: 
![node  _C__Users_m1che_Documents_Dev_lolApp_node_mo](https://user-images.githubusercontent.com/8958040/77769954-94406280-7055-11ea-9a9c-65aa5acbdec7.png)

No issue if i debug in IDE....:
![index ts - lolApp - Visual Studio Code 2020-03-27 ](https://user-images.githubusercontent.com/8958040/77770248-02852500-7056-11ea-9d8f-7314a74ae614.png)

What am i doing wrong? How to fix this issue ?

**Comment by luanmuniz** [comment]
Cheerio was `designed specifically for the server.` as pointed in the description of the project. As far as I know, it doesn't support `react-native`. 

With that in mind. you can try a workaround, but I don't know if something else will break after this.
Try to put `global.Buffer = require('buffer')` somewhere in your code.

**Comment by micheilsgrey** [comment]
I replaced `cheerio `with `cheerio-without-node-native` and all working fine now.
