### ISSUE TITLE
Feature Request: lazy next() function

### ISSUE THREAD

**Issue by andykais** [cheeriojs/cheerio#1388]
Hi! I have a project working with large html pages and I was wondering if there was a way to partially evaluate a html string. This is useful, for instance, if I have a document with 5000 list items, but I only want to grab the first 4. After poking around in the code a bit I can gather that the whole document is walked at least once when loaded. Based on the fact that the number of items of a query is known ahead of time. E.g.

```js
const html = `
<ul>
  <li>item1</li>
  <li>item2</li>
  <li>item3</li>
  <li>item4</li>
  <li>item5</li>
</ul>
`

const $ = cheerio.load(html)
const items = $('li')

let i = 0
// the length is precomputed, therefore I assume the whole tree has been pre-generated
while (i < 4 && i < items.length) {
  const item = items.next()
  console.log(item.text())
  i++
}
```

If there already exists a way to walk through a document in a lazy manner please let me know! If not, I think this could be a very powerful feature to avoid extra stress on memory.

I assume if streaming parsing is still on the TODO list (it is a little unclear based on this [issue](https://github.com/cheeriojs/cheerio/issues/442)) then I imagine lazy evaluation could fall under a similar umbrella

**Comment by fb55** [comment]
Supporting CSS selectors without parsing the entire document is hard. I've attempted this before in the [`cornet` module](https://github.com/fb55/node-cornet), which will still end up with the entire document in memory (if not canceled externally), while not supporting several selectors users of cheerio would expect.

Please note that Cheerio collections will be iterable with the next release, which will at least provide a similar API as you've proposed.

Closing this as out of scope.

**Comment by andykais** [comment]
thank you for the explanation. I may poke at that project since cancelling early is what I am interested in, and the application I am working only needs to expose css queries and a limit
