### ISSUE TITLE
Make cheerio objects Iterable

### ISSUE THREAD

**Issue by bxqgit** [cheeriojs/cheerio#1390]
Cheerio objects should be Iterable, so that we can use them in normal loops:

```
for(el of $('div')) {
  ...
}
```

**Comment by maxcanna** [comment]
Have you tried using `get()` method? It returns an `Array`

**Comment by SirkoS** [comment]
Actually, the code to make objects iterable is [already in the repo](https://github.com/cheeriojs/cheerio/commit/f698a31e2fd143aaf7c1999bc9c034d3ad69f5be). However, there was no new release since then ...

**Comment by maxcanna** [comment]
...so in the meanwhile you can use `get()`. Just kididng 😅 You can use it even if it has not been released yet. Just reference the repo and the commit/branch in your `package.json` 😉
