### ISSUE TITLE
Cheerio install size doubles on v1 RCs

### ISSUE THREAD

**Issue by franciscop** [cheeriojs/cheerio#1394]
It seems that the [RCs for v1 (very excited!) doubles the size of the installed library](https://bundlephobia.com/result?p=cheerio@1.0.0-rc.2). It goes from **47kb** (180kb) on v0.22.0 to **92kb** (320kb) on v1.0.0-rc.3. Sizes are min+gzip (minified) respectively:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/2801252/80319755-698f2880-8812-11ea-8403-4b8a1ea9cf07.png">

Is this a concern? Maybe not because Cheerio seems to be mainly for back-end, but wanted to bring this up since this is a factor for me deciding for/against using Cheerio on a library I'm making. Please feel free to close it if it's not a concern for Cheerio's team.

**Before**:

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/2801252/80319795-c4c11b00-8812-11ea-815e-53eee859ca47.png">

**After**:

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/2801252/80319799-cd195600-8812-11ea-91f8-9227b57317d5.png">

**Comment by guanzo** [comment]
I'm using cheerio in the browser, in the service worker, since the web worker environment doesn't have any html parsing APIs. So a large package is a concern for me. It's not so terrible, b/c the service worker js doesn't need to be loaded/parsed on every page load.

**Comment by TrySound** [comment]
You guys are choose either parse5 or htmlparser2 and alias another module to empty module. Lodash dropping is coming soon.
