### ISSUE TITLE
Cheerio selector gets null while jQuery get proper result

### ISSUE THREAD

**Issue by Behinder** [cheeriojs/cheerio#1397]
my problem is when i try to get a href attributes from `https://www.teleman.pl/program-tv/stacje`
response is not null
````
var $ = cheerio.load(response);
let a = $('#stations-index a').text();
       console.log(a);
```` 
gives nothing while the same doing in chrome dev tools gives:
````
"13 Ulicaale kino+AMCAnimal PlanetATM RozrywkaAXNAXN BlackAXN SpinAXN WhiteBBC BritBBC EarthBBC FirstBBC LifestyleBoomerangCANAL+ 1CANAL+ 4KCANAL+ DokumentCANAL+ FamilyCANAL+ FilmCANAL+ PremiumCANAL+ SerialeCANAL+ SportCANAL+ Sport 2CANAL+ Sport 3CANAL+ Sport 4Cartoon NetworkCBS EuropaCBS RealityCI PolsatCinemaxCinemax 2Comedy CentralDiscovery ChannelDiscovery HistoriaDiscovery LifeDiscovery ScienceDisney ChannelDisney JuniorDisney XDDomo+DTXEleven Sports 1Eleven Sports 2Eleven Sports 3Eleven Sports 4Epic DramaEurosport 1Eurosport 2ExtremeFilmbox ActionFilmBox ArthouseFilmBox Extra HDFilmBox FamilyFilmBox Premium HDFokus TVFood NetworkFOXFOX ComedyHBOHBO 2HBO 3HGTVHISTORYHISTORY 2IDKino PolskaKino TVKuchnia+Metro TVMezzoMiniMini+MTV PolskaNat Geo PeopleNational Geo.Nat. Geo. WildNickelodeonNicktoonsNowa TVnSport+Paramount ChannelPLANETE+Polonia 1PolsatPolsat 2Polsat CafePolsat Comedy C. E.Polsat DokuPolsat FilmPolsat GamesPolsat NewsPolsat PlayPolsat RodzinaPolsat SerialePolsat SportPolsat Sport ExtraPolsat Sport FightPolsat Sport NewsPolsat Sport Premium 1Polsat Sport Premium 2Polsat Viasat ExplorePolsat Viasat HistoryPolsat Viasat NatureRomance TVSCI FISportKlubStopklatkaSundance TVSuper PolsatSuperstacjaTele 5TLCTNTTravelTTVTV 4TV 6TV PulsTV Puls 2TV RepublikaTV TrwamTVNTVN 7TVN FabułaTVN StyleTVN TurboTVN24TVN24 BiSTVP 1TVP 2TVP ABCTVP HDTVP HistoriaTVP InfoTVP KulturaTVP PoloniaTVP RozrywkaTVP SerialeTVP SportTVSWPZoom TV"
````

This is extremely annoying and time-consuming when I need to think is it something with connection or with cheerio, therefore it's difficult to fix errors.

**Comment by MA-Maddin** [comment]
It does also work well with cheerio:

`const https = require('https');
const cheerio = require('cheerio');

const url = 'https://www.teleman.pl/program-tv/stacje';

https.get(url, (res) => {
  res.on('data', (d) => {
    const $ = cheerio.load(d);
    let a = $('#stations-index a').text();
    console.log(a);
  });
}).on('error', (e) => {
  console.error(e);
});
`

`13 Ulicaale kino+AMCAnimal PlanetATM RozrywkaAXNAXN BlackAXN SpinAXN WhiteBBC BritBBC EarthBBC FirstBBC LifestyleBoomerangCANAL+ 1CANAL+ 4KCANAL+ DokumentCANAL+ FamilyCANAL+ FilmCANAL+ PremiumCANAL+ SerialeCANAL+ SportCANAL+ Sport 2CANAL+ Sport 3CANAL+ Sport 4Cartoon NetworkCBS EuropaCBS RealityCI PolsatCinemaxCinemax 2Comedy CentralDiscovery ChannelDiscovery HistoriaDiscovery LifeDiscovery ScienceDisney ChannelDisney JuniorDisney XDDomo+DTXEleven Sports 1Eleven Sports 2Eleven Sports 3Eleven Sports 4Epic DramaEurosport 1Eurosport 2ExtremeFilmbox ActionFilmBox ArthouseFilmBox Extra HDFilmBox FamilyFilmBox Premium HDFokus TVFood NetworkFOXFOX ComedyHBOHBO 2`

**Comment by Behinder** [comment]
Thank You very much, it worked :) not sure what was the problem.

**Comment by fb55** [comment]
Thanks @MA-Maddin!
