### ISSUE TITLE
Can't create plugins with typescript

### ISSUE THREAD

**Issue by remborg** [cheeriojs/cheerio#1407]
Using cheerio with typescript works fine until I try to create a plugin:
``` 
import cheerio from 'cheerio';

const html: string = `
<ul id="fruits">
    <li class="apple">Apple</li>
    <li class="orange">Orange</li>
    <li class="pear">Pear</li>
</ul>`;

const $ = cheerio.load(html, {
    normalizeWhitespace: true
});

$.prototype.logHtml = function () {
    console.log(this.html());
};

$('#fruits').logHtml();
```
Typescript returns me error:
> Property 'logHtml' does not exist on type 'Cheerio'.ts(2339)

This is normal, since logHtml is not part of '@types/cheerio'. So I've tried to do some module augmentation by adding this after the import:
```
declare module "cheerio" {
    interface Cheerio {
        logHtml(): void
    }
}
```
The previous error is still there and I get a new one:
> Cannot augment module 'cheerio' because it resolves to a non-module entity.ts(2671)

I'm I doing something wrong or is this an issue with the way the module is created?
---
EDIT: I'm using node v12.16.3, tsc v3.9.3, @types/cheerio v0.22.18 and cheerio v1.0.0-rc.3

**Comment by remborg** [comment]
I've found a similar issue in another library: 
https://github.com/googleapis/google-auth-library-nodejs/issues/177

The workaround here is to use the require syntax `const cheerio = require('cheerio');` instead of the import. 
Not great but typescript doesn't complain anymore.

My tsconfig file is as follow:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "rootDir": "src",
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "noImplicitAny": true,
    },
    "include": [
        "src/"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by fb55** [comment]
Typescript interfaces are open, so you should be able to add methods to them [like this](https://stackoverflow.com/questions/23306562/how-to-extend-a-primitive-type-in-typescript).

**Comment by remborg** [comment]
Thanks for the link but this solution doesn't work. 
vscode tells me that the new interface is `Cheerio' is declared but never used.ts(6196)`
And the custom function still has 'Property `logHtml' does not exist on type 'Cheerio'.ts(2339)`

Here is the full code:
```
import cheerio from 'cheerio';

const html: string = `
<ul id="fruits">
<li class="apple">Apple</li>
<li class="orange">Orange</li>
<li class="pear">Pear</li>
</ul>
`;
const $ = cheerio.load(html, {
    normalizeWhitespace: true
});

interface Cheerio {
    logHtml(): void
}

$.prototype.logHtml = function () {
    console.log(this.html());
};

$('#fruits').logHtml();
```

**Comment by remborg** [comment]
I've managed to get typescript happy, thanks to this post: https://github.com/Microsoft/TypeScript/issues/7148#issuecomment-197528646

I had to define my plugin globally with:
```
declare global {
    interface Cheerio {
        logHtml(): void
    }
}
```

**Comment by fb55** [comment]
Awesome, thanks for updating @remborg!
