### ISSUE TITLE
How to create a custom element in cheerio?

### ISSUE THREAD

**Issue by mtwzim** [cheeriojs/cheerio#1412]
Hello person, I would like to know if it is possible to do something like https://developers.google.com/web/fundamentals/web-components/customelements?hl=pt-br in cheerio? It's possible?

**Comment by fb55** [comment]
Cheerio does not support the custom element spec. You are able to create tags with arbitrary names (eg. `<custom-tag>` is usable in your markup) but there won't be any value-added features.
