### ISSUE TITLE
:nth-child() selector returns empty result

### ISSUE THREAD

**Issue by piffie** [cheeriojs/cheerio#143]
i know that :eq() is not implemented,
but nth-child is. (https://github.com/fb55/CSSselect/blob/master/index.js#L179)

anyways, always returns an empty result set.

**Comment by coderofsalvation** [comment]
I had a similar problem:

div.result_data > table > tbody > tr:nth-child(1) > td:nth-child(2)
did not work (although it matches the html markup)
This however did work:

div.result_data > table > tr:nth-child(1) > td:nth-child(2)
My theory: chrome's fault.
I rightclicked the element inside the chrome inspector and pressed 'copy css path'.
Chrome generates the CSSPath from the generated DOM (which autocorrects missing elements, hence the in the selector.).

So my advice, make sure all elements are present in the actual html :)

**Comment by kunKun-tx** [comment]
Firefox also seems to like insert a `tbody`.
More for this question on [SO](http://stackoverflow.com/questions/938083/why-do-browsers-insert-tbody-element-into-table-elements)
