### ISSUE TITLE
Feature Request: Deno Support

### ISSUE THREAD

**Issue by bdearborn** [cheeriojs/cheerio#1442]
Any plans to support Deno?

[https://deno.land/](https://deno.land/)

**Comment by fb55** [comment]
What would be required to make this work?

**Comment by fb55** [comment]
Closing this due to an apparent lack of interest. Happy to revisit should someone be able to lead this effort.

**Comment by niklaas** [comment]
I'm interested in this too. My gut feeling tells me that it shouldn't be too complicated because for an earlier version of cheerio someone already made it to work: https://github.com/justjavac/deno_cheerio That said, I would need some support for this because I'm fairly new to both deno and cheerio

**Comment by fb55** [comment]
Just reading the diffs in the README (as that is the only part I can read), this seems to be primarily an issue with the use of the `Buffer` type, which has been removed. Happy to accept patches for any other necessary changes!

**Comment by justjavac** [comment]
Cheerio works in Deno with `no-check` flag.

```ts
import cheerio from "https://dev.jspm.io/npm:cheerio/index.js";

const $ = cheerio.load('<h2 class="title">Hello world</h2>');

$("h2.title").text("Hello Deno!");
$("h2").addClass("deno");

console.log($.html());
```

Run it:

```bash
> deno run --no-check mod.ts
<h2 class="title deno">Hello Deno!</h2>
```

What is not compatible with deno is the dts `@types/cheerio`.

**Comment by takker99** [comment]
Now Cheerio also works in Deno without `no-check` flag.
(using esm.sh instead of dev.jspm.io)

```ts
import cheerio from "https://esm.sh/cheerio@1.0.0-rc.10";

const $ = cheerio.load('<h2 class="title">Hello world</h2>');

$("h2.title").text("Hello Deno!");
$("h2").addClass("deno");

console.log($.html());
```

```sh
> deno run mod.ts
<html><head></head><body><h2 class="title deno">Hello Deno!</h2></body></html>
```
