### ISSUE TITLE
Scrape images with lazy load style not working 

### ISSUE THREAD

**Issue by EngAhmedMahmoud** [cheeriojs/cheerio#1450]
When get images from a web page and these images displayed in a lazy load style which appears when scrolling web page. I get blank images for all elements. any solution for this issue.

All scrapped images like this.
```html
<img class="card-img-top" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEX/TQBcNTh/AAAAAXRSTlMAQObYZgAAAApJREFUeJxjYgAAAAYAAzY3fKgAAAAASUVORK5CYII=" id="card-img">
```

**Comment by fb55** [comment]
You don't seem to be extracting the lazy-loaded images. Please note that cheerio does not execute JS, so anything added by JS will not be available.
