### ISSUE TITLE
Mixed case tags are not recognized  e.g. dataType

### ISSUE THREAD

**Issue by jjmartin540** [cheeriojs/cheerio#147]
In XML mode tag names are case sensitive. cheerio does not accurately recognize mixed case tag names. Note that this would affect both XML users and people trying to use cheerio to parse XHTML strict documents.

For example:
$ = cheerio.load("<FooBar></FooBar>",{ignoreWhitespace:false,xmlMode:true});
$("FooBar").attr("color","green");
console.log($.html());

$ = cheerio.load("<fooBar></fooBar>",{ignoreWhitespace:false,xmlMode:true});
$("fooBar").attr("color","green");
console.log($.html());

Neither of these succeed in adding the color attribute. Note that in HTML you can use the lowerCaseTags flag, but if you look in the XML definition from the W3 it <b>requires</b> you to consider tag names (and I believe attribute names as well) to be case sensitive. I am running into a government standard (it's a healthcare thing) that requires all of the tag and attribute names to be case-sensitive. Unless this is fixed I can't use this library, which is a shame because it seems awesome. Due to the possible performance impact on other use cases I think this should be done with another flag similar to the "lowerCaseTags" flag that perhaps reads "caseSensitive:true" (or caseSensitiveTagNames and caseSensitiveAttributeNames flags). I talked about this with Matt Mueller over email and he suggested I create an issue, so here I am. From that discussion, a little more elaboration about the issue:

"it appears that both XHTML and pure XML are case sensitive when it comes to tag names and attribute names (from http://www.w3.org/TR/xhtml1/#h-4.2 , “This difference is necessary because XML is case-sensitive e.g. <li> and <LI> are different tags.”). The lowercase trick appears to work with XHTML because the w3 chose to have all tag names to be lowercase to make it easier to implement the standard. Note that afaik DoCTypE would be invalid in an XHTML strict document."

Please note that this is NOT a duplicate of issue #137 

Further note that I am willing to help write a patch I need more information as to where to get started as there appear to be several layers and dependencies that parse the underlying HTML/XML (fb55/node-htmlparser, htmlparser2 etc.)

**Comment by pietersv** [comment]
Is this still an issue in 1.4.23 or might there be an option?  It seems to be lowercasing tagnames on creation and OpenXML uses mixed-case tag names.

```js
var $ = require('cheerio')
$('<patternFill></patternFile>', {xmlMode: true})
```

```js
{ '0': 
   { type: 'tag',
     name: 'patternfill',
     attribs: {},
     children: [],
     next: null,
     prev: null,
     parent: null,
     root:  { ... } 
 },
  options:  { ... },
  length: 1 }
```

**Comment by fb55** [comment]
Passing options to `$()` is currently  quite cumbersome: You need to call `$('<patternFill></patternFile>', null, null, {xmlMode: true})`. The better choice is to call `.load(str, opts)`.

**Comment by pietersv** [comment]
Perfect, thanks!
