### ISSUE TITLE
Cheerio still maintained?

### ISSUE THREAD

**Issue by eklem** [cheeriojs/cheerio#1470]
Hi! Thanks for a super project and module. I was wondering if you are still maintaining it, at least when it comes to bugs and security issues?

I'm a bit dependent on cheerio, or will be, so I was thinking I sould become a financial backer, but I need to know if the project is still maintained enough to keep afloat.

Anyway, thanks for the great effort so far.

**Comment by matthewmueller** [comment]
Yep. It's still very much maintained and depended on by many large companies at this point.

Sponsorships are very much welcome.

**Comment by eklem** [comment]
Thanks! Monthly support added =)
