### ISSUE TITLE
Issues with DomUtills dependency when compiling with ASAR

### ISSUE THREAD

**Issue by sushant-t** [cheeriojs/cheerio#1504]
Hi, I am running into an issue with Cheerio when packaging my Electron application using ASAR. Specifically, when I run the production build with Cheerio, its DomUtil dependency always throws the following error. 

<img width="568" alt="Screen Shot 2020-10-07 at 11 47 42 AM" src="https://user-images.githubusercontent.com/13423028/95374479-3ce83e00-0893-11eb-937d-4044dfff63b4.png">

This is the file in which the error points to.
<img width="610" alt="Screen Shot 2020-10-07 at 11 51 25 AM" src="https://user-images.githubusercontent.com/13423028/95374645-728d2700-0893-11eb-8424-2112c110aab3.png">

Can someone provide me with some guidance with this? I am not sure if its an issue with my project or an issue with the actual dependency.

**Comment by fb55** [comment]
Not sure what is happening here, as this seems to work for other environments. Besides that, this code will not be a part of the next version of cheerio. The dependency has already been replaced with a compatible version, hope it is okay that I'm resolving this.
