### ISSUE TITLE
Replacing cloneDeepWidth with alternative

### ISSUE THREAD

**Issue by TrySound** [cheeriojs/cheerio#1506]
[Here](https://github.com/cheeriojs/cheerio/pull/1500#issuecomment-702999040) was mentioned new cloneNode api in domhandler. Though it covers only htmlparser2 integration. Is there any similar api in parse5?

cc @fb55

**Comment by fb55** [comment]
Hi @TrySound, the idea was to provide a `cloneNode` function that also works on parse5's flavor of the htmlparser DOM. Unfortunately, parse5 has two additional properties for attributes that aren't supported by `cloneNode` right now.

Ultimately, it would be good if parse5's htmlparser2 adapter could actually use domhandler's node interface. @inikulin Is this something you'd be okay with?

**Comment by inikulin** [comment]
I'm fine with that, though it will be a breaking change and will require a major release
