### ISSUE TITLE
any suggestions for something similar to cheerio with xpath support?

### ISSUE THREAD

**Issue by mreinstein** [cheeriojs/cheerio#152]
@MatthewMueller  cheerio is freaking awesome. Great work man! 

One thing I'm curious about is using xpath selectors instead of jquery. It seems like most browsers have a firebug/web inspector that expresses dom nodes positions in xpath. So while I know and love jquery, I'm tired of having to manually convert my xpath selector to a jquery equivalent. I'm wondering if cheerio supports this? I'm assuming it doesn't, so I'm wondering if there is another modular similar to cheerio that has similarly awesome perf characteristics, foregiving html parsing, and support for xpath that you would recommend. Or maybe I'm just doing it wrong, and there is some other tool where I can click a dom element and get a selector expressed in cheerio compatible syntax?

**Comment by softmarshmallow** [comment]
why would't cheerio support xpath by default? (its lot used for crawling/page parsing purpose)

**Comment by fb55** [comment]
Xpath is a complicated beast. Cheerio is pretty well scoped at the moment, adding xpath support would complicate things a lot. Happy to link to an xpath extension tho, should someone want to invest the time.
