### ISSUE TITLE
The Cheerio interface is not exported in the type definitions

### ISSUE THREAD

**Issue by unicrus** [cheeriojs/cheerio#1540]
See https://github.com/cheeriojs/cheerio/blob/v1.0.0/types/index.d.ts
The interface Cheerio is declared but not exported. It leads to TS compilation errors in projects, that need it. E.G. https://github.com/vuejs/vue-test-utils/issues/1737

**Comment by fb55** [comment]
Feel free to open a PR to add this!

**Comment by fb55** [comment]
Looking at your link, it seems like the issue is that we export a value type. If all that's needed is a `typeof`, the additional export does not really seem worth it.

**Comment by lynxtaa** [comment]
> 
> 
> Looking at your link, it seems like the issue is that we export a value type. If all that's needed is a `typeof`, the additional export does not really seem worth it.

Consider this code when using `cheerio@1.0.0-rc.3`:

```ts
function getTrimmedText(el: cheerio.Cheerio): string {
  return el.text().trim()
}

const $ = cheerio.load(html)
const trimmedText = getTrimmedText($('#text'))
```

How can I type an argument for a function `getTrimmedText` in cheerio@1.0.0-rc.5? `typeof cheerio` will return `cheerio.CheerioAPI` which is not the same as `cheerio.Cheerio`.

I think this issue should be reopened.

**Comment by lynxtaa** [comment]
After further investigation I think declaring `type Cheerio = ReturnType<typeof cheerio>` works. But it's not obvious in comparison with `@types/cheerio`
