### ISSUE TITLE
Feature Request: HTML Canvas Mocking

### ISSUE THREAD

**Issue by CoryGH** [cheeriojs/cheerio#1567]
I'd like to request a feature for cheerio allowing for HTML Canvas element mocking alongside the extant jQuery mocking capabilities it has.  I came across https://www.npmjs.com/package/jest-canvas-mock while searching for some way to do this, however an integration with cheerio would make this a lot easier as I'm currently using jest to create unit tests for JavaScript-driven DHTML GUI controls via cheerio - the one failure point I'm reaching with this method thus far is for controls which utilize a Canvas element for rendering.

**Comment by fb55** [comment]
Canvas doesn't make much sense in Cheerio, as it doesn't run a site's code. Have a look at JSDom, which implements most of a browser.
