### ISSUE TITLE
`content.forEach` is not a function when loading node that is not a root

### ISSUE THREAD

**Issue by NeverBehave** [cheeriojs/cheerio#1577]
I don't know whether is it an undocumented behavior or not, when trying to load a node that is not a root, cheerio will try to parse it as a list of nodes. 

I believe this commit cause such break: https://github.com/cheeriojs/cheerio/commit/2e75c2a4e38a83d89a32cb5edb74edacd0118042#diff-cc0e533610b6395aec57bad8971c3692fbf20950660cc5aa5014e58333a738baR28

## Minimal Example

> similar usage https://stackoverflow.com/questions/39044690/cheerio-map-strange-behaviour 

```js
const cheerio = require('cheerio');
const html = `
    <div class="test">
        <div></div>
        <div></div>
    <div>
`

cheerio.load(html)('.test').map((i, e) => {
    cheerio.load(e) // Break, not a root and not an array
})
```

If this is the desired behavior, what are the alternative ways to workaround this? Thanks!

**Comment by fb55** [comment]
Thanks for the report! I've opened #1580 to fix this.

To help with your issue in the meantime: Typically, the function returned by `cheerio.load` is used to wrap elements in loops. For you, this would be:

```js
const $ = cheerio.load(html);
$('.test').map((i, e) => {
    $(e).html() // `.html` as one example.
})

```
