### ISSUE TITLE
Question: Cheerio in React Native, should it work?

### ISSUE THREAD

**Issue by uripre** [cheeriojs/cheerio#1586]
Hey all,

Tried to add Cheerio to a React Native project, to see if that works. It runs just fine, but I'm encountering some weird issues in parsing. Should it work at all? 

Thanks

**Comment by fb55** [comment]
It should work! Cheerio is just JavaScript, and should run with any JS environment. The last release also fixes compatibility with React Native's bundler. Please note that cheerio is implementing the jQuery API, so some behavior is different when compared to eg. JS arrays. Other than that, feel free to report any bugs you might encounter.
