### ISSUE TITLE
content.each is not a function

### ISSUE THREAD

**Issue by aalzubidy** [cheeriojs/cheerio#1620]
There is an issue with .each on the new version/release. It's always returning "content.each is not a function". I switched back to 0.22.0, and it worked fine, but on 1.x.x, it is not working. Not sure if it is related to Parse5 or something else.

**Comment by fb55** [comment]
Hi @aalzubidy, do you have some code to relocate the issue?

**Comment by aalzubidy** [comment]
Hi,

This is what I was running:

`const cheerio = require('cheerio');
let $ = cheerio.load(testItem);
 $('.some-class-name').each((i, item) => {
console.log(i); //prints 0 and then the error shows up
console.log(item);
})
`

cheerio: 1.0.0-rc.5
npm version: 6.14.8
node version: v12.19.0

Error:
`(node:276024) UnhandledPromiseRejectionWarning: TypeError: content.forEach is not a function
    at parse (/home/user/Desktop/testCheerio/node_modules/cheerio/lib/parse.js:38:15)
    at Function.exports.load (/home/user/Desktop/testCheerio/node_modules/cheerio/lib/static.js:39:14)
    at Node.<anonymous> (/home/user/Desktop/testCheerio/index.js:3722:30)
    at initialize.exports.each (/home/user/Desktop/testCheerio/node_modules/cheerio/lib/api/traversing.js:562:24)
    at getURLSearchArticles (/home/user/Desktop/testCheerio/index.js:3720:30)
    at Object.<anonymous> (/home/user/Desktop/testCheerio/index.js:3781:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
(node:276024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:276024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Let me know if you need more information.

**Comment by fb55** [comment]
Thanks for the context! The error actually comes from the `.load` above, and has been reported as #1591 (and already fixed on `main`).

**Comment by aalzubidy** [comment]
Awesome, thank you so much! Looking forward to the new release.

**Comment by talha0324** [comment]
is there any workaround for this? I'm stuck on my production app, this issue just came after a little update, I cannot revert my app update as it's crucial.

**Comment by 5saviahv** [comment]
I believe it happens in `.load` function, it expects function input to be string or array.

workaround would be make sure input is Array before using with `.load`
``` js
elem = Array.isArray(elem) ? elem : [elem];
const $ = cheerio.load(elem);
```
or if elem is always singular you can call even:
``` js
const $ = cheerio.load([elem]);
```

**Comment by talha0324** [comment]
I'm getting this on a .each function which is:
`$('.product-detail-wrapper .product-price .product-price-row').each((_,e)=>{`

**Comment by aalzubidy** [comment]
I downgraded back then, but as 5saviahv said, make sure the .load function is getting an array so the .each won't throw the error.

**Comment by talha0324** [comment]
okay downgrading did the trick. !

**Comment by 5saviahv** [comment]
This error is already fixed in in repo but rc5 in npm is still affected. 

Not sure my code fixes something, but at least provides some examples.

I tested each function elements, you can call `cheerio(el)` or load with array casting `cheerio.load([el])`.
``` js
const cheerio = require('cheerio');

const content = '<html><body><h2 id="test/id-1">ID 1</h2><h2 id="id-2">ID 2</h2></body></html>';
const $ = cheerio.load(content);

// loop with cheerio(...)
$('h2').each((i, e) => {
    const ee = cheerio(e);
    console.log(`${i} - ${ee.text()}`);
});

// loop with cheerio.load([...]) and array casting
$('h2').each((i, e) => {
    const ee = cheerio.load([e]);
    console.log(`${i} - ${ee.text()}`);
});
```

**Comment by talha0324** [comment]
@5saviahv  it doesn't work for me, I tried casting it in an array.

**Comment by 5saviahv** [comment]
did you get same error ?
