### ISSUE TITLE
html parse not correct!

### ISSUE THREAD

**Issue by vaseala** [cheeriojs/cheerio#1621]
### test.js
```js
const cheerio = require("cheerio");
const html = `
<html>
  <head>
    <title>parse test</title>
    <%- css %>
  </head>
  <body></body>
</html>
`;

const $ = cheerio.load(html, {
  decodeEntities: false
});

console.log($.html());
```

### result
```
<html><head>
    <title>parse test</title>
    </head><body><%- css %>
  
  

</body></html>
```

### puzzle
The `<%- css %>` should be under the `head` tag, but was parsed to the `body`, why ?

**Comment by fb55** [comment]
`<%- css %> ` is considered text, and placed under the body tag as only that can have text. You can use `xml: true` to parse the document as XML and preserve the order of nodes.

**Comment by vaseala** [comment]
@fb55  thanks. 
I change some core code:
```
const $ = cheerio.load(html, {
  decodeEntities: false,
  xml: true
});
```

but then it console:
```
<html>
  <head>
    <title>parse test</title>
    <%- css="" %="">
  </%-></head>
  <body>
    
  </body>
</html>
```

it conver `<%- css %>` to `<%- css="" %="">`, which I do not want to.

**Comment by 5saviahv** [comment]
These seems to be ASP.NET code nuggets, they are template engine specific elements. not cheerio nor parsers know how to treat those elements. Maybe use regex and convert them to comment before using cheerio. later use regex to extract elements again.

**Comment by vaseala** [comment]
@5saviahv  thanks. It is a good solution idea！
