### ISSUE TITLE
Feature Request: export Root from the types

### ISSUE THREAD

**Issue by Allain55** [cheeriojs/cheerio#1649]
Hi,
It would be great if the type Root would be accessible outside. Eg. when I pass around the result of the load method I'd need to use the Root type, the default export is not good in this case.

**Comment by 5saviahv** [comment]
Can you provide some code.

I believe you wanted use `cheerio.load`
``` js
const $ = cheerio.load(rootElement)
```
 but you didn't know how to get that `rootElement` ?

**Comment by Allain55** [comment]
Hi,
yes I want to use the type of the result of cheerio.load, for example in a ts file:

```
import {Root} from 'cheerio';

function getHtml($: Root) {
    return $.root();
}
```

Root would be exported in types/index.d.ts. Now only CheerioAPI is exported. 
The Cheerio interface could be useful too

**Comment by fb55** [comment]
For now, there is a solution in #1540. I agree that having this interface would be useful and we might add this in the future.
