### ISSUE TITLE
`attr` converts `undefined` to string

### ISSUE THREAD

**Issue by fb55** [cheeriojs/cheerio#1664]
jQuery removes attributes when setting their value to `undefined`, while cheerio sets them to the string `'undefined'`.

Discovered in #1659.

**Comment by 5saviahv** [comment]
Notes:

in jQuery if value is specified, but its value is undefined it returns **this** object
``` js
const ret = elems.attr('name', undefined)
// ret == elems
```
if value is not specified, it tries get first element attribute value, if it is not existing it returns undefined
``` js
const ret = elems.attr('name')
// ret == undefined
```
