### ISSUE TITLE
Rename `_make` to `pushStack`

### ISSUE THREAD

**Issue by fb55** [cheeriojs/cheerio#1665]
The internal method `_make` is equivalent to jQuery's `pushStack`. Let's rename it, to make it an official API.

Uncovered in #1656.

**Comment by 5saviahv** [comment]
It would be nice, it is internal in jQuery also, but this way you have at least more information sources available.

**Comment by 5saviahv** [comment]
Interesting why `_make` wont call directly
``` js
new Cheerio(...)
```

**Comment by 5saviahv** [comment]
in jQuery methods can call for constructor either `jQuery(...)` or `jQuery.pushStack(...)`. When first one simply creates new jQuery instance. Second one creates new instance and pushes current object into `prevObject`.

in Cheerio calling `_make` is basically only way to get access to constructor. I think this way `prevObject` isnt always previous object.

**Comment by fb55** [comment]
I decided against doing this, as the semantics don't quite line up.
