### ISSUE TITLE
index.d.ts isn't match the real code

### ISSUE THREAD

**Issue by li7228166** [cheeriojs/cheerio#1671]
```js
cheerio.load('<h2 class="title">Hello world</h2>', null, false)
```

```js
interface CheerioAPI extends Root {
    version: string;
    load(
      html: string | { toString(): string },
      options?: CheerioParserOptions
    ): Root;
    load(element: Element, options?: CheerioParserOptions): Root;
  }
```

**Comment by 5saviahv** [comment]
Yes, this definition was written originally for **v0.22** by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/cheerio)

property **isDocument** was added to cheerio with **v1.0**, definition file definitely needs some overhauling.
