### ISSUE TITLE
.merge() - wont accept Cheerio object.

### ISSUE THREAD

**Issue by 5saviahv** [cheeriojs/cheerio#1674]
### Test

``` js
const cheerio = require('cheerio');

const ret = cheerio.merge(new cheerio(), ["elem1","elem2"]);
```
Problem is **merge** uses function **isArrayLike** and **isArrayLike** uses **Object.hasOwnProperty** for testing does object has **length** property. Cheerio objects has **length** property, but it is defined in prototype and it wont meet criteria.

### Option 1

Remove check and let it throw if object has not array like

### Option 2

maybe test is property length a number instead

**Comment by fb55** [comment]
Great find! My gut instinct is to make `length` a property on all Cheerio instances, as that will also make them less polymorphic and trigger some optimizations in V8.

**Comment by 5saviahv** [comment]
Yes, guaranteed instantiated length property would also be option.
