### ISSUE TITLE
rc.4 and rc.5 crash on a script that works in rc.3

### ISSUE THREAD

**Issue by ljharb** [cheeriojs/cheerio#1679]
To repro:

1. Clone https://github.com/ljharb/es-abstract/ and `npm install`
1. `npm install cheerio@1.0.0-rc.3`
1. `node operations/getOps 2020`, observe it completes
1. `npm install cheerio@1.0.0-rc.4` (or 5)
1. `node operations/getOps 2020`, observe it crashes with:
```sh
$PWD/node_modules/cheerio/lib/api/traversing.js:30
    return newElems.concat(elem.children.filter(isTag));
                                         ^

TypeError: Cannot read property 'filter' of undefined
    at $PWD/node_modules/cheerio/lib/api/traversing.js:30:42
    at Array.reduce (<anonymous>)
    at module.exports.exports.find ($PWD/node_modules/cheerio/lib/api/traversing.js:29:30)
    at Object.<anonymous> ($PWD/operations/getOps.js:29:43)
```

Since this is a dev-only script, I only need to use it in node 14 or higher.

**Comment by 5saviahv** [comment]
yes, it seems like in `find` function does not have condition determine if collection element is text node.

**Comment by 5saviahv** [comment]
Cheerio should be able handle it, but I would suggest change code so document will be parsed with `load` function
``` js
...
const root = $.load(specHTML);

let aOps = root('[aoid]').add(root('[aoid]'));

if (aOps.length === 0) {
	aOps = root('p:contains(" abstract operation ")').closest('section').add(root('#sec-reference-specification-type > section'));
}
...
```

**Comment by ljharb** [comment]
What’s the advantage of that?

**Comment by 5saviahv** [comment]
This is how Cheerio is meant to work. Load document and then make requests against it.

Current setup also should work, but it is clearly not enough tested.

**Comment by ljharb** [comment]
I expect cheerio to work just like jquery works :-) but thanks, appreciate the workaround.

**Comment by fb55** [comment]
Thanks for the report! Quite unfortunate that this happened & thanks @5saviahv for stepping in!

**Comment by ljharb** [comment]
Thanks, with this and hopefully #1585 fixed, i'll be able to update to rc6 (or a regular v1) everywhere ;-)

**Comment by lsbyerley** [comment]
I have come across this issue as well after upgrading from `1.0.0-rc.3` to `1.0.0-rc.5` .. however, i'm not exactly sure what I should be doing differently. My function is below and the error is generated at the `.find()` line

```
  const myFunc = async () => {
  const url = 'https://www.myurl.com';
  const theRes = await axios.get(url);

  const $ = cheerio.load(theRes.data, { normalizeWhitespace: true });
  const theDiv = $('#some_div_id');
  let rawHtml = theDiv.html();
  rawHtml = rawHtml.replace('<!--', '');
  rawHtml = rawHtml.replace('-->', '');

  const theDomNodes = cheerio.parseHTML(rawHtml);
  const theRows = $(theDomNodes).find('table#some_table_id tbody tr');

  ...
}
```

**Comment by fb55** [comment]
Hi @lsbyerley, what error are you seeing?

**Comment by lsbyerley** [comment]
@fb55 the same one posted by the OP.. 

`TypeError: Cannot read property 'filter' of undefined`
`at /sandbox/node_modules/cheerio/lib/api/traversing.js:30:42`

**Comment by ljharb** [comment]
The fix isn’t released yet, afaict

**Comment by lsbyerley** [comment]
alright no problem, i can downgrade until the release
