### ISSUE TITLE
$.toJSON

### ISSUE THREAD

**Issue by crackcomm** [cheeriojs/cheerio#169]
Hey, I'd like to be able to serialize cheerio object to JSON but it's often not possible because of Circular Object. I chose to delete `prev`, `next` and `parent` object from every cheerio child and then it's serializable, you can take a look at this [gist](https://gist.github.com/crackcomm/5204778). What do you think about bringing this kind of function to native ?

**Comment by timiyay** [comment]
I came across this particular issue too, as I was building an array of objects returned from a `$.map()` operation. I was getting circular reference errors when trying to `JSON.stringify` the results, as I didn't immediately realise that my plain object was converted to a Cheerio object.

I'll either manually strip the Cheerio-specific properties off the objects returned by `$.map()`, and / or use a custom `replacer` function in `JSON.stringify`.

`$.toJSON`, or a way to get plain objects back from iterators, could be handy.
