### ISSUE TITLE
How to use cheerio interface

### ISSUE THREAD

**Issue by keyiis** [cheeriojs/cheerio#1696]
I used cheerio  in typescript ,i need pass cheerio.Root Object in different method
```
import * as cheerio from 'cheerio';
async function parse(html:string){
        let $ = cheerio.load(html);
        methodA($);
 }
function methodA($:cheerio.Root){
     ......
}
```
but vscode prompted an error
![image](https://user-images.githubusercontent.com/7766085/105566177-b3874980-5d65-11eb-93d1-dc513c13011a.png)
I find Root type in index.d.ts
![image](https://user-images.githubusercontent.com/7766085/105566240-0e20a580-5d66-11eb-93a1-e74542f4f3d0.png)

**Comment by 5saviahv** [comment]
You can check #1649 and #1540

**Comment by keyiis** [comment]
@5saviahv i tried #1682 ,but still not work

**Comment by keyiis** [comment]
i installed @types/cheerio,it works. so i think the root cause is not export interface in index.d.ts.

**Comment by dominik-korsa** [comment]
The idea of bundling types is so you **don't** have to install a package from DefinitelyTyped (`@types`)

**Comment by 5saviahv** [comment]
True, bundling types also gives you opportunity to give version specific definitions. I believe `@types` gives you currently types for v0.22.

**Comment by 5saviahv** [comment]
Like @keyiis mention in #1682 it is solvad
