### ISSUE TITLE
$.html() return without head & body tags

### ISSUE THREAD

**Issue by krishnaTORQUE** [cheeriojs/cheerio#1697]
`$.html()` return html, head & body tags, which I do not need.

I went to documentation & it was not clear.

I am using `v1.0.0-rc.5`

`const $ = cheerio.load('<ul id="fruits">...</ul>', null, false)`

this is not valid in `v1.0`

I have tried `const $ = cheerio.load('<ul id="fruits">...</ul>', {})` but no luck.

I have find the xml options but no option for `load` function.

can anyone please help me out

**Comment by 5saviahv** [comment]
It works with:
``` js
const cheerio = require('cheerio');

const $ = cheerio.load('<ul id="fruits">...</ul>', null, false);
console.log($.html());
```
result:
```html
<ul id="fruits">...</ul>
```

**Comment by krishnaTORQUE** [comment]
no its not

Error

`Expected 1-2 arguments, but got 3.`

I am using Typescript

**Comment by krishnaTORQUE** [comment]
I have resolved the issue 

First of all the `load` function accept only 2 arguments. 2nd is optional.

`cheerio.load(content, { xmlMode: true })`

**Comment by 5saviahv** [comment]
OK, this 3rd argument was added in 1.0

you can try
```
const cheerio = require('cheerio');

const $ = cheerio('<ul id="fruits">...</ul>');
console.log(cheerio.html($));
```

**Comment by krishnaTORQUE** [comment]
no this introduce new error `Uncaught TypeError: nodes[index] is undefined`
