### ISSUE TITLE
Test for .map method is actually calling .each method

### ISSUE THREAD

**Issue by Pustur** [cheeriojs/cheerio#1705]
Hello,

I was looking at some test files and I found this line that I think is wrong:

https://github.com/cheeriojs/cheerio/blob/9b28b49527b22f72ef81e28c069302ca3eb7c329/test/api/traversing.js#L706

It's in the tests for the `.map` method but has been changed to `.each` in https://github.com/cheeriojs/cheerio/commit/21de2c55d0459db0564de91fed20fd33c9647e19

Not sure why it's been changed, but it should be `.map` being tested here right?

I can open a PR if requested.

**Comment by 5saviahv** [comment]
haha, nice - I think it should be map there.

**Comment by 5saviahv** [comment]
You are always welcome to create PR.
