### ISSUE TITLE
Cutting a new release to avoid deprecation warning

### ISSUE THREAD

**Issue by JustinBeckwith** [cheeriojs/cheerio#1717]
Greetings folks - thank you for building a lovely library.  When installing `1.0.0-rc.5`, downstream users are getting a deprecation warning for `cheerio-select-tmp`, telling them to move to `cheerio-select`.  I see that the change already landed on main, but I was wondering if we could maybe get an `rc.6` :).

**Comment by starzou** [comment]
I think so too.😊

**Comment by kevinvanrijn** [comment]
This was also requested on https://github.com/cheeriojs/cheerio/pull/1594#issuecomment-754108134 and then promptly ignored.

**Comment by KenEucker** [comment]
bumping this as it seems well within the ability of the cheeriojs team to address their own internal deprecations.

**Comment by fb55** [comment]
Done!

**Comment by EHadoux** [comment]
Thanks for the new version! Does it mean that now PrevAll with a filter returns the list in the same order as JQuery (and thus in reversed compared to the previous version)? (see #1754) If that's the case, should it be mentioned as a BugFix or a Breaking Change? Cheers

**Comment by fb55** [comment]
@EHadoux Thanks for flagging, updated the release notes!
