### ISSUE TITLE
Typescript type for Cheerio.load doesn't include isDocument overload

### ISSUE THREAD

**Issue by RyKilleen** [cheeriojs/cheerio#1739]
![image](https://user-images.githubusercontent.com/4615840/107991316-5ff2cf00-6fa4-11eb-8684-37e2c7947323.png)

![image](https://user-images.githubusercontent.com/4615840/107991358-6ed98180-6fa4-11eb-9513-0886a2caf75f.png)

![image](https://user-images.githubusercontent.com/4615840/107991412-929cc780-6fa4-11eb-998b-8545f2c9b3e3.png)

**Comment by sea129** [comment]
[this commit](https://github.com/cheeriojs/cheerio/commit/6a90bda51249a96a3c60d62d7425200381f615b4#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccce) would fix it

**Comment by 5saviahv** [comment]
Yes, it does - it is fixed in repo, but it is not available in npm.

**Comment by RyKilleen** [comment]
Closing this as @sea129 has a fixing commit in the right repo
