### ISSUE TITLE
PrevAll with selector returns reversed order

### ISSUE THREAD

**Issue by EHadoux** [cheeriojs/cheerio#1754]
Hello, 

First of all thanks a lot for this lib.

I'm using ```1.0.0-rc.5```. When I do a ```prevAll``` I have different behaviours depending on whether I'm using a selector or not. 

```typescript
$(el).prevAll(sel).each((_, el1) => console.log(getSelector($(el1))));
```
Where ```getSelector``` is a function giving the path in the document. 
So when the selector ```sel``` is empty, I get the expected JQuery behaviour (closest first):
```
body > div:nth-child(3) > div:nth-child(10)
body > div:nth-child(3) > div:nth-child(9)
body > div:nth-child(3) > div:nth-child(8)
body > div:nth-child(3) > div:nth-child(7)
body > div:nth-child(3) > div:nth-child(6)
body > div:nth-child(3) > div:nth-child(5)
body > div:nth-child(3) > div:nth-child(4)
body > div:nth-child(3) > div:nth-child(3)
body > div:nth-child(3) > div:nth-child(2)
body > div:nth-child(3) > div:first-child
```
but interestingly, when I put something in the selector, I get the list in reverse (and obviously shorter because filtered)
```
body > div:nth-child(3) > div:first-child
body > div:nth-child(3) > div:nth-child(7)
```

Would it be because the ```filter``` function sorts or something?
https://github.com/cheeriojs/cheerio/blob/f386975b627c870e88eac54e32cb593ce5300e99/lib/api/traversing.js#L409

Cheers

**Comment by 5saviahv** [comment]
Answer would be - yes, filter does the sorting. It happens because under the hood we use "cheerio-select" filter function and there was built-in sorting until v1.2.0. It is written out now, but older versions, including "cheerio-select-tmp" still use sort.

**Comment by EHadoux** [comment]
Cheers, thanks for the heads up. Have you planned to change that at some point? Just for me to know if it's safe to keep the ```.last()``` instead of the ```.first()``` or if I should track the new versions and switch at the right time? Hopefully this change will be flagged somewhat.

**Comment by fb55** [comment]
Closing in favor of #1717

**Comment by fb55** [comment]
This is already fixed on `main`, but a new release has to be cut.
