### ISSUE TITLE
lang="" attribute on <html> is ignored

### ISSUE THREAD

**Issue by colorcube** [cheeriojs/cheerio#1762]
Wenn you parse html

`$template = cheerio.load('<html lang="de">...')`

the lang attribute is no longer there if you get the html with

`$template.html();`

But if you add the attribute by yourself
`
$template('html').attr('lang', 'de');`

The attribute is there when you use `$template.html();`

The same happens with `<body>.` Maybe with all other tags too (not tested). 

A parser problem?

**Comment by 5saviahv** [comment]
I can't reproduce this issue:
``` js
const cheerio = require('cheerio');
const $template = cheerio.load('<html lang="de">');
console.log($template.html());
```
and output is:
``` html
<html lang="de"><head></head><body></body></html>
```
attribute **lang** is there

**Comment by colorcube** [comment]
Thanks for the quick response.

It turned out the 'bug' was totally unrelated to cheerio.

Sorry for the inconvenience!!
