### ISSUE TITLE
Object.forEach

### ISSUE THREAD

**Issue by szundi** [cheeriojs/cheerio#1773]
Hello guys, I am using i18next-parser package that uses cheerio. I found a bug in cheerio I think, when I run the program, it cannot find method forEach on the content variable - because there is no forEach in ES6 on Object. 

Line 38 of parse.js, I fixed it with using Object.keys.

```
    } else {
      // Generic root element
      var root = new domhandler.Document(content);
      Object.keys(content).forEach(function (node) {
        console.log("===", node);
        if (content[node]) {
          content[node].parent = root;
        }
      });

```

What do you think? This way it worked, I think it is more compatible with all the js out there. I hope this helped. If it helps, I can send a PR.

**Comment by fb55** [comment]
Thanks for the patch! This is already fixed on `main`, see #1591.
