### ISSUE TITLE
serializeArray() inconsistent with jquery -  is case sensitive on `type` values

### ISSUE THREAD

**Issue by FullStackFlamingo** [cheeriojs/cheerio#1782]
Thanks for the invaluable library! Sorry if this a duplicate issue.

I've noticed unlike jquery, serializeArray is case sensitive, so the following code returns badly cased checkboxes as checked.

https://replit.com/@cheeriotester/ReliableJoyfulLegacysystem#index.js
```javascript 
const cheerio = require('cheerio'); // v1.0.0-rc.5

const form = `<form id="case-insensitive">
  <input type="CheckBox" name="sitemarketing" value="True">
  <input type="CheckBox" name="thirdpartymarketing" value="True">
  <input type="checkbox" name="normalcasing-off" value="True" >
  <input type="checkbox" name="normalcasing-on" value="True" checked >
</form>`;

const $ = cheerio.load(form);

console.log($('form').serializeArray());
/*[
  { name: 'sitemarketing', value: 'True' }, // should not be here
  { name: 'thirdpartymarketing', value: 'True' }, // should not be here
  { name: 'normalcasing-on', value: 'True' }
]*/

```

I tried to narrow down the problem, I was going to write a PR to replace this line https://github.com/cheeriojs/cheerio/blob/cee6b7a2c21925a6a42ea1d5408ddc7a89435a67/lib/api/forms.js#L56 with:
` ':is([checked], :not([type="checkbox" i], [type="radio" i]))'` .

That would fix this particular case, but it seems the problem is deeper than that, as in jquery searching with `[type="checkbox"]` or `:checkbox` is case-insensitive already.

**Comment by 5saviahv** [comment]
Interesting problem - your PR will work, but there are also `:submit`, `:button`, `:image`, `:reset`, `:file` filters and they probably also should be not case sensitive.

https://github.com/cheeriojs/cheerio/blob/cee6b7a2c21925a6a42ea1d5408ddc7a89435a67/lib/api/forms.js#L54-L56

they all come from `css-select` package: [JQuery extensions](https://github.com/fb55/css-select/blob/efcfcdb51e12f56108f16ec0831850ed1e111d8e/src/pseudo-selectors/filters.ts#L178-L184) and [getAttribFunc](https://github.com/fb55/css-select/blob/efcfcdb51e12f56108f16ec0831850ed1e111d8e/src/pseudo-selectors/filters.ts#L16-L29) are both in filtrers.ts so maybe instead change `ignoreCase` value on line 20 to `true` there. This function is really only used with those extensions so it should not have huge impact.

If this approach is not acceptable by @fb55 we should use `[type="..." i]` with other filters as well.

**Comment by fb55** [comment]
The HTML rules for which attributes should be case-sensitive actually landed in `css-what` very recently, and it just hasn't made its way up the dependency chain. I hope to spend some time upgrading all packages soon, which should fix this.

**Comment by fb55** [comment]
This is fixed in RC6!
