### ISSUE TITLE
Unwrap functionality

### ISSUE THREAD

**Issue by irenashemesh** [cheeriojs/cheerio#1789]
Hello, first of all, thanks for creating and maintaining Cheerio, awesome library!

Our functionality requires `unwrap` method, per https://cheerio.js.org/Cheerio.html#unwrap. I am using v1.0.0-rc.5 version, is this functionality available there? Trying to use it returns error.

If this is not yet available, what is the proper way to replace tag with just its text content in the parent:

`<div> Text start <tag>continue</tag> finish </div>`  to turn into 
`<div> Text start continue finish </div>`

Thank you in advance.

**Comment by 5saviahv** [comment]
function `unwrap` was actually added after v1.0.0-rc.5 version release, so currently it is available only in github.
