### ISSUE TITLE
Boolean attributes should not be special in xmlMode

### ISSUE THREAD

**Issue by rau8344** [cheeriojs/cheerio#1805]
For HTML boolean attributes cheerio's attr() method behavior is both different from jquery and undocumented:
- [jquery documented behavior](https://api.jquery.com/attr/) is to get the actual value of attributes (_except_ for values matching the attribute name in version 1.5 and earlier, which gets true)
  - This seems to match actual behavior, as per the following unit test, run against jquery@3.4.1, jquery@1.6, and jquery@1.5
- [cheerio documented behavior](https://cheerio.js.org/module-cheerio_attributes.html#.attr) refers to jquery documentation, without mentioning any edge cases attributes.
  - Actual behavior gets attribute _name_ for boolean attributes, as per the following unit test using xmlMode.
```
    it("jquery reads boolean attributes as-is", () => {
        const text = `<Item name="a" checked="a" disabled="a" required="a" selected="a" />`;
        const xmlJ = jQuery(jQuery.parseXML(text));
        const rootJ = xmlJ.children();
        expect(rootJ.attr("name")).toBe("a");
        expect(rootJ.attr("checked")).toBe("a");
        expect(rootJ.attr("disabled")).toBe("a");
        expect(rootJ.attr("selected")).toBe("a");
        expect(rootJ.attr("required")).toBe("a");
    });

    it("cheerio gets the name of defined boolean attributes instead of value", () => {
        const options = { xmlMode: true };
        const text = `<Item name="a" checked="a" disabled="a" required="a" selected="a" />`;
        const xml = cheerio.load(text, options);
        const root = xml.root().children();
        expect(root.attr("name")).toBe("a");
        expect(root.attr("checked")).toBe("checked");
        expect(root.attr("disabled")).toBe("disabled");
        expect(root.attr("selected")).toBe("selected");
        expect(root.attr("required")).toBe("required");
    });
```
This behavior was apparently intentional, and commented in the source for getAttr() [https://cheerio.js.org/lib_api_attributes.js.html](https://cheerio.js.org/lib_api_attributes.js.html), and made for made for [https://github.com/cheeriojs/cheerio/pull/570](https://github.com/cheeriojs/cheerio/pull/570). Stated reason was "jquery behaviour is to return the attrribute name when present", but I cannot find any version of jquery where that is the actual behavior. This may have related behavior for attribute setting, though I have not tested that.

Suggest one of the following:
1. (Breaking change) Change attr() to always match documented jquery behavior.
2. Change attr() to conditionally match documented jquery behavior _if certain options are provided to cheerio.load()_ (e.g. for xmlMode)
3. Change [cheerio documentation](https://cheerio.js.org/module-cheerio_attributes.html#.attr) to match the actual behavior.
4. Provide additional API methods/overloads to allow both old and new behavior. (Could be confusing; would definitely require documentation)

**Comment by fb55** [comment]
Very interesting case. It seems like this only applies to XML inside of jQuery — HTML actually shows the behavior described in #570.

@rau8344 My proposed solution would be to change the behavior in XML mode. How do you feel about this?

**Comment by rau8344** [comment]
@fb55 That makes sense to me.
