### ISSUE TITLE
Children iteration is too verbose

### ISSUE THREAD

**Issue by xamgore** [cheeriojs/cheerio#1819]
The standard approach for children iteration is via `.each` or `.map` or `.toArray().map`.

```js
$('selector').toArray().map(it => {
  const $el = $(it)
  // do something with $el
})
```

We may notice `const $el = $(it)` is repeated constantly. If we want to extract the lambda to a separate function, we will have to add `$` as an argument, without it you can't wrap `$(it)`. Also `it: Element` is useless by itself.

```js
// better
$('selector').map($el => {
  // do something with $el
})
```

What do you think about it?

**Comment by fb55** [comment]
We actually made this change a while ago, but reverted as some users were confused by the difference of behavior to jQuery. I agree that this is a change that makes sense, but keeping compatibility has priority for now.
