### ISSUE TITLE
Wrap doesn't work for Table

### ISSUE THREAD

**Issue by Sangkwun** [cheeriojs/cheerio#1820]
I'm trying to wrap some class with tag but doesn't work.
The table is appended in targetClass.

cheerio version:  "^1.0.0-rc.6",

```
const wrapper = $(`<table style="table-layout:fixed;">
    <tbody style="line-height:inherit">  
    </tbody>
  </table>`)
  $('body').wrapInner(wrapper);
  return $.html();
```
![image](https://user-images.githubusercontent.com/23003207/115984084-28c21f00-a5e0-11eb-9af4-f8dce88bd2a4.png)

In a small test case, it works well.
```
const cheerio = require('cheerio');
const $ = cheerio.load(`
  <html><head></head><body><ul class="fruits">
  <li class="apple">Apple</li>
  <li class="orange">Orange</li>
  <li class="pear">Pear</li>
  </ul></body></html>
`);


const redFruit = $(`<div class="hifruit">
  <table style="table-layout:fixed;">
    <tbody style="line-height:inherit">  
    </tbody>
  </table>
  </div>`)
$('body').wrapInner(redFruit);
console.log($.html());

>>
<html><head></head><body><div class="hifruit">
  <table style="table-layout:fixed;">
    <tbody style="line-height:inherit"><ul class="fruits">
  <li class="apple">Apple</li>
  <li class="orange">Orange</li>
  <li class="pear">Pear</li>
  </ul>
</tbody>
  </table>
  </div></body></html>
```

I tested with just div it works as expected.
but with the table tag, there is some problem.
div successfully wrap the target class but the table is not.
```
const wrapper = $(`<div class="hifruit">
  <table style="table-layout:fixed;">
    <tbody style="line-height:inherit">  
    </tbody>
  </table>
  </div>`)
  $('body').wrapInner(wrapper);
  return $.html();
```
![image](https://user-images.githubusercontent.com/23003207/115984872-24980080-a5e4-11eb-89e7-7eacfaf43665.png)

**Comment by fb55** [comment]
I unfortunately am not able to replicate this, especially as your one complete example shows the expected behavior. Happy to revisit this should you be able to share the code that leads to the issue.
