### ISSUE TITLE
the cheerio npm package  has a invalid main entry path for 1.0.0-rc.8

### ISSUE THREAD

**Issue by bingjianguo** [cheeriojs/cheerio#1843]
main entry path value in package.json, as follow
![image](https://user-images.githubusercontent.com/2384478/117329739-89e2d000-aec7-11eb-8d4f-cc1b37b389fb.png)

The installed npm package as follow:
![image](https://user-images.githubusercontent.com/2384478/117329824-9ff09080-aec7-11eb-8100-22fdd5689606.png)

**Comment by fb55** [comment]
Have a look at #1842 — `v1.0.0-rc.9` hopefully solves this!
