### ISSUE TITLE
Accept Uint8Array also instead of Buffer?

### ISSUE THREAD

**Issue by karlhorky** [cheeriojs/cheerio#1844]
Hi @fb55 ! In `1.0.0-rc.9` I noticed that [the types for `cheerio.load`](https://github.com/cheeriojs/cheerio/blob/726f94a4677fd07b9528079172fe6176e70235be/src/load.ts#L25) only accept `string | Node | Node[] | Buffer`.

I'm trying to pass in a `vfile.VFileContents` (via `remark.process`), which is `string | Uint8Array`.

Would it be possible to also accept [`Uint8Array`, the base type for `Buffer`](https://github.com/vfile/vfile/blob/f95280cbd0d8d29a3fd49984e91e7c665175bceb/lib/index.js#L16)?

**Comment by fb55** [comment]
Happy to accept PRs for this! We currently rely on `Buffer.isBuffer` to see if something is a buffer; if you have a more generic approach, I'm happy to take it :)

**Comment by karlhorky** [comment]
Open: https://github.com/cheeriojs/cheerio/pull/1845

**Comment by fb55** [comment]
Closing this, as the change seems pretty involved.
