### ISSUE TITLE
require("cheerio") no longer returns a function

### ISSUE THREAD

**Issue by codeworrior** [cheeriojs/cheerio#1846]
Since yesterday evening, our builds using cheerio fail with errors like

```js
const cheerio = require("cheerio");

let tree = new Tree(cheerio('div.dk-sidebar > ul', outXmlString));
06:07:58                      ^
06:07:58  
06:07:58  TypeError: cheerio is not a function
06:07:58      at Object.<anonymous> 
```

I guess this is related to the new release candidate 1.0.0-rc9. 

Is this kind of usage no longer supported?

**Comment by fb55** [comment]
Thanks for flagging; I've added a note about this to the release notes: https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0-rc.9

Tl;dr this should fix your code:

```diff
- const cheerio = require("cheerio");
+ const cheerio = require("cheerio").default;
```
