### ISSUE TITLE
parse5.parseFragment is not a function => parsers/parse5.js|ts

### ISSUE THREAD

**Issue by MathiasBoisgardDev** [cheeriojs/cheerio#1847]
Hello ! 

I found an issue after searching for a while where it came from.

I use enzyme in a project for my Unit Tests, and the library uses cheerio for its internal function 'render'

# The problem
When I execute my tests, every call to 'render' method from enzyme has an error :

`TypeError: parse5.parseFragment is not a function`

This error only occurs for cheerio version >v1.0.0-rc.5 as the structure of your library changed between .5 and .6
Before the import of parse5 was made directly in lib/parse.js and then moved to parsers/parse5.js

The problem is that when you require('parse5') in parsers/parse5.js, you actually require the file itself, so 

`var parse5 = require('parse5'); `
is actually an object containing the function `parse` and `render` and not the functions from the library parse5 (`parse`, `parseFragment` and `serialize`)

## The solution 
I can do a Pull request to change the name of the file and so avoid this problem (tested locally and functionnal)

**Comment by fb55** [comment]
Hi @MathiasBoisgardDev, thanks for the report! Could you provide some details on which environment you are using? Module resolution as it is done within Node shouldn't have an issue here.

**Comment by MathiasBoisgardDev** [comment]
Yeah sure:

MacOS Big Sur : v11.3.1 
node : v12.14.1

Do you need more than those information ?

**Comment by egor-yolabs** [comment]
Just wanted to note that I have the same exact issue with this library. I have to lock it down to rc5 to get around it.

**Comment by MathiasBoisgardDev** [comment]
Same, everything works fine by locking on .5
Would be great to be able to be up to date though
