### ISSUE TITLE
怎么获取没有在标签里的文本

### ISSUE THREAD

**Issue by developer-wlj** [cheeriojs/cheerio#1849]
![65d00d579c806bd6](https://user-images.githubusercontent.com/55836679/117559817-0ab5ed80-b0bb-11eb-8017-014ebc976d42.jpg)
怎么只获取圈红的文本

**Comment by K2Ratus** [comment]
申し訳ありませんが、蜂蜜、私たちは日本語が話せません

**Comment by fb55** [comment]
Hi @developer-wlj, responding using Google Translate — I hope this is understandable. For your issue, this code will work:

---

@developer-wlj，您好，请使用Google翻译回应-我希望这是可以理解的。 对于您的问题，此代码将起作用：

```js
$('#sss').contents().last()
```
