### ISSUE TITLE
TS1110: Type expected error in node_modules/cheerio/lib/types.d.ts

### ISSUE THREAD

**Issue by akhilp-10** [cheeriojs/cheerio#1855]
We have enzyme in our react typescript project. Now enzyme using latest cheerio version v1.0.0-rc.9. which breaks while running our app with an error like TS1110: Type expected error in node_modules/cheerio/lib/types.d.ts

Environment
-------------
Node version:14.16.0
Typescript version: 3.8.3
React: ^16.8.8
enzyme: ^3.9.2
webpack: "^4.16.5",
webpack-dev-server: "^3.1.14",
webpack-merge: "^4.1.4",
storybook : 5.3.21

Project running fine in cheerio-1.0.0-rc.3. Could you please check this issue?

**Comment by jack4dev** [comment]
Getting the same error

**Comment by duongnv-0312** [comment]
I'm getting the same error with cheerio-1.0.0-rc.9

let's check version of cheerio in your file package-lock.json and node_modules/cheerio/package.json.
If cheerio version rc9, please override by rc5 or rc3.

Run bellow command in your terminal to override version cheerio:

`npm i cheerio@1.0.0-rc.5`

It run with me.

**Comment by ANDRUXUIS** [comment]
the same error

**Comment by nukeop** [comment]
Me too

**Comment by nukeop** [comment]
If I delete these lines manually from `lib/types.d.ts`, it seems to work:

```typescript
declare type LowercaseLetters = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z';
declare type AlphaNumeric = LowercaseLetters | Uppercase<LowercaseLetters> | `${number}`;
declare type SelectorSpecial = '.' | '#' | ':' | '|' | '>' | '+' | '~' | '[';
/**
 * Type for identifying selectors. Allows us to "upgrade" queries using
 * selectors to return `Element`s.
 */
export declare type SelectorType = `${SelectorSpecial}${AlphaNumeric}${string}` | `${AlphaNumeric}${string}`;
```

Maybe it's because of the template literal type?

**Comment by fb55** [comment]
Yeah – we use a template literal type here to identify if you are passing a selector to the query function, which provides more accurate types. Unfortunately, this means TypeScript 4.1 is required.

**Comment by fb55** [comment]
Documented this in the release notes.

**Comment by xiaotiandada** [comment]
> Yeah – we use a template literal type here to identify if you are passing a selector to the query function, which provides more accurate types. Unfortunately, this means TypeScript 4.1 is required.

usable

npm i typescript -D

"typescript": "^4.2.4"

**Comment by gerton1111** [comment]
updated my TS version to 4.3.5 still doesnt help

**Comment by fb55** [comment]
Could you share your error? You might have a different problem if a TypeScript upgrade doesn't fix it.
