### ISSUE TITLE
Breaking change in RC??

### ISSUE THREAD

**Issue by imaegoo** [cheeriojs/cheerio#1856]
https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0-rc.9

This breaking change will affect all historical versions of packages that depend on cheerio, why we have breaking change in an RC release? https://semver.org/

package.json
``` json
{
  "dependencies": {
    "cheerio": "^1.0.0-rc.5"
  }
}
```
index.js
``` js
const $ = require('cheerio')
$(someVar).text()
```
```
$ is not a function
```

**Comment by imaegoo** [comment]
https://github.com/imaegoo/twikoo/issues/165

**Comment by k-randstad** [comment]
Experiencing the same issue

return cheerio.html($(type), { decodeEntities: false });

TypeError: cheerio.html is not a function

**Comment by fb55** [comment]
Hi @imaegoo, to quote the semver spec:

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

Earlier RCs already included breaking changes. In this instance, using the exported function directly has been deprecated for years, and there was no good way to move the project forward without dropping it. There is a drop-in replacement to restore compatibility if you need it (`const $ = require('cheerio').default`), so hopefully this doesn't cause too much pain.

I expect there to be one additional RC before the final release. We will continue to conform to stability guarantees from the semver spec.
