### ISSUE TITLE
Selection of node.type === "comment" no longer works as of 1.0.0-rc.9

### ISSUE THREAD

**Issue by bluepeter** [cheeriojs/cheerio#1880]
In 1.0.0-rc.5 and previous, the following would correctly identify HTML comments (i.e., `<!-- comment -->`):

```
$.root().find("*").contents().filter(isComment).remove();

function isComment(index, node) {
  return node.type === "comment"; 
}
```

As of (at least) 1.0.0-rc.9, this no longer works.

**Comment by bluepeter** [comment]
Take a closer look, it appears that there are no `node.type` of comments. The previously referenced code seemingly just totally ignores all comment nodes.

**Comment by fb55** [comment]
This is a shortcoming of the current release and has been fixed in https://github.com/cheeriojs/cheerio/pull/1870
