### ISSUE TITLE
Typescript Compilation Errors

### ISSUE THREAD

**Issue by paularah** [cheeriojs/cheerio#1894]
The new typescript definition breaks my build with the error below

`
node_modules/cheerio/lib/types.d.ts:2:78` - error TS1110: Type expected.
2 declare type AlphaNumeric = LowercaseLetters | Uppercase<LowercaseLetters> | `${number}`;
node_modules/cheerio/lib/types.d.ts:8:36 - error TS1110: Type expected.
8 export declare type SelectorType = `${SelectorSpecial}${AlphaNumeric}${string}` | `${AlphaNumeric}${string}`;                                     
Found 2 errors
`

Node version: 12.22.1

**Comment by fb55** [comment]
Duplicate of #1855. Tl;dr you'll have to bump your TS version.

**Comment by paularah** [comment]
Thanks!
