### ISSUE TITLE
types.d.ts generated type definition errors

### ISSUE THREAD

**Issue by jdedwards3** [cheeriojs/cheerio#1942]
The code linked here:

https://github.com/cheeriojs/cheerio/blob/b1d224868f9ce1e7b82df5a173dfafcde8db458c/src/types.ts#L39-L41
is being generated into types.d.ts file: 

```
declare type LowercaseLetters = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z';
declare type AlphaNumeric = LowercaseLetters | Uppercase<LowercaseLetters> | `${number}`;
declare type SelectorSpecial = '.' | '#' | ':' | '|' | '>' | '+' | '~' | '[';
/**
 * Type for identifying selectors. Allows us to "upgrade" queries using
 * selectors to return `Element`s.
 */
export declare type SelectorType = `${SelectorSpecial}${AlphaNumeric}${string}` | `${AlphaNumeric}${string}`;
import type { Cheerio } from './cheerio';
import type { Node } from 'domhandler';
/** Elements that can be passed to manipulation methods. */
export declare type BasicAcceptedElems<T extends Node> = Cheerio<T> | T[] | T | string;
/** Elements that can be passed to manipulation methods, including functions. */
export declare type AcceptedElems<T extends Node> = BasicAcceptedElems<T> | ((this: T, i: number, el: T) => BasicAcceptedElems<T>);
/** Function signature, for traversal methods. */
export declare type FilterFunction<T> = (this: T, i: number, el: T) => boolean;
/** Supported filter types, for traversal methods. */
export declare type AcceptedFilters<T> = string | FilterFunction<T> | T | Cheerio<T>;
export {};
//# sourceMappingURL=types.d.ts.map
```

The template literals are not able to be used as types.

This results in TypeScript errors, and is resolved if reverting cheerio back to version  1.0.0-rc.5 and using @types/cheerio package instead.

**Comment by fb55** [comment]
Hi @jdedwards3, this is using a feature introduced in TypeScript 4.2. It looks like you might have to update.

**Comment by jdedwards3** [comment]
@fb55 - is 1.0.0-rc.10 still intended to be used with the cheerio types package provided here: https://www.npmjs.com/package/@types/cheerio? 

if so it doesn't make sense to include the .d.ts files in the cheerio distribution.

**Comment by fb55** [comment]
Nope, the @types package is no longer needed.

**Comment by jdedwards3** [comment]
thanks for clarifying. 

to update from rc.5 to rc.10 here are the steps: 

- change cheerio imports to 
```typescript
import * as cheerio from "cheerio";
```
- uninstall @types/cheerio 
- upgrade typescript to latest version
