### ISSUE TITLE
`wrapInner` is not in the typedef

### ISSUE THREAD

**Issue by RedGuy12** [cheeriojs/cheerio#1980]
![image](https://user-images.githubusercontent.com/61329810/125022160-a921e900-e041-11eb-874d-5218359f06df.png)

**Comment by fb55** [comment]
The latest version of Cheerio (1.0-RC 10) is written in TypeScript and will include this. Please try updating!

**Comment by RedGuy12** [comment]
Oh, I was on 1.0-RC.10, but I somehow had @types/cheerio (which was only for 0.x) installed as well! Oops!
