### ISSUE TITLE
Issue on `children` following `prevAll`

### ISSUE THREAD

**Issue by EHadoux** [cheeriojs/cheerio#1988]
Following up on #1754 it looks like `prevAll` does something the rest doesn't.
I have:
1. `.prevAll(sel1).children(sel2)` 
2. `.prevAll(sel1).first().children(sel2)`
3. `.prevAll(sel1).last().children(sel2)`

Both 2. and 3. act like they should. However given the documentation on `children` (the children of the first selected element) you would expect 1. to act like 2. but it does exactly act like 3.

Edit: tested on both RC9 and RC10

**Comment by fb55** [comment]
Thanks for flagging! I can confirm that the docs for `children` don't match the actual behavior. The actual implementation returns the children from every element in the selection.

**Comment by EHadoux** [comment]
Cool, thanks for confirming. What's the planned next step? Changing the doc or the implementation? I probably have a lot of calls to `children` where I didn't check the behaviour, so just for me to know if I need to put `first` everywhere or if it's gonna be fixed in a later version. Cheers!

**Comment by fb55** [comment]
We follow the jQuery API in cases like this. jQuery's docs point at the implemented behavior, so we'll update the docs: https://api.jquery.com/children/

**Comment by fb55** [comment]
Updated the docs. Thanks @EHadoux for the report!
