### ISSUE TITLE
will support unwrap & wrap?

### ISSUE THREAD

**Issue by youxiachai** [cheeriojs/cheerio#203]
cheerio have any way wrap element?

**Comment by operatino** [comment]
+1, really would like to see $wrap here

**Comment by jugglinmike** [comment]
Patches welcome!

**Comment by Lomacar** [comment]
Hmm. Well for now I found this to work:

`$(unwrapMe).each(function(){$p` = $(this).parent(); $(this).insertAfter($(this).parent()); $p.remove()})

**Comment by asumaran** [comment]
I've implemented a .unwrap() method by myself. It was very specific, I'll be glad to submit a PR but I was wondering if there's a reference how a unwrap should word in most cases.

**Comment by fb55** [comment]
@asumaran The jQuery test cases are a good reference.

**Comment by asumaran** [comment]
@fb55 Thanks. I'll take  a look.
