### ISSUE TITLE
Broken tag causes cheerio to hang indefinitely

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [cheeriojs/cheerio#2034]
This one caused me a lot headaches, basically calling `$("style />")` never returns. There are no errors, it just hangs forever. Tried locally and on RunKit with the latest stable cheerio.

**Comment by fb55** [comment]
What version of cheerio are you using? I am getting a `Uncaught Error: Unmatched selector: />` when trying to do this in a current version.

**Comment by OzymandiasTheGreat** [comment]
My bad, didn't notice I was using 0.22. The issue is solved in the latest RC.
