### ISSUE TITLE
Cheerio does not see certain elements

### ISSUE THREAD

**Issue by metalwarrior665** [cheeriojs/cheerio#2038]
I have trouble using Cheerio on pagination elements on [Amazon](https://www.amazon.com/s?k=Collectible+Card+Games&i=toys-and-games&rh=n%3A166242011&qid=1628630485). Nor `$('.s-pagination-item')` or `$('[class*="s-pagination-item"]')` return anything.

I can use document.querySelector or JQuery on it. I can also parse it from HTML string.

Here is the [copy of the HTML](https://api.apify.com/v2/key-value-stores/ZItAO4GOBPtPoMHeK/records/AMAZON-HTML)

Any idea what could be causing this? Or am I missing something?

**Comment by fb55** [comment]
You might want to disable the `scriptingEnabled` option: https://cheerio.js.org/interfaces/CheerioOptions.html#scriptingEnabled
