### ISSUE TITLE
`parent` and `closest` type discrepancies

### ISSUE THREAD

**Issue by EHadoux** [cheeriojs/cheerio#2056]
Hey, is there a reason why `parent(selector)` returns a `Cheerio<Element>` and `closest(selector)` a `Cheerio<Node>`?
I imagine one would expect `closest` to be (in theory) a recursive `parent`.

This prevents (at compilation, without casting) the element to be a selector in functions like `nextUntil`.

**Comment by fb55** [comment]
This was a consequence of Cheerio's `closest` allowing a filter function to be passed (jQuery only allows a selector). I have opened #2057 that restricts a filter function to only elements, which fixes this.

**Comment by EHadoux** [comment]
Cheers for that. So it still returns a `Cheerio<Node>`, that's intended, right?
My initial issue is that it looks like I can do:
```typescript
const stopper = $(selector1).parent(selector2);
$(selector3).nextUntil(stopper)
```
but not
```typescript
const stopper = $(selector1).closest(selector2);
$(selector3).nextUntil(stopper)
```
because `nextUntil` accepts a `Cheerio<Element>` (as returned by `parent`) but not a `Cheerio<Node>` (as returned by `closest`). I'm not sure if that's intended or not. Sorry my previous post wasn't clear enough.

**Comment by fb55** [comment]
The next release will return a `Cheerio<Element>`.
