### ISSUE TITLE
README out of sync with v1.0.0-rc.10

### ISSUE THREAD

**Issue by shellscape** [cheeriojs/cheerio#2069]
While looking into improving performance of my use of cheerio, I was reading up on the different parsers that cheerio can use and ran across this tidbit in the README: 

> If you want to save some bytes, you can use Cheerio's slim export, which always uses htmlparser2

Unfortunately, that hasn't shipped yet. I'm all for making master the latest state of the working tree, but it looks like we're quite a few commits behind master on v1.0.0-rc.10.

I'm loathe to ask this, and I do dislike when users stop by to ask me the same; may we get a new release to make use of the new features that have been added since June?

**Comment by nikosgpet** [comment]
I just tried to use slim as well, and I realized that it's not really there

**Comment by jimmywarting** [comment]
isn't it about time to release it as stable soon? 
...remove `rc

**Comment by fb55** [comment]
There currently is only a single blocker for a new release, and that is that the default parser (`parse5`) isn't using the same node interface as `htmlparser2`. `parse5` isn't maintained actively anymore, so after months of trying to get added as a maintainer, I have forked the project recently and am now working on a new version at https://github.com/parse5/parse5-fork. Hoping to get a new RC out soon, which should hopefully be equivalent to the final 1.0.

**Comment by fb55** [comment]
`cheerio@1.0.0-rc.11` is out!
