### ISSUE TITLE
Selector types mismatch

### ISSUE THREAD

**Issue by wigarddev** [cheeriojs/cheerio#2087]
when using a string as a selector, everything works:

![image](https://user-images.githubusercontent.com/55100874/132097776-14c3be44-f621-466a-879d-ec1da8f074ff.png)

element is a `Cheerio<Element>`.

but if you use an array and combine it via `join`:

![image](https://user-images.githubusercontent.com/55100874/132097790-026ea790-9539-480c-958e-1d3182fb8fd3.png)

element is a `Cheerio<Node>`

Cheerio v1.0.0-rc.10

**Comment by fb55** [comment]
If you pass a string to `$`, it will be either parsed as a selector, or as HTML. A selector produces exclusively elements, while HTML can be anything (so it uses the base type `Node`). We use TypeScript's tagged template literals to identify selectors and set the type accordingly.

In your example, there is no way for TypeScript to analyze what you are passing in. You could just cast the result as a workaround.
