### ISSUE TITLE
security: update version nth-check

### ISSUE THREAD

**Issue by Sotatek-TuanVo** [cheeriojs/cheerio#2128]
Please update version of `nth-check` to 2.0.1
Link: https://snyk.io/test/npm/nth-check/2.0.1

**Comment by fb55** [comment]
The latest version is already part of the range for this package. A `npm audit --fix` is all you'll have to do.

**Comment by Sotatek-TuanVo** [comment]
https://snyk.io/test/npm/nth-check/2.0.0
version 2.0.0 has one bug security

**Comment by fb55** [comment]
I am aware – `nth-check` is my module. But there is nothing to do for `cheerio`, as the version range already includes that patch.
