### ISSUE TITLE
Can cheerio use in frontend?

### ISSUE THREAD

**Issue by Hutao6688** [cheeriojs/cheerio#2226]
I want to ues cheerio in frontend  html page , only use it parse html string (not  a  file), donot use network request function.

Please tell me how to compile  cheerio to a singal  .js file or .min.js , in order to directly use it  in html page with <script src="xx.min.js"></script> import lib ?

**Comment by fb55** [comment]
You should be able to use a service like Skypack to use Cheerio in the browser: https://www.skypack.dev

**Comment by Hutao6688** [comment]
Hi, I mean is direct use it in html (donnot use webpack and nodejs), my html is a simple file, dont use webpack.

such as  <script src="http://a.com/ cheerio.min.js"></script>

Where can i find this existing js file "cheerio.min.js" to download?

**Comment by fb55** [comment]
Hi @Hutao6688, what I was referring to: You ~~should~~ will* be able to use cheerio like this in a regular HTML document:

```js
<script type=module>
import * as cheerio from 'https://cdn.skypack.dev/cheerio';

const $ = cheerio.load('<div>MY HTML</div>');
// ...
</script>
```

\* This is broken for the current release due to Skypack failing to import JSON, but will be supported in the next version.

**Comment by Hutao6688** [comment]
Excuse me , is there any other lib to use in broswer parse html?
Can you help me to find another lib which **don't need the webpack and nodejs env**, only run in browser? 
My projext need such a lib now. Only use it  to **parse html string**.
It has to be in this form : <script src="http://abc.com/cheerio.min.js"></script>.
Thank you very much !

**Comment by fb55** [comment]
I thinking you are looking for https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString

jQuery uses this inside its `parseHTML` method, which might be of interest to you as well.
