### ISSUE TITLE
index.d.ts not up to date for .load (missing isDocument)

### ISSUE THREAD

**Issue by MeStrak** [cheeriojs/cheerio#2265]
Hello there,

I'm using Typescript with v1.0rc-10, and I was trying to use .load with the isDocument parameter documented here: https://cheerio.js.org/interfaces/CheerioAPI.html. I found something weird with `index.d.ts`.

This is my code:
```javascript
private cheerioBody = cheerio.load(myHtml, null, false);
```

I get the following type error `Expected 1-2 arguments, but got 3`. I noticed the same problem reported here but the issue was closed: https://github.com/cheeriojs/cheerio/issues/1697.

I checked `index.d.ts` from the installed npm package and it looks like the `isDocument` parameter is missing:
```javascript
interface CheerioAPI extends Root {
        version: string;
        load(html: string | Buffer, options?: CheerioParserOptions): Root;
        load(element: Element | Element[], options?: CheerioParserOptions): Root;
    }
```

I assume that it should contain `isDocument` as an optional (even thought it is not currently defined as optional in the code) like below:
```javascript
interface CheerioAPI extends Root {
        version: string;
        load(html: string | Buffer, options?: CheerioParserOptions, isDocument?: boolean): Root;
        load(element: Element | Element[], options?: CheerioParserOptions, isDocument?: boolean): Root;
    }
```

The source `load,ts` does contain this parameter (although not as optional), so I'm not sure why it does not appear in index.d.ts: https://github.com/cheeriojs/cheerio/blob/6f664b691a2eddbda24e532dbd5c85d9dda0bc9a/src/load.ts#L95.

**Comment by fb55** [comment]
Is this the `index.d.ts` from `@types/cheerio`? If that's the case: That module isn't required anymore, as Cheerio ships with TypeScript types itself now.

**Comment by MeStrak** [comment]
You're right 😃 

I hadn't noticed that @types was still left in devDependencies from an upgrade a while back.

Thanks for the tip!
