### ISSUE TITLE
Package lock file prevents using newer versions of dependencies

### ISSUE THREAD

**Issue by MikePikanin** [cheeriojs/cheerio#2273]
# Issue 
In the package-lock.json file version of css-select is hardcoded to v4.1.3, which prevents from updating to a new version.
It's used from cheerio-select, and in it's package.json the version should be at least v4.2.0
https://github.com/cheeriojs/cheerio-select/blob/0331cba997752029a43a8812f571b8e24acae71f/package.json#L37

# Proposal
Please update the version in package-lock.json or remove the file completely

**Comment by fb55** [comment]
The lock file isn't shipped to npm, so this should be a limitation of your local env. Try removing the local lock file & node_modules and installing again?

**Comment by MikePikanin** [comment]
Yes, you're right - lock file indeed doesn't affect it. I am closing this issue.
