### ISSUE TITLE
Unmatched pseudo-class :prose-xl and :where

### ISSUE THREAD

**Issue by gijo-varghese** [cheeriojs/cheerio#2282]
I'm using Tailwind CSS [Typography plugin](https://tailwindcss.com/docs/typography-plugin) to style markdown rendered content. CSS generated by Tailwind has ".lg:prose-xl ..." and ".prose :where(h2)..." which doesn't seems to be working with Cheerio.

Here is a code to reproduce the issue:

```js
const cheerio = require('cheerio');

const $ = cheerio.load(
  `<article class="prose prose-indigo lg:prose-xl">
        <h2>Agreement</h2>
    </article>`,
);

const selector_1 =
  '.lg:prose-xl :where(h2):not(:where([class~="not-prose"] *))';

const selector_2 =
  '.prose :where(h2):not(:where([class~="not-prose"] *))';

console.log($(selector_1));
// Error: unmatched pseudo-class :prose-xl

console.log($(selector_2));
// Error: unmatched pseudo-class :where

```

**Comment by fb55** [comment]
For `lg:prose-xl` you will have to escape the colon to reference it in a CSS selector: `'.lg\\:prose-xl'` selects the element.

`:where` is already supported by the CSS selector library, but Cheerio needs to have another release for it to become available.
