### ISSUE TITLE
why img tag has no close tag after render($.html())?

### ISSUE THREAD

**Issue by uzoice** [cheeriojs/cheerio#230]

**Comment by milu2003** [comment]
How to solve this problem? I also met

**Comment by meisl** [comment]
See #1235 which is related, and contains further discussion.

**Comment by e-tang** [comment]
I have the same issue, very annoying as I need to generate React code from the given html. All img tags are generated without the ending slash which is a problem to React.

**Comment by e-tang** [comment]
And also obviously the <input> as well
