### ISSUE TITLE
Is there support for NOT Contains?

### ISSUE THREAD

**Issue by fredericomattos** [cheeriojs/cheerio#2384]
I tried to explore some ways to get NOT Contains to work, but honestly none of the attempts using the template for Cheerio worked.

In the examples I found here on cheeriogs I didn't see any mention of NOT Contains either, I really felt in doubt and needed to ask.

I'll leave an example of an attempt so that someone can tell me if there is any way and what the correct way to use would be, because I couldn't find it.

If it doesn't exist, here's the ideia to add it because it's great value!

A hug and thanks to all.

```
  var sheet = SpreadsheetApp.getActive().getSheetByName('Seu Seriado');
  var url = 'https://seuseriado.org/';

  const contentText = UrlFetchApp.fetch(url).getContentText();
  const $ = Cheerio.load(contentText);
  
	$('h2.entry-title.h6 > a:not(contains("SEM LEGENDA"))')
		.each((index, element) => {sheet.getRange(index+1,1).setValue($(element).text().trim());}); 
```

**Comment by fb55** [comment]
Try `:not(:contains(SEM LEGENDA))`!

**Comment by fredericomattos** [comment]
> Try `:not(:contains(SEM LEGENDA))`!

That's perfect mate, thanks a lot!
