### ISSUE TITLE
In XPATH I use '''...and''' to add an additional criterion, in cheerio is there this option?

### ISSUE THREAD

**Issue by fredericomattos** [cheeriojs/cheerio#2391]
**_First I would like to thank for the project because it is magnificent, second I want to apologize for the beginner question and I hope don't think it's bad for me to ask for help in the doubt._**

Using `=IMPORTXML('url','xpath')` I make the call with this XPATH:

`//div[contains(@class,'match-card') and ../../td[@class='score-time ']/a[contains(@href, 'matches')]]`

The idea is to collect the `div` that contain the `@class` with the word `match-card`
BUT 
he needs to have `td` linked to `@class='score-time'` and `a` contains the `@href` with the word `matches`

I tried to find a way to do this with CHEERIOGS but it always returns blank, my attempts were:

```
    $('tr:contains(td.score-time > a[href^="/matches/"]) > div[class^="match-card"]')
                  .each((index, element) => {ss.getRange(index + 2, 2).setValue($(element).text().trim());});
```

```
    $('tr td.score-time:contains(a[href^="/matches/"]) > div[class^="match-card"]')
                  .each((index, element) => {ss.getRange(index + Alast + 2, 2).setValue($(element).text().trim());});
```
```
    $('tr td.score-time > a[href^="/matches/"] > div[class^="match-card"]')
                  .each((index, element) => {ss.getRange(index + Alast + 2, 2).setValue($(element).text().trim());});
```

Could help me on how I could go about achieving my expected result?

**Comment by fb55** [comment]
Your confusion stems from `:contains` being for text (eg. `:contains(foo)` would match `<a>foo</a>`); try `:has` instead, which checks if an element contains an element matching a selector.
