### ISSUE TITLE
static `text()` method is not actually exported

### ISSUE THREAD

**Issue by Hashbrown777** [cheeriojs/cheerio#2402]
As mentioned in the README:

 > You may also render the text content of a Cheerio object using the text static method:

```javascript
const $ = cheerio.load('This is <em>content</em>.');
cheerio.text($('body'));
//=> This is content.
```

Yet neither `index.d.ts` nor `index.js` actually forwards `text` from `lib/static.{d.ts,js}` (it appears to re-export methods one-by-one for some reason, and misses `text`).

![image](https://user-images.githubusercontent.com/6907206/157560355-7ccd2147-6362-43b2-8b92-fe33b11ae226.png)

As a workaround I tried importing static directly, but it doesnt like it.

![image](https://user-images.githubusercontent.com/6907206/157560421-7c487593-6f29-43cc-884a-99ebdc6991fc.png)

Using `import {text} from 'cheerio/lib/static'` gets past typescript complaints, but for some reason doesn't transpile to mjs well.

![image](https://user-images.githubusercontent.com/6907206/157561433-a379cc08-d8fc-4550-82f1-500ac4d3760f.png)

So [at least in typescript targeting ES2020 using modules] it's impossible to use the text static method.

**Comment by Hashbrown777** [comment]
`1.0.0-rc.10` pulled via npm, btw

**Comment by brettz9** [comment]
Looks like this is a document bug; see #2286 for what it apparently actually should be. Also for `cheerio.html()` missing.

**Comment by Hashbrown777** [comment]
@brettz9 no he's using the object methods, not the static ones, that pull request should definitely not go through.

He's breaking the readme, not fixing the issue https://github.com/cheeriojs/cheerio/pull/2286/files

He's changed the static call `cheerio.text($('body'));` to a call to the member function (of the document) `$.text($('body'));`.
If he's willing to use member functions, he could have just done `$('body').text()`, he's completely missed the point.

**Comment by brettz9** [comment]
Ok, but the big problem now is that the static functions aren't exported and that PR is the only issue I see doing anything to draw attention to what a user can do. That doesn't make it right, but it does point to the need to get the main issue resolved.

**Comment by fb55** [comment]
I'm happy to accept a PR that adds the missing exports. Agreed they should be there.
