### ISSUE TITLE
New RC ?

### ISSUE THREAD

**Issue by bodinsamuel** [cheeriojs/cheerio#2436]
Hello team,

I was wondering if you could release a new RC (**11** I think) so we can have all the underlying `node_modules` up to date.
For example, `domhandler` has changed some of its type and their are now incompatible with the current RC but Cheerio is up to date in Github, "just" need a npm release ☺️ 

Best Regards,

**Comment by fb55** [comment]
I am currently working towards a new release of parse5 and will publish a new release of cheerio once that lands. Shouldn't be too long now.

**Comment by bodinsamuel** [comment]
Amazing news thanks a lot <3
