### ISSUE TITLE
<tr> tags with no <td> are not properly handled

### ISSUE THREAD

**Issue by liuxing** [cheeriojs/cheerio#2478]
`<tr>` tags with no `<td>` are not properly handled

```javascript
const cheerio = require('cheerio')

const html = `
<table>
    <tbody>
        <tr>
            <div>1</div>
            <div>2</div>
            <div>3</div>
        </tr>
        <tr>
            <div>1</div>
            <div>2</div>
            <div>3</div>
        </tr>
        <tr>
            <td>1</td>
        </tr>
        <tr>
            <div>1</div>
            <div>2</div>
            <div>3</div>
        </tr>
    </tbody>
</table>
`
const $ = cheerio.load(html)

$('table tr').each(function (i, elem) {
  const html = $(elem).html()
  console.log(html) 
})
```

can not get child elements of tr `div` tags

node version: v16.13.0
cheerio version: "^1.0.0-rc.10"
platform: MacBook Pro (13-inch, M1, 2020)

**Comment by fb55** [comment]
What version of Cheerio are you using?

**Comment by liuxing** [comment]
> What version of Cheerio are you using?

```
"cheerio": "^1.0.0-rc.10",
```

**Comment by fb55** [comment]
What you are experiencing here is the consequence of HTML's foster parenting: The `div`s without `td`s are moved right before the table. You can confirm this on JSFiddle: https://jsfiddle.net/3n24eouL/
