### ISSUE TITLE
next() and nextAll() stop at self-closing element 

### ISSUE THREAD

**Issue by cburatto** [cheeriojs/cheerio#2489]
Using cheerio `^1.0.0-rc.10` and `0.22.0`
Scenario: using `next() or nextAll()` to iterate on next siblings after a certain element
Expected: loop will find each and every next sibling of the element
Result: `next() and nextAll()` don't find elements if the current element is self-closing

Sample HTML to reproduce issue (Look at `<div style="page-break-before: always; clear:both"/>`):

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
    <body>
    
        <div class="TOCChapter" style="text-align: right;"><strong><span
                style="font-size: 24pt;">CHAPTER 12<br/></span></strong><span style="font-size: 24pt;"><em>Something</em></span>
        </div>
        <div class="TOCDescription">Explains something.</div>
        <div style="page-break-before: always; clear:both"/>
        <div style="text-align: center;"><span
                style="font-size: 12pt;"><strong><u>Something<br/><br/></u></strong></span>
        </div>
        <table class="tableNoInsideBorder" style="width: 100%; border-style: none;" border="1">
            <tbody>
        
            <tr>
                <td> TEST
                </td>
            </tr>
            </tbody>
        </table>
    
    </body>
</html>
```
Find first element `<div class="TOCChapter" style="text-align: right;">`, then get all its `next` siblings.

JS code:

    let content = fs.readFileSync(glossaryFileLocation, 'utf8');
    let $ = cheerio.load(content);
    let chapter = $('div.TOCChapter span:contains(\'CHAPTER 12\')');
    if(!chapter || chapter.length === 0){
        console.log('not found');
        return;
    }
    console.log('found');
    let parent = $(chapter[0]).parents("div.TOCChapter");
    let next = $(parent[0]).nextAll();
    console.log(next.length);
    $(next).each((i) => {
        console.log(next[i].attribs);
    });

Results with `<div style="page-break-before: always; clear:both"/>`:
Finds only 2 siblings.
```
found
2
Object {class: "TOCDescription"}
Object {style: "page-break-before: always; clear:both"}
```
If you change to `<div style="page-break-before: always; clear:both"></div>` (not self-closing), results are:
Finds all 4 siblings
```
found
4
Object {class: "TOCDescription"}
Object {style: "page-break-before: always; clear:both"}
Object {style: "text-align: center;"}
Object {class: "tableNoInsideBorder", style: "width: 100%; border-style: none;", border: "1"}

```

**Comment by fb55** [comment]
Self-closing tags in HTML are ignored. The other elements cannot be found in your example, because they are children of the `div` ending with `/>`.

**Comment by cburatto** [comment]
Fantastic: I had no idea of this in the HTML spec. Thanks for the quick lesson.
