### ISSUE TITLE
attr automatically encodes html entities

### ISSUE THREAD

**Issue by nnscr** [cheeriojs/cheerio#2497]
Hello,
I'm using cheerio to convert view files from one framework to another. 

When I do:
```ts
const $ = ch.load("<div></div>", {}, false)
$("div").attr("foo", "bar && baz")
console.log($.html())
```

I get this output:
```html
<div foo="bar &amp;&amp; baz"></div>
```

But I need this:
```html
<div foo="bar && baz"></div>
```

So I want to disable the automatic encoding of entities. I understand that it makes perfect sense to do this automatically, usually. But in my case, where I convert template languages, I need to have my entities not encoded.

Is there any way to do this?
Thanks a lot!

**Comment by nnscr** [comment]
Sorry, only just realized that this is not only an issue with attr(). But the problem remains.

```ts
const $ = ch.load("<div bar=\"foo && baz\">{{&&}}</div>", { decodeEntities: false }, false)
console.log($.html({ decodeEntities: false }))
```

This produces
```html
<div bar="foo &amp;&amp; baz">{{&amp;&amp;}}</div>
```

So basically I would need an `encodeEntities: false` option

**Comment by nnscr** [comment]
Found a solution that seems to be working for now, but it relies on an internal option, which is weird to use with Typescript. If there is a better option to do this I would be happy to use that instead.

```ts
const $ = ch.load("<div bar=\"foo && baz\">{{&&}} &amp;&amp;</div>", { decodeEntities: false, _useHtmlParser2: true } as any, false)
console.log($.html())
```

Output:
```html
<div bar="foo && baz">{{&&}} &amp;&amp;</div>
```

**Comment by fb55** [comment]
@nnscr The latter is what I would have recommended.
