### ISSUE TITLE
selector after :nth- does not match

### ISSUE THREAD

**Issue by tp** [cheeriojs/cheerio#251]
I have come across some interesting queries, failing to match, after I use `nth-of-type` or `nth-child`.

Here is a simple example:

```
var cheerio = require('cheerio');
var request = require('request');

request('http://research.swtch.com/goblog', function(err, r, body) {
  var $ = cheerio.load(body);

  console.log($('div.main > div:nth-of-type(2) > div:nth-of-type(2) .plus-comment').length);
});
```

With jQuery or `document.querySelectorAll` I get 14 matches, which `cheerio` none.

**Comment by coderofsalvation** [comment]
I had a similar problem:

    div.result_data > table > tbody > tr:nth-child(1) > td:nth-child(2)

did not work (although it matches the html markup)
This however did work:

    div.result_data > table > tr:nth-child(1) > td:nth-child(2)

My theory: chrome's fault.
I rightclicked the element inside the chrome inspector and pressed 'copy css path'.
Chrome generates the CSSPath from the *generated* DOM (which autocorrects missing <tbody> elements, hence the <tbody> in the selector.).

So my advice, make sure all elements are present in the actual html :)
