### ISSUE TITLE
complex positional selectors fail to return matches

### ISSUE THREAD

**Issue by rylan** [cheeriojs/cheerio#2516]
Hello, 

While investigating moving from rc.3 to rc.10 which removes the need for cheerio-advanced-selectors, I found rc.10 fails these test cases outlined in by that project (https://github.com/watson/cheerio-advanced-selectors/blob/master/test.js#L65)
```
 ['Simple selector with :eq() in the middle', '<div><span>foo</span></div><div><span>bar</span></div>', 'div:eq(0) span', 'foo'],
 ['Complex selector', '<div><span><h1>foo</h1></span><span><h1>bar</h1></span></div>', 'div:first span:eq(1) h1', 'bar']
```
in both cases empty strings are returned.

**Comment by fb55** [comment]
This was already fixed in https://github.com/cheeriojs/cheerio-select/pull/292. A new release of Cheerio should come soon with a final fix :)

Thanks for linking to the test cases, I'll make sure to include them in `cheerio-select`.
