### ISSUE TITLE
Broken :nth-child selector

### ISSUE THREAD

**Issue by harimambura** [cheeriojs/cheerio#2542]
In last version ([1.0.0-rc.11]) selector with :nth-child(n) throws an error "Uncaught TypeError TypeError: getNCheck is not a function", but previous version works fine.

I use the esm package if it matters

**Comment by fb55** [comment]
I am unable to replicate this:

```js
import { load } from 'cheerio';

console.log(load('<p>1<p>2')('p:nth-child(2)').text());
```

You likely have old package versions installed and running a `rm -r node_modules package-lock.json` before the `npm install` should resolve things.

**Comment by harimambura** [comment]
> I am unable to replicate this:
> 
> ```js
> import { load } from 'cheerio';
> 
> console.log(load('<p>1<p>2')('p:nth-child(2)').text()); // 2
> ```
> 
> You likely have old package versions installed and running a `rm -r node_modules package-lock.json` before the `npm install` should resolve things.

Clear npm cache, create new folder, init npm, set "type": "module" in package.json, next "npm i cheerio"
use the next code to reproduce:
`import cheerio from 'cheerio';
const $ = cheerio.load('<html><body><div></div><div></div></body></html>');
$('body > div:nth-child(1)')`

**Comment by fb55** [comment]
I am able to replicate now. Turns out a default import to `nth-check` wasn't available, as that module was still CommonJS. Fix incoming with https://github.com/fb55/nth-check/pull/206

**Comment by fb55** [comment]
Bumping `nth-check` to `2.1.0` resolves the issue. That version is already in range for `cheerio`, so no steps are required here.

@harimambura Thank you for the report!

**Comment by eelkevdbos** [comment]
I'd like to report that this still seems broken in version 1.0.0.

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/dbc1a52e-6dc3-43fc-a83f-85fdccdd1e63">
