### ISSUE TITLE
Get an Error About export 

### ISSUE THREAD

**Issue by cuobiezi** [cheeriojs/cheerio#2547]
The Error is
Ã— ERROR: Package subpath './lib/utils' is not defined by "exports" in D:\Jenkins\workspace\app\node_modules\cheerio\package.json

**Comment by fb55** [comment]
Seems like you are using a deep import of `lib/utils`. Could you provide some context on what you are trying to accomplish? With that, `lib/utils` can be added as an exported file.

**Comment by RossMcMillan92** [comment]
Getting this too:

```
    Cannot find module 'cheerio/lib/utils' from 'node_modules/enzyme/build/Utils.js'

    Require stack:
      node_modules/enzyme/build/Utils.js
      node_modules/enzyme/build/ShallowWrapper.js
      node_modules/enzyme-to-json/utils.js
      node_modules/enzyme-to-json/createSerializer.js
      node_modules/enzyme-to-json/serializer.js

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (node_modules/enzyme/src/Utils.js:10:1)
```

**Comment by cuobiezi** [comment]
> Seems like you are using a deep import of `lib/utils`. Could you provide some context on what you are trying to accomplish? With that, `lib/utils` can be added as an exported file.

My error should be enzyme too

**Comment by cuobiezi** [comment]
> > Seems like you are using a deep import of `lib/utils`. Could you provide some context on what you are trying to accomplish? With that, `lib/utils` can be added as an exported file.
> 
> 
> 
> Enzyme uses a deep import lib/utils (https://github.com/enzymejs/enzyme/blob/master/packages/enzyme/src/Utils.js#L11), so Enzyme and libraries built on Enzyme are failing due to this.
> 
> See: https://github.com/enzymejs/enzyme/issues/2558 and https://github.com/enzymejs/enzyme/issues/2559
> 
> 
> 
> The second Enzyme issue seems to imply that no immediate fix is coming from Enzyme to correct their import, so it may be easier and faster to add `lib/utils` as an exported file in Cheerio to make Enzyme's import valid.

I think so. Seem Enzyme didn't updated any release and it is working right when we use cheerio 1.0.0-rc.10. I think cheerio should be backward compatibility

**Comment by ygnoh** [comment]
It looks like the same cause w/ https://github.com/cheeriojs/cheerio/issues/2545

**Comment by nnegi79** [comment]
> > > Seems like you are using a deep import of `lib/utils`. Could you provide some context on what you are trying to accomplish? With that, `lib/utils` can be added as an exported file.
> > 
> > 
> > Enzyme uses a deep import lib/utils (https://github.com/enzymejs/enzyme/blob/master/packages/enzyme/src/Utils.js#L11), so Enzyme and libraries built on Enzyme are failing due to this.
> > See: [enzymejs/enzyme#2558](https://github.com/enzymejs/enzyme/issues/2558) and [enzymejs/enzyme#2559](https://github.com/enzymejs/enzyme/issues/2559)
> > The second Enzyme issue seems to imply that no immediate fix is coming from Enzyme to correct their import, so it may be easier and faster to add `lib/utils` as an exported file in Cheerio to make Enzyme's import valid.
> 
> I think so. Seem Enzyme didn't updated any release and it is working right when we use cheerio 1.0.0-rc.10. I think cheerio should be backward compatibility

I am also getting the same issue. Because of enzyme;s deep link dependency, build is failing with this error "
 Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/utils' is not defined by "exports".  Do you know any workaround/immediate fix for this?

**Comment by Christophe31** [comment]
@nnegi79 I think I'll lock 1.0.0-rc.10

**Comment by zburke** [comment]
We have [the same sort of error](https://github.com/folio-org/stripes-connect/runs/6616143602?check_suite_focus=true):

> Error: Package subpath './lib/utils' is not defined by "exports"... 

but IIUC @fb55 is telling us, "We changed some private implementation details in the latest release, but that shouldn't matter if you consume our public exports, which did not change. Enzyme must rely on some of the private implementation details that we changed." IOW, "Cheerio isn't broken, Enzyme is (and always was, we just didn't know until now)."

**Comment by fb55** [comment]
@zburke The truth is that I didn't know about enzyme's dependency. I also would have added the exports by now if there weren't some other issues with enzyme (see https://github.com/cheeriojs/cheerio/issues/2547 and #1585).

As enzyme recommends users stay with `1.0.0-rc.3`, I honestly still don't have a good way forward.

**Comment by yehor-anisimov** [comment]
In case someone looking for solution. You should lock `cheerio` version in your package.json

`"cheerio": "1.0.0-rc.3",`

```
npm list cheerio
@microlink/react-json-view@1.23.1 /react-json-view
├── cheerio@1.0.0-rc.3
└─┬ enzyme@3.11.0
  └── cheerio@1.0.0-rc.3 deduped
```
