### ISSUE TITLE
prop('src'): TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by Markus-Rost** [cheeriojs/cheerio#2552]
I'm using `1.0.0-rc.11`. Trying to get the `src` property of an Cheerio without any elements throws a TypeError.
```js
$('.infobox').find('img').filter( (i, img) => {
	img = $(img).prop('src')?.toLowerCase();
	return img?.startsWith('https://');
} ).first().prop('src');
```
The `.prop('src')` on the `.first()` throws an error if the `filter()` returned an empty list.
```js
file:///home/wikibot/bots/discord-wiki-bot/node_modules/domelementtype/lib/esm/index.js:29
    return (elem.type === ElementType.Tag ||
                 ^

TypeError: Cannot read properties of undefined (reading 'type')
    at isTag (file:///home/wikibot/bots/discord-wiki-bot/node_modules/domelementtype/lib/esm/index.js:29:18)
    at isTag (file:///home/wikibot/bots/discord-wiki-bot/node_modules/domhandler/lib/esm/node.js:224:12)
    at LoadedCheerio.prop (file:///home/wikibot/bots/discord-wiki-bot/node_modules/cheerio/lib/esm/api/attributes.js:155:22)
    at file:///home/wikibot/bots/discord-wiki-bot/functions/parse_page.js:379:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.1.0
```
This worked without an error in `1.0.0-rc.10`.

Also there is a `'` missing in the description.
![image](https://user-images.githubusercontent.com/37275477/170106965-d5198b59-c5f4-4665-9b70-c319f1f6fff3.png)

**Comment by fb55** [comment]
Thanks for the report! I had a look at all props, and have a comprehensive fix coming in with #2557.

**Comment by Kikobeats** [comment]
Hey @fb55, can you release a new rc version? latest is broken because prop throws an error under no presence 🙂

btw, thanks for this, I didn't note about `.prop` until now.

being the output the same, will be `.prop` prefer over `.attr`? asking form a perf point of view

**Comment by fb55** [comment]
`.attr` is doing less work and will always be faster.
