### ISSUE TITLE
`:empty` does not match elements that only have whitespaces.

### ISSUE THREAD

**Issue by issuefiler** [cheeriojs/cheerio#2561]
```javascript
import Cheerio from "cheerio";
Cheerio.load("<test></test>")("test:empty").length; // 1
Cheerio.load("<test> </test>")("test:empty").length; // 0 (Expected: 1.)
```

-----

The `:empty` CSS pseudo-class should match elements that only have whitespaces as well as completely empty ones.

From [the CSS _Selectors Level 4_ specification](https://www.w3.org/TR/selectors-4/#the-empty-pseudo):

> ## 14.2. [`:empty`](https://www.w3.org/TR/selectors-4/#empty-pseudo) pseudo-class
>
> The `:empty` pseudo-class represents an element that has no children except, optionally, [_document white space characters_](https://www.w3.org/TR/css-text-3/#white-space). ….
>
> ### Example 46
>
> Examples: `p:empty` is a valid representation of the `<p>` elements in the following HTML fragment:
> - `<p></p>
`
> - `<p>`
> - `<p> </p>`
> - `<p></p>`

**Comment by fb55** [comment]
Thanks for the bump, released a new version

**Comment by yorch** [comment]
awesome, thanks a lot!
