### ISSUE TITLE
Faulty esbuild bundle since 1.0.0-rc.11

### ISSUE THREAD

**Issue by shishkin** [cheeriojs/cheerio#2573]
I've noticed a regression in 1.0.0-rc.11 from 1.0.0-rc.10 when bundling for node with esbuild. The issue is with the nth-check import. Esbuild generates this:

   const func = (0, import_nth_check.default)(rule);

And fails at runtime with:

    TypeError: (0 , import_nth_check.default) is not a function

Steps to reproduce are to use `nth-child` selector and bundle with esbuild:

    esbuild --bundle --format=esm --platform=node --target=node16 --main-fields=module,main script.ts > script.mjs
    node script.mjs

But it also fails with CommonJS bundling format.

I suspect it might be fixed in https://github.com/fb55/nth-check/commit/aeeb0676f6af940e8639f64e27781443694ca05e but just want to make sure the issue is known at cheerio repo.

**Comment by fb55** [comment]
Yes, there was a fault release of nth-check. The release with a fix is in-range for cheerio, so there is nothing to do here :)

**Comment by shishkin** [comment]
Do you mean that is fixed in the next upcoming rc? Or is there something else that needs to happen so that the issue is fixed in rc11?

**Comment by fb55** [comment]
Nope, you just have to convince your package manager to pull in the fix. Removing the lock file & `node_modules` generally does the job.

**Comment by shishkin** [comment]
Thanks! It worked and the regression is fixed.
