### ISSUE TITLE
Cheerio :contains Case-Insensitive

### ISSUE THREAD

**Issue by zhakypadil** [cheeriojs/cheerio#2577]
There are a bunch of solutions to make jQuery's `:contains` selector case-insensitive  

However they don't apply to Nodejs's cheerio? Is it possible to add that feature and use it like `:icontains`?

**Comment by fb55** [comment]
There is already an `:icontains` pseudo-class! 😃

**Comment by zhakypadil** [comment]
Thanks! I guess I had some weird error when I tried that, but now it works
