### ISSUE TITLE
Changing selected property of an element should not affect attribute

### ISSUE THREAD

**Issue by andolf** [cheeriojs/cheerio#2648]
When changing the `selected` property using `.prop()` you're changing the inherent state of the element. The attribute `selected` only defines the initial state of the document when parsed.

However, when changing the property `selected` it now also alters the attribute.

Simple code example:

```js
const {load} = require("cheerio");

const $ = load(`<select>
<option>1</option>
<option selected>2</option>
</select>`);

const option = $("option").eq(0);

console.log(option.prop("selected")); // should be false
console.log(option.attr("selected")); // should be undefined

option.prop("selected", true);

console.log(option.prop("selected")); // should be true
console.log(option.attr("selected")); // should still be undefined, but is "selected"
```

Notable is that this same behaviour also applies to the `checked` property.

[jQuery's docs on `.prop()`](https://api.jquery.com/prop/)

**Comment by fb55** [comment]
Interesting issue. cheerio's `prop` also accesses attributes by default, which is non-standard. I quite like the way `prop` works in Cheerio at the moment, and will have to think about the best way forward.

**Comment by fb55** [comment]
I believe that the current behaviour is more useful in a server context. Having state that is not reflected by rendered content will be surprising, and has limited uses. Please let me know if you disagree, I am curious about your use-case.
