### ISSUE TITLE
Parsing self closing tag produce bad html

### ISSUE THREAD

**Issue by juanSanchezAlcala** [cheeriojs/cheerio#2678]
Self closing tag is been removed.

Example :

```
cheerio.load(`<div class="n-content-video n-content-video--youtube">
			<iframe src="https://www.youtube.com/?rel=0"/>
		</div>`).html()
```

This produces : 

`'<html><head></head><body><div class="n-content-video n-content-video--youtube">
			<iframe src="https://www.youtube.com/?rel=0">
		</div></iframe></div></body></html>'`

As you can see closing slash from iframe has disappeared producing bad html syntax

**Comment by juanSanchezAlcala** [comment]
the way to resolve this is using xmlMode or recognizeSelfClosing

```
cheerio.load(`<div class="n-content-video n-content-video--youtube">
			<iframe src="https://www.youtube.com/?rel=0"/>
		</div>`,{recognizeSelfClosing : true}).html()
```

**Comment by juanSanchezAlcala** [comment]
with recognizeSelfClosing option produces bad html syntax also.

```

'<html><head></head><body><div class="n-content-video n-content-video--youtube">
			<iframe src="https://www.youtube.com/?rel=0">
		</div></iframe></div></body></html>'
```

**Comment by fb55** [comment]
The original behaviour is in line with how browsers work: [Try it in yours](https://jsconsole.com/?document.body.innerHTML%3D%27%3Cdiv%20class%3D%22n-content-video%20n-content-video--youtube%22%3E%3Ciframe%20/%3E%3C/div%3E%27%3Bdocument.body.innerHTML).

**Comment by juanSanchezAlcala** [comment]
The problem comes from transforming from xml to html
```
 cheerio.load(cheerio.load(`<div class="n-content-video n-content-video--youtube">
			<iframe src="https://www.youtube.com?rel=0"></iframe>
		</div><div><div class="n-recommended"></div></div>`).xml()).html()
```

**Comment by 5saviahv** [comment]
When I put code (from above) into Chrome browser I got:
``` html
<html><head></head><body><div class="n-content-video n-content-video--youtube">
<iframe src="https://www.youtube.com?rel=0"></iframe>
</div><div><div class="n-recommended"></div></div>
</body></html>
```
so browser actually closes ```iframe``` before it's parent element ```div```

maybe you should decode content first, so you can avoid this "repairing" functionality.

``` javascript
// decode self closed tags as fragment
const decodedHTML = cheerio.load(selfclosedHTML, { xmlMode: true }, false).html({ xmlMode: false });

// and now use it as regular 
console.info(cheerio.load(decodedHTML).html());
```

result:
``` html
<html><head></head><body><div class="n-content-video n-content-video--youtube">
<iframe src="https://www.youtube.com?rel=0"></iframe>
</div><div><div class="n-recommended"></div></div></body></html>
```
