### ISSUE TITLE
Why cannot select?

### ISSUE THREAD

**Issue by 2GEasy** [cheeriojs/cheerio#2682]
`<noscript><img alt="4kUp" src="https://lh5.ggpht.com/-uM9dqtKdSUc/Yuvsv8rX4SI/AAAAAAAAkVU/-0qaTc9wxsEUmbJ15KhgoyBINkVaLQ91QCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-052.webp" title="4kUp"/></noscript> <div class='download-box'><p>- Album: XIUREN</p><p>- Model: <a title='Xu An An (徐安安)' href='/search?q=Xu An An (徐安安)&max-results=18' target='_blank'>Xu An An (徐安安)</a></p><p>- Number of Photos: 52P</p><div>- This post 
only contain a few selected pictures with reduced size and quality.<br />- To download full-size with high-quality, click the following button:</div></div><a name='more'></a><div class='download-box' id='download'><h3>Download</h3><div>- Download from <a href='https://bit.ly/3zWOkpR' target='_blank'>TeraBox</a></div></div><br/><div id='gallery' class='flex-images'><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-1UlMiNOvdD0/YuvshdytbOI/AAAAAAAAkSI/a0TDnWWsaP4vv7krAnY4ECJ_34qFOit3gCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-001.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-Giq5uQnBEkk/YuvshxPX8pI/AAAAAAAAkSM/eLdK7bz-fkQmlGsG-bwcgSI5kZMI7H6DQCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-002.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-tunrCAr9a94/YuvsiynhbJI/AAAAAAAAkSQ/m98e1SidlxoOtMdYYtOfZlU27n6LBa94QCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-003.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-FF6K7GGrfuE/YuvsizN9KAI/AAAAAAAAkSU/Axsp7qDy6TQLlXnnKaWNbNSbEBy411yewCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-004.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-q_GZCvXXRkI/YuvsjPHlHrI/AAAAAAAAkSY/rPNoj6PZcFQ7VBmfQkV6zcfqqG1MYkh9QCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-005.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-_qWj0xaXJHk/YuvsjZysRPI/AAAAAAAAkSc/zzu5Dmx6SZQfkCiUWlR2nR2iMaQpJqHPgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-006.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-1QuIpHlUfuQ/YuvsjWlg9jI/AAAAAAAAkSg/4Wx5n_JPMM0pU0DFSrgd9Ma7TROoGaGvACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-007.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-0T0f1X3fYto/Yuvsj8mJ0SI/AAAAAAAAkSk/Vg2r1pLDHnc5al5-UYfH7VE0H-QXd3KJACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-008.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-uosDfsTXlU4/YuvskDwE3XI/AAAAAAAAkSo/Kga_cdnM6rQfrJOG0rGOp4eqbzr1v8xYACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-009.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-Eg8sVLeIvOg/YuvskF_JwpI/AAAAAAAAkSs/xYBbG2XC1UUTH_ejjJs7_2KApZaL42UQwCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-010.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-MF0r6nxWtNY/YuvskQN4ekI/AAAAAAAAkSw/zpyE55sL6Jw5-6lUrYIZ5N5i-lRYBS7OQCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-011.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-iQbNfCaZi7s/YuvskiFjy0I/AAAAAAAAkS0/_2307WGdoccyh1VVfhJLNVfVP0GEhDKyACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-012.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-jUjbc5M6eFs/YuvskkfhrzI/AAAAAAAAkS4/nkDZ7knfuos6Nf6q0HnCEL0cy-kuHXmQwCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-013.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-742dYeOV2kI/YuvslJnh5LI/AAAAAAAAkS8/Dtdjkld29VEXrep6n0m3rQlwOxKNhbQ9QCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-014.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-sYXSbcIRtVU/YuvslN5lauI/AAAAAAAAkTA/UClAEssfeDox-nyqPyUgWGB4LF0qpJleACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-015.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-jNuRqia9XtI/Yuvslb2n-_I/AAAAAAAAkTE/SJWj9uR1_Z0NusMhVS-FYLn311WePG3MQCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-016.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-8hIjDnFhy3U/YuvsliLpjZI/AAAAAAAAkTI/YIERexxOwwUkIKYv5VNftL7Z-3UclU8cgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-017.webp" /><img data-original-height="120" data-original-width="181" src="https://lh5.ggpht.com/-QY718PyIkLA/Yuvsl1L671I/AAAAAAAAkTM/0xTWRchbLsskkAi65BE7vncp4RUaXcf-wCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-018.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-gol9MLjYQ9E/Yuvsl14okvI/AAAAAAAAkTQ/8XFR2S4VxV8jQnELuzBSXqM4umTFhGWpwCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-019.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/--Ry-GmLl5ao/YuvsmDpiJkI/AAAAAAAAkTU/5pY35hybOtw2e0_FU52h07TYXFhdeHQFQCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-020.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-Lq9t7PT8YWY/YuvsmTmQrvI/AAAAAAAAkTY/s9TTijKEGhwOARWvjiabH9xZJCFaUMduwCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-021.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-pICS2UIxANQ/YuvsmnzO2LI/AAAAAAAAkTc/DqAOQsFNJX4dh4WUIDV7hdirOMxwyMkBACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-022.webp" /><img data-original-height="120" data-original-width="181" src="https://lh5.ggpht.com/-4l6jLjv6a7M/Yuvsmwzdo0I/AAAAAAAAkTg/WEg5f0msCkwIqNGqvcQudcJZXiXRxbASgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-023.webp" /><img data-original-height="120" data-original-width="181" src="https://lh5.ggpht.com/-ok5Q13t3Hnk/Yuvsm_DNBNI/AAAAAAAAkTk/YuijLSI2MkcVAbUkb9tO0Fak47PEPe5uACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-024.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-XdVXXacF-70/YuvsnCruznI/AAAAAAAAkTo/DZTlWNvwpLQxXcdfb1a4kFZJzXKjOJPwQCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-025.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-bl1Z_6VfozM/YuvsnR6jntI/AAAAAAAAkTs/81MvbjfMKsEpv67T-9EggbG98qYu4TLewCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-026.webp" /><img data-original-height="120" data-original-width="181" src="https://lh5.ggpht.com/-0AZQpK3ZdOA/YuvsnjsrZOI/AAAAAAAAkTw/tZ27xHU8EJcBQxj2OJPJOijLlPO-ltwZwCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-027.webp" /><img data-original-height="120" data-original-width="181" src="https://lh5.ggpht.com/-nLwP50UwOwY/Yuvsnl7vEJI/AAAAAAAAkT0/2Cny8LyJegUE_TOvjzknxAN_kxT_N6WwwCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-028.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-N9tn_jO52tU/Yuvsn8QxuII/AAAAAAAAkT4/EMWeaPmGyqA6ytkUpcdZXgI6Frpcv07JQCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-029.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-cDTEhAFzW2g/YuvsnwL1VlI/AAAAAAAAkT8/zzxc1LblY9M9pFAHiCzz9tyCwa8i9SZ0ACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-030.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-vBxRiNSWJzw/YuvsoKMP_bI/AAAAAAAAkUA/BQA0qKLvKEIBsukOJG1hKoySwgHfwyTMgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-031.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-2mL0P4U4Cq8/YuvspBzuTSI/AAAAAAAAkUE/iILvurHldLAHJtuq748NBS1vZh8bYTh4QCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-032.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-1oSkmxXaDlc/YuvspYAEpKI/AAAAAAAAkUI/4ifhiUlPlacSowe4mU1n7vszjIy2VpjQACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-033.webp" /><img data-original-height="120" data-original-width="181" src="https://lh5.ggpht.com/-dzgpHXI7Cac/YuvspZT-T-I/AAAAAAAAkUM/pQRH7P7A2PUp4B7taM8HRdBJWKl6psLagCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-034.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-KCkttdD36AI/Yuvsp4_kVTI/AAAAAAAAkUQ/0yatmKvSRtILX5S-3z5G_S4WveHwNWk_ACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-035.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-tDVoXjAeQlE/YuvsqdMILAI/AAAAAAAAkUU/AK7-CA5nb1w_P_ls9sp7bqQ8nP9g-kqEACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-036.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-0wP4C5TCIDs/Yuvsq3XnsOI/AAAAAAAAkUY/vm2V0_EGbIUoUnG5DWUUQdzzu1iSfRM3QCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-037.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-Yg3R51XQSn8/YuvsrWfKwaI/AAAAAAAAkUc/mWs8YTFdTGMI9gTq46zMeZb3shrGzJAegCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-038.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-vb9TQJHuQQA/YuvsrwZBZlI/AAAAAAAAkUg/O4oSL9htErkcxJPuQDe3DYkIf2VzpOjmACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-039.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-A4olyu_PMYg/Yuvsr1gVH4I/AAAAAAAAkUk/QI56RLSU3lATGjxNG9uZDTmJAf_Y8JVzgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-040.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-OyzQ6O8-N6w/Yuvsr7hvSFI/AAAAAAAAkUo/TvEj9HvZY_MFBsWF7eCCDUySa0FWs4gKgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-041.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-tw1P8ZqiArs/YuvssZm7t5I/AAAAAAAAkUs/rYexOGC9bosMvmLsiWurDU7wquGszOsZgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-042.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-A2Vu7DR56vs/Yuvss57C5xI/AAAAAAAAkUw/9lWTHxNa-PYfiEYdfcfIH6OdeE1Ynnj6wCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-043.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-2Z1apRBIZF4/Yuvste4LhQI/AAAAAAAAkU0/GRq0NJoy2zUjw0lQv1rJREBzAzgzBos0ACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-044.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-lvVdwYgE_N8/YuvsuOZ7yqI/AAAAAAAAkU4/bQ91wyZslhAbB_3o9tXNyDaK7A5Osz7tgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-045.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-VichCFA8Zio/YuvsunIdFrI/AAAAAAAAkVA/Jf54Co57I7ohxXJSJmQWKz2TeC1XQmdwgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-046.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-uyjndrHKkC8/YuvsuuZ9_CI/AAAAAAAAkU8/SAP8KcxyT3cNgV6XHJRHTmZeRJIDo0mDgCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-047.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-c3CaA7e7bAI/Yuvsu32t2uI/AAAAAAAAkVE/B5oWAgfILD450K0xLEb0T5M-GfvTKqi2ACNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-048.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-KV3kYfOwl10/YuvsvOM9vrI/AAAAAAAAkVM/3nI5FpxvQicZ2_Z9O-h-Vdp9dQ62wfqWQCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-049.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-V9zDSrgotJg/YuvsvJys-rI/AAAAAAAAkVI/047PWEIX_dgVK7gkfv7qoivuJ5SO07sKQCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-050.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-mqAoHvijGKc/YuvsvXnawTI/AAAAAAAAkVQ/152tZ2UBd50o6XXsO9QrIU0hH3YNgjALwCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-051.webp" /><img data-original-height="120" data-original-width="80" src="https://lh5.ggpht.com/-uM9dqtKdSUc/Yuvsv8rX4SI/AAAAAAAAkVU/-0qaTc9wxsEUmbJ15KhgoyBINkVaLQ91QCNcBGAsYHQ/h120/XIUREN-No.4954-Xu-An-An-4kUp-052.webp" /></div>`

this is html and i want select ".download-box > a" but, cannot select .download-box. (return null)

**Comment by 5saviahv** [comment]
with selector: ```".download-box > a"``` you specify <a> tag has to be direct sibling for a "download-box" tag, but in your case <a> tags are nested within other tags.

for selecting <a> tags inside of download-box you simply need selector as ```".download-box a"```
