### ISSUE TITLE
TypeError: that is not a function when call html() to get outerHTML

### ISSUE THREAD

**Issue by genru** [cheeriojs/cheerio#2692]
Hi,

when I tried to get selected element, I got this error. the blowing demo can reproduce this issue
```javascript
const s = '<ul id="fruits">\
<li class="apple">Apple</li>\
<li class="orange">Orange</li>\
<li class="pear">Pear</li>\
</ul>';
const $ = cheerio.load(s);
console.info(cheerio.html($('.apple')));
```

is it a known bug?

"cheerio": "^1.0.0-rc.12"
node:  v16.13.1

**Comment by locona** [comment]
I also got the same error.

But the test code is successful.
Is it an environmental issue?
Is there a nodejs version specification or something?

**Comment by locona** [comment]
## Debug Result

**target**
https://github.com/cheeriojs/cheerio/blob/main/src/static.ts#L20-L29

`that`  function

**sample code (use part of src/static.spec.ts)**
```
    const $elem = cheerio('<span>foo</span>').html('');
    console.info(cheerio.html($elem));
``

### cheerio

```
      [Function: initialize] {
        html: [Function: html],
        xml: [Function: xml],
        text: [Function: text],
        parseHTML: [Function: parseHTML],
        root: [Function: root],
        contains: [Function: contains],
        merge: [Function: merge],
        load: [Function: load],
        _root: Document {
          parent: null,
          prev: null,
          next: null,
          startIndex: null,
          endIndex: null,
          children: [],
          type: 'root'
        },
        _options: { xml: false, decodeEntities: true },
        fn: Cheerio {
          constructor: [Function: LoadedCheerio],
          _make: [Function (anonymous)],
          _parse: [Function (anonymous)],
          _render: [Function (anonymous)]
        }
      }
```


### My Project 
```
{
  load: [Function: load],
  html: [Getter],
  xml: [Getter],
  text: [Getter],
  contains: [Function: contains],
  merge: [Function: merge],
  parseHTML: [Function: parseHTML],
  root: [Function: root],
  default: [Function: initialize] {
    html: [Function: html],
    xml: [Function: xml],
    text: [Function: text],
    parseHTML: [Function: parseHTML],
    root: [Function: root],
    contains: [Function: contains],
    merge: [Function: merge],
    load: [Function: load],
    _root: Document {
      parent: null,
      prev: null,
      next: null,
      startIndex: null,
      endIndex: null,
      children: [],
      type: 'root'
    },
    _options: { xml: false, decodeEntities: true },
    fn: Cheerio {
      constructor: [Function: LoadedCheerio],
      _make: [Function (anonymous)],
      _parse: [Function (anonymous)],
      _render: [Function (anonymous)]
    }
  }
}
```

**Comment by lseongjoo** [comment]
I have the same problem with same platform.

**Comment by Jscherbe** [comment]
I ran into the same issue, when trying to get the outer HTML as described in the README. I think it may be a typo. If you use the cheerio instance (ie. "$") in the example it seems to work as intended. 

Modified working example below for reference:
```js
const s = '<ul id="fruits">\
<li class="apple">Apple</li>\
<li class="orange">Orange</li>\
<li class="pear">Pear</li>\
</ul>';
const $ = cheerio.load(s);
console.info($.html($('.apple')));
```

**Comment by genru** [comment]
@Jscherbe it works for me, great!

maybe usage document should be updated
