### ISSUE TITLE
Cannot find module '.' or its corresponding  type declarations

### ISSUE THREAD

**Issue by poisoncat** [cheeriojs/cheerio#2703]
when I use cheerio in my project with typescript,  and try to compile it by `tsc`. The compiler throws an exception described below:
```typescript
error TS2307: Cannot find module '.' or its corresponding type declarations.

2 import type { CheerioAPI, Cheerio } from '.'; 

Found 1 error in node_modules/cheerio/lib/esm/static.d.ts:2
```
This seems to be a bug in the package itself. How should I solve this problem? Thanks.

And I only use cheerio in my project like this:
```typescript
import * as cheerio from "cheerio";
cheerio.load(content) // The type of content is string.
```
"cheerio": "^1.0.0-rc.12"
"@types/cheerio": "^0.22.31"
node v16.16.0
npm v8.16.0

**Comment by javaarchive** [comment]
The temporary workaround I came up with was to change '.' to './index.js' for the time being but this is a generated file so not sure how to fix in the source itself.

**Comment by fb55** [comment]
Could you share the TypeScript version you are using?

**Comment by poisoncat** [comment]
Hi, the TypeScript version I'm using is the latest 4.7.4

**Comment by javaarchive** [comment]
Same version, `tsconfig.json` is set so that it should be producing js files with es6 imports.
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "lib": ["ES2022"],
    "moduleResolution": "Node16",
    "rootDir": ".",
    "outDir": "build",
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "alwaysStrict": false,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": false,
    "esModuleInterop": true,
    "allowJs": true
  },
  "include": ["src/**/*", "__tests__/**/*"]
}
```

**Comment by poisoncat** [comment]
My `tsconfig.json` file looks like this, but the compiler still throws the same error.
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "moduleResolution": "node16",
    "rootDir": ".",
    "outDir": "build",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "alwaysStrict": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": false,
    "esModuleInterop": true,
    "allowJs": true
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "./src/**/*", "__tests__/**/*"
  ]
}
```

**Comment by fb55** [comment]
Thanks for sending this by — the import should be updated to conform with ESM. I will make sure this is covered in the next release.

**Comment by manuth** [comment]
As a workaround, I recommend you to add the following to your `tsconfig.json`s `compilerOptions`:
```json
{
    "compilerOptions": {
        "paths": {
            "cheerio": [
                "./node_modules/cheerio/lib/index.d.ts"
            ]
        }
    }
}
```

This will use `cheerio`s `cjs` types instead of the `esm` types.
The type declarations look exactly the same so it fits as a workaround replacement perfectly well.

**Comment by wickning1** [comment]
I got this error when I changed moduleResolution from 'node' to 'node16' in my tsconfig.json. I had to do this for the 'file-type' library, so between a rock and a hard place.

@manuth's workaround helped, thanks.

**Comment by andreash** [comment]
This still occurs with rc-12. I needed to go back to rc-10, to resolve this. Any clues?

**Comment by cdwmhcc** [comment]
Any update?

**Comment by cdwmhcc** [comment]
> As a workaround, I recommend you to add the following to your `tsconfig.json`s `compilerOptions`:
> 
> ```json
> {
>     "compilerOptions": {
>         "paths": {
>             "cheerio": [
>                 "./node_modules/cheerio/lib/index.d.ts"
>             ]
>         }
>     }
> }
> ```
> 
> This will use `cheerio`s `cjs` types instead of the `esm` types. The type declarations look exactly the same so it fits as a workaround replacement perfectly well.

When use [`tsx`](https://github.com/privatenumber/tsx) modules, error: `ReferenceError: _default is not defined`

**Comment by virtuallyunknown** [comment]
> As a workaround, I recommend you to add the following to your `tsconfig.json`s `compilerOptions`:
> 
> ```json
> {
>     "compilerOptions": {
>         "paths": {
>             "cheerio": [
>                 "./node_modules/cheerio/lib/index.d.ts"
>             ]
>         }
>     }
> }
> ```
> 
> This will use `cheerio`s `cjs` types instead of the `esm` types. The type declarations look exactly the same so it fits as a workaround replacement perfectly well.

This worked great until I migrated my monorepository to use pnpm. Now it got really nasty.

```json
{
    "compilerOptions": {
          "paths": {
            "cheerio": ["../../../node_modules/.pnpm/cheerio@1.0.0-rc.12/node_modules/cheerio/lib/index.d.ts"]
        }
    }
}
```

**Comment by yincrash** [comment]
It looks like the `-rc12` release is from before the fix.

**Comment by elalienx** [comment]
> It looks like the `-rc12` release is from before the fix.

I can confirm. `-rc12` does not contain the fix. You need to roll back to `rc-10` as @andreash mentioned.
