### ISSUE TITLE
Please release new rc including parse5 change

### ISSUE THREAD

**Issue by jbadan** [cheeriojs/cheerio#2741]
Hello, this commit https://github.com/cheeriojs/cheerio/commit/5d3fe3d89addb93b8222c38428eff01c270db9a4 resolves an issue in parse5 https://github.com/inikulin/parse5/issues/663. Could you release a rc version with this update included?

Thanks!

**Comment by fb55** [comment]
That version is part of the range in the `package.json`. No new release necessary, but you might have to delete your `node_modules` directory and lock file.
