### ISSUE TITLE
Cannot find module "cheerio"

### ISSUE THREAD

**Issue by GodsonAddy** [cheeriojs/cheerio#2765]
I installed cheerio to use in my node js backend. Everything works perfectly in my localhost but when I deploy to render., it now says `Error: Cannot find module "cheerio"`.

cheerio version:  1.0.0-rc.12,
node version: v16.15.1

**Comment by fb55** [comment]
Could you provide a reproducible example? 

Just as a heads-up: I suspect that this is a deployment platform issue, not a cheerio issue. Otherwise this would be more wise-spread.
