### ISSUE TITLE
<![CDATA getting output as <!--[CDATA in version 0.22.0 and earlier. Works fine with any RC candidates 

### ISSUE THREAD

**Issue by sagar441989** [cheeriojs/cheerio#2771]
I am loading a xml file and then print it as below. But the output xml file add extra '--' into `CDATA` tags which i want to avoid

```js
const $ = cheerio.load(data, { xml: {
    xml: true,
    withStartIndices: false,
  },});

$.xml() -->
`<![CDATA` getting output as `<!--[CDATA`
```

**Comment by fb55** [comment]
Even though the current releases are marked as RC releases, they are safe to use in production. There won't be any bug fix releases for 0.22, as that version is almost a decade old. Hope that makes sense!
