### ISSUE TITLE
[Question] Which one is the fastest `cheerio` vs `xmldom` vs `linkedom`?

### ISSUE THREAD

**Issue by tachibana-shin** [cheeriojs/cheerio#2778]
Sorry here is a question

I just parsed html on `WebWorker` I'm wondering whether which one is the fastest?

**Comment by fb55** [comment]
This will change based on your workload, so probably best to benchmark yourself. 

`linkedom` uses quite a few of the same underlying libraries, so some performance characteristics should be similar. And then there are accuracy differences: cheerio's default parser is spec-compliant, which other parsers are not. By switching to the non-spec-compliant parser, you can speed up parsing in cheerio as well.

Unfortunately there isn't a catch-all answer here. If speed is an absolute must, implementing multiple versions and benchmarking then seems like the best way forward.
