### ISSUE TITLE
load function is marked deprecated with message saying to use function returned by load

### ISSUE THREAD

**Issue by mike-lang** [cheeriojs/cheerio#2786]
Hi,

I believe https://github.com/cheeriojs/cheerio/commit/c370f4ed1dac20ed0a2fbe85c1da4d3d3ce383e7 marked the exported load function as deprecated in error.  It looks like the documentation was simply copied from the export of a `Cheerio` constructor over to the load function, including a deprecation message that made sense if someone was using the constructor, but is confusing when `load` is used. 

As an example the following code:
```
let $ = cheerio.load(pageHTML);
```
produces the following JSDoc documentation in code editors:
> The default cheerio instance
@deprecated - Use the function returned by `load` instead.

As best I can tell, this example uses the same method of loading html as is what is shown in the project documentation.

If this was not intentional, could we update the JSDoc to remove this deprecation warning and maybe update the function description?

If it is, could the project documentation we updated to indicated what is now the preferred method of loading and parsing HTML?

**Comment by fb55** [comment]
You are likely importing the default export:

```js
import cheerio from 'cheerio';
```

This will import a pre-loaded instance of cheerio, which can lead to subtle bugs and issues. Instead, try

```js
import * as cheerio from 'cheerio'
```

or

```js
import { load } from 'cheerio'
```

Hope this helps!

**Comment by fb55** [comment]
Re-opening this as the default export should probably be removed.

**Comment by sthota-fms** [comment]
Any progress on this one?

**Comment by fb55** [comment]
See my response above.

**Comment by sthota-fms** [comment]
I keep getting this error when installing this package in my react-native project. My react-native project is pure js and not TS.
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/121507008/220996465-2c1970b5-36da-40e3-8ff3-2865698148e6.png">

It looks like you're missing to export package.json
<img width="453" alt="image" src="https://user-images.githubusercontent.com/121507008/220996343-d85b9f6d-eb73-4a73-95b6-bca21aa8f45b.png">

**Comment by sthota-fms** [comment]
@fb55, Could we please include the above suggestion in the release? I need this package for my solution

**Comment by fb55** [comment]
The default export has been removed.
