### ISSUE TITLE
Documented methods don't always show optional parameters in the title

### ISSUE THREAD

**Issue by valscion** [cheeriojs/cheerio#280]
I found out that your README.md file has documented many methods that have optional parameters without the square brackets `[]` declaring those parameters as optional.

For example, see [.siblings()](https://github.com/MatthewMueller/cheerio#siblings-selector-) method. The parameter is clearly optional as seen through the examples but the title of the method doesn't directly show it.

**Comment by fb55** [comment]
Assuming TS types took care of this one.
