### ISSUE TITLE
Texts within consecutive li tags get concatenated when using $.text()

### ISSUE THREAD

**Issue by gaganprajapati** [cheeriojs/cheerio#2841]
Texts within consecutive li tags get concatenated without any space between which converts the last word in the li tag and the first word of the next li tag into a single word.
For example:
`<ul><li>It has an easy-to-use interface.</li><li>Flipboard is customizable by topic interest, making it great for niche blog promotion.</li></ul>`
Using $.text() for this html I get the following result:
It has an easy-to-use interfaceFlipboard is customizable by topic interest, making it great for niche blog promotion.

You can see how 'interface'(last word of first li tag) and 'Flipboard'(first word of the next li tag) is converted to a single text 'interfaceFlipboard'

**Comment by fb55** [comment]
Unfortunately there isn't much we can do here; the browser's `innerText` implementation [is based](https://html.spec.whatwg.org/#the-innertext-idl-attribute) entirely on CSS properties, which Cheerio doesn't have access to, as we don't render the document. Instead, Cheerio follows the spec for nodes that aren't rendered — this is technically correct, but not ideal.
