### ISSUE TITLE
Cheerio Error

### ISSUE THREAD

**Issue by RolH1992** [cheeriojs/cheerio#2856]
Hi all,

I tried to install Cheerio but I keep getting these errors.

npm ERR! code ERR_OSSL_UNSUPPORTED
npm ERR! error:1E08010C:DECODER routines::unsupported

My npm -v 8.19.3
My node -v  19.1.0

Thanks

**Comment by RolH1992** [comment]
No actually its with other installments, I have only noticed now.

**Comment by RolH1992** [comment]
@fb55 Thank you for pointing that out.

**Comment by fb55** [comment]
Sorry that I don't have a more concrete answer. Closing this as it is unrelated to Cheerio. Best of luck figuring this out!
