### ISSUE TITLE
Question: How to free memory used by cheerio?

### ISSUE THREAD

**Issue by nleush** [cheeriojs/cheerio#297]
I tried this example and it shows continuously growing memory usage.

```
var fs = require('fs');
var async = require('async');
var util = require('util');
var cheerio = require('cheerio');

var file = fs.readFileSync('./test.html').toString();

var count = 0;

async.whilst(
    function () {
        return true;
    },
    function (callback) {

        count++;

        var $ = cheerio.load(file);

        // Usage.
        console.log($('p').length);

        // Log mem.
        console.log(util.inspect(process.memoryUsage()));

        callback();
    },
    function (err) {
        console.log('finished');
    }
);
```

First output looks like:

```
{ rss: 54222848, heapTotal: 51012352, heapUsed: 24097600 }
...
{ rss: 990982144, heapTotal: 956552960, heapUsed: 952297264 }
```

**Comment by belvederef** [comment]
I am still experiencing this issue in a similar use case in 2021, both with cheerio@0.22.0 and cheerio@1.0.0-rc.6.

Memory usage increases every time the load function is called and never stops. @nleush should I create a new issue or best to reopen this one?

**Comment by belvederef** [comment]
I am still experiencing this issue in a similar use case in 2021, both with cheerio@0.22.0 and cheerio@1.0.0-rc.6.

Memory usage increases every time the load function is called and never stops.
