### ISSUE TITLE
Cheerio encodes HTML entities with decodeEntities: false

### ISSUE THREAD

**Issue by dprandzioch** [cheeriojs/cheerio#2974]
When using the latest-tagged version of cheerio on npm (1.0.0-rc12), decodeEntities apparently does not do what it was doing before.

Example:
```
const cheerio = require('cheerio');
const outHtml = cheerio.load('foo > bar', { decodeEntities: false });
console.log(outHtml.html());
```

With > 0.22.0 (1.0.0-rc*):
```
foo &gt; bar
```

While with 0.22.0:
```
foo > bar
```

In general, I'm not super sure about the name of this option because in 0.22.0, decodeEntities actually prevents encoding the characters to HTML entities in the first place while no "encodeEntities" option exists. Since we're relying on this behavior, I had to downgrade to 0.22.0 for now.

Other dependents of cheerio also have this problem now, e.g. https://github.com/jonkemp/inline-css in version 4.0.0 is using the rc-* version of cheerio, which causes the same problem there. As described in #1261 tagging an rc as latest is probably the problem here.

**Comment by fb55** [comment]
This is intentional: The default parser has changed in 1.0, and the new parser doesn't support these options. See this (not yet published) guide that explains how to restore htmlparser2 as the parser: https://github.com/cheeriojs/cheerio/blob/335e65d0cd93dc4f866019719575b22449068bd9/website/docs/advanced/configuring-cheerio.md

**Comment by dprandzioch** [comment]
@fb55 Thanks for your fast reply. So assuming I use 1.0.0-rc12 with that example:

```
    let outHtml = cheerio.load('foo > bar', {
      decodeEntities: false,
      xml: {
        xmlMode: false,
      },
    });

    console.log(outHtml.html());
```

I would expect to get back the original behavior, right?

However, that still returns

```
foo &gt; bar
```

Am I doing something wrong then?
