### ISSUE TITLE
Cannot read property 'createDocument' of undefined

### ISSUE THREAD

**Issue by a77uu** [cheeriojs/cheerio#3094]
When I give some document element to call with

```js
Cheerio.load('<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">')
```

But I got a error like: Cannot read property 'createDocument' of undefined

**Comment by fb55** [comment]
That sounds like you have incompatible package versions. `rm -rf package-lock.json node_modules; npm install` in your package directory should fix things.
