### ISSUE TITLE
cheerio docs

### ISSUE THREAD

**Issue by punkish** [cheeriojs/cheerio#3165]
the cheerio website "is still a work-in-progress, and covers Cheerio's next release that isn't available yet". In the meantime, where can I find the docs (with all the api methods, attribs, etc.) for the currently available release?

**Comment by fb55** [comment]
The website is the right place — the only missing bits are (1) the `extract` method, and (2) loading methods besides `.load`.

**Comment by loganknecht** [comment]
@fb55 - Do you know when the next release will be made? I am experiencing issues stating a function does not exist besides the documentation indicating that it should.

See #3233

**Comment by cfuendev** [comment]
@loganknecht - Wondering the same. I came from https://github.com/cheeriojs/cheerio/issues/3233 and it's a bit discouraging to see that the one function I was looking to use in a small web scraping + AI project is not available yet.

I got the same error after adding cheerio to my bun project through `bun add cheerio`. I gave the object returned by `cheerio.load()` the name `qs`:
```
TypeError: qs.extract is not a function.
```

**Comment by vibl** [comment]
I lost time converting all my selectors to the `extract` pattern, before reading here that it does not exist. Given that Cheerio is downloaded 8 milion times a week, I'm guessing that hundreds (if not thousands) of people have had the same experience in the past year. How hard would it be to remove it from the doc? Or put it in a Roadmap section?

As a replacement, I found https://github.com/wopehq/muninn, which I like a lot and seems to work where so far.

**Comment by punkish** [comment]
Yes, it is a bit weird that either the website or the package has not yet been updated after all this time. Note that your suggested `muninn` uses `cheerio` anyway

**Comment by vibl** [comment]
> Note that your suggested muninn uses cheerio anyway

Yes! I mentioned it because it replaces the missing `extract` method (with added features).
