### ISSUE TITLE
issue with custom tags defined in head

### ISSUE THREAD

**Issue by dkfdkdodkms** [cheeriojs/cheerio#3331]
It seems when a custom element is found cheerio prematurely exits the head tag, placing any following tags in the body tag (seen when outputting $.html()). I haven't tested the specific code below, but it should repro the issue:

```
<html>

   <head>
       <foo-bar></foo-bar>
       <title>test</title> <!--title gets put in body tag -->
  </head>

  <body>
     <div></div>
  </body>

</html>
```

**Comment by Hardekerlis** [comment]
I have the same problem

**Comment by fb55** [comment]
That is how the HTML spec likes parsing to work. Use `xmlMode` to work around this.
