### ISSUE TITLE
Multiple html tags are deleted

### ISSUE THREAD

**Issue by tyzion** [cheeriojs/cheerio#3360]
Hi there everybody!
Thanks for this fantastic library!
I use cheerio to change the html I receive from emails.
It has happened that a mail sent to me had 2 html tag in the body of the text.

I don't know if this is the right behaviour, but when I pass this text to cheerio, it deletes both html tags.
Example:

```

        const parsedDom = cheerio.load("<html><h1>hellooooo1</h1></html><html><h1>helloooooo2</h1></html>")
        const body = parsedDom('body')
        console.log('parsedDom.html(): ', parsedDom.html())
        // output: <html><head></head><body><h1>hellooooo1</h1><h1>helloooooo2</h1></body></html>
        console.log('body.html(): ', body.html())
        // output:  <h1>hellooooo1</h1><h1>helloooooo2</h1>
```

Is there a way to not let him do that?

Thanks in advance!

**Comment by SagarKapoorin** [comment]
So the issue is that when you parse HTML containing multiple <html> tags using Cheerio, it appears to remove one of the <html> tags, resulting in an unexpected structure in the parsed DOM?

**Comment by fb55** [comment]
The behavior is in line with the HTML spec; this is how HTML works. Enable XML mode to opt out of this.
