### ISSUE TITLE
Output of german umlauts is wrong

### ISSUE THREAD

**Issue by dat-leth** [cheeriojs/cheerio#338]
If I'm scraping a german webpage containing special characters like Ä, ä, Ö, ö, Ü, ü or ß, the output will be wrong (displaying � or other fancy stuff).
Seems like cheerio doesn't support UTF-8 or ISO-8859-1.

EDIT: It's not an issue by cheerio itself.

**Comment by Ra1d3n** [comment]
So, what is the issue then? I'm having it right now.

**Comment by Ra1d3n** [comment]
Well for reference if someone else finds this:
It seems that you need to set `decodeEntities: false` to get the correct behavior.
