### ISSUE TITLE
Method text() should skip <style> tag.

### ISSUE THREAD

**Issue by imysak** [cheeriojs/cheerio#339]
Hi, 
    I use cheerio for getting text content from html pages.
Most of all works great by one found one problem.

Page content of www.yahoo.com/  have tag <style> which contain css.

I assume text() should skip content of <style> tag.

**Comment by patelvishal1401** [comment]
Hi, i have same issue. 

i just use this $elements.find('style').remove();

And its remove all html code instead of style.

I wanted to remove style from my whole html code. 

Anyone help me on this. it will save my day.
