### ISSUE TITLE
Unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by andreiregpin** [cheeriojs/cheerio#3423]
Trying to scrape legacy apis with node 18 causes the following error:

` error TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: [Error: C8370000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:
  ] {
    library: 'SSL routines',
    reason: 'unsafe legacy renegotiation disabled',
    code: 'ERR_SSL_UNSAFE_LEGACY_RENEGOTIATION_DISABLED'
  }
}
`

There are some[ threads ](https://stackoverflow.com/questions/74324019/allow-legacy-renegotiation-for-nodejs)on stackoverflow that provide workarounds for fetching data with fetch and axios, but I'm using  CheerioWebBaseLoader from Langchain integration and so those don't apply to it.

Here is how to reproduce it.

Install node 18+

try scraping this website: https://scsanctions.un.org/resources/xml/en/consolidated.xml

Any help will be appreciated.

**Comment by fb55** [comment]
No published version of Cheerio does network calls, so this isn't a Cheerio issue. Have a look at undici instead!
