### ISSUE TITLE
Error with nextjs 14

### ISSUE THREAD

**Issue by mr-scrpt** [cheeriojs/cheerio#3517]
I have a function that uses cheerio, here is its code
```
import { load } from 'cheerio'

export const parseHTMLToString = (html: string) => {
  const $ = load(html)
  return $.text()
}
```
As soon as I import the file they are in into the project, I immediately get an error when building the project, even though I'm not even using the function. In dev mode the project works, but in build mode it crashes with an error

```
./node_modules/.pnpm/cheerio@1.0.0-rc.12/node_modules/cheerio/lib/esm/index.js + 69 modules
Cannot get final name for export 'encodeXML' of ./node_modules/.pnpm/entities@4.5.0/node_modules/entities/lib/esm/index.js
```
 **"cheerio": "1.0.0-rc.12",**
 **"next": "14.0.1",**

**Comment by fb55** [comment]
Odd error, likely an issue with the bundler. If you using Turbopack, this might be worth raising with the Turbopack team.

I don't see a way to work around this from Cheerio's side, closing.
