### ISSUE TITLE
.CSS() Documentation

### ISSUE THREAD

**Issue by becush** [cheeriojs/cheerio#357]
I'm really enjoying Cheerio, but have hit a wall with .CSS() method.  

var request = require('request'),
cheerio = require("cheerio");

var arbitraryPage = 'http://www.bonobos.com/slim-red-and-navy-tattersall-oxford-shirt-for-men';

request(arbitraryPage, function(err, resp, html){
  $ = cheerio.load(html);
  $('.price').css('color');    //UNDEFINED
});

Am I missing something?  Do I need to import the css like jsDom?

**Comment by fanxinjie** [comment]
Hello, why can't simple styles be obtained?

url:http://nipponcolors.com/#nadeshiko

![image](https://user-images.githubusercontent.com/23193063/42198067-8a6d5cee-7eb8-11e8-8896-7aa0a711ec2b.png)

this will return {},  why?
