### ISSUE TITLE
how to add defer to script tag

### ISSUE THREAD

**Issue by hasakilol** [cheeriojs/cheerio#3603]
It seems impossible to add defer to script tag. 

I have a `<script src="xxx" />`. Now I want to add `defer` to it.
I tried many ways and couldn't create `<script defer src="xxx" />`.

**Comment by yogeshkudikala** [comment]
Use `.attr` to add `defer="true"` to your script tab
`$('script').attr('defer', true);`

**Comment by fb55** [comment]
Thanks @yogeshkudikala!
