### ISSUE TITLE
:hidden and :visible selectors are not available

### ISSUE THREAD

**Issue by richorama** [cheeriojs/cheerio#362]
The `:hidden` and `:visible` selectors are not available.

http://api.jquery.com/hidden-selector/
http://api.jquery.com/visible-selector/

Test case:

``` js
var cheerio = require('cheerio');
var $ = cheerio.load('<h1 style="display:none">Test</h1>');
console.log($("h1:hidden").length);
```

Error:

```
SyntaxError: unmatched pseudo-class :hidden
```

**Comment by denis-aes** [comment]
Why not to implement this selector according to DOM information? For example display:none / display:block cases - can be processed easily.

This may be very useful for many users.

**Comment by fb55** [comment]
IMHO this would do more harm than good - a partial implementation would
have people expecting the selector to work properly, which it never will.

**Comment by shiyulong** [comment]
Hi @richorama , I meet the same problem with you, have you found the solution?

**Comment by richorama** [comment]
@shiyulong I'm afraid not. I just did some simple stuff like detect `display:none`.

**Comment by skozz** [comment]
`$('.button').css('display') == 'none'`

**Comment by ktrzeciaknubisa** [comment]
I needed to remove :hidden elements, and so I made this piece of code which checks `.css('display')` value:

```js
var cheerio = require('cheerio');
var $ = cheerio.load('<h1 style="display:none">Test Hidden</h1><h1>Test Visible</h1>');

$.root().children().filter(function(i, el) {
    var display = $(this).css('display');
    if (display === 'none')
        $(this).remove();
});

console.log($.html());
// <h1>Test Visible</h1>
```
