### ISSUE TITLE
.val() result differs from jQuery for radio buttons

### ISSUE THREAD

**Issue by mlilley** [cheeriojs/cheerio#370]
I wanted to flag a difference between cheerio and jQuery (tested 1.10.1) when calling .val() on radio buttons in a form.

When I have a reference to a specific radio button (of a set of radio buttons), cheerio's .val() unexpectedly returns the value for the set (the checked radio), whereas jQuery will return the value of the specific radio (it's value attribute).

Consider:

```
var $ = require('cheerio').load(
              '<form>'+
              '    <input type="radio" name="rad" value="1">'+
              '    <input type="radio" name="rad" value="2" checked>'+
              '    <input type="radio" name="rad" value="3">'+
              '</form>');
var radios = $('input'), radio;

for (var i = 0, n = radios.length; i < n; i++) {
    radio = $(radios[i]);      // <-- get just the i'th radio
    console.log(radio.val());
}
```

here I iterate over each radio button and call .val() on each.  This will (unexpectedly) output:

```
2
2
2
```

whereas doing the same thing with jquery (fiddle: http://jsfiddle.net/GZ27t/1/) will output:

```
1
2
3
```

**Comment by fb55** [comment]
Fixed in #544
