### ISSUE TITLE
Memory leaks / RAM consumption?

### ISSUE THREAD

**Issue by dandv** [cheeriojs/cheerio#373]
A [node-crawler](https://github.com/sylvinus/node-crawler/issues/54) user reports Cheerio consuming unnecessarily large amounts of RAM vs. [jsdom](https://github.com/tmpvar/jsdom). Is this still the case?

**Comment by ChieveiT** [comment]
@fb55 I think I can provide a case for this issue. I request this page [易车网](http://car.m.yiche.com/) and call cheerio.load on it. My CPU suddenly run into 100% and after a long while node exits with 137. Then I switch to jsdom and call new JSDOM, the code works fine.

I think there is still something different between cheerio and jsdom.

Versions used:
"cheerio": "0.22.0" or "1.0.0-rc2"
"jsdom": "12.2.0"
