### ISSUE TITLE
xhtml tags are not closed

### ISSUE THREAD

**Issue by bsctl** [cheeriojs/cheerio#378]
Hello,
it looks that cheerio does not close xhtml tags. For example,

```
$page('.fs').append('<div><img src="../images/' + filename[0] + '.jpg" class="singlePage"/></div>');
```

becomes:

```
<div>
       <img src="../images/img.jpg" class="singlePage">
</div>
```

getting a "tag mismatch error" trying to open the xhtml page in Safari.

Thanks,
Adriano

**Comment by solarkraft** [comment]
Maybe this was changed, but `$.root()` does not currently have an `xml` method. What did work for me is using `cheerio.load` using the option `xml: true`.
