### ISSUE TITLE
 error TS2724: '"/app/node_modules/cheerio/lib/esm/index"' has no exported member named 'Text'

### ISSUE THREAD

**Issue by ArtjomP** [cheeriojs/cheerio#3790]
Hello there!
I have the next in my .ts file:
```ts
import * as cheerio from 'cheerio';
...

 tdNodeElement.children?.forEach(tdItem =>
                {
                  const text = tdItem as cheerio.Text;
...
```

I get the next error on build:
`
error TS2724: '"/app/node_modules/cheerio/lib/esm/index"' has no exported member named 'Text'
`

Do you have any ideas how to fix it? 

Thank you in advance!

**Comment by fb55** [comment]
Please import the `Text` type from [`domhandler`](https://github.com/fb55/domhandler).
