### ISSUE TITLE
Chaining `replaceWith` method takes only the first one

### ISSUE THREAD

**Issue by MatteoGauthier** [cheeriojs/cheerio#3884]
Hello

When attempting to replace multiple elements in sequence using Cheerio, the second replacement operation seems to be ignored. The provided test case aims to replace occurrences of ﻿`<li>` tags and the text "Plum" string, but the second replacement with `<li class="juice">Juice</li>` does not take effect as expected. 

## Reproduction

In the `manipulation.spec.ts` file add this test case to the `replaceWith` describe

```ts
    it('(elem) : should replace 2 times', () => {
      const $plum = $('<li class="plum">Plum</li>');
      $('.orange').replaceWith($plum).replaceWith(
        '<li class="juice">Juice</li>'
      )
      
      expect($('.apple').next().hasClass('juice')).toBe(true);
      expect($('.apple').next().html()).toBe('Juice');
      expect($('.pear').prev().hasClass('juice')).toBe(true);
      expect($('.pear').prev().html()).toBe('Juice');
    });
```

**Comment by prokoma** [comment]
This is not a bug, `replaceWith` returns the original detached element, not the new one.

**Comment by fb55** [comment]
Thank you @prokoma!

@MatteoGauthier Curious what your use-case is for chaining these — replacing and immediately replacing again seems counter-intuitive?
