### ISSUE TITLE
Cheerio 1.0.0 is incompatible with enzyme 3.11.0.

### ISSUE THREAD

**Issue by miskatonicfilm** [cheeriojs/cheerio#3987]
Due to the massive changes between release candidate 12 and version 1.0.0, enzyme 3.11.0 no longer works. 

When running tests, the following error occurs: 

Cannot find module 'node:stream' from 'node_modules/parse5-parser-stream/dist/cjs/index.js'

    Require stack:

      node_modules/parse5-parser-stream/dist/cjs/index.js

      node_modules/cheerio/dist/commonjs/index.js

      node_modules/enzyme/build/Utils.js

      node_modules/enzyme/build/ReactWrapper.js

      node_modules/enzyme/build/index.js

      [src/setupTests.js](https://bitbucket.org/clearcaptions/dms-frontend/src/ec34279508e934b12f4d623fd2c0f332d0c787b1/src/setupTests.js)

    > 1 | import { configure } from 'enzyme';

        | ^

      2 | import Adapter from 'enzyme-adapter-react-16';

      3 |

      4 | configure({ adapter: new Adapter() });

**Comment by NeKosmico** [comment]
Encountered a different error; resolved by reverting to the previous version:

json
```
Copiar código
{
  "dependencies": {
    "cheerio": "1.0.0-rc.12"
  }
}
```

This is the only workaround for now until compatibility improves in dependent projects.

**Comment by fb55** [comment]
That error is related to your node version or bundler. Cheerio now requires Node 18, and bundlers have to make sure to pick up to "browser" condition (which web bundlers should do anyway).
