### ISSUE TITLE
rror cheerio@1.0.0: The engine "node" is incompatible with this module. Expected version ">=18.17". Got "16.18.1" error Found incompatible module.

### ISSUE THREAD

**Issue by kjanghel** [cheeriojs/cheerio#4003]
Updating the node version is not an option.

can we have a immediate solution for this? Our prod deployment is failing for the same.

**Comment by Sleepyy007** [comment]
The same problem, we use enzyme, which uses cheerio, we don't really want to update node either

**Comment by 4rgs** [comment]
we used,
"overrides": {
    "cheerio": "1.0.0-rc.12"
  }
  
 on our package.json to solve our product in the meanwhile

**Comment by Sleepyy007** [comment]
Its work for me:
},
  "resolutions": {
    "cheerio": "1.0.0-rc.12"
}

**Comment by kjanghel** [comment]
can u share a sample package json it doesn't work for us

**Comment by StevenTso** [comment]
after adding @Sleepyy007 suggestion, try deleting package-lock.json or yarn.lock and node_modules folder and try reinstalling (npm i or yarn install)

**Comment by wghule** [comment]
I have the same problem。I use cheerio 1.0.0-rc.10。It can supprt the node version I am using。 but cheerio 1.0.0 recently only support node 18。It causes automatic upgrade issues for existing projects。Please upgrade the major version if necessary！

**Comment by wardariaz70** [comment]
error cheerio@1.0.0: The engine "node" is incompatible with this module. Expected version ">=18.17". Got "16.18.1" 1.0.0 uses node 18; but my os centOS 7, only support upto 16

**Comment by xahmejaz-rakbank** [comment]
> Its work for me: }, "resolutions": { "cheerio": "1.0.0-rc.12" }

worked for me as well

**Comment by fb55** [comment]
Sorry for the inconvenience — not something that can be rolled back unfortunately.
