### ISSUE TITLE
Latest deployment(1.0.0) caused  SyntaxError: Unexpected token 'export';

### ISSUE THREAD

**Issue by ankushkamboj580** [cheeriojs/cheerio#4023]
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { contains, merge } from './static.js';

**Comment by Joanneyoung01** [comment]
Also having the same issue, I have downgraded my version aswell

**Comment by hani-10p** [comment]
+1

**Comment by pvev** [comment]
experiencing this still

**Comment by fb55** [comment]
Please upgrade your environments if you can, or hardcode an older version of Cheerio.
