### ISSUE TITLE
Get unescaped html

### ISSUE THREAD

**Issue by zivni** [cheeriojs/cheerio#4029]
I need to get the html with hyperlinks not escaped.

consider this example:
```typescript
const $ = cheerio.load(`<a href="https://www.google.com/maps/search/?api=1&query=NEW+YORK">NEW YORK</a>`, null, false);
console.log($.html()) 
```

What I get in the console is `<a href="https://www.google.com/maps/search/?api=1&amp;query=NEW+YORK">NEW YORK</a>` with `&amp;`. I need to get it with `&` like in the source. 

I think that there is   need for an option on the `html` function to not escape the result HTML

**Comment by nwalters512** [comment]
In case this helps, if you read the `href` attribute, you'll see that it's returned to you unescaped:

```js
console.log($('a').attr('href'));
// https://www.google.com/maps/search/?api=1&query=NEW+YORK
```

Cheerio's behavior is consistent with how browsers work. You can prove this to yourself by executing this in a browser:

```js
const el = document.createElement('div');
el.innerHTML = '<a href="https://www.google.com/maps/search/?api=1&query=NEW+YORK">NEW YORK</a>';
console.log(el.innerHTML);
// <a href="https://www.google.com/maps/search/?api=1&amp;query=NEW+YORK">NEW YORK</a>
```

**Comment by zivni** [comment]
Thank you for the explanation. 

The use case I have is that I have html files that I need to manipulate and save back.

So I think that it makes sense that there will be another method that will export the html without escaping

**Comment by nwalters512** [comment]
I suspect that's outside the scope of this library. You might consider using a third-party library like [`he`](https://github.com/mathiasbynens/he). Note that this will also decode any entities that exist in the starting HTML, which might not be what you want. That is, if you start with `<div>&lt;</div>`, you'll end up with `<div><</div>`. If it's possible for you to relax your requirements such that you can tolerate encoded entities in the output (which any browser, HTML parser, etc. would be perfectly happy with), that would probably work out best for you in the long run.

**Comment by zivni** [comment]
Thanks
