### ISSUE TITLE
first last eq selectors dont work

### ISSUE THREAD

**Issue by steve-heine** [cheeriojs/cheerio#408]
SyntaxError: unmatched pseudo-class :last

**Comment by OKNoah** [comment]
So is there an alternative?

**Comment by allain** [comment]
sometimes you can get away with :nth-child(1).

Or $("blah").each(function(index) {
  if (index === 0) {
    //this is the first
  } 
});

**Comment by CoDEmanX** [comment]
@allain: why not `$("blah").first()`? I assume there's always an overhead if `:first` can't be used.

**Comment by allain** [comment]
Good points.

**Comment by SystemDisc** [comment]
Just to help someone else out if they run into this.

A selector like:
```js
$('.page_nav:first() .single:last() b:last()').text();
```
Can be changed to this:
```js
$('.page_nav').first().find('.single').last().find('b').last().text();
```

**Comment by lktvlm** [comment]
First has a valid usecase with .not:
`$('.whatever').not(':first')`
is much more readable than
`$('.whatever').not(':nth-child(1)')`
and can not be replaced by first() function.

Given that one of cheerio's strengths is the ability to test the same code in browser using jQuery, this omittance is unfortunate..

**Comment by fb55** [comment]
@lktvlm These two are far from equivalent. `:first` checks whether it is the first element in the selection. You can archive the same effect as the first selector using

```js
$('.whatever').filter(i => i > 0)
```

`:nth-child` on the other hand checks whether the element is the first child of its parent element, which is an entirely different beast.

**Comment by SystemDisc** [comment]
You could also do:
```javascript
$('.whatever').slice(1);
```

**Comment by tleb** [comment]
And for a `:not(:last)`, this should work:

```js
$('.foo').slice(0, -1)
```

**Comment by mike442144** [comment]
Read all above, but I have one scenario that I have many configurations with selector string like 'ul li:first', and I wanna read from file and pass to cheerio, what can I do?

**Comment by SystemDisc** [comment]
@mike442144 I'm not sure what you're asking. Can you be more verbose and provide an example? It seems to me like you could do `$('ul li').first();`

**Comment by mike442144** [comment]
Hey, say I have a configuration.json file with content:

```json
{
    "selector1": "ul li:first",
    "selector2": "ul > li:nth-child(4)",
}
```

And in a index.js maybe like below:

```javascript
config cfg = require('configuration.json');
// here I want to apply the selector to the document directly and get what I want
$(cfg.selector1).text();
$(cfg.selector2).text();
```
In this way I can configure the selector in a json file rather than write in a javascript file, which I can only maintain the configuration file when the DOM changed. Do you have any idea?

**Comment by CoDEmanX** [comment]
How is that related to this issue?

Anyway, your approach seems alright.

```js
let cfg = require('./configuration.json');
$(cfg.selector1).text();
```

Note that there is a module cache, so if you need to re-read your configuration file, then doing `require(...)` won't cut it. You may want to read and parse the file instead:

```js
const fs = require('fs');
let cfg = JSON.parse(fs.readFileSync('./configuration.json', { encoding: 'utf8' }))
```

**Comment by mike442144** [comment]
@CoDEmanX I suggest you to reread the issue and all posts. I define selectors with `pseudo-class` in file, a file is just an example, what is important is predefined selector with `pseudo-class`, so it is certainly related to this issue isn't it?

**Comment by CoDEmanX** [comment]
I see, I did not actually look at the selectors

`:first` is not supported, so `ul li:first` is not a valid selector in cheerio and it doesn't look like it will be implemented. If you want to stick with cheeriojs and write such selectors in a file, then I guess you will have to write a selector parser and perform `$('ul li').first()` for instance. Or write selector functions and call them with $ as argument...

**Comment by SystemDisc** [comment]
@mike442144 instead of a JSON file with an mapping of selectors, you could have a JS file like so (where each value is *either* a selector *or* a function):

```javascript
module.exports = {
    "selector1": (context) => context ? context.("ul li").first() : $("ul li").first(),
    "selector2": "ul > li:nth-child(4)",
};
```

**Comment by mike442144** [comment]
@SystemDisc Actuall I don't understand your point, `selector1` makes sense, but why `selector2`?

**Comment by SystemDisc** [comment]
Merely to keep things consistent. You may like the first example better. I just grabbed the same examples you posted above.

**Comment by leodutra** [comment]
What about ":first-of-type"?
