### ISSUE TITLE
SyntaxError: The requested module 'cheerio' does not provide an export named 'default'

### ISSUE THREAD

**Issue by dimaslanjaka** [cheeriojs/cheerio#4103]
I'am running on NodeJS v20 with ESM to compile this module into electron builder. got this error:

```log
import cheerio from "cheerio"; // load is named export, so wrapping in a default import
       ^^^^^^^
SyntaxError: The requested module 'cheerio' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:229:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.17.0
```

- when i using load import `import { load } from 'cheerio'` when i run test using `jest` is working, no error. But, when compiled using electron builder got error message like

```log
TypeError: Cannot destructure property

it should be

import cheerio from 'cheerio';
const { load } = cheerio;
```

- when i using default import below

```js
import cheerio from 'cheerio';

// rest of codes
const $ = cheerio.load('string html');
```

Error when using jest or direct nodejs run (node filename.js), but no error message showing on compiled electron (but the html parsing not working at all). here screenshoot.

![image](https://github.com/user-attachments/assets/7da74895-35ac-4cdf-9544-72dcd9612e37)

how to fix this ?

**Comment by Muhammad-Owais-Warsi** [comment]
As per the docs, use `import * as cheerio from "cheerio"` instead of `import cheerio from "cheerio"`

**Comment by dimaslanjaka** [comment]
> As per the docs, use `import * as cheerio from "cheerio"` instead of `import cheerio from "cheerio"`

ah yeah forgot about to use wildcard import

![image](https://github.com/user-attachments/assets/653ee2b3-dd6d-4adf-b3d8-d183228b619d)
