### ISSUE TITLE
Examples using `.html()` show inaccurate return values

### ISSUE THREAD

**Issue by nex3** [cheeriojs/cheerio#4165]
According to [the documentation for `Cheerio<T>.html()`](https://cheerio.js.org/docs/api/classes/Cheerio#html), it returns the *content* of the element—that is, its `innerHTML` rather than its `outerHTML`. This matches the current behavior. However, many documentation examples are written as though it returns the `outerHTML`. For example, this is the code snippet from [`Cheerio<T>.addClass()`](https://cheerio.js.org/docs/api/classes/Cheerio#addclass):

```js
$('.pear').addClass('fruit').html();
//=> <li class="pear fruit">Pear</li>

$('.apple').addClass('fruit red').html();
//=> <li class="apple fruit red">Apple</li>
```

We can test this in the browser's dev inspector:

```js
const cheerio = await import("https://jspm.dev/cheerio");
const $ = cheerio.load('<ul><li class="pear">Pear</li><li class="apple">Apple</li></ul>');
console.log($('.pear').addClass('fruit').html());
console.log($('.apple').addClass('fruit red').html());
```

where it prints

```
Pear
Apple
```

rather than the documented output values.

**Comment by Lansa-18** [comment]
Hello, I am a Frontend Developer looking to increase my experience in open source. Can i work on this?

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by fb55** [comment]
Thanks for the report!
