### ISSUE TITLE
Cannot handle div elements nested within <a> tags

### ISSUE THREAD

**Issue by OneSir** [cheeriojs/cheerio#4186]
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/71351574-539a-48c5-b417-f748ef2c116b">

**cheerio code：** 
`function parseHtml(html: string): Element[] {
  const $ = cheerio.load(html);
  console.log($.html())
  function extractElement($el: cheerio.Cheerio): Element {
    const tag = $el.prop('tagName').toLowerCase();
    const attributes = $el.attr() || {};

    const children: Element[] = [];
    $el.children().each((_, child) => {
      children.push(extractElement($(child)));
    });

    return {
      tag,
      attributes,
      children: children.length > 0 ? children : undefined,
    };
  }
  const rootElement = $('body').children().first();
  return [extractElement(rootElement)];
}`

Want a tag child element that can be extracted hierarchically.

**Comment by OneSir** [comment]
return
[
  {
    "tag": "div",
    "attributes": {
      "class": "header__icons display-none-tablet"
    },
    "children": [
      {
        "tag": "a",
        "attributes": {
          "id": "HeaderBtnBox",
          "class": "Modern_wishlist_header header__btn seedmore_wishlist_header",
          "style": "display: inline-flex; justify-content: center; align-items: center; min-width: 40px;"
        }
      },
      {
        "tag": "a",
        "attributes": {
          "class": "indexstyle__LinkBox-sc-18jtyu9-1 eyYnPk header__btn  notranslate",
          "href": "/user/signIn?redirectUrl=/pages/wishlist_5e.buvk"
        }
      },
      {
        "tag": "div",
        "attributes": {
          "direction": "row",
          "class": "indexstyle__LinkBtn-sc-18jtyu9-0 jMUhyS index-module_link_btn_05f09c6",
          "style": "flex-direction: row; direction: ltr;"
        },
        "children": [
          {
            "tag": "a",
            "attributes": {
              "class": "indexstyle__LinkBox-sc-18jtyu9-1 eyYnPk header__btn  notranslate",
              "href": "/user/signIn?redirectUrl=/pages/wishlist_5e.buvk"
            }
          },
          {
            "tag": "div",
            "attributes": {
              "class": "index-module_link_btn_content_3d4aa20"
            },
            "children": [
              {
                "tag": "a",
                "attributes": {
                  "class": "indexstyle__LinkBox-sc-18jtyu9-1 eyYnPk header__btn  notranslate",
                  "href": "/user/signIn?redirectUrl=/pages/wishlist_5e.buvk"
                }
              },
              {
                "tag": "div",
                "attributes": {
                  "class": "index-module_Popconfirm_8b8fc27"
                },
                "children": [
                  {
                    "tag": "a",
                    "attributes": {
                      "class": "indexstyle__LinkBox-sc-18jtyu9-1 eyYnPk header__btn  notranslate",
                      "href": "/user/signIn?redirectUrl=/pages/wishlist_5e.buvk"
                    },
                    "children": [
                      {
                        "tag": "div",
                        "attributes": {
                          "class": "index-module_Arrow_06e31e6"
                        },
                        "children": [
                          {
                            "tag": "div",
                            "attributes": {
                              "class": "index-module_ArrowContent_3de6e9c"
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "tag": "div",
                    "attributes": {
                      "class": "index-module_loginContainer_44bd926"
                    },
                    "children": [
                      {
                        "tag": "a",
                        "attributes": {
                          "class": "indexstyle__LinkBox-sc-18jtyu9-1 eyYnPk header__btn  notranslate",
                          "href": "/user/signIn?redirectUrl=/pages/wishlist_5e.buvk"
                        },
                        "children": [
                          {
                            "tag": "div",
                            "attributes": {},
                            "children": [
                              {
                                "tag": "svg",
                                "attributes": {
                                  "width": "77",
                                  "height": "66",
                                  "viewBox": "0 0 77 66",
                                  "fill": "none",
                                  "xmlns": "http://www.w3.org/2000/svg"
                                },
                                "children": [
                                  {
                                    "tag": "path",
                                    "attributes": {
                                      "d": "M70.0109 6.90449L70.0114 6.90499C71.7532 8.61586 73.1335 10.6458 74.0747 12.8781C75.0159 15.1104 75.5 17.5021 75.5 19.9168C75.5 22.3316 75.0159 24.7233 74.0747 26.9556C73.1335 29.1879 71.7532 31.2178 70.0114 32.9287L70.0112 32.929L66.1065 36.7662L38.499 63.8969L10.8915 36.7662L6.98683 32.929C3.47055 29.4734 1.5 24.7923 1.5 19.9168C1.5 15.0414 3.47055 10.3603 6.98683 6.90474C10.504 3.44831 15.2798 1.50194 20.2649 1.50194C25.25 1.50194 30.0258 3.44831 33.543 6.90474L37.4476 10.742C38.0312 11.3155 38.9668 11.3155 39.5504 10.742L43.4551 6.90474L43.4553 6.90449C45.1963 5.19276 47.2649 3.83353 49.5434 2.90571C51.822 1.97788 54.2652 1.5 56.7331 1.5C59.2011 1.5 61.6443 1.97788 63.9229 2.90571C66.2014 3.83353 68.27 5.19276 70.0109 6.90449Z",
                                      "stroke": "black",
                                      "stroke-width": "3",
                                      "stroke-linecap": "round",
                                      "stroke-linejoin": "round"
                                    }
                                  }
                                ]
                              }
                            ]
                          },
                          {
                            "tag": "div",
                            "attributes": {
                              "class": "index-module_loginText_e702488"
                            }
                          }
                        ]
                      },
                      {
                        "tag": "div",
                        "attributes": {
                          "style": "width: 100%;"
                        },
                        "children": [
                          {
                            "tag": "a",
                            "attributes": {
                              "class": "indexstyle__LinkBox-sc-18jtyu9-1 eyYnPk header__btn  notranslate",
                              "href": "/user/signIn?redirectUrl=/pages/wishlist_5e.buvk"
                            }
                          },
                          {
                            "tag": "a",
                            "attributes": {
                              "class": "index-module_loginBtn_3c121c9",
                              "href": "/user/signIn",
                              "style": "background: rgb(0, 0, 0); color: rgb(205, 242, 77);"
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "tag": "span",
            "attributes": {
              "style": "position: relative; display: inline-flex;"
            },
            "children": [
              {
                "tag": "svg",
                "attributes": {
                  "xmlns": "http://www.w3.org/2000/svg",
                  "width": "20",
                  "height": "19",
                  "viewBox": "0 0 20 19",
                  "fill": "none"
                },
                "children": [
                  {
                    "tag": "path",
                    "attributes": {
                      "d": "M10.2822 2.96051C11.183 2.10511 12.3413 1.58301 13.7497 1.58301C16.7813 1.58301 19.1663 3.93703 19.1663 7.24976C19.1663 9.23684 18.1372 10.889 16.2363 12.6715C15.8272 13.0554 14.5768 14.1432 14.5205 14.1947C14.3434 14.3546 14.1526 14.5204 13.9484 14.6914C13.6835 14.913 13.4146 15.1303 13.1418 15.343C12.5584 15.7982 11.9355 16.2566 11.313 16.6959C11.0371 16.8907 10.7592 17.0828 10.4793 17.2723C10.3389 17.3661 10.1714 17.4165 9.99967 17.4165C9.82799 17.4165 9.6605 17.3661 9.52009 17.2723C9.24 17.083 8.96193 16.891 8.68592 16.6963C8.06504 16.2593 7.45542 15.8081 6.85759 15.343C6.58474 15.1303 6.31581 14.913 6.05092 14.6914C5.84676 14.5204 5.65592 14.3546 5.47884 14.1947C5.42259 14.1432 4.17217 13.055 3.76301 12.6715C1.86259 10.889 0.833008 9.23724 0.833008 7.24976C0.833008 3.93663 3.21801 1.58301 6.24967 1.58301C7.65801 1.58301 8.81634 2.10472 9.71717 2.96051C9.81842 3.0567 9.91259 3.15288 9.99967 3.24788C10.0872 3.15288 10.1809 3.0563 10.2822 2.96051Z",
                      "fill": "white"
                    }
                  },
                  {
                    "tag": "path",
                    "attributes": {
                      "d": "M10.2822 2.96051C11.183 2.10511 12.3413 1.58301 13.7497 1.58301C16.7813 1.58301 19.1663 3.93703 19.1663 7.24976C19.1663 9.23684 18.1372 10.889 16.2363 12.6715C15.8272 13.0554 14.5768 14.1432 14.5205 14.1947C14.3434 14.3546 14.1526 14.5204 13.9484 14.6914C13.6835 14.913 13.4146 15.1303 13.1418 15.343C12.5584 15.7982 11.9355 16.2566 11.313 16.6959C11.0371 16.8907 10.7592 17.0828 10.4793 17.2723C10.3389 17.3661 10.1714 17.4165 9.99967 17.4165C9.82799 17.4165 9.6605 17.3661 9.52009 17.2723C9.24 17.083 8.96193 16.891 8.68592 16.6963C8.06504 16.2593 7.45542 15.8081 6.85759 15.343C6.58474 15.1303 6.31581 14.913 6.05092 14.6914C5.84676 14.5204 5.65592 14.3546 5.47884 14.1947C5.42259 14.1432 4.17217 13.055 3.76301 12.6715C1.86259 10.889 0.833008 9.23724 0.833008 7.24976C0.833008 3.93663 3.21801 1.58301 6.24967 1.58301C7.65801 1.58301 8.81634 2.10472 9.71717 2.96051C9.81842 3.0567 9.91259 3.15288 9.99967 3.24788C10.0872 3.15288 10.1809 3.0563 10.2822 2.96051Z",
                      "fill": "currentColor"
                    }
                  }
                ]
              }
            ]
          },
          {
            "tag": "span",
            "attributes": {
              "class": "indexstyle__TitleText-sc-18jtyu9-2 cOZAzz body4"
            }
          }
        ]
      },
      {
        "tag": "div",
        "attributes": {
          "class": "user__container"
        },
        "children": [
          {
            "tag": "a",
            "attributes": {
              "class": "icon-button header__icon-button",
              "href": "/user/signIn"
            },
            "children": [
              {
                "tag": "svg",
                "attributes": {
                  "class": "icon icon-user",
                  "width": "28",
                  "height": "28",
                  "viewBox": "0 0 28 28",
                  "fill": "none",
                  "xmlns": "http://www.w3.org/2000/svg"
                },
                "children": [
                  {
                    "tag": "path",
                    "attributes": {
                      "fill-rule": "evenodd",
                      "clip-rule": "evenodd",
                      "d": "M14 13C16.2091 13 18 11.2091 18 9C18 6.79086 16.2091 5 14 5C11.7909 5 10 6.79086 10 9C10 11.2091 11.7909 13 14 13ZM9 14C6.79086 14 5 15.7909 5 18V22C5 22.5523 5.44772 23 6 23H22C22.5523 23 23 22.5523 23 22V18C23 15.7909 21.2091 14 19 14H9Z",
                      "fill": "currentColor"
                    }
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "tag": "a",
        "attributes": {
          "id": "cart-icon-bubble",
          "class": "icon-button header__icon-button ",
          "href": "/cart"
        },
        "children": [
          {
            "tag": "div",
            "attributes": {
              "id": "cart-icon-bubble-wrapper"
            },
            "children": [
              {
                "tag": "svg",
                "attributes": {
                  "class": "icon icon-cart",
                  "width": "28",
                  "height": "28",
                  "viewBox": "0 0 28 28",
                  "fill": "none",
                  "xmlns": "http://www.w3.org/2000/svg"
                },
                "children": [
                  {
                    "tag": "path",
                    "attributes": {
                      "d": "M6 12C6 11.4477 6.44772 11 7 11H21C21.5523 11 22 11.4477 22 12V22C22 22.5523 21.5523 23 21 23H7C6.44772 23 6 22.5523 6 22V12Z",
                      "fill": "currentColor"
                    }
                  },
                  {
                    "tag": "path",
                    "attributes": {
                      "d": "M18 10C18 11.0677 18.0001 13.5 18.0001 13.5H10.0001L10 10C10 7.79086 11.7909 6 14 6C16.2091 6 18 7.79086 18 10Z",
                      "stroke": "currentColor",
                      "stroke-width": "2"
                    }
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
]

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by fb55** [comment]
This is how HTML works. Try using htmlparser2 to parse (eg. using the options `{ xml: { xmlMode: false }}`) to escape some of the HTML parsing specifics.
