### ISSUE TITLE
Explain \\: escaping colon for xml namespace pseudo

### ISSUE THREAD

**Issue by dandv** [cheeriojs/cheerio#419]
While attempting to parse an RSS feed, I got the `SyntaxError: unmatched pseudo-class :origlink` error. Looking through [the issues](https://github.com/MatthewMueller/cheerio/search?q=pseudo&type=Issues), I only found references to jQuery pseudo-classes.

For XML parsing, it might help to mention escaping the `:` with a double backslash. On the other hand, that's a standard CSS selector feature, so maybe the text of this issue will be enough SEO to help others who run into the same error.

**Comment by toolness** [comment]
Me too! Hooray for SEO! :smile:

**Comment by kevinpeno** [comment]
In case anyone stumbles upon this with the intention to use `attr`, escaping is not necessary (nor possible) in that use case.

**Comment by Meekohi** [comment]
lol just ended up back here a year and a half later. It might be nice if this error message were slightly different when `xmlMode:true` to give a hint at the quick fix.
