### ISSUE TITLE
is it possible to select and get html comments?

### ISSUE THREAD

**Issue by lhwparis** [cheeriojs/cheerio#423]
i am searching for a node html parser which make it possible to get not only DOM nodes but html comments too in any way. is this possible`?

**Comment by MCTaylor17** [comment]
Does this not work:

```js
var $comments = $( "body" ).contents().filter(function() {
    return this.nodeType === 8;
});
```

I haven't tested with nodeType 8 (comments), but I've used it plenty with nodeType 3.

**Comment by MCTaylor17** [comment]
I can confirm that you can access the comments like so:

```js
var $comments = $("*").contents().filter(function () {
    return this.nodeType === 8;
});

$comments.each(function(){
    // read the existing comment
    console.log(this.data);

    // change it to something else
    this.data = "something else";
});
```

**Comment by samism** [comment]
> I can confirm that you can access the comments like so in older versions of Cheerio:
> 
> ```js
> var $comments = $("*").contents().filter(function () {
>     return this.nodeType === 8;
> });
> 
> $comments.each(function(){
>     // read the existing comment
>     console.log(this.data);
> 
>     // change it to something else
>     this.data = "something else";
> });
> ```

What versions?

**Comment by MCTaylor17** [comment]
> What versions?

I'm not sure.  What version is it not working in?

**Comment by harrynewsome** [comment]
> > I can confirm that you can access the comments like so in older versions of Cheerio:
> > ```js
> > var $comments = $("*").contents().filter(function () {
> >     return this.nodeType === 8;
> > });
> > 
> > $comments.each(function(){
> >     // read the existing comment
> >     console.log(this.data);
> > 
> >     // change it to something else
> >     this.data = "something else";
> > });
> > ```
> 
> What versions?

Seems to be working for me in `"cheerio": "^1.0.0-rc.2"`

**Comment by MCTaylor17** [comment]
> Seems to be working for me in "cheerio": "^1.0.0-rc.2"

Nice.

**Comment by Mizumaki** [comment]
I'm using `"cheerio": "^1.0.0-rc.3",`, and I find out this works.

```
  const $ = cheerio.load(htmlData, { decodeEntities: false });

  $('body').contents().map((i, el) => {
    if (el.type === 'comment') {
      console.log(el.data)  // You can get the contents of html comment
      console.log($(el).html())  // This is null
      console.log($(el).text())  // This is ' '
    }
  })
```

`CheerioElement` type has `.type` property, which is [defined as string](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cheerio/index.d.ts#L253), and it looks like the possible strings are 3, `'tag' | 'text' | 'comment'.`

And I tried 3 ways and find that the contents of comment is assigned in `el.data`.

**Comment by lionel-rowe** [comment]
Some experiments with TypeScript and `1.0.0-rc.12`. `getComments` seems to work pretty well at getting all comments recursively, in a manner similar to `$(selector)`.

```ts
import { load } from 'cheerio'
import type { AnyNode, Cheerio } from 'cheerio'

// util to get `Comment` type as cheerio doesn't export it
type Comment = ReturnType<typeof _commentOrThrow>
function _commentOrThrow(x: AnyNode) {
    if (x.type === 'comment') return x
    throw null
}

function* getComments($node: Cheerio<AnyNode>, maxDepth = Infinity, _currentDepth = 0): Generator<Comment, void> {
    if (_currentDepth > maxDepth) return

    for (const node of $node.contents()) {
        switch (node.type) {
            case 'comment':
                yield node
                break
            case 'root':
            case 'tag':
                yield* getComments($(node), maxDepth, _currentDepth + 1)
                break
            default:
                break
        }
    }
}

const xml = `<root>
    <child />
    <!-- foo -->
    <!-- bar -->
    <child>
        <!-- baz -->
        <grandchild>
            <!-- quux -->
        </grandchild>
    </child>
</root>`

const $ = load(xml, { xml: true })

eachComment: for (const comment of getComments($.root())) {
    const val = comment.data.trim()

    console.info({ val })

    switch (val) {
        case 'bar':
            comment.data = ` ${val.toUpperCase()} `
            break
        case 'baz':
            break eachComment
        default:
            comment.data = ` ${val}!!! `
    }
}

console.log(`=== Result ===\n${$.xml()}`)
```

Console output:

```plain
{ val: "foo" }
{ val: "bar" }
{ val: "baz" }
=== Result ===
<root>
    <child/>
    <!-- foo!!! -->
    <!-- BAR -->
    <child>
        <!-- baz -->
        <grandchild>
            <!-- quux -->
        </grandchild>
    </child>
</root>
```
