### ISSUE TITLE
cheerio reported an error when using app router mode in next.js

### ISSUE THREAD

**Issue by tianez** [cheeriojs/cheerio#4285]
cheerio reported an error when using app router mode in next.js
![1](https://github.com/user-attachments/assets/d3fb9347-0c29-4956-af35-af94dfcc84d0)

The code is as follows
`import * as cheerio from 'cheerio'

export async function GET(request: Request) {
    console.log(cheerio)
    return Response.json({ success: true, code: 200 })
}`

**Comment by fb55** [comment]
Looks like an issue with undici, which needs a current engine. Please try upgrading to a current NodeJS release.

**Comment by Brian-Newbury** [comment]
I've upgraded to the newest version of NodeJS and I'm still getting that error message.

**Comment by candycandycc** [comment]
i meet this error too，please tell me how to resolve this.
