### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by matthewmueller** [cheeriojs/cheerio#442]
Jotting down some quick thoughts of what I'd like to see to make 1.0 awesome:

Must haves:
- [x] Rename internal attributes to match their DOM keys (type => nodeType)
- [ ] Cleaner code, with JSDoc block syntax
- [ ] A smaller browser build for webworkers (that's compatible with all the major package managers)
- [ ] A more defined list of API methods that are "core jQuery" to be ridiculously well-tested and match the jQuery API exactly.
- [ ] An official way to stream with cheerio that doesn't add a lot of bloat / complexity. Maybe this is a completely separate repository. Maybe something along the lines of: 

``` js
var $ = cheerio.stream();
req.pipe($('.signup').addClass('blah'))
```
- [ ] More support for CSS3 selectors in CSSSelect
- [ ] Clearer options. Optimize for what we actually use, possibly removing some options.
- [ ] XML love. More tests, more support.
- [ ] More forgiving parser for crazy angular things.

Nice to haves:
- [ ] Remove lodash/underscore entirely
- [ ] A website! And a logo.

What are your thoughts? Anyone else have anything they'd like to see?

/cc @fb55 @davidchambers @jugglinmike

**Comment by ianstormtaylor** [comment]
Any word on `1.0`? Seems weird that this module is so widely depended on but it's still in the `0.x` range which makes managing it as a dependency harder 😢

**Comment by matthewmueller** [comment]
haha, i'm not sure these are going to get done without some new love at this point. as far as i can tell cheerio is quite stable though. 

you guys want to bump it?

**Comment by fb55** [comment]
IMHO #863 would be a good place to bump it, as people will have to actually check their code. Or should we release v2 at that point?

**Comment by andykais** [comment]
I see `1.0.0-rc.2` is the latest version now (congrats!). Has been streaming added? I see an old PR #637 which implements streaming, but other than that, no mention of it in the #1145 PR, and none in the docs

**Comment by UziTech** [comment]
Is this still the todo list before v1.0.0 is stable? I would like to help it get over the bump.
