### ISSUE TITLE
Iterating over an array of table rows

### ISSUE THREAD

**Issue by mixinmax** [cheeriojs/cheerio#456]
I'm trying to iterate over each row in a table. Currently, I have something like this:

```
var rows = $(".my_table").find("tr");
for (var i = 0; rows.length; i++) {
    var current = rows[i];
    var title = current.children("td a").text();
    var text = current.children("td:nth-child(2)").text();
    console.log(title + " " + text + "\n");
}
```

With a table that looks something like this:

```
<table>
    <tr>
        <td><a href="#">Title</a></td>
        <td>Some more text</td>
    </tr>
    <tr>
        ...
</table>
```

I haven't played around with the DOM in quite a while so I may be completely off with some things. Anyways, this approach doesn't seem to be working. I think the issue lies with using `Cheerio` with the `current` variable instead of just using it as a DOM object.

Any help would be appreciated.

**Comment by ergoli** [comment]
great  fb55, your answer help me!

**Comment by jaswinder97** [comment]
I would like to know how we can iterate over children of a row
