### ISSUE TITLE
cheerio.load() with decodeEntities: true does not parse encoded HTML

### ISSUE THREAD

**Issue by zanecodes** [cheeriojs/cheerio#467]
Reproduction (run directly in node from command line):

```
> var cheerio = require('cheerio');
> var p = cheerio.load('&lt;p&gt;Test&lt;/p&gt;', {decodeEntities: true});
> p('p').html();
```

expected:

```
'Test'
```

actual:

```
null
```

Is this a bug or a feature?
How should I decode such HTML prior to parsing?

**Comment by ajbodev** [comment]
Thanks fb55, this solution of using entities worked!
