### ISSUE TITLE
seg fault when using 0.16.0

### ISSUE THREAD

**Issue by quizzicol** [cheeriojs/cheerio#498]
I've written a simple parser to parse Oracle xls data files. I originally wrote it using 0.13.1 and it worked fine.  Just tried it with 0.16.0 on a Windows 7 64 bit machine using Node 0.10.28 and it seg faults.

Running from the terminal, seg fault code 11424 or 10492
Running from Webstorm, Process finished with exit code -1073741819 (0xC0000005)

Specific point where the code wasn't working

$ = cheerio.load(data);                            # worked fine
var dataTable = $('table').last();              # debugger would get to this line but then crash
$ = cheerio.load(dataTable);                   # counldn't get to this line.

**Comment by fb55** [comment]
Not enough info to reproduce, also probably already resolved.
