### ISSUE TITLE
Feature request: Implement $.wrap()

### ISSUE THREAD

**Issue by impinball** [cheeriojs/cheerio#541]
This is actually a rather useful method, and would probably be even better server-side. It would simplify a lot of things server-side. It has been part of jQuery since 1.0, with the callback equivalent since 1.4.

**Comment by htmljosh** [comment]
> 
> 
> A couple of my utility functions for cheerio - feel free to make them into proper methods ;-)
> 
> ```js
> function wrap(selector, wrapper) {
>     return $(selector).each(function() {
>         $(this).before(wrapper).prev().append(this);
>     });
> }
> 
> function unWrap(selector) {
>     $(selector).each(function() {
>         var $this = $(this);
>         $(this).after($this.contents()).remove();
>     });
> }
> 
> function wrapAll(selector, wrapper) {
>     $(selector).first().before(wrapper).prev().append(selector);
> }
> ```

Very helpful, thank you
