### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by Ictinus** [cheeriojs/cheerio#549]
When loading Cheerio in a web worker, I am receiving the error:
`Uncaught TypeError: Cannot read property 'prototype' of undefined`

I'm bundling worker_test.js (using Browserify); loading it with the help of [patch-worker.js](https://github.com/Rob--W/chrome-api/tree/master/patch-worker); and successfully receiving console.log messages from the onmessage function of worker_test.js.

If I then add `var cheerio = require('cheerio');` in worker_test.js without any other call, bundle again and test, I receive the same console.log messages and then the error listed above.

The error occurs within `function runInContext` of lodash:

``` javascript
    /** Used for native method references */
    var objectProto = Object.prototype;
```

... and that is where I'm at. This is my first attempt at web workers, and only my second use of Cheerio.

Is this a bug with Cheerio or an incompatibility with the combination I'm using?
Is there a better way to get Cheerio loaded in a web worker?

**Comment by fb55** [comment]
Assuming this has been resolved.
