### ISSUE TITLE
Add support for insertAfter/insertBefore

### ISSUE THREAD

**Issue by benjamincochran** [cheeriojs/cheerio#608]
As a user, I would like to have access to jquery-style [insertAfter](http://api.jquery.com/insertAfter) and [insertBefore](http://api.jquery.com/insertBefore) methods (the inversion of `after()` and `before()`).

Reasonable support should include target value types of both cheerio objects and selector strings, representing both single and multiple targets.

**Comment by cvrebert** [comment]
So, this can now be closed since the PR was merged?

**Comment by davidchambers** [comment]
Yes it can. Thanks.
