### ISSUE TITLE
Replace .text()

### ISSUE THREAD

**Issue by alitavector** [cheeriojs/cheerio#621]
It may sound strange to replace api ```.text()``` as ```.t```. I guess there a cleaner way to write less code and for my clarity sake. How do I use it?

``` $$.find("choice").text() ```
into
``` $$.f("choice").t ```

**Comment by davidchambers** [comment]
jQuery compatibility is important, so we won't change the name of this method.

**Comment by jugglinmike** [comment]
David's right, but [you can now do this yourself](https://github.com/cheeriojs/cheerio#plugins)! Here's how:

```js
$$.prototype.f = $$.prototype.find;

Object.defineProperty($$.prototype, 't', {
  get: function() {
    return this.text();
  }
});
```
