### ISSUE TITLE
Wiki: Criteria for "Cheerio in Production"

### ISSUE THREAD

**Issue by fb55** [cheeriojs/cheerio#625]
The last three entries of the "Cheerio in Production" page are an agency, a person, and a job portal and I'm still not sure if they aren't spam (or some SEO bs). Also, just listing names is pretty useless; IMHO the idea is to underline how "production ready" cheerio is, which doesn't work without actually describing how it's used.

It would be great if @kpdecker, @defunctzombie, @iparamonau, @stockholmux and others could just write a short, possibly vague description of what they are doing with cheerio.

**Comment by iparamonau** [comment]
@fb55 I put in more details about Iframely's use cases. Feel free to redact, should you expect different style, etc.

**Comment by stockholmux** [comment]
@fb55 Added a bit in about how we use it - we use Cheerio a lot, actually. Feel free to modify if it isn't the right tone or what not.

I'd be glad to add more details. We're working on a blog post about how and how often we end up finding solutions with Cheerio.

**Comment by defunctzombie** [comment]
I have also added a quick sentence about our Cheerio use and like @stockholmux I am happy to elaborate if it helps.

**Comment by fb55** [comment]
Thanks a lot guys, that's exactly what I was looking for :)

@iparamonau I moved your description of the module up to the product.

**Comment by fb55** [comment]
@stockholmux A link to the blog post should definitely be included, the wiki page should remain light though.

**Comment by kpdecker** [comment]
Added a note about our use.
