### ISSUE TITLE
Option decodeEntities: true turns stand-alone ' into encoddd apos - not proper encoding

### ISSUE THREAD

**Issue by windhandel** [cheeriojs/cheerio#627]
Leaving the default attribute of decodeEntities: true incorrectly converts stand-alone apostrophes to an encoding of &apos;.  However, this apos encoding is not standards compliant and is unsupported by certain compliant software.  It should instead be &#39; if it must be encoded.

**Comment by windhandel** [comment]
The workaround it to set decodeEntities: false, but I assume this turns off encoding completely, which probably isn't preferable in most cases.

**Comment by fb55** [comment]
Duplicate of https://github.com/cheeriojs/dom-serializer/issues/1.
