### ISSUE TITLE
$.text() can not get entire text

### ISSUE THREAD

**Issue by TangMonk** [cheeriojs/cheerio#635]
``` coffeescript
c = require 'cheerio'

$ = c.load '<p><span>sssss</span></p>'

$.text()  -----> ''

```

**Comment by TangMonk** [comment]
and your home page demo not work too:

```coffeescript
var cheerio = require('cheerio'),
    $ = cheerio.load('<h2 class = "title">Hello world</h2>');

$('h2.title').text('Hello there!');    -----> not work
```

**Comment by speedneeder** [comment]
you should put it into console.log()

**Comment by TangMonk** [comment]
@speedneeder sure, I just Ignore it, You put my code to your computer to test. :D

**Comment by JamesBoon** [comment]
@TangMonk try this:
```javascript
var cheerio = require('cheerio'),
    $ = cheerio.load('<p><span>sssss</span></p>');

console.log($('p').text());
```

**Comment by fb55** [comment]
I'm not sure this behavior is the best we can do, it's also not in line with `.html` and `.xml`. Is there any reasons not to change it?

**Comment by Nomeasmo** [comment]
Or you can use the following to get all.
```
$.root().text()
```

**Comment by evandrix** [comment]
for `$.root().text()`, i get the error msg `TypeError: $.root is not a function`

how about `$("*").text()` instead?

**Comment by fb55** [comment]
Looks like the original example is now working as intended:

```js
const $ = cheerio.load('<p><span>sssss</span></p>');

console.log($.text()); //⇒ "sssss"
```
