### ISSUE TITLE
How do you get the doctype from cheerio?

### ISSUE THREAD

**Issue by greim** [cheeriojs/cheerio#640]
I looked at the docs but don't see any obvious way to do this.

**Comment by hollowdoor** [comment]
I was trying to figure out the same thing. When the source of the document is unknown getting the doctype can be beneficial.

I see there was some fix in hoxy, but for cheerio to do this would be very nice. The lack of this behavior is not preventing me from using cheerio as everything else it does is really great. I was just surprised at how hard it is to get the doctype.

**Comment by hollowdoor** [comment]
Never mind. I now see that this is a limit with htmlparser2. I'll be patiently waiting for [high5](https://github.com/fb55/high5) to approach stable.

**Comment by karankaw** [comment]
Any Update on this Thread ?

**Comment by jugglinmike** [comment]
How about `$.root().html()`? For example:

```js
'use strict';

var cheerio = require('../cheerio');
var $ = cheerio.load('<!DOCTYPE html><html><head></head><body>Hi there</body></html>');

console.log(cheerio.version);
console.log($.root().html());
```

Output for the latest release (0.22.0):

    0.22.0
    <!DOCTYPE html><html><head></head><body>Hi there</body></html>

and on the release candidate for version 1.0:

    1.0.0-rc.2
    <!DOCTYPE html><html><head></head><body>Hi there</body></html>

Would any of you folks care to confirm?

**Comment by fb55** [comment]
Assuming this response does the job.
