### ISSUE TITLE
Implementation of appendTo and prependTo

### ISSUE THREAD

**Issue by YetiCGN** [cheeriojs/cheerio#641]
While cheerio features some methods of DOM manipulation compatible with the jQuery API, it is missing [appendTo()](http://api.jquery.com/appendto/) and [prependTo()](http://api.jquery.com/prependto/), which are basically just flipped versions of append() and prepend().

I'd like to see this in cheerio, if it's not too much of a problem since I'm trying to test code which would need much refactoring to work without those methods.

**Comment by fb55** [comment]
Pull requests welcome :)

**Comment by tommedema** [comment]
+1 This would allow me to write

    $parent = $('<' + fragment.tag + '></' + fragment.tag + '>').attr(fragment.attribs) .appendTo($parent);

Instead of

       $newParent = $('<' + fragment.tag + '></' + fragment.tag + '>').attr(fragment.attribs);
        $parent.append($newParent);
        $parent = $newParent;

**Comment by digihaven** [comment]
@jugglinmike is the pull request good?

**Comment by fb55** [comment]
Fixed with #797
