### ISSUE TITLE
How to predict if $(':contains("whatever")') will be slow?

### ISSUE THREAD

**Issue by farzher** [cheeriojs/cheerio#648]
`$(':contains("whatever")')` is super slow if run on heavily embedded html.

Running it on the content of this website for example locks up my cpu for minutes http://paulkangas.tripod.com/

That's fine, BUT, is there anyway I can detect if it's going to be slow? I'm running through unsafe html. I'd rather just be able to trash those requests instead of trying to process them.

**Comment by jugglinmike** [comment]
It's no wonder that's taking a long time--that is a lot of DOM you're throwing at Cheerio! There are plenty of heuristics you could use to avoid checking huge structures like this.

The simplest is checking the `length` property of the string containing the markup. This isn't foolproof, though--the amount of text does not directly correlate to the number of nodes.

A slower but more accurate test would be to parse the document with Cheerio, then count the nodes--`$('*').length`. This is a better predictor of `:contains` search time, but it comes at the cost of parsing the document first.

Finally, you could try using a RegExp to see if your search term occurs in the string. This is obviously not the same thing as `:contains`, but it's another litmus test.

The strongest solution probably involves multiple approaches with different thresholds.

**Comment by farzher** [comment]
Yeah, I don't blame it for being slow. That dom is a mess. It even freezes chrome dev tools.

Length doesn't work for me because there's bigger sites where cheerio is still quick. `$('*').length` is interesting. Although I think the issue has to do with too many nested elements instead of just too many elements. That might work, I'll try it.

I need to know the element and its parents, so I can't just use regex.

**Comment by fb55** [comment]
When evaluating `:contains`, every element is stringified and checked, which is pretty costly. Just adding another selector in front of it will speed things up considerably.

If the entire text is part of a single text node, you can also pass a function to `$('*').filter`, which looks for that text node. Not doing string concatination (and therefore avoiding memory allocation) should be a serious improvement.

**Comment by farzher** [comment]
`$('*').length` doesn't really work. http://www.huffingtonpost.com/ has a load of elements but `:contains` is quick enough.

`$('*').filter` is a lot faster, but still too slow for http://paulkangas.tripod.com/

Is there a way to see how nested elements are? I think that's what makes it slow. If elements are nested 100 times, I want to ignore that.
