### ISSUE TITLE
Escaping css syntax in IDs ("." , ":")

### ISSUE THREAD

**Issue by melbourne2991** [cheeriojs/cheerio#652]
Apparently in jQuery you can do this with double backslashes eg:

$('#id\\\\.with\\\\.dots')

This doesn't appear to work either:

$('[id="id.with.dots"]')

Doesn't appear to work in Cheerio.

**Comment by fb55** [comment]
```js
$=require("cheerio").load("<div id='foo.bar.baz'>")
$("#foo\\.bar\\.baz").length //=> 1
```

What version of cheerio are you using?

**Comment by smac89** [comment]
Is there a builtin functionality for this? In the dom, we can do [`CSS.escape`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape_static)
