### ISSUE TITLE
Cannot load a html code

### ISSUE THREAD

**Issue by rafaelcremasco** [cheeriojs/cheerio#659]
I have searched on the Web but could not find something related to my problem.

When I use the following code in the browser:

```js
$('#tabDados tbody tr:nth-child(2) td:nth-child(2)').text()
```

The result is "8,9 %"

But when I use the same code in cheerio I cannot see the result.
I tried this way:
```js
var d = $('#tabDados tbody tr:nth-child(2) td:nth-child(2)').text();
console.log('Title ' + d);
```

Also tried this way:
```js
$('#tabDados tbody tr:nth-child(2) td:nth-child(2)').filter(function(){
        var d = $(this);
        d = d.text();
        console.log('Title ' + d)
})
```

As I test, this statement works fine for the same html page:
```js
$('#lblData').filter(function(){
        var date = $(this);
        date = date.text();
        console.log('Title ' + date)
})
```

Any sugestion why `$('#tabDados tbody tr:nth-child(2) td:nth-child(2)').text()` does not work?

Thanks

**Comment by fb55** [comment]
My guess is that `tbody` isn't present in the original document & the parser doesn't add it. Using `table` should fix your problem.

As a side-note: You can use backticks (<code>\`</code>) to highlight code on GitHub. I edited your issue and added them, click on edit to have a look at the changes.

**Comment by rafaelcremasco** [comment]
Thanks for your reply.
In the browser console I use the code with "tbody", but after copying/pasting the html code does not have the tbody tag, causing the error. I have just noticed that.

Thank you for the support,
Rafael
