### ISSUE TITLE
outdated lodash - improving performance

### ISSUE THREAD

**Issue by igorlino** [cheeriojs/cheerio#665]
There is a newer version of lodash (3.3.1) which  improved performance 20-40% overall  by better utilizing the JIT in JavaScript engines, using internal helper functions that avoid optimization disqualifications & increase the likelihood of function inlining.

lodash 3.0.0 is 40%  (1.40x) faster than lodash 2.4.1.

In v3 also introduced were lazily evaluated chaining for massive performance wins in certain scenarios.

Any chance to update to the latest release?

**Comment by fb55** [comment]
Already done in `master` :)

**Comment by igorlino** [comment]
great :)

**Comment by igorlino** [comment]
mmm, not to spoil the fun, the latest lodash version is 3.3.1.
in the master seems to be one lower:  "lodash": "^3.2.0"
