### ISSUE TITLE
SVG output non-renderable

### ISSUE THREAD

**Issue by Nedlinin** [cheeriojs/cheerio#666]
I've got an SVG created with Illustrator that I was hoping to make some changes to programatically with cheerio.  However, I've found that it seems to mangle the SVG a bit causing it to be unrenderable.

Using cheerio to load the file and make zero edits and then spit it back out (all options are default).

Because I appear to be awful at Markdown and it would make this ticket massive, the SVG is on pastebin: http://pastebin.com/S5P7KmHT

The output of cheerio can be found here: http://pastebin.com/zX6FMpwG

Opening the first one up in Chrome or IE works fine.  Opening the second one up gives the following error:

    This page contains the following errors:
    error on line 156 at column 6: Opening and ending tag mismatch: path line 0 and g

Any help in figuring out what is causing this would be greatly appreciated!

**Comment by Nedlinin** [comment]
In the interest of full disclosure, I am using the gulp-cheerio plugin and running this with gulp.  My gulp file for this task is as follows:



    /**
     * Testing Cheerio for SVG Manipulation
     */
    gulp.task("fixIllustratorSVGs", function() {
	var cheerio = require("gulp-cheerio");
	var imagemin = require("gulp-imagemin");

	return gulp
		.src(["tuttle_draft.svg"])
		.pipe(gulp.dest("dist/test1"))
		.pipe(cheerio(function($, file, done) {
			done();
		}))
		.pipe(gulp.dest("dist/test2"));
    });

**Comment by fb55** [comment]
You might want to pass `xmlMode: true`, as SVG is an XML document (the default mode is HTML).
