### ISSUE TITLE
Using jQuery's "Attribute contains word" selector

### ISSUE THREAD

**Issue by jascination** [cheeriojs/cheerio#675]
I'm trying to find all links on a page that contain the word "twitter" in their href. This is how I do it in jQuery:

      var twitter = $("a[href*=twitter]").attr('href');

In jQuery this works just fine. When I try to do the same in Cheerio I get undefined.

As far as I now Cheerio is meant to use all the same selectors at jQuery so I'm a little at odds with this one.

Open to any other suggestions on how I can find URLs on a page that contain the word "twitter" using Cheerio if this method won't work.

**Comment by fb55** [comment]
This should definitely work. My first guess would be that you're dealing with a site with dynamic content, or the links aren't lowercase (cheerio doesn't resolve or lowercase links). If the latter is the case, you can use `[href*=twitter i]` for a case-insensitive match.

**Comment by jascination** [comment]
This was a stupid error on my part - I didn't load the scraped HTML content into Cheerio properly! Works fine.
