### ISSUE TITLE
Document get() (and document toArray()'s deprecation)

### ISSUE THREAD

**Issue by astorije** [cheeriojs/cheerio#684]
I was naively expecting [map(callback)](https://github.com/cheeriojs/cheerio#map-functionindex-element-) to return an `Array` when it actually returns a Cheerio object... My fault to not fully read the doc!

However, doing `something.map(callback).toArray()` works although [`toArray`](https://github.com/cheeriojs/cheerio/blob/ccd9369153e9c580782ae422eff59d6caed16f1d/lib/cheerio.js#L149) is not specified in the [API](https://github.com/cheeriojs/cheerio#api).

Would that be worth having a description of converting a Cheerio objecto to an `Array` there?

**Comment by fb55** [comment]
There is a `@deprecated` note above the definition, the recommended way to do this is `get()`. I agree though that this is a pretty common case and the documentation of `get` could definitely be improved to highlight this behavior.

**Comment by astorije** [comment]
Right, I missed the `@deprecated`, thanks!
Indeed, I'd better use `get()`. I'm guessing it's [this one](https://github.com/cheeriojs/cheerio/blob/f71387ed334dc3eff66a11923f43b1129112b84d/lib/api/traversing.js#L357), right?
Then in that case, I am re-naming this issue :-)

**Comment by jugglinmike** [comment]
Actually, `$.fn.toArray` is defined by jQuery and is not deprecated: https://api.jquery.com/toArray/ This is a strange observation coming from [the person who introduced that deprecation notice](https://github.com/cheeriojs/cheerio/commit/f0dc4d2cbb20d70d15d29bcf91bee718c92eda35). Not sure what I was thinking there. Anyway, I'm proposing the notice's removal in gh-732.
