### ISSUE TITLE
how can i use javascript value after request ?? 

### ISSUE THREAD

**Issue by YooJaSung** [cheeriojs/cheerio#686]
after request, some site response javascript value 

like this,, 

```js
var s0={};var s1={};var s2={};var s3={};var s4={};var s5={};var s6={};var s7={};var s8={};var s9={};var s10={};var s11={};var s12={};var s13={};var s14={};var s15={};var s16={};var s17={};var s18={};var s19={};var s20={};var s21={};var s22={};var s23={};var s24={};var s25={};var s26={};var s27={};var s28={};var s29={};var s30={};var s31={};var s32={};var s33={};var s34={};var s35={};var s36={};var s37={};var s38={};var s39={};var s40={};var s41={};var s42={};var s43={};s0['LINK_ID']="AS3020006600";s0['LINK_ORDR']=2639;s0['LINK_SEQ']=1;s0['COORD_X']="235718.7,235695.6,235531.8,235528.2";s0['COORD_Y']="324912.2,324903.5,324630.1,324589.9";
s1['LINK_ID']="AW3020006410";s1['LINK_ORDR']=2637;s1['LINK_SEQ']=2;s1['COORD_X']="235528.2,235509.9,235245.8,235214.6";s1['COORD_Y']="324589.9,324609.8,324726.2,324725.5";
s2['LINK_ID']="AW3020008010";s2['LINK_ORDR']=2704;s2['LINK_SEQ']=3;s2['COORD_X']="235214.6,235194.3,234743.8,234723.5";s2['COORD_Y']="324725.5,324750.4,324927.6,324923.5"; 
```

not html tags ,, 

so ,, how can i use script value ?? 

any idea load script value ?

**Comment by fb55** [comment]
Cheerio doesn't evaluate Javascript. You might want to have a look at jsdom.

**Comment by spicecoder** [comment]
This looks like standard query string i.e a series of name= value  where
the value side is standard js objects, in short you need to have a pre
knowledge about the name of each parameter in the query string and parse it
to extract relevant key it will be much easier if you can manage to agree
on a json format of the data sent...



Pronab Pal

 Compute the World With Words,Lets Mend It Now.

Join The Community
https://plus.google.com/u/0/communities/111254712011749369781
