### ISSUE TITLE
Cheerio doesn't close polygon SVG tag when render with $.html()

### ISSUE THREAD

**Issue by kaemu** [cheeriojs/cheerio#691]
Release #673 fixes most of the tags (path, line, polyline…) excepted \<polygon\> which is not closed, and breaks the svg.

**Comment by fb55** [comment]
Are you using `0.19.0`? There is no more special handling for `polygon` and this should definitely be fixed.

**Comment by kaemu** [comment]
Ok. Fixed. The problem was elsewhere.
