### ISSUE TITLE
<!--> eats dom until next comment

### ISSUE THREAD

**Issue by Cauldrath** [cheeriojs/cheerio#692]
Found some terrible html I couldn't parse and discovered this was what was making large sections of the page inaccessible.  Chrome interprets <!--> as being an empty comment, so the page in question had no display issues.

Test:
```
var cheerio = require('cheerio');
var $       = cheerio.load("<html><body><div><!--></div><div class='test'>1st test text</div><!-- This is another comment --><div class='test'>2nd test text</div></body></html>");
console.log($('.test').text());
$           = cheerio.load("<html><body><div>     </div><div class='test'>1st test text</div><!-- This is another comment --><div class='test'>2nd test text</div></body></html>");
console.log($('.test').text());
```

Result:
```
2nd test text
1st test text2nd test text
```
Expected:
```
1st test text2nd test text
1st test text2nd test text
```

**Comment by Cauldrath** [comment]
Looking at the specification more closely, Cheerio would probably be considered to have the correct behavior here, even if it doesn't match what browsers generally do.  Perhaps some sort of compatibility flag would be in order?

**Comment by fb55** [comment]
No, that's the expected behavior in HTML5 (though it's considered a parse error). It's already [implemented](https://github.com/fb55/high5/blob/a836d9bbcee62e3bbabc822e36fcba26717692e1/index.js#L787) in high5, the next iteration of htmlparser2, though I don't know when it's going to be ready.
