### ISSUE TITLE
SyntaxError: unmatched pseudo-class :foo

### ISSUE THREAD

**Issue by redonkulus** [cheeriojs/cheerio#697]
@MatthewMueller 

Trying to use cheerio to match against a custom HTML node receives that error.

Here is a simple test to try it out:

```js
var cheerio = require('cheerio');
var markup = '<html><body><esi:foo attr="test"></esi:foo></body></html>';

var $ = cheerio.load(markup);
$('esi:foo').text();
```

**Comment by redonkulus** [comment]
The use case is basically for running unit tests on rendered HTML that will be parsed by apache traffic server (ats) and execute these `esi` tags.

**Comment by MatthewMueller** [comment]
@fb55 does the html parser support `<esi:foo>`? 

In the meantime, @redonkulus you may want to try:

```js
var $ = cheerio.load(markup, { xmlMode: true });
```

**Comment by redonkulus** [comment]
@MatthewMueller same issue with xmlMode flag passed in.

**Comment by fb55** [comment]
Try escaping the colon with a backslash (which needs to be escaped itself
with an additional backslash inside JS strings). Otherwise, it is parsed as
a pseudo selector.

**Comment by redonkulus** [comment]
@fb55 double backslash fixed it. I originally tried one but not two, smh.

**Comment by redonkulus** [comment]
Thanks!

**Comment by MatthewMueller** [comment]
> Try escaping the colon with a backslash (which needs to be escaped itself
with an additional backslash inside JS strings). Otherwise, it is parsed as
a pseudo selector.

Do pseudo selectors apply to HTML? Or is this just for `style="div:hover { color: blue }"`?

**Comment by fb55** [comment]
`<div:hover>` will produce an `HTMLUnknownElement` named `DIV:HOVER` If you'd like to query for it in an CSS selector, you'll need to escape the colon (`div\:hover`). Otherwise, you'll match elements named `DIV` in their hover state. Same applies to classes (eg. `[foo\.bar]`).

Because JS uses backslashes for escaping inside itself, this weird double escape is required.

**Comment by gurleensethi** [comment]
Double black slash `\\`  before the `:` fixed it! : 
`\\:`

**Comment by mdehghani65** [comment]
in my case I just omitted the coloned classes of the selector path and the target elements were still unique enough for cheerio to find them
