### ISSUE TITLE
Best Practice for including Cheerio "snippets"

### ISSUE THREAD

**Issue by MCTaylor17** [cheeriojs/cheerio#698]
I'm trying to decide how to break-up my Cheerio scripts into more modular pieces and I'm wondering if there are any recommendations for doing this.  For example, if I have the following operation:

```
$("p").each(function(){
    // do something
]);
```

and I want to call that from an index.js file, how would you recommend doing this?

Do I have to require Cheerio in every snippet file?
Is it possible to make use of `$(this)`?

**Comment by fb55** [comment]
One possibility would be to pass the cheerio instance around. Your example could be contained in a file like this:

```js
module.exports = function($){
  $("p").each(function(){
    // do something
  ]);
};
```

**Comment by jugglinmike** [comment]
I'd recommend the same

**Comment by MCTaylor17** [comment]
@fb55 that makes sense.  Much simpler than I imagined.

Would you return the cheerio instance? As in:
```
module.exports = function($){
  $("p").each(function(){
    // do something
  });
  return $;
};
```
Then in the index:
```
var cheerio = require("cheerio");
var doSomething = require("do-something.js");
var doSomethingElse = require("do-something-else.js");

var $ = cheerio.load(html);

$ = doSomething($);
$ = doSomethingElse($);
```
Is that what you're thinking, or are you saying it's possible to just run `doSomething($)` any changes to the cheerio instance will persist?
