### ISSUE TITLE
Is cheerio still 8x faster than jsdom?

### ISSUE THREAD

**Issue by DavidBruant** [cheeriojs/cheerio#700]
This part of the readme has been written 3,5 years ago.

https://github.com/cheeriojs/cheerio/commit/ba80a89428a44f31759e5fe009be731556c4a3b9

Is it still the case (especially regarding the 4.x serie of jsdom)?

**Comment by fb55** [comment]
jsdom 4.x switched the HTML parser to a slower & more accurate one and now uses io.js' `vm` module instead of contextify, which isn't a speed improvement over cheerio (since cheerio doesn't evaluate JS at all). The actual comparison depends on the workload, cheerio should definitely be faster in pretty much all cases, though.

**Comment by domenic** [comment]
I'd like this to be reopened and reinvestigated. jsdom doesn't use contextify or vm anymore for the simple types of workloads that cheerio supports. It is also notably faster on selector-based traversal. We'd like to get the benchmark from which the "8x faster" number comes from open-sourced so that jsdom can work on improving itself. If that's not possible, toning down the language to "sometimes faster than jsdom (no benchmarks though)" or similar would be more sensible ;).

**Comment by fb55** [comment]
The claim should definitely be substantialized. I assume the number originates from @matthewmueller's [screencast](https://vimeo.com/31950192), but he might have more details. In general, cheerio's [benchmarks](https://github.com/cheeriojs/cheerio/tree/8ee743e89ee03f04bba971ade430490b079abdaf/benchmark) also run on jsdom, with varying differences (I haven't run them recently).

On the other hand, we might want to highlight that cheerio runs on pretty much every JS platform, not only on io.js and node, but also on Rhino/Nashorn, inside browsers, you name it.

**Comment by tconroy** [comment]
Hey folks, 
curious if anyone had taken recent benchmarks of cheerio vs jsdom performance? Trying to decide which to use for a project that utilizes lots of server-side node parsing.

**Comment by matthewmueller** [comment]
yah, the "8x faster" claim was correct about 4 years ago. I have no idea about now and would happily accept a PR that these metrics over time.

**Comment by cmawhorter** [comment]
Been looking for some numbers myself.  FWIW -- Came across [this page](https://habrahabr.ru/post/163979/) which seems to substantiate the claim (and then some), but I didn't dig all that deeply.  There is a repo: https://github.com/seriyps/html-parsers-benchmark

**Comment by domenic** [comment]
I don't read Cyrilic that well but that post looks to be from 2012 to me.

**Comment by cmawhorter** [comment]
Don't know how I missed that.  Must've been the coffee and white rum.  That repo even has a last mod of 5yrs but I remember less than that.  mbad

**Comment by Vivism** [comment]
In a performance test where 13k records are scraped and parsed, averaging three runs of Cheerio against JSDOM, all else held the same, JSDOM performed 3.8s faster.

**Comment by fb55** [comment]
@Vivisim 3.8s out of which total? What’s the statistical significance of that result (seems pretty low given the size of your dataset and the relatively small difference between runs)?

Generally it would be great if you (or someone else) could publish a comprehensive benchmark. We have some benchmarks in cheerio’s codebase, but they will likely have to be updated to get closer to real-life performance results.

**Comment by lpoulter1** [comment]
Does anyone know which is faster in 2019? I'd rather use native methods, `document.querySelectorAll` with JSDOM I don't think that's possible in cheerio? However i'd be interested if Cheerio was significantly faster.

**Comment by matthewmueller** [comment]
I've removed this claim from the Readme until one of us has time to properly benchmark.

**Comment by rightaway** [comment]
If anyone has a benchmark and would like me to test it and report back let me know.

**Comment by SagnikPradhan** [comment]
I would be very interested in seeing some benchmarks. Will allow us users to choose between what they need.

**Comment by AlexRMU** [comment]
so?

**Comment by cmawhorter** [comment]
fwiw - i've used both pretty extensively and have come to the conclusion they're not comparable. jsdom is _the-browser-in-js_ and cheerio is scraping. 

from my experience, cheerio is more lightweight and quicker but 8x is definitely a bit much. **maybe** 1.5x. maybe.  and that's out of the box. jsdom can be tuned a bit for scraping but i've never bothered because cheerio exists.

under the hood they both use [parse5](https://github.com/inikulin/parse5) which does the heavy lifting of parsing the html text. 

if performance is truly a concern skip both and parse the raw html text yourself and you'll definitely hit 8x. parsing a html tree is expensive.

**Comment by jakobrosenberg** [comment]
Very unscientific experiment:

Iterated through 302 HTML pages.

cheerio
```javascript
async function getContent(filepath) {
    const content = await readFile(filepath, 'utf-8')
    const doc = cheerio.load(content)
    
    const querySelectors = ['.c-sidebar-layout__main', 'main']
    for (const qs of querySelectors) {
        const el = doc(qs)
        
        const text = el.text()
        if (text) {
            return text
        }
    }
}
```

jsdom
```javascript
async function getContent(filepath) {
    const content = await readFile(filepath, 'utf-8')

    const doc = new JSDOM(content)
    const text = doc.window.document.getElementsByClassName('c-sidebar-layout__main')[0]
    if (text) return text.textContent

    const text2 = doc.window.document.getElementsByName('main')[0]
    if (text2) return text2
}
```

cheeriojs: 1349ms ~5x faster
jsdom: 6936ms

I don't know if there are better ways to run the tests, but OOTB cheeriojs is the winner for my use case.

**Comment by altruer** [comment]
Cheerio was 4x times faster for my cases

**Comment by gustawdaniel** [comment]
Cheerio beats JSDOM totally.

Results depends from machine specs and files properties but look at my example:

---

JSDOM 27k files, summary size of all files 250MB.

Processing by:

```
const processFile = (content: string): ExtraOutput => {
    const window = (new JSDOM(content)).window;
    const {document} = window;
    const res = {
        date: document.querySelector('.line_list_K div:nth-of-type(2) div:nth-of-type(1)')?.textContent || '',
        address: document.querySelector('.line_list_K div:nth-of-type(3) div:nth-of-type(1)')?.textContent?.trim() || '',
        phone: document.querySelector('.line_list_K div:nth-of-type(4) div:nth-of-type(1)')?.textContent || '',
        email: document.querySelector('.line_list_K div:last-of-type div:nth-of-type(1)')?.getAttribute('data-ea')
            + '@'
            + document.querySelector('.line_list_K div:last-of-type div:nth-of-type(1)')?.getAttribute('data-eb'),
        speciality: [...document.querySelectorAll('.line_list_A > div')].map((el: Element): string => el?.textContent?.trim() || '') || [],
        workplace: cleanText(document.querySelector('.mb_tab_content.special_one .line_list_K')?.textContent?.trim() || '')
    };
    window.close();
    return res;
}
```

with 

```
global.gc();global.gc();global.gc();global.gc();global.gc();
```

every 100 files.

Crashes after processing 21k files and usage about 32 GB ram and 29 min

![Screenshot from 2021-02-16 14-51-59](https://user-images.githubusercontent.com/16663028/108071739-6184cb80-7066-11eb-90ae-03e8b3aa2ede.png)

The same code with Cheerio

+ no `global.gc()`
+ no `window.close()`

```
const processFile = (content: string): ExtraOutput => {
    const $ = cheerio.load(content);
    return  {
        date: $('.line_list_K div:nth-of-type(2) div:nth-of-type(1)').text(),
        address: $('.line_list_K div:nth-of-type(3) div:nth-of-type(1)').text(),
        phone: $('.line_list_K div:nth-of-type(4) div:nth-of-type(1)').text(),
        email: (el => el.attr('data-ea') + `@` + el.attr('data-eb'))($('.line_list_K div:last-of-type div:nth-of-type(1)')),
        speciality: $('.line_list_A > div').toArray().map((el):string => cheerio(el).text()),
        workplace: cleanText($('.mb_tab_content.special_one .line_list_K').text())
    };
}
```

Ram oscillates between 480 MB and 850 MB all processing executed in 1.34 MIN

![Screenshot from 2021-02-16 15-08-04](https://user-images.githubusercontent.com/16663028/108073692-9e51c200-7068-11eb-8eed-e925c70e7be2.png)

**Comment by gustawdaniel** [comment]
Next example:

About 270 files

Code with JSDOM

```
import fs from 'fs';
import {JSDOM} from 'jsdom';

import {Output} from './helpers'

const getFiles = (): string[] => fs
    .readdirSync(process.cwd() + `/raw`)
    .filter((name) => /^\d+\.html/.test(name))
    .map(name =>
        fs.readFileSync(process.cwd() + '/raw/' + name).toString()
    );

const processFile = (content: string): Output[] => {
    const document = new JSDOM(content).window.document;

    return [...document.querySelectorAll('.rejestr tbody tr')].map(row => ({
        surname: row.querySelector('td:nth-of-type(2)')?.textContent || '',
        name: row.querySelector('td:nth-of-type(3)')?.textContent || '',
        second_name: row.querySelector('td:nth-of-type(4)')?.textContent || '',
        city: row.querySelector('td:nth-of-type(5)')?.textContent || '',
        office: row.querySelector('td:nth-of-type(6)')?.textContent || '',
        status: row.querySelector('td:nth-of-type(7)')?.textContent || '',
        link: row.querySelector('td:nth-of-type(8) a')?.getAttribute('href') || '',
    }))
}

const main = () => {
    return getFiles().map(processFile).reduce((a, b) => [...a, ...b]);
}

const out = main();
fs.writeFileSync(process.cwd() + '/out/basic_data.json', JSON.stringify(out))

console.dir(out)
```

Usage 4.4 GB ram before end of program and about 1 minute of processing.

```
ts-node entry.ts  77.15s user 2.04s system 138% cpu 57.231 total
```

The same program rewritten to cheerio

```
import fs from 'fs';
import cheerio from 'cheerio';

import {Output} from './helpers'

const getFiles = (): string[] => fs
    .readdirSync(process.cwd() + `/raw`)
    .filter((name) => /^\d+\.html/.test(name))
    .map(name =>
        fs.readFileSync(process.cwd() + '/raw/' + name).toString()
    );

const processFile = (content: string): Output[] => {
    const $ = cheerio.load(content);

    return $('.rejestr tbody tr').toArray().map(row => ({
        surname: cheerio(row).find('td:nth-of-type(2)').text(),
        name: cheerio(row).find('td:nth-of-type(3)').text(),
        second_name: cheerio(row).find('td:nth-of-type(4)').text(),
        city: cheerio(row).find('td:nth-of-type(5)').text(),
        office: cheerio(row).find('td:nth-of-type(6)').text(),
        status: cheerio(row).find('td:nth-of-type(7)').text(),
        link: cheerio(row).find('td:nth-of-type(8) a').attr('href') || '',
    }))
}

const main = () => {
    return getFiles().map(processFile).reduce((a, b) => [...a, ...b]);
}

const out = main();
fs.writeFileSync(process.cwd() + '/out/basic_data.json', JSON.stringify(out))

console.dir(out)
```

Ram oscillating between `900 MB` and `1.5 GB` time, 28 sec

```
ts-node entry.ts  35.42s user 1.12s system 126% cpu 28.991 total
```
