### ISSUE TITLE
empty attributes are appended with =""

### ISSUE THREAD

**Issue by kfuchs** [cheeriojs/cheerio#702]
Original element:

`<div class="user-menu" dropdown-toggle>`

After using cheerio on file:

`<div class="user-menu" dropdown-toggle="">`

For some reason cheerio is appending all empty attributes with `=""`

**Comment by pyhedgehog** [comment]
XHTML standard defines attr=attr for empty attributes.

**Comment by kfuchs** [comment]
Anyway to turn this off?

**Comment by fb55** [comment]
IMHO this should become the default behavior in non-XML mode. PRs for the `dom-serializer` module very appreciated.

**Comment by etiktin** [comment]
@fb55, I sent a PR to fix this issue.
Please review and merge

**Comment by ghetolay** [comment]
Well I have the opposite problem :)
I'm working with xhtml and ```default=""``` is converted into ```default```.

Problem come from that line : 
```
if (!value && booleanAttributes[key]){
```

```default``` is part of the ```booleanAttributes``` array.
So I guess we should check about xmlMode sooner.

Do you want a pull request ?

**Comment by timaschew** [comment]
since dom-serializer ist not published to npm and cheerio is not updated to that new version this issue is not fixed

**Comment by timaschew** [comment]
Please reopen this issue, it's still broken!

**Comment by arthurevans** [comment]
Any chance of a new release of dom-serializer to fix this issue?

**Comment by mankins** [comment]
Maybe interested in https://github.com/cheeriojs/dom-serializer/pull/72
