### ISSUE TITLE
.html call on cheerio.load fn is escaping content post 0.15.0 release

### ISSUE THREAD

**Issue by vikaskbajaj** [cheeriojs/cheerio#705]
We were using cheerio version `0.15.0` for really long time in our production application. We used .html function like this:

```javascript
doc = cheerio.load(myContent);
doc("[" + attr + "='" + id + "']").html(content);
```
Post version `0.15.0`, output of this function is escaped HTML content whereas until `0.15.0' it was unescaped and that's causing issues while upgrading.

Any plan on fixing this or workaround available?

**Comment by fb55** [comment]
Setting `decodeEntities: false` disables encoding of possibly unsafe characters as HTML entities.

**Comment by vikaskbajaj** [comment]
Thank you for the update. How and where should I set this `decodeEntities: false` ?

**Comment by jugglinmike** [comment]
See our documentation on loading markup: https://github.com/cheeriojs/cheerio/#loading

**Comment by vikaskbajaj** [comment]
Thanks! That worked well :+1:
