### ISSUE TITLE
Strange attribute getting html

### ISSUE THREAD

**Issue by mattimatti** [cheeriojs/cheerio#706]
hello I'm trying to scrape a wiki, getting just the body content.

     var response_text = .... / / response from node request;

      $ = cheerio.load(response_text, {
        decodeEntities: false
      });

      var htmlcontent = $("#content").html();

     console.log(htmlcontent);

I'm expecting nodes like this:

       <a href="/wiki/index.php/Coworkers" title="Coworkers">Nuovi Collaboratori</a>

but the console outputs this.

    <a href="/wiki/index.php/Coworkers" title="Coworkers" toURL="function () {
    var obj;
    obj = this;
    return '?' + Object.keys(obj).map(function(k) {
      return encodeURIComponent(k) + '=' + encodeURIComponent(obj[k]);
    }).join('&');
      }">Nuovi Collaboratori</a>

Do you know where i'm usign wrong your library? tried to google for it with no luck.
Thank you in advance

**Comment by fb55** [comment]
You seem to have some code monkey-patching `Object.prototype`, adding a `toURL` method. Please use `Object.defineProperty` to modify global objects (if you must), setting `enumerable` to `false`.
