### ISSUE TITLE
Cheerio .html() should not encode cyrillic symbols

### ISSUE THREAD

**Issue by operatino** [cheeriojs/cheerio#711]
```
var cheerio = require('cheerio');
var $ = cheerio.load('<div>кириллица</div>');
console.log($.html()); // => <div>&#x43A;&#x438;&#x440;&#x438;&#x43B;&#x43B;&#x438;&#x446;&#x430;</div>
```

when expected output is `<div>кириллица</div>`

**Comment by operatino** [comment]
`$('div').text()` returns normal, not encoded value

**Comment by operatino** [comment]
Found a solution with `$.html({decodeEntities: false})`, which works fine. Anybody knows what could be the downsides of using this option?

**Comment by operatino** [comment]
And here's the downside - `$('div').html({decodeEntities: false})` returns an object, instead of a string with actual HTML.

**Comment by fb55** [comment]
`decodeEntities` is not an option for `.html`, but for `.load` (or the constructor).

**Comment by operatino** [comment]
Thanks, that helped!

**Comment by aeron11** [comment]
> `decodeEntities` is not an option for `.html`, but for `.load` (or the constructor).

thanks, this helped me!
