### ISSUE TITLE
.text() not working properly

### ISSUE THREAD

**Issue by cakeinpanic** [cheeriojs/cheerio#713]
.text() works so weird with nested nodes, it combines nested nodes innerText
Here's the issue presented in code
``` javascript
elem = $('div', someCode)
html = elem.html(); // <span>a, <span>b,<span>c</span></span>
text = elem.text(); // a, b, cb, ca
```

**Comment by owenallenaz** [comment]
That's the same behavior your get with jQuery to my knowledge, which Cheerio tries to mimic. 
 
```
$("<span>a, <span>b,<span>c</span></span>").text()
a, b,c
```

**Comment by fb55** [comment]
What @owenallenaz said :)
