### ISSUE TITLE
Searching with the id (#) won't find any results but searching each element will

### ISSUE THREAD

**Issue by mikealeonetti** [cheeriojs/cheerio#716]
Hello,

I've found a particular interesting issue. I have the following HTML that I'm parsing:

    <span id="ASXBP912_DETAIL.D.V.R1.PROP_ZIP">11706</span>

I try to find it with the following code:

			// Parse it
			$ = cheerio.load( body );

			console.log( $('#ASXBP912_DETAIL.D.V.R1.PROP_ZIP').html() );

Which will not work, but the following will:

			$('span').each( function( i, element ) {
				if( $(element).attr( 'id' )=='ASXBP912_DETAIL.D.V.R1.PROP_ZIP' ) {
					console.log( $(element).html() );
				}
			} );
It produces the following result (when I run the above code one after the other):
> null
> 11706

Is there an issue in the way I am trying to search?

**Comment by fb55** [comment]
The dots are interpreted as class selectors. Try `$('#ASXBP912_DETAIL\\.D\\.V\\.R1\\.PROP_ZIP').html()`.
