### ISSUE TITLE
Maintain tag attribute quote characters

### ISSUE THREAD

**Issue by desandro** [cheeriojs/cheerio#720]
Cheerio changes attributes with single quotes into double quotes.

``` js
var cheerio = require('cheerio');
// uses 'single quotes'
var $ = cheerio.load('<div attr=\'value\'></div>')
$.html();
// => <div attr="value"></div>
// has "double quotes"
```

This is useful for me, as I use JSON in HTML attributes for [widget settings](http://flickity.metafizzy.co/#initialize-with-html).

``` html
<div data-settings='{ "option": true }'></div>
```

Which is encoded with HTML entities (possibly breaking JSON) as

``` html
<div data-options="{ &quot;option&quot;: true }"></div>
```

Setting `decodeEntities: false` is encoded and breaks HTML

``` html
<div data-options="{ "option": true }"></div>
```

Ideally, cheerio would preserve which quote character is used. I understand this is an edge case, so I'm reporting it in case others run into it. Similar to #460

**Comment by fb55** [comment]
This definitely won't break JSON within browsers. IMHO this won't be fixed.

**Comment by OverFlow636** [comment]
@fb55 is there any chance of this being fixed? 

The html my app has to consume is very horribly written and I do not have control over fixing it. Not only does it contain raw json inside of a div tag, but most of the `href` attributes for anchors only work because of single quotes `href='javascript: dostuff("asdf");'` which like the issue breaks the tag when double quotes are replaced and the `decodeEntities: false` is used.

**Comment by rajsite** [comment]
+1, I also store JSON in HTML attributes and would like to second keeping single quoted escapes because it makes the html with embedded json much easier to manipulate and read

**Comment by achtan** [comment]
+1

**Comment by rostacik** [comment]
gentlemen any update on this one? do you intend to fix this or not at all? its more that 1 year later and task is still open.

**Comment by EugeneButusov** [comment]
@fb55, any update for this? Problem is really important, can't store json in meta tags there.

**Comment by fb55** [comment]
Switching to parse5 could fix this (it's another open issue). As I said
before, not sure if this will be fixed with the current architecture as it
doesn't break anything.


-- 
– Felix

**Comment by EugeneButusov** [comment]
ok @fb55, thank you very much for the feedback.

**Comment by plm0677com** [comment]
1. find the file  node_modules/node_modules/dom-serializer/index.js
2.  location the line at 68,change 
```js
else {
output += key + "='" + (opts.decodeEntities ? entities.encodeXML(value) : value) + "'";
}
```

***To***

```js
  if(/[^\\]\"/.test(value)){
        output += key + "='" + (opts.decodeEntities ? entities.encodeXML(value) : value) + "'";
      }else {
        output += key + '="' + (opts.decodeEntities ? entities.encodeXML(value) : value) + '"';

      }
```

**Comment by gaecom** [comment]
I fix this.
steps:
1. find the file node_modules/dom-serializer/index.js
2.  location the line at 68,change 
```js
else {
output += key + "='" + (opts.decodeEntities ? entities.encodeXML(value) : value) + "'";
}
```

***To***

```js
else {
  if(/[^\\]\"/.test(value)){
        output += key + "='" + (opts.decodeEntities ? entities.encodeXML(value) : value) + "'";
      }else {
        output += key + '="' + (opts.decodeEntities ? entities.encodeXML(value) : value) + '"';

      }
}
```

**Comment by andreysm** [comment]
Thanks, @gaecom.
I've slightly modified your solution.
```
    if (opts.plainQuotes && /[^\\]\"/.test(value)) {
        if (opts.decodeEntities) {
          value = entities.encodeXML(value);
          if (opts.plainQuotes) { value = value.replace(/&quot;/g, '"'); }
        }
        output += key + "='" + value + "'";
      } else {
        if (opts.decodeEntities) {
          value = entities.encodeXML(value);
          if (opts.plainQuotes) { value = value.replace(/&apos;/g, "'"); }
        }
        output += key + '="' + value + '"';
      }
```
This variant works with `decodeEntities: true`.
It makes some double job with encoding and replacing &quot; back, but it is acceptable for better readability.

**Comment by nicolasbadia** [comment]
I also have this issue and the proposed solutions doesn't works for my use case. The HTML parsed by cheerio (via [Inky](https://github.com/zurb/inky)) will also by parsed later by [Twig](https://github.com/twigphp/Twig) and the quote needs to remain the same. Here is a HTML sample which fail:

    {{ "The content may have simple quote like « l' » or « d' », as it is the case for <a href='http://my.link'>tags</a>."|trans }}

**Comment by alexflorisca** [comment]
We are having this issue with implementing the new AMP pages by google. One of the parameters requires JSON inside a data attribute like so:

```<amp-ad rtc-config='{"urls": ["url1",...]}'>```

The single quotes get converted to doubles which invalidates the HTML. JSON can't contain single quotes so swapping double and single quotes doesn't work.

Please cheerio, we need you.

**Comment by stephengardner** [comment]
SOS.  Does anyone have a fix for this?
