### ISSUE TITLE
why is .css('font-size') returning undefined?

### ISSUE THREAD

**Issue by francoisromain** [cheeriojs/cheerio#722]
`.css('font-size')` on a jquery object returns `undefined`. 

Is it possible to get the value of `.css('font-size')` coming form an external css file?

**Comment by fb55** [comment]
`.css` is only for internal variables.

**Comment by JaKXz** [comment]
@fb55 is it possible to check the styles applied to an element?

**Comment by fb55** [comment]
Cheerio doesn't render pages, so this sadly isn't possible.

**Comment by wearhere** [comment]
This is actually a difference from jQuery's `$.css`, which gets the value of computed styles. What is your policy around maintaining compatibility with jQuery? Would you consider adding a warning [here](https://github.com/cheeriojs/cheerio#css-propertname---css--propertynames---css-propertyname-value---css-propertname-function---css-properties-), if not renaming the method? Glad to make a PR for either.

**Comment by bitvitez** [comment]
A warning in the docs would be appreciated!
