### ISSUE TITLE
$('meta[name="description"]').attr("content") returns empty

### ISSUE THREAD

**Issue by hershko** [cheeriojs/cheerio#723]
Running the following code (server-side, on Node):

    var request = require('request');
    var cheerio = require('cheerio');
    request('https://www.google.com', function(error, response, html){
        var $ = cheerio.load(html);
        console.log($('meta[name="description"]').attr("content"));
    });

The console output is empty, and I can't figure out why. The page includes this meta tag:
> meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"

So the console output should be "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." 

Any thoughts? Is this a bug? Am I being super stupid and missing something obvious? Thanks :)

**Comment by jugglinmike** [comment]
To debug, I'd recommend starting with the value of `html`. Copy that into a variable inside a test file so you don't need the "request" module or an Internet connection to reproduce the issue. Then start removing all the non-essential part of the markup until it works as expected. Once you have this reduced test case, you can share it here and we can begin to help you

**Comment by hershko** [comment]
Thank you jugglinmike. When I logged the actual HTML returned by the request, I saw that the relevant meta tag isn't there (even though it is there when you view-source at the browser). Odd, but obviously not a Cheerio issue. My apologies, I'll close the issue.
