### ISSUE TITLE
$('li') error!

### ISSUE THREAD

**Issue by yjhjstz** [cheeriojs/cheerio#724]
```html
<ul>
<li>(internal array) @257&nbsp;-&nbsp;274,420 (7.62%) bytes.
<li>(internal array) @95&nbsp;-&nbsp;131,080 (3.64%) bytes.
</ul>
```
```javascript
$('li', this).each(function(j) {
        console.log(j, $(this).text());

});
```
OUTPUT:
1 (internal array) @257&nbsp;-&nbsp;274,420 (7.62%) bytes.  (internal array) @95&nbsp;-&nbsp;131,080 (3.64%) bytes.
2 (internal array) @95&nbsp;-&nbsp;131,080 (3.64%) bytes.

expected output: 
1 (internal array) @257&nbsp;-&nbsp;274,420 (7.62%) bytes.
2 (internal array) @95&nbsp;-&nbsp;131,080 (3.64%) bytes.

could `cheerio` compatible for this case?

**Comment by jugglinmike** [comment]
I'm not able to reproduce this bug, but I also don't have all the information we need. Can you provide a complete, standalone script that demonstrates the problem? Please include the version of Cheerio, as well. Here's an example:

```js
'use strict';
var cheerio = require('.cheerio');
var markup = [
  '<ul>',
  '<li>(internal array) @257&nbsp;-&nbsp;274,420 (7.62%) bytes.',
  '<li>(internal array) @95&nbsp;-&nbsp;131,080 (3.64%) bytes.',
  '</ul>'
].join('\n');

var $ = cheerio.load(markup);

console.log(cheerio.version);

$('li').each(function(j) {
  console.log(j, $(this).text());
});
```

My output:

```
0.19.0
0 '(internal array) @257 - 274,420 (7.62%) bytes.\n'
1 '(internal array) @95 - 131,080 (3.64%) bytes.\n'
```

The use of `this` as a second argument to `$` is a likely suspect, but I'll need to see a complete script before I can say for sure.

**Comment by cvrebert** [comment]
@yjhjstz Can you respond to Mike's request?

**Comment by yjhjstz** [comment]
sorry , my mistake.
