### ISSUE TITLE
update to 0.19.1

### ISSUE THREAD

**Issue by growlsworth** [cheeriojs/cheerio#727]
Hey cheerio,

I've been running off the current master since the last merged PR (https://github.com/cheeriojs/cheerio/pull/719) in production. Would you be able to update the version to 0.19.1 and publish to npm, so `npm outdated` command will show that this dependency is up to date. Thanks!

Here's a picture of a baby duck as a thank you:

![Baby duck](http://thejunglemag.com/wp-content/uploads/2015/04/cute-baby-animals-01.jpg)

**Comment by jugglinmike** [comment]
We won't be publishing a new release until gh-728 is resolved. (By the way, you can expect version 0.20.0, not 0.19.1, as new features have landed in `master`.)
