### ISSUE TITLE
mixed case element names?

### ISSUE THREAD

**Issue by freder** [cheeriojs/cheerio#730]
hi,

I was wondering if / how I can maintain case sensitivity:
I'm loading a mixed case XML string, do some transformations and then output a string again. but somewhere along the way, all element names are converted to lower case.

```javascript
var opts = {
	xmlMode: true,
	normalizeWhitespace: false,
	lowerCaseTags: false,
	lowerCaseAttributeNames: false
};
var $ = cheerio.load(xml_str, opts);

// [...]

var output = $.xml();
```

apparently [a `lowerCaseTags` option once existed](https://github.com/cheeriojs/cheerio/search?utf8=%E2%9C%93&q=lowerCaseTags) (it's still used in one of the tests, btw). but I find it hard to tell, what exactly I have to do to prevent this case conversion from happening.

I tried turning `xmlMode` on and off, and `$.html()` instead of `$.xml()`, the result is always lower case though.

any ideas?

**Comment by fb55** [comment]
Setting the `lowerCaseTags` option to false still works. The patch only removed it as it is a parser option and can be found on the parser wiki page.
