### ISSUE TITLE
How to extend "every" instance of cheerio?

### ISSUE THREAD

**Issue by NickStefan** [cheeriojs/cheerio#736]
I'm trying to fake some jQuery stuff like $.extend and $.ajax.
In theory it works fine to just do:

```
var $ = $.load('<body></body>')
$.ajax = require('najax');
```

but it doesn't really work. this only adds an ajax method on this one instance. It goes away on numerous operations.

Things I've tried:

```
var oldMake = cheerio.prototype._make;
cheerio.prototype._make = function(){
   return _.extend(oldMake.call(this, arguments), najax);
};
```

```
cheerio.prototype.ajax = najax
```

My guess is that some of the circular dependencies and different places that module.exports is being mixed into itself (ie see ./statics file) makes this impossible? Is there some other way I can extend ALL cheerio instances?

**Comment by joepie91** [comment]
Try setting `$.prototype.ajax` instead. This should keep it available on 'derived' Cheerio objects as well.

**Comment by jugglinmike** [comment]
@joepie91 That won't work in this case, since @NickStefan Is trying to add a static method.

@NickStefan How about

```js
var myLoad = function() {
  var $ = cheerio.load.apply(cheerio, arguments);
  $.ajax = require('najax');
  return $;
};
```
