### ISSUE TITLE
addClass bug.

### ISSUE THREAD

**Issue by ljesparis** [cheeriojs/cheerio#741]
``` javascript
 <h1 class="something">...</h1>
    $(".something").addClass("classvalue")
```

result:

``` javascript
    <h1 class="somethingclassvalue">...</h1>
```

 I need not explain too much...
=P

**Comment by jugglinmike** [comment]
I've edited the original report so that the sample code is visible--hope you don't mind!

**Comment by jugglinmike** [comment]
I'm unable to reproduce the reported behavior:

```js
'use strict';
var cheerio = require('cheerio');

var $ = cheerio.load('<h1 class="something">...</h1>');

$('.something').addClass('classvalue');

console.log($.html());
console.log(cheerio.version);
console.log(process.version);
```

produces:

```
<h1 class="something classvalue">...</h1>
0.19.0
v0.12.7
```

Can you share the result of running that script in your environment?

**Comment by leoxnidas** [comment]
i did write this... 
```javascript
'use strict';
var cheerio = require('cheerio');

var $ = cheerio.load('<h1 class="something">...</h1>');

$('.something').addClass('classvalue');

console.log($.html());
console.log(cheerio.version);
console.log(process.version);
```
and the output

```javascript
 <h1 class="somethingclassvalue">...</h1>
0.19.0
v0.12.7
```

![captura de pantalla de 2015-08-22 21 19 21](https://cloud.githubusercontent.com/assets/9313243/9426541/8a7b8932-4913-11e5-8d59-75df5d190890.png)

**Comment by jugglinmike** [comment]
The same script is producing different output between our computers--that's very strange! This limits the kind of help I can offer you. My best guess right now is that there is some problem with a dependency. We could test this hypothesis like so:

1. Create a new directory. Ensure that none of its parents contain a directory named `node_modules`. Make this your current working directory
2. Run `npm cache clean`
3. Run `npm install cheerio`
4. Run `npm ls`
5. Execute the test script

...and then share the output from step 4 and 5 here.
