### ISSUE TITLE
I would like to share a diff with you

### ISSUE THREAD

**Issue by kylezeeuwen** [cheeriojs/cheerio#744]
Made a recent update to my project after finding cheerio:

    -jsdom = require 'node-jsdom'
    +cheerio = require 'cheerio'
    
    ... 
       parseContent: () =>
    -    deferred = Q.defer()
    -
    -
    -    jsdom.env
    -      html: body
    -      src: [jqueryScript]
    -      done: (errors, window) =>
    -        if errors
    -          @logger.error '', { eventType: 'jsdom-error', error: errors, url: @url }
    -          deferred.reject new Error errors
    -
    -        else
    -          jQuery = window.$
    -          @jQuery = jQuery
    -          @window = window
    -          deferred.resolve()
    -
    -    deferred.promise
    
    +    @jQuery = cheerio.load body
    +    Q.resolve()

Cheerio is awesome thank you so much ! I was dealing with huge memory footprints, parsing issues, and concurrency issues. All I wanted was to run a few simple assertions on some html snapshots I use for SEO. The process now runs 10x faster and uses less memory !!!

Thanks ! 

To be clear there is no issue in this issue

**Comment by matthewmueller** [comment]
Haha thanks for your kind words :-)
