### ISSUE TITLE
Unexpected behaviour with custom tag "line"

### ISSUE THREAD

**Issue by yfp** [cheeriojs/cheerio#746]
``` javascript
cheerio.load("<line>text</line>").html()
```

returns `"<line></line>text"`, expected `"<line>text</line>"`. The parsed tree is wrong, it's not just the html output bug.

**Comment by pyhedgehog** [comment]
Confirmed for cheerio==0.19.0, nodejs==0.12.7.

**Comment by yfp** [comment]
Thanks. That helps.

**Comment by fb55** [comment]
Fixed by #985
