### ISSUE TITLE
Here is a user-side implementation of .wrapAll()

### ISSUE THREAD

**Issue by sfinktah** [cheeriojs/cheerio#748]
I would have written this properly and sent a pull request (using the internal functions for dom manipulation, etc), but the current git version is failing testing.

``` js
var cheerio = require('cheerio');
var _ = require('lodash');

module.exports = (function() {
    var extendCheerio = function extendCheerio($) {
        _.extend($.prototype, {
            wrapAll: function(wrapper) {
                if (this.length < 1) {
                    return this;
                }

                if (this.length < 2 && this.wrap) { // wrap not defined in npm version,
                    return this.wrap(wrapper);      // and git version fails testing.
                }

                var elems = this;
                var section = $(wrapper);
                var marker = $('<div>');
                marker = marker.insertBefore(elems.first()); // in jQuery marker would remain current
                elems.each(function(k, v) {                  // in Cheerio, we update with the output.
                    section.append($(v));
                });
                section.insertBefore(marker); 
                marker.remove();
                return section;                 // This is what jQuery would return, IIRC.
            },
        });
    };

    if ("test") {
        $ = cheerio.load("<html><body><div><p><span>This <em>is <i>test</p><span>More <em>test");
        extendCheerio($);
        $('span').wrapAll('<section>');
        var passed = ($.html() === '<html><body><div><p><section><span>This <em>is <i>test</i></em>'+
                          '</span><span>More <em>test</em></span></section></p></div></body></html>');
        console.log("passed: " + (passed ? "yes" : "no"));
        // console.log($.html() + "\n\n");
    }
    return extendCheerio;
})();
```

**Comment by ajsnyde** [comment]
Doesn't wrap the children, I don't think. I try to $('a').wrapAll('<outer>'):

`<a><b></b><a><a><b></b><a><a><b></b><a>`

and I get `<outer><a></a><a></a></outer><b></b><b></b>`

**Comment by mhjb** [comment]
@sfinktah works for me — thank you very much

**Comment by fb55** [comment]
Happy to accept a PR for this, should someone want to polish things up a bit!

**Comment by antecuic** [comment]
Hi guys!
How did you implement this in code?

**Comment by mhjb** [comment]
@antecuic I did like this: https://github.com/mhjb/studentrights-www-generator/blob/schema/extend_cheerio.js

**Comment by antecuic** [comment]
![Screenshot 2020-12-23 at 09 35 21](https://user-images.githubusercontent.com/54537239/102976735-4bdda480-4502-11eb-97f5-6c6362c41471.png)
I need to use .wrapAll() like this.
![Screenshot 2020-12-23 at 09 37 10](https://user-images.githubusercontent.com/54537239/102976830-6fa0ea80-4502-11eb-9c20-f9361edb8c77.png)
And this is my way of implementing.
had to change to arrow functions because of tslint and different import because of my project setup.
I'm struggling with this problem for days now since .wrapAll() isn't supported on cheerio.
