### ISSUE TITLE
Convert a cheerio array to a Javascript array?

### ISSUE THREAD

**Issue by ryan-williams** [cheeriojs/cheerio#750]
Is there any easy way to do this?

e.g. I've obtained a cheerio array with some strings, and I'd like to `.join('\n')` them.

**Comment by pyhedgehog** [comment]
You can apply join like follows:
```Javascript
var a = ...get some jquery/cheerio array...;
var s = Array.prototype.join.call(a, '\n');
```

**Comment by ryan-williams** [comment]
Fair enough, thanks!
