### ISSUE TITLE
async function in the $.each callbacks

### ISSUE THREAD

**Issue by chenweiyj** [cheeriojs/cheerio#752]
I have following code in my node script.

```
$('p').each(function (idx, elem) {
  var article = new Article({content: $(this).html()});
  article.save(function (err) {// do something}); // db save async function or other async function
});

mongoose.connection.close();
```

However, the `mongoose.connection.close()` will run before all the documents are saved to the database. So how can I make sure all things are done before closing the db connection?

**Comment by angelgarrido** [comment]
I think this is not a question for cheerio repo.

You can for example create a async queue to be sure all your elements are
treated properly

**Comment by felixfbecker** [comment]
This is a problem with async code in general. Mongoose has support for promises, so you could do this:
```
var promises = [];
$('p').each(function (idx, elem) {
  var article = new Article({content: $(this).html()});
  var promise = article.save();
  promises.push(promise); // db save async function or other async function
});
Promise.all(promises)
  .then(doSomethingOnSuccess)
  .catch(doSomethingOnError)
  .finally(mongoose.connection.close);

**Comment by fb55** [comment]
I guess this has been answered :)

**Comment by rithpath** [comment]
Better solution - 
await $('p').each(async function (idx, elem) {
  var article = new Article({content: $(this).html()});
  article.save(function (err) {// do something}); // db save async function or other async function
});

**Comment by fb55** [comment]
Cheerio now supports iterators, so the modern way of doing this would be:

```js
for (const elem of $('p')) {
  const article = new Article({content: $(elem).html()});
  try {
     // db save async function or other async function
    await article.save();
  } catch(err) {
    // do something
  }
}

await mongoose.connection.close();
```
