### ISSUE TITLE
How to remove the `<a>` tag but reserve its text?

### ISSUE THREAD

**Issue by chenweiyj** [cheeriojs/cheerio#753]
I have an article with some `<a>` tags inside. I want to show the text between the `<a>` and its closing tag `</a>`. How can I do this?

**Comment by felixfbecker** [comment]
`$('a').unwrap()`

**Comment by alanev** [comment]
There is no method 'unwrap' in cheerio (and 'wrap' too).
But you can manipulate with cheerio object:
$('a').each(function () {});

**Comment by alanev** [comment]
There is no method 'unwrap' in cheerio (and 'wrap' too).
Use 'replaceWith' instead:
```js
$('a').each(function () {
  $(this).replaceWith($(this).html());
});
```

**Comment by alanev** [comment]
And also you can add method `unwrap` in cheerio.
```js
$.prototype.unwrap = function () {
  this.replaceWith(this.html());
}
$('a').unwrap();
```

**Comment by chenweiyj** [comment]
@alanev  it works
