### ISSUE TITLE
.not('script') not working?

### ISSUE THREAD

**Issue by JulianKingman** [cheeriojs/cheerio#757]
I'm trying to understand why I can't filter out script, style, etc... tags. Actually, I can't seem to get it to filter out any tags at all. Here's what I have:

````javascript
var $ = cheerio.load(Meteor.http.get(url).content,{});
var content = $('body').not('script').text();
````

(Meteor.http.get(url) gets the contents of the url)

**Comment by alanev** [comment]
You are trying to get tag `body` that is not a `script`.
Try to use all selector (“*”)
```js
var $ = cheerio.load(Meteor.http.get(url).content,{});
var content = $('*').not('script').text();
```

**Comment by fb55** [comment]
Thanks, @alanev!

**Comment by JulianKingman** [comment]
Perfect, thanks! Any idea why it's not working with .html() in place of .text()?

**Comment by alanev** [comment]
@JulianKingman Can you show an example of code that you are parsing?
