### ISSUE TITLE
Attribute selector error

### ISSUE THREAD

**Issue by Hiswe** [cheeriojs/cheerio#758]
Hi,

Thanks for your library! It's a really great job :)

I have encouter an issue while using cheerio to clean some SVG files. I'm trying to remove all attributes named `sketch:type`. 

Trying this make an error:
```js
$('[sketch:type]').removeAttr('sketch:type');
```
jQuery seems to support an [escaping syntax](http://api.jquery.com/category/selectors/) but trying it doensn't error (which is good :) but doesn't work (which is sad).

```js
$('[sketch\\:type]').removeAttr('sketch:type');
```

Do you have any ideas?

Thanks in advance.

**Comment by fb55** [comment]
The `]` in `removeAttr` seems unnecessary.

**Comment by Hiswe** [comment]
@fb55 You're totally right. My exemple was mal formatted… I will fix it.
The  `.removeAttr('sketch:type')` is working as expected :) 

It's really the `$('[sketch:type]')` that throw me an error…

**Comment by fb55** [comment]
This won't work in jQuery, either :)

**Comment by Hiswe** [comment]
@fb55 life is so sad :P
Ok I will close the ticket. We can still have the functionality with a filter :)
