### ISSUE TITLE
$(*).text returns text for all elements in collection, concatenated

### ISSUE THREAD

**Issue by JulianKingman** [cheeriojs/cheerio#760]
I have two separate ways of getting text, which should both return the same result, but the .text() version combines header tags (and possibly some others) with the tag that follows (in my case a p tag).

``` javascript
$(selector + ' *').not('style, script').map(function(idx, el) { return $(el).text(); }).get(); //returns all text correctly
$(selector + ' *').not('style, script').text(); //Combines headers with the next element
```

``` html
<h2> A title</h2>
<p>Some content goes here</p>
```

First way returns:
['A title', 'Some content goes here']

Second way returns:
['A titleSome content goes here']

**Comment by fb55** [comment]
`text` does not map over values — this is in line with jQuery. There is a bug here, as `text` should only return the text of the first element (in line with `.html`).

**Comment by 5saviahv** [comment]
As far I can tell concatenation is expected behavior - [jQuery API says](https://api.jquery.com/text/):
>Get the combined text contents of each element in the set of matched elements, including their descendants, or set the text contents of the matched elements.

[source also](https://github.com/jquery/jquery/blob/8ae477a432f0924cd4bd3bdeaef2c4c15e483a8f/src/core.js#L270) support that 
``` js
... 
// If no nodeType, this is expected to be an array
while ( ( node = elem[ i++ ] ) ) {

	// Do not traverse comment nodes
	ret += jQuery.text( node );
}
...
```

**Comment by fb55** [comment]
Thanks for double-checking me @5saviahv, and good find!
