### ISSUE TITLE
ES6 arrow functions

### ISSUE THREAD

**Issue by gajus** [cheeriojs/cheerio#762]
Might be worth mentioning somewhere in the documentation that cheerio will not work as expected with arrow-function.

Arrow function `this` value refers to the lexical `this` value (`this` in the scope of the declaration), i.e.

```js
$('div').each(() => {
    $(this).text(); // "this" does not refer to the element.
});
```

You can either continue to use the functional expression or use the parameter value, e.g.

```js
$('div').each((element) => {
    $(element).text(); // "this" does not refer to the element.
});
```

**Comment by manjufy** [comment]
It did not work either of them.
I ended up doing

```
$('div').each(function(index, element) {
    $(element).text();
});
```

**Comment by Rotimi-Best** [comment]
> that cheerio will not work as expected with arrow-function.
Really??? I never knew about that, it is actually in the docs that `this` or `element` could be used in the callback.
