### ISSUE TITLE
How can I convert the .html() to normal text?

### ISSUE THREAD

**Issue by chenweiyj** [cheeriojs/cheerio#763]
Cheerio only provides `$.html()` to get the html string. However, all the unicode is converted like `&#x4F60;&#x53EF;&#x80FD;&#x611F;&#x5174;&#x8DA3;`. I want to convert these encoded html to normal text like `你可能感兴趣`. 

How can I do it in Node.js?

**Comment by alanev** [comment]
```js
$ = cheerio.load('<ul id="fruits">你可能感兴趣</ul>', {
    decodeEntities: false
});
```

**Comment by chenweiyj** [comment]
@alanev So if I already have a string of `&#x4F60;&#x53EF;&#x80FD;&#x611F;&#x5174;&#x8DA3;`, how can I get the original text?

**Comment by chenweiyj** [comment]
I find a library to convert the html entity to unicode text.

https://github.com/substack/node-ent

**Comment by lichunqiang** [comment]
Good job!

**Comment by ufo22940268** [comment]
Cool. But what is `decodeEntities` used for. If set it to false, it will cause parsing slower?
