### ISSUE TITLE
No simple way to preserve new lines in text

### ISSUE THREAD

**Issue by Canop** [cheeriojs/cheerio#764]
When you do

     $b.text($a.text());

you lose the new lines coming from `<BR>` elements.

This is consistent with what you have in jQuery but jQuery users have the option to use `innerText` which doesn't have the same problem (contrary to `textContent`).

Would a PR adding a new `textln` function be welcome or should cheerio users just monkey patch when they need to preserve new lines ?

**Comment by jugglinmike** [comment]
The goal of this project is parity with jQuery's DOM manipulation/traversal API, so I don't think a custom function is in-scope.

**Comment by alanev** [comment]
You can write you own method. Like this:
```js
$.prototype.textln = function () {
    this.find('br').replaceWith('\n');
    this.find('*').each(function () {
        $(this).replaceWith($(this).html());
    });
    return this.html();
}
$('a').textln();
```

**Comment by fb55** [comment]
Thanks, @alanev!
