### ISSUE TITLE
How to check if object is an instance of cheerio?

### ISSUE THREAD

**Issue by gajus** [cheeriojs/cheerio#765]
There is no documented way to check whether an element is an instance of cheerio element, e.g.

```js
let subject;

subject = $('div');

// How to make sure that "subject" is an instance of cheerio selector?
```

**Comment by stramel** [comment]
I would imagine you could do `subject.cheerio` like in the source.

https://github.com/cheeriojs/cheerio/blob/master/lib/api/traversing.js#L16
