### ISSUE TITLE
dom href

### ISSUE THREAD

**Issue by Zverushko** [cheeriojs/cheerio#770]
Hi!
Can i parse absolute url in href attr if in html this is relative path?
thx!

$('a').each(function(index, element) {
            console.log($(element).attr('href'));
});
// /reviews/

but i need full path - http://domain.com/reviews/

**Comment by fb55** [comment]
Try node's `url.resolve` :)

**Comment by polRk** [comment]
`url.resolve(from, to)`
It doesn't work, when i dont know from url.
It doesn't work, when i have absolute url "https://example2.com" and realite "/path"
