### ISSUE TITLE
.siblings() not returning prior children of parent

### ISSUE THREAD

**Issue by swachtma** [cheeriojs/cheerio#771]
I'm having trouble getting the siblings() method to properly return siblings that occur after the main element of my selection.  Moving the sibling lines so the occur after the selected line causes them to be returned.  My understanding though is that siblings() should return all children in the parent element, regardless of order.

here's the XML I'm selecting from:
``` XML
  <dcterms:subject>
      <rdf:Description rdf:nodeID="Ne7861777571341afa42bb9d46468501d">
        <rdf:value>War -- Early works to 1800</rdf:value>
        <dcam:memberOf rdf:resource="http://purl.org/dc/terms/LCSH"/>
      </rdf:Description>
    </dcterms:subject>
    
    <dcterms:subject>
      <rdf:Description rdf:nodeID="N686d4d27be934fb4b99562de2b0e525d">
        <dcam:memberOf rdf:resource="http://purl.org/dc/terms/LCSH"/>
        <rdf:value>Military art and science -- Early works to 1800</rdf:value>
      </rdf:Description>
    </dcterms:subject>
```

And the code I've written:
``` Javascript
"use strict"

const
  fs = require('fs'),
  cheerio = require('cheerio');

//importing module exports a function that expects 2 params, a file path and a callback function
module.exports = function(filename,callback){
  // reads passed file path and invokes it's own callback
  fs.readFile(filename,function(err,data){
    //if error return err through callback
    if(err){ return callback(err);}
    let
      //otherwise cheerio loads FS data to $ as a string
      $ = cheerio.load(data.toString()),
      // define collect as a function to parse data into arrays
      collect = function(index,elem){
        return $(elem).text();
      };

      callback(null,{
        _id: $('pgterms\\:ebook').attr('rdf:about').replace("ebooks/",""),
        title: $("dcterms\\:title").text(),
        authors: $("pgterms\\:agent pgterms\\:name").map(collect).get(),
        subjects: $('[rdf\\:resource$="/LCSH"]').siblings('rdf\\:value').map(collect).get(),
      })
  })
}
```

Returns the following:
```javascript
{ _id: '132',
  title: 'The Art of War',
  authors: [ 'Sunzi, active 6th century B.C.', 'Giles, Lionel' ],
  subjects: [ 'War -- Early works to 1800' ] }
```

**Comment by vlidou** [comment]
I am seeing the same problem with cheerio 0.19.0.

I think the title of this bug should say ".siblings() ONLY returning prior children of selected element". Tweaking the xml fixes the problem (move all siblings appearing after the selected element). So this is obviously a bug in the library.

**Comment by brightgarden** [comment]
This is resolved by passing in the `recognizeSelfClosing` option on load:

```
      $ = cheerio.load(data.toString(), {
          recognizeSelfClosing: true
      })
```

The [htmlparser2](https://github.com/fb55/htmlparser2) library does not handle self-closing tags by default (because it expects to parse html).

There is an `xmlMode` option as well that you can turn on, but this option alone will not resolve this issue.

**Comment by D3VON** [comment]
Here it is almost 2017, and these comments are super-helpful!  All of the above made the example in Node.js the Right Way work.
