### ISSUE TITLE
Support for all attribute variations

### ISSUE THREAD

**Issue by stramel** [cheeriojs/cheerio#772]
Not sure if this is specific to angular or not but it would be great to see support for `ng:` attribute. Angular supports a varying number of attributes but I don't believe `ng:` is supported by cheerio at the moment.

Supported attribute variations: `ng-`, `ng:`, `ng_`, `data-ng-`, `x-ng-`

Reference: https://docs.angularjs.org/guide/directive#normalization

**Comment by fb55** [comment]
Definitely specific to Angular. You can implement this on top of cheerio, but I don't see a reason to include it in the library.
