### ISSUE TITLE
incorrect .val() behaviour for select options without value attr

### ISSUE THREAD

**Issue by yurks** [cheeriojs/cheerio#774]
``` html
<select>
  <option value=2015>2015</value>
  <option value=2014>2014</value>
</select>
```

For above html snippet `$('select').val()` returns `2015` and this is correct.

``` html
<select>
  <option>2015</value>
  <option>2014</value>
</select>
```

And now `$('select').val()` is empty, but should be `2015` according to [w3c html5 recommendation](http://www.w3.org/TR/html5/forms.html#attr-option-value)

> The value attribute provides a value for element. The value of an option element is the value of the value content attribute, if there is one, or, if there is not, the value of the element's text IDL attribute.

**Comment by 5saviahv** [comment]
``` javascript
const cheerio = require('cheerio');

const $ = cheerio.load(`
<select>
  <option value=2015>2015</value>
  <option value=2014>2014</value>
</select>`);

console.log($('select').val());

const $$ = cheerio.load(`
<select>
  <option>2015</value>
  <option>2014</value>
</select>`);

console.log($$('select').val());
```

results:
```
2015

2015
```
So it should be ok
