### ISSUE TITLE
Limit maximum DOM tree depth to prevent [Maximum call stack size exceeded]

### ISSUE THREAD

**Issue by peakji** [cheeriojs/cheerio#778]
Some malformed pages with extremely deep nested tags, like [this one](http://blog.sina.com.cn/s/blog_5e54397201015h3l.html), will cause **[Maximum call stack size exceeded]** while using .text() or .html().

In fact, the WebKit project limits the maximum DOM tree depth by **512**: http://trac.webkit.org/browser/trunk/Source/WebCore/page/Settings.h#L220

These deep nested tags are usually generated by templates. We've found hundreds of pages from various major sites having this issue.

So maybe we can add an option to limit the parsing depth in cheerio (or the underlying [htmlparser2](https://github.com/fb55/htmlparser2/))?

**Comment by sholladay** [comment]
The proper protection against such things is almost always to use iteration instead of recursion. And in this case, doing so has the added benefit of not expanding Cheerio's API or those in its dependency tree.

**Comment by peakji** [comment]
Thanks @sholladay, but how can I get text() using iteration?

**Comment by sholladay** [comment]
I don't think we can do anything about it as users. What I meant is that I am in favor of fixing this, but I am against adding a recursion limiting API option. The parser ought to switch to using iteration, internally. Doing anything else would just be programming around undesirable programming. That rarely ends well. :)

**Comment by garymoon** [comment]
For anyone running across this issue, I got this a few times when I accidentally loaded a PDF into cheerio (in case it's relevant, [this](https://www.st.cs.uni-saarland.de/edu/seminare/2005/advanced-fp/docs/sweeny.pdf) is the PDF in question). Best to do some sanity checking (I'm checking mime type now) before loading things up. Been processing a few hundred pages a day for a couple of weeks now and haven't had it since.

cc #240

**Comment by peakji** [comment]
This issue has been inactive for a while, for anyone still running across this issue, just implement a DFS with depth limit:

```javascript
function innerText(nodes, limit) {

	// Depth limit exceeded
	if (limit < 0) return "";

	// Collect text chunks
	const chunks = [];

	for (let i = 0; i < nodes.length; i++) {
		const node = nodes[i];

		// Comment node
		if (node.type == "comment")
			continue;

		// Text node
		if (node.type == "text")
			chunks.push(node.data);

		// Go deeper
		else if (node.children)
			chunks.push(innerText(node.children, limit - 1));
	}

	return chunks.join("");
};
```
