### ISSUE TITLE
.html() outputs &apos; which is not correct HTML4

### ISSUE THREAD

**Issue by thorn0** [cheeriojs/cheerio#779]
```
var $ = require('cheerio').load("<span style=\"font-family: 'Some font'\"></span>");
console.log($.html());
```
This code outputs:
```
<span style="font-family: &apos;Some font&apos;"></span>
```
`&apos;` is an XML thing, it doesn't exist in HTML4. `&#39;` should be used instead.

Yes, it's adopted by the HTML5 spec, but many HTML parsers still don't understand it. Why introduce this useless incompatibility?

**Comment by fb55** [comment]
Known issue of the `entities` project.
