### ISSUE TITLE
Unexpected result while using .find(">") on a string containing <html> tag

### ISSUE THREAD

**Issue by Delgan** [cheeriojs/cheerio#780]
Hello.

I had not had the opportunity to say it so far, but I wanted first of all to thank you for the wonderful tool that is Cheerio.js. You have done an amazing job, I can not express how much your work is valuable.
Really, thank you.

I recently encountered an unexpected behavior of Cheerio.js which I suspect to be a bug.

I opened [a question on StackOverflow](http://stackoverflow.com/questions/33713139/cheerio-and-find-return-too-many-elements-compared-to-jquery#) but I decided to come here and report this as an issue.

I try to parse HTML:
```html
<html>
    <head></head>
    <body>
        <div>
            <table>
                <tr>
                    <td>
                        <a href="/link_1.php">Link 1</a>
                    </td>
                    <td>
                        <a href="/link_2.php">Link 2</a>
                        <a href="/link_3.php">Link 3</a>
                    </td>
                    <td>
                        <a href="/link_4.php">Link 4</a>
                        <a href="/link_5.php">Link 5</a>
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>
```

Using this code:
```javascript
var cheerio = require("cheerio");
var $ = cheerio.load(html);
var page = $.root();

var tr = page.find("tr");

console.log(tr.find("> :nth-child(2) a").length);
```

What happens is that this code returns `5` whereas the second child of the `<tr>` tag contains only 2 links.

A test case can be found [here](https://jsfiddle.net/ub1wL25y/2/).
I also tried to [remove `$.root()`](https://jsfiddle.net/ub1wL25y/4/) and to [use `$.parseHTML()`](https://jsfiddle.net/ub1wL25y/5/) but the issue is still the same.

As you can see [here](https://jsfiddle.net/veajq33v/2/), jQuery works as expected.
Maybe is it related to a limitation of [selecting direct children using `querySelector()`](https://stackoverflow.com/questions/6481612/queryselector-search-immediate-children)?

What is strange is that removing `<html>` tag [seems to work](https://jsfiddle.net/ub1wL25y/6/), it returns `2`.
Moreover, `tr.find("> :nth-child(2)").find("a")` [works just fine too](https://jsfiddle.net/ub1wL25y/13/).

I really do not see what is wrong with my first code, so I opened this issue hoping you can help me and confirm whether or not it is a bug.

**Comment by fb55** [comment]
That's due to the shipped version of `css-select` not having proper support for contexts. The current version supports this, but has a severe bug left.

**Comment by Delgan** [comment]
Hey @fb55, I am sorry to bother you again with this closed issue but I have a problem: the update of `css-select` do not seems to fix it. :fearful:

What I did is that I browserified (just to being able to share a jsFiddle) the last committed version of Cheerio, but with 3 differentes release of `css-select`:
* [Cheerio using css-select 1.0.0](https://gist.githubusercontent.com/Delgan/834b6c029acc2337f07f/raw/409ee5e4e1defbc00bfb52bcd4fc2c6b61fbcc90/Cheerio%2520using%2520css-select%25201.0.0)
* [Cheerio using css-select 1.1.0](https://gist.githubusercontent.com/Delgan/1e31d16ba18763399886/raw/1be0331a8066a813390171fa3d8d6fd29498b6b8/Cheerio%2520using%2520css-select%25201.1.0)
* [Cheerio using css-select 1.2.0](https://gist.githubusercontent.com/Delgan/31a258613526644d61d5/raw/402c57e45e3c7c504d6d1a54d46bf17a4c279b54/Cheerio%2520using%2520css-select%25201.2.0)

v1.0.0 is before the fix, 1.2.0 is the last release and I added the 1.1.0 because I wanted to be sure that it was not my changes which added a regression.

Now, back to the example I provided in jsFiddle:
* [Using v1.0.0](https://jsfiddle.net/ub1wL25y/14/)
* [Using v1.1.0](https://jsfiddle.net/ub1wL25y/15/)
* [Using v1.2.0](https://jsfiddle.net/ub1wL25y/16/)

We can see that using v1.0.0 returns 5 as stated before. But the two last versions returns 0 instead of 2.

So, as this issue seemed very close to [this one](https://github.com/cheeriojs/cheerio/issues/742), I made the tests.
* [Using v1.0.0](https://jsfiddle.net/ub1wL25y/21/)
* [Using v1.1.0](https://jsfiddle.net/ub1wL25y/22/)
* [Using v1.2.0](https://jsfiddle.net/ub1wL25y/23/)

The first case returns 2, which is wrong. The two others versions return 1 which is the correct and expected result.
But if we look closer, we can see that the returned element is not the expected one.
`$('foo').find('> bar')` should return the immediate children of `<foo>`, but instead, it returns the deepest one which as no other descendant. So the fix to `css-select` did not seem to work.

Finally, I installed `css-select` module and I tried the same tests by using `CSSselect()` and so without involving Cheerio. As expected, it worked just fine.

I looked into Cheerio code and I saw this:

```javascript
exports.find = function(selectorOrHaystack) {
  var elems = _.reduce(this, function(memo, elem) {
    return memo.concat(_.filter(elem.children, isTag));
  }, []);
  
  (...)

  return this._make(select(selectorOrHaystack, elems, this.options));
};
```

What happens is that `elems` contains the immediate children of the element to which is called `.find()`. For example in my case, it is an array containg the three `<td>` elements. 
From what I understand, if these elements are passed to `select()` (which is `CSSselect()`) with the selector `"> "` then it will not work because each `<td>` will be considered as the context while it should be `<tr>`, and as there is no `<td>` immediate children of a `<td>`, it will return nothing.

So, did I misunderstand something or is this a issue which should be fixed?
You wrote that this was fixed in the `css-select` repo and indeed it is. But I think my mistake could be that I overinterpreted your words. In fact, it is not enough to just update the version of css-select, there are other changes to the code of Cheerio that should be implemented in order to obtain the expected behavior, is it?
Do you (or others members of CheerioJS) know which these changes are, or do you need someone to look at it?

Thank you for your time.

**Comment by fb55** [comment]
@Delgan You're right. We need to pass the current elements to `select` as the context to make this work. Want to send a PR?

**Comment by Delgan** [comment]
@fb55 I do not know, I do not have as much knowledge about Cheerio than you, I do not want to break everything. :sweat_smile:

It seems that `root` elements are special and still need `.children`. So I ended up with something like that:
```javascript
var elems = _.reduce(this, function(memo, elem) {
  return memo.concat(_.filter(elem.type === 'root' ? elem.children : [elem], isTag))
}, [])
```

It looks that it solves the issue and passes all the tests, but is it the way you want this issue to be fixed?

**Comment by fb55** [comment]
This way, the selected elements can be part of the result of `.find`, which should not be the case (and it's surprising that there is no test case for it).

One solution would be to pass `{__proto__: this.options, context: this.toArray()}` as the options to `select`.

**Comment by Delgan** [comment]
@fb55 My bad, there is such a test case, I missed the file while running the tests, sorry. And indeed, it fails.
