### ISSUE TITLE
.map() return value is dirty when iterator returns a Cheerio object instead of a node

### ISSUE THREAD

**Issue by tmslnz** [cheeriojs/cheerio#783]
SEE UPDATE BELOW

Hello, I’ve been stumped on a strange error when using `$el.attr(’someattr’)`

I traced it down to https://github.com/cheeriojs/cheerio/blob/ec2414dd1d3b6db5b866673f10e06efe437ea472/lib/api/attributes.js#L73
where in my case `this[0]` happens to be `undefined`.

This only happens when the attribute `someattr` exists in the node. If the node has no `someattr` the script continues without error.

What happens is that `getAttr(elem, name)` is called with `elem` undefined, and in turn it calls `isTag(type)` with an undefined argument, which throws when attempting to access `type.type`.

Returning `isTag()` `false` early fixes this, but I can’t understand how in the first place `this[0]` can be `undefined`…

**Comment by tmslnz** [comment]
UPDATE: I found the issue in my code. However I wonder if it stems from a bug in Cheerio’s `.map()`.

This is what I was doing:

```js
function getUploadItemsOfType (xmlNode, type) {
	if (!xmlNode || !xmlNode.length) return;
	var uploads = xmlNode[0].tagName === 'upload' ? xmlNode : xmlNode.find('upload');
	if (!uploads.length) return;
	var uploadsOfType = uploads.filter( function (i, el) {
		return getUploadType(cheerio(el)) === type;
	});
	return uploadsOfType.map(function (i, el) {
		return cheerio(el).parents('content-item');
	});
}
```

Where in the above, the iterator in the last call of `.map()` was returning a cheerio object.

This change resolved the issue:

```js
…
return uploadsOfType.map(function (i, el) {
	return cheerio(el).parents('content-item')[0];  // <— getting [0] fixes it
});
```

Shouldn’t `.map()` test if the iterator return value is an instance of cheerio before wrapping?

**Comment by fb55** [comment]
This seems to work as intended.
