### ISSUE TITLE
Retrieving all attributes of an Element

### ISSUE THREAD

**Issue by robogeek** [cheeriojs/cheerio#786]
I recently needed to retrieve all attributes of an Element to loop through the elements.  After awhile of beating my head against the tutorials on doing this with jQuery (e.g. use the .attributes object) I remembered that Cheerio doesn't implement everything ...

I did find inside one of the source files that the $(element) object has a .attribs array and was able to write my code to access that array.  But it's not compatible with the existing suggestions out there for using jQuery API approaches.

For example http://stackoverflow.com/questions/2048720/get-all-attributes-from-a-html-element-with-javascript-jquery

```
var element = $("span[name='test']");
$(element[0].attributes).each(function() {
console.log(this.nodeName+':'+this.nodeValue);});
```

What I did instead is:

```
var elem = $(element).get(0);
// attribs is an implementation detail of Cheerio
for (var nm in elem.attribs) {
    var attr = elem.attribs[nm];
    ....
}
```

Seems to me that at the time you create the .attribs array, you could also/instead create a compatible .attributes object.

**Comment by fb55** [comment]
Supporting the entire DOM API is what jsdom is for, cheerio (probably) won't implement the `attributes` interface. You are in luck, though: `attribs` is already an object, with the attribute name as the key and the value as the entry for the key.

**Comment by MonsieurV** [comment]
Here is a wrapper that can be used between jQuery and Cheerio code:

```js
const getAllAttributes = function (node) {
	return node.attributes || _.map(node.attribs,(value,name) => {
		return { name,value };
	});
};
```

Then instead of using directly `element.attributes`, you do `getAllAttributes(element)`. The API of the returned attributes is the same as for `element.attributes`.

Example:

```js
const element = '<ul id="tomato" class="vegetables"></ul>';
$(getAllAttributes(element)).each() {
     console.log(`Attribute ${this.name}: ${this.value}`);
}
// Output:
// > Attribute id: tomato
// > Attribute class: vegetables
```

**Comment by bogem** [comment]
@MonsieurV thank you for your tip, it works! There is a small typo in usage though. This really works:
```js
const element = '<ul id="tomato" class="vegetables"></ul>';
getAllAttributes($(element)).forEach(({name, value}) => {
     console.log(`Attribute ${this.name}: ${this.value}`);
})
```

**Comment by MonsieurV** [comment]
You're spot-on right @bogem, I've updated the example. (Also replaced the `_.map` by `Object.keys().map` for a more native implementation).

**Comment by moatorres** [comment]
I've managed to do something similar in order to extract `<line>`'s attributes from an `<svg>` with help of `object-assign`.

```js
const cheerio = require('cheerio')
const assign = require('object-assign')

const svg = fs.readFileSync('./icon.svg')

const $ = cheerio.load(svg, assign({ xmlMode: true }))

$('line').each(function () {
   console.log(this.attribs)
})

// → { x1: '1', y1: '1', x2: '23', y2: '23' }
```
