### ISSUE TITLE
Cheerio is not throwing the error.

### ISSUE THREAD

**Issue by eawer** [cheeriojs/cheerio#788]
Hey,
when I'm trying to do something like

```
$ = cheerio.load(123)
$ = cheerio.load('asdddsa')
```

or

```
$('non-existing-input-selector').val()
$('table td').eq(10000000000000000000000000000).text()
```

I can see no error thrown (with obviously incorrect input). Is it default behaviour, is there any way to enable such kind of errors?

Checking if `$('non-existing-input-selector').val()` is `undefined` for each selector does not seem really good solution.

**Comment by fb55** [comment]
This is expected behavior.
