### ISSUE TITLE
Question: how can I extend cheerio

### ISSUE THREAD

**Issue by kisenka** [cheeriojs/cheerio#789]
How can I extend cheerio (add custom method `toString()` for example)

**Comment by alanev** [comment]
Hello! It is very simple. Look this example https://github.com/cheeriojs/cheerio#plugins
But if you want just transform html into string, there is [build-in method](https://github.com/cheeriojs/cheerio#html-htmlstring-) in cheerio 

Also i can advise you to use [Postxml](https://github.com/postxml/postxml) - a tool for transforming html with plugins based on cheerio.

**Comment by kisenka** [comment]
@alanev thanks a lot!
