### ISSUE TITLE
[With Fix] $.html() // uncaughtException: undefined is not a function at Object.encodeXML

### ISSUE THREAD

**Issue by dleeq8** [cheeriojs/cheerio#791]
the code:

```
var cheerio = require('cheerio'),
$ = cheerio.load('<h2 class="title">Hello world</h2>');

console.log($.html()) // <-- Error
```

Error:

```
uncaughtException: undefined is not a function
TypeError: undefined is not a function
    at Object.encodeXML (cheerio\node_modules\entities\lib\encode.js:59:6)
    at formatAttrs (cheerio\node_modules\dom-serializer\index.js:67:62)
    at renderTag (cheerio\node_modules\dom-serializer\index.js:132:17)
    at module.exports (cheerio\node_modules\dom-serializer\index.js:113:17)
    at render (cheerio\lib\static.js:67:10)
    at Function.exports.html (cheerio\lib\static.js:91:10)
    at Object.<anonymous> (server.js:58:15) // <-- at cosole.log()
```

Fix:
cheerio\node_modules\entities\lib\encode.js:51

```
51: function getInverse(inverse, re){
    function func(name){
        return inverse[name];
    }

    return function(data){
        // ++ add this line so data will have prototype Of String
        if (typeof data !== 'string'){data=data+'';} 
        return data
                .replace(re, func)
                .replace(re_astralSymbols, astralReplacer)
                .replace(re_nonASCII, singleCharReplacer);
    };
}
```

i am new at github so sorry for breaking any rules here .. just i want to notice the cheeriojs about this error and for people who is google a fix without success .. good luck

**Comment by henr-y** [comment]
+1 Thank you a lot for the fix!

**Comment by jugglinmike** [comment]
I can't reproduce this with Cheerio on `master`, version `0.18.0` or version `0.19.0` (latest). Can you share which version of cheerio you are using? Retrieve it via

```js
var cheerio = require('cheerio');
console.log(cheerio.version);
```

**Comment by dleeq8** [comment]
its looks a problem with one of cheerio plugins called "entities"

{
  "name": "entities",
  "version": "1.1.1",
  "description": "Encode & decode XML/HTML entities with ease",
  "author": {
    "name": "Felix Boehm",
    "email": "me@feedic.com"
  }
https://github.com/fb55/entities

still not fixed
https://github.com/fb55/entities/blob/master/lib/encode.js#L57


need a check before
data.replace(..)
 if(typeof data != "string"){data =data+'';}
or a fix in cheerio side
find where the calls go to entities\lib\encode.js:51
maybe this lines
...
at render (cheerio\lib\static.js:67:10)
at Function.exports.html (cheerio\lib\static.js:91:10)
...
the fix will make sure data passed as string not as any//object

**Comment by dleeq8** [comment]
strange i re installed cheerio versions 0.18/0.19/0.20
and every thing works normal without that fix
but i am sure at my windows7/ + vps ubuntu my app crashed with that Error at first post
and i fixed them by editing encode.js:51 func
now its work without the fix !

@henr-y can you tell if you have the same problem before?

**Comment by henr-y** [comment]
oh sry forgot to answer. I got the issue on both windows 10 (latest node 4) and ubuntu 15.1 (latest node 5). Tried to reproduce it too, only happend in a project i'm working on (https://github.com/explodingcamera/padplus/blob/master/src/bundle/changeHtml.js) and not when i tried to reproduce it. https://imgur.com/Oiqhr9b (as a work around i just copy a fixed encode.js to node_modules/dom-serializer/node_modules/entities)

**Comment by dleeq8** [comment]
@henr-y thank you .. now i am sure about it 
.. and like i say before it seems a problem with one of plugins Cheerio used
called "entities"
https://github.com/fb55/entities
https://github.com/fb55/entities/blob/master/lib/encode.js#L57 (last update 2 years ago)

hope cheerio team have a look at this ..

**Comment by henr-y** [comment]
I changed some stuff in my code and somehow everything works fine now, i only get the error when i call $.html(); directly after i loaded the html

**Comment by gahabeen** [comment]
This seems somehow linked to my issue #970

**Comment by rimmer** [comment]
This shall be retested in 1.0.0-rc.2.
I have had simmilar issue, then I tried with 1.0.0-rc.2 and it helped.
