### ISSUE TITLE
`.html` behave different from `.text`

### ISSUE THREAD

**Issue by ufo22940268** [cheeriojs/cheerio#793]
var page = $('body > section > div.leftWrap > article').children('.item-box');
      //the page.length is 2
     
     //code 1
    page.html()

    // code2
    page.text()

`code 1` will only return the first element, but `code 2` will return the result of join the two elements.

**Comment by kfranqueiro** [comment]
What you're describing sounds consistent with jQuery's documentation of those two functions, so I would think it is intended.

> .html()
> Get the HTML contents of the first element in the set of matched elements

> .text()
> Get the combined text contents of each element in the set of matched elements, including their descendants

**Comment by fb55** [comment]
@kfranqueiro That's right, thanks :)
