### ISSUE TITLE
Release incorporating .wrap()

### ISSUE THREAD

**Issue by sehrgut** [cheeriojs/cheerio#794]
Since you said in #432 that there's no release schedule other than "by request", I'd love if you put out a release incorporating commit 7098ce3fd07c68d261806a0f6ed2cea0fe6db66f. I'm working on a project that uses Cheerio to correct improper tag nesting, and using a built-in `wrap()` would be simpler than my existing solution.

**Comment by MCTaylor17** [comment]
I second this motion.

**Comment by jpreynat** [comment]
:+1: for this.

**Comment by MCTaylor17** [comment]
Upon closer inspection, I realized what I actually want is the `.wrapAll()` method.  That said, I made a custom prototype for my needs: 

```
				$.prototype.wrapAll = function(wrapper){
					var $container = $(wrapper).clone();
					$(this).eq(0).before($container);
					
					for(var i in this) {
						var clone = $(this).eq(i).clone();
						$container.append($("<div>" + clone + "</div>").html());
						$(this).eq(i).remove();
					}
				};
```

**Comment by fb55** [comment]
Wrap was added a while ago.
