### ISSUE TITLE
innerText(),innerHtml

### ISSUE THREAD

**Issue by KevinZoro** [cheeriojs/cheerio#799]
I use cheerio to load this url:http://list.jd.com/list.html?cat=9987,653,655 ,and load it,but I didn't get what I need,see the code below
```
var $ = cheerio.load(body.toString());//body is response.body
$('.gl-item .p-price .J_price').each(function(){
	console.log('start p_price')
	var $me = $(this);
	console.log($me.html());// I got <em></em><i></i>,but lost the price
})
```
Then I find that maybe because the text inside ‘i’ label is innerText(),could I get the correct text by using cheerio?

**Comment by alanev** [comment]
The problem is that price is added width JS.

**Comment by alanev** [comment]
The problem is that price is added with JS.

**Comment by KevinZoro** [comment]
@alanev Thank u for your reply.I got it.
