### ISSUE TITLE
Is a upgrade to lodash 4 planned?

### ISSUE THREAD

**Issue by leifhanack** [cheeriojs/cheerio#800]
Hi there, 

is it planned to upgrade to lodash 4 in the near future?

Regards, Leif

**Comment by fb55** [comment]
AFAICT there doesn't seem do be a reason to make the switch immediately, but nothing should break & PRs are obviously welcome :)

**Comment by nathanmarks** [comment]
@fb55 I'm not super familiar with cheerio and was just checking out the issues here, but here's the v4 compatibility warnings if you want to have a gander: https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

**Comment by leifhanack** [comment]
I forked cheerio and tried the upgrade. Currently I encountered one problem with building up the instance. The`_.forEach` in `cheerio.js` line 47 did not work any longer, so that `elem` is not added to `this`. Maybe tonight I could take another look.

```
  // $([dom]) 
  if (Array.isArray(selector)) {
    _.forEach(selector, function(elem, idx) {
      this[idx] = elem; 
    }, this);
    // unfortunately `this` did not contain `elem` at `idx` even the selector is an array 
    this.length = selector.length;
    return this;
  }
```

**Comment by nathanmarks** [comment]
@leifhanack lodash 4 removed those scope binding args IIRC.

The solution in es5 is to bind the function or use `var self = this;` to keep scope
```
_.forEach(selector, (function(elem, idx) {
  this[idx] = elem; 
}).bind(this));
```

**Comment by leifhanack** [comment]
Thanks @nathanmarks. I'm not very familiar with JavaScript tooling, how do I see which JavaScript cheerio is using?

**Comment by nathanmarks** [comment]
Cheerio is es5 -- I was just making a reference to part of the justification for removing that feature in lodash 4.

**Comment by fb55** [comment]
@leifhanack In this case, dropping lodash for a `selector.forEach` is probably the easier fix (the native `forEach` still accepts the `this`-value as a third argument). Awesome that you're looking into it :)

**Comment by leifhanack** [comment]
My PR is #808 so that I close this issue. Thanks for your help, Regards, Leif
