### ISSUE TITLE
quick question - export Cheerio object as global variable for use with server-side WebWorkers

### ISSUE THREAD

**Issue by ORESoftware** [cheeriojs/cheerio#802]
I'd like to use Node WebWorkers ( a misnomer, I know) with Cheerio

https://www.npmjs.com/package/webworker-threads

WebWorkers use importScripts, and I don't believe importScripts work with modules that don't export a global variable...

Does this library export a global variable and do you know if it will work with WebWorkers?

Thanks!

**Comment by fb55** [comment]
`module.exports` is set. Still, cheerio uses `require` to import modules – if that isn't supported, then you'll need to run browserify on your code. In any case, simply `require` cheerio in your script, it shouldn't make a difference.
