### ISSUE TITLE
How to automatically ignore mismatch/unclosed tags?

### ISSUE THREAD

**Issue by mike442144** [cheeriojs/cheerio#803]
As the title says. I have a html document like

    <div> <span> bbc </span> </span> <span> abc </span> <span>hhhh</span></div>

and I want to remove `</span>` to get:

    <div> <span> bbc </span> <span> abc </span> <span>hhhh</span></div>

I try to load the document in chrome and chrome remove the tag automatically and display without errors, but when I load in `cheerio`, I got:

    <div><span>bbc</span></div>

All nodes after the first `span` are not in the `div` tag.

Anybody know how to deal with this problem? 
thanks a lot.

**Comment by stevezau** [comment]
How did you fix this?

**Comment by mike442144** [comment]
In my case, it turned out a bug of the page and I skipped this kind of page
