### ISSUE TITLE
Support for partial attributes?

### ISSUE THREAD

**Issue by hristod** [cheeriojs/cheerio#811]
I have tried using partial attribute selector, but it doesn't work... Here is a snippet from my code that uses it:
`$('div[class^=nav], div[class$=nav], div[class*=navigation]')`
Am I missing something, or is this not supported?

Thanks!

**Comment by alanev** [comment]
Try to use this:
`$('div[class^="nav"][class$="nav"][class*="navigation"]')`

**Comment by hristod** [comment]
Just tried it, it doesn't work. I ended up using a filter like so:

`  $('div').filter(function(index, el) {
    var classes = $(this).attr('class');
    var id = $(this).attr('id');

    if(classes) {
      return classes.search('nav') > -1;
    } else if(id) {
      return id.search('nav') > -1;
    }

    return false;
  }).remove();
`

This works but is much more code, and only on divs :(

**Comment by alanev** [comment]
For such filtering you can use this code:
```js
$('div[class*="nav"], div[id*="nav"]).remove()
```

**Comment by hristod** [comment]
Tried it, but it didn't work.

**Comment by alanev** [comment]
Please, show your html code.

**Comment by hristod** [comment]
I am so sorry, just found my mistake! It's all good! Again, sorry for the bother!

**Comment by hristod** [comment]
I am using it on a scraper. The page I am using for test is: http://aztekmarbella.com/about-us/

The code that I am using to filter out the navigation is:
`  $('div[class^="nav"], div[class$="nav"], div[class*="navigation"]').remove();`

and the target div is with a class of "main-nav visible-desktop", so it should be filtered by the second rule...

**Comment by alanev** [comment]
You should use `$('div[class*="nav "]')` to filter class "main-nav visible-desktop"

**Comment by hristod** [comment]
The thing is that I'd like to filter any elements that have a class which begins with "nav", ends with "nav" or includes "navigation" somewhere in the classname. It should work on:
mainnav, nav-main, main-navigation, navigation, nav, etc. If I have to also include the spaces, this would be a nightmare and I will be better off writing filter functions ...

**Comment by fb55** [comment]
@hristod `[class^=foo]` means *has a class __attribute__ starting with `foo`*. You could use something like `:matches([class*=" nav"], [class^=nav])` instead, plus variants for all the other whitespace you want to support.
