### ISSUE TITLE
<figure>

### ISSUE THREAD

**Issue by the1mills** [cheeriojs/cheerio#815]
For some reason, Cheerio doesn't seem to be picking up the`<img>` tag which is inside`<span>` inside `<figure>` is there a good reason for that?

![image](https://cloud.githubusercontent.com/assets/2148448/12868703/ace93fba-ccc0-11e5-98e2-ec6697d7fb35.png)

I am just using this to get the image tags

``` js
            var $ = cheerio.load(body);

            $('img').filter(function () { }
```

maybe that is wrong / incomplete

thanks

**Comment by zapplebee** [comment]
The images are dynamically created. Look at the source.
```html
<div class="js-delayed-image-load" data-alt="Rescuers search the collapsed building in Tainan, Taiwan, on 6 February 2016" data-src="http://ichef-1.bbci.co.uk/news/320/cpsprodpb/098B/production/_88134420_11e807ca-5aa9-4d5d-a048-abfd502dea0a.jpg" data-width="976" data-height="549"></div>
```

This is a not an issue with cheerio.
