### ISSUE TITLE
Cheerio performance issue with 0.20.0

### ISSUE THREAD

**Issue by toddbluhm** [cheeriojs/cheerio#819]
Not really sure what to say or how to to prove this, but I was recently upgrading a project to Node 5.6 and  part of that was also upgrading to cheerio 0.20.0. We have a bunch of test cases that call methods that use cheerio in them (simple cheerio usage like `$('img')` to find all image tags and loop through them to get a specific image tag) and when I ran our test cases the cheerio tests cases took an enormously long time to complete (like 90% of them failed with timeouts). At first I thought maybe our code was not optimized so I changed it and optimized it to use `.each` for the loops, etc... Anyways that did not work. So I reverted to cheerio 0.19.0 and suddenly everything was working fast and great again.

So I have no idea what changed between cheerio 0.19.0 and 0.20.0, but it was causing a massive performance decrease when using Node 5.6. Just thought I would give a heads up to a problem I was having with 0.20.0.

**Comment by fb55** [comment]
Some slowdown could be expected, but nothing immediately noticeable. Could you try reverting 47797621503919cbebe5874f9713ebc0c7c800f8?

**Comment by toddbluhm** [comment]
Okay so this is a bit frustrating. I can get this to be reproducible by doing just an `npm install cheerio@latest` using node 5.6 and npm 3.6, but when I do an npm link, there is no performance issues anymore and it all just works fine with the latest master branch. I tried updating to the latest npm 3.7.x thinking maybe it as an npm issue, but same problem still happens.

The cheerio test cases seem to work well on Node 5 and npm 3.6.

Maybe something got messed up with the latest push to npm?

Not sure what else to try really at this point?! Very weird issue...
