### ISSUE TITLE
Provide alternative set of API that would use cheerio wrapped nodes in iteration

### ISSUE THREAD

**Issue by gajus** [cheeriojs/cheerio#821]
Example:

> ### .each( function(index, element) )
> 
> Iterates over a cheerio object, executing a function for each matched element. When the callback is fired, the function is fired in the context of the DOM element, so this refers to the current element, which is equivalent to the function parameter element. To break > out of the each loop early, return with false.
> 
> ``` js
> var fruits = [];
> 
> $('li').each(function(i, elem) {
>   fruits[i] = $(this).text();
> });
> 
> fruits.join(', ');
> //=> Apple, Orange, Pear
> ```

https://github.com/cheeriojs/cheerio#each-functionindex-element-

There is hardly ever a need to access either DOM element or index. A less verbose API therefore would be:

``` js
var fruits = [];

$('li').each(function(cheerioElement, index) {
  fruits[i] = cheerioElement.text();
});

fruits.join(', ');
//=> Apple, Orange, Pear
```

I understand there might be a use case for wanting to access the DOM node too. But that is possible simply using `cheerioElement[0]`.

This API could be an opt-in feature.

**Comment by fb55** [comment]
Assuming `map` works here, closing.
