### ISSUE TITLE
Keep line-indentation on node.replaceWith()

### ISSUE THREAD

**Issue by F1LT3R** [cheeriojs/cheerio#822]
It would be nice to have the node.replaceWith() maintain indentation in the exported node.html() rendering.

For example, lets suppose we are replacing a Comment Node:

``` html
<body>
<section>
    <!-- This Comment Will Be Replaced -->
</section>
</body>
```

We will replace the comment with:

``` html
<div class="includedFile">
    <p>This line and the next should share the indentation with the line above.</p>
</div>
```

When running:

``` javascript
$(commentNode).replaceWith(includeFileContents);
```

I would expect to see this:

``` html
<body>
<section>
    <div class="includedFile">
        <p>This line and the next should share the indentation with the line above.</p>
    </div>
</section>
</body>
```

Except, I see this: :sob: 

``` html
<body>
<section>
    <div class="includedFile">
    <p>This line and the next should share the indentation with the line above.</p>
</div>
</section>
</body>
```

I could use a beautifier, but that would destroy places where I _do not_ want code indented. Ie: I don't want the `<section>` to be indented from the `<body>` in this example. It would be preferable to have a block inserted at the correct indentation automatically if specified, eg:

``` javascript
$(node).replaceWith(includeFileContents, {matchIndent: true});
```

Alternatively it a workaround would be to be able to get the indentation of the node, like so:

``` javascript
$(node).getIndentation();
// { tabs: 2 }
```

I know it's a giant mess of a request, people may mix tabs and spaces, maybe this request should be for the underlying [htmlparser2](https://github.com/fb55/htmlparser2/), etc, but I'll ask anyway and get your thoughts :)

**Comment by fb55** [comment]
Unfortunately seems like too much of an edge-case. Hope you've found an alternative!
