### ISSUE TITLE
Implement a separator option between each tag for the text getter 

### ISSUE THREAD

**Issue by arnaudbesnier** [cheeriojs/cheerio#835]
It would be great if we could have an option to separate the text content of tags.

Here is an example:
```
<div id='content'>
  <p>foo</p>
  <p>bar</p>
</div>
```
The current behavior is:
```
$('#content').text() // returns "foobar"
```

This option could be great:
```
$('#content').text({ separator: '-' }) // would return "foo-bar"
```

Maybe there is such an option but I did not find anything like that.

Thank you for this great tool!

**Comment by jugglinmike** [comment]
Our goal with this project is API-parity with jQuery, so it's unlikely that we will implement additional functionality like this.

In this case, you can achieve your goal by reducing the text contents of children of the `#content` element and inserting a separator of your choosing.
