### ISSUE TITLE
Cheerio adding double quotes to user defined attributes

### ISSUE THREAD

**Issue by AdityaJitu** [cheeriojs/cheerio#838]
Hi,

When I run 
var test = $.load(`'<div anyattribute></div>'`);
it ruturns 
**`'<div anyattribute=""></div>'`**

I am not able to understand the reason behind the **extra double quotes**.

Do we need to pass any flag to prevent this type of behavior?

i.e. var test = $.load(`'<div anyattribute></div>'`);
should return **`<div anyattribute></div>`**

**Note:- I am getting this type of output only for user defined attributes**
Awaiting your reply please.

**Comment by timaschew** [comment]
any feedback @matthewmueller ?
