### ISSUE TITLE
text() preserve line breaks

### ISSUE THREAD

**Issue by loretoparisi** [cheeriojs/cheerio#839]
I need to access innerHTML and preserve line breaks, so where is like `<br>`.
In jQuery a solution could be this one

``` javascript
(function($){
   $.fn.innerText = function(msg) {
         if (msg) {
            if (document.body.innerText) {
               for (var i in this) {
                  this[i].innerText = msg;
               }
            } else {
               for (var i in this) {
                  this[i].innerHTML.replace(/&amp;lt;br&amp;gt;/gi,"n").replace(/(&amp;lt;([^&amp;gt;]+)&amp;gt;)/gi, "");
               }
            }
            return this;
         } else {
            if (document.body.innerText) {
               return this[0].innerText;
            } else {
               return this[0].innerHTML.replace(/&amp;lt;br&amp;gt;/gi,"n").replace(/(&amp;lt;([^&amp;gt;]+)&amp;gt;)/gi, "");
            }
         }
   };
})(jQuery);
```

so that you can easily use `innerText()` function like

``` javascript
 $(this).find('a').each(function(index,item) {
      console.log( $(this).innerText() )
   })
```

But how to do this in `cheerio`?

**Comment by loretoparisi** [comment]
Another solution that I have found is this:

```javascript
function htmlDecodeWithLineBreaks(html) {
  var breakToken = '_______break_______',
      lineBreakedHtml = html.replace(/<br\s?\/?>/gi, breakToken).replace(/<p\.*?>(.*?)<\/p>/gi, breakToken + '$1' + breakToken);
  return $('<div>').html(lineBreakedHtml).text().replace(new RegExp(breakToken, 'g'), '\n');
}
```

**Comment by lucaswxp** [comment]
+1

@loretoparisi Your solution didnt work for my html, this is what I came up with:

```javascript
var he = require('he'); // he for decoding html entities
var myhtml = $('#description').html().replace(/<(?:.|\n)*?>/gm, '\n') // remove all html tags
var mytext = he.decode(myhtml)
console.loh(mytext)
```

**Comment by thealexbaron** [comment]
+1

**Comment by aysark** [comment]
Would like to see this supported to.  For now, i'm using html-to-text package.

**Comment by Dublerq** [comment]
Why not just add a peserve text breaks option in `text()` method?

**Comment by fb55** [comment]
html-to-text is definitely a solution for this right now. This would also be a candidate for a major release. Only taking care of `<br>`s and `<p>`s should take us most of the way there.

**Comment by msikma** [comment]
I'm not sure if this workaround is good enough for your purposes, but I needed to quickly fetch some text from an HTML document with `<br>` converted to linebreaks. I ended up doing this:

    $('.cc-newsbody').find('br').replaceWith('\n')
    const text = $('.cc-newsbody').text() // can't chain

Turns `<br>` into linebreaks, converts everything else into plain text.

**Comment by EvanCarroll** [comment]
I have two ideas to fix this, we could either.

1. Implement a `.text(fn)` where fn is a map function that takes html and pre-processes it before passing it on to the normal routine.
2. Implement a `.textWith(fn)` along the same lines. The only real advantage to this is `.text()` is less voody and doesn't have to type-test its argument.

Neither of these requiring mucking with the entire HTML, nor breaking `.text()` as it currently sits.

**Comment by fb55** [comment]
This unfortunately won't be implemented, as it diverges from browsers.

**Comment by issuefiler** [comment]
Use `.end()` to chain them. It moves the cursor back to the previous selection.

```javascript
$(".test").find("br").replaceWith("\n").end().text()
```
