### ISSUE TITLE
Error: Cannot find module 'util' - require("cheerio") in phantomjs

### ISSUE THREAD

**Issue by loretoparisi** [cheeriojs/cheerio#841]
I get this error trying to run `cheerio` as module in a phantomjs script

``` shell
Error: Cannot find module 'util'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /node/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:120
  /node/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:351
TypeError: 'undefined' is not a function (evaluating 'ext[key].bind(DomUtils)')

  /node/node_modules/cheerio/node_modules/css-select/node_modules/domutils/index.js:12
TypeError: 'undefined' is not a function (evaluating 'ext[key].bind(DomUtils)')

  /node/node_modules/cheerio/node_modules/htmlparser2/node_modules/domutils/index.js:12
'waitFor()' finished in 579ms.
```

**Comment by jflayhart** [comment]
I get the same for `Module not found: Error: Cannot resolve 'file' or 'directory' ./package in /Users/joshflayhart/Documents/Development/crunch/HPM-554/node_modules/cheerio` I don't know how to help fix this or I would.

**Comment by MichaelTSS** [comment]
+1

**Comment by stinghz** [comment]
+1

**Comment by stinghz** [comment]
After manually add util and events module by :   
npm install --save util
npm install --save events


I get:
   phantomjs://platform/Parser.js:121
TypeError: undefined is not a constructor (evaluating 'require("util").inherits(Parser, require("events").EventEmitter)')

**Comment by stinghz** [comment]
using browserified cheerio solved the problem.

**Comment by loretoparisi** [comment]
@stinghz so did you run something like `browserify index.js -o dist/cheerio-bundle.js`? Or you needed to expose the module with the `--s moduleName` option?

**Comment by stinghz** [comment]
try download this 
https://wzrd.in/standalone/cheerio@latest

it worked for me.

**Comment by fernandoPalaciosGit** [comment]
I think the problem is the scope from bundles that do not expose module.exports on shrinkwrap dependencies, the fact changing domutils/index.js on "htmlparser2" and "css-select" works:

```javascript
[
    require("./lib/stringify"),
    require("./lib/traversal"),
    require("./lib/manipulation"),
    require("./lib/querying"),
    require("./lib/legacy"),
    require("./lib/helpers")
].forEach(function (ext) {
    Object.keys(ext).forEach(function (key) {
        module.exports[key] = ext[key];
    });
});
```
