### ISSUE TITLE
Escaped Character

### ISSUE THREAD

**Issue by JustinSeidl** [cheeriojs/cheerio#852]
I'm trying to prepend an element with a string as follows:

`$('body').prepend('{{> content}}');`

but when I do this it is encoding the > into `&gt;`

`{{&gt; content}}`

How do I prevent Cheerio from doing this?

**Comment by alanev** [comment]
Try do work just string, like this:
```js
var body = $('body');
body.html('{{> content}}' +  body.html());
```

**Comment by JustinSeidl** [comment]
@alanev that produces the same result... as noted above

**Comment by fb55** [comment]
You can disable entity en- and decoding by setting the `decodeEntities` option to `false`.
