### ISSUE TITLE
.serializeArray() for inputs contained in sub-elements (<td>, <div>, ...) of the form

### ISSUE THREAD

**Issue by patrickjane** [cheeriojs/cheerio#858]
I am loading a website wich contains a form like this:

```
<form action="/path" accept-charset="UTF-8" method="post">
   <input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="somevalue" />
   <fieldset>
      <div class='formrow'>
         <label for='email'>
         E-Mail
         </label>
         <input type="text" name="email" id="email" class="input" />
      </div>
      <div class='formrow'>
         <label for='password'>
         Passwort
         </label>
         <input type="password" name="password" id="password" class="input" />
      </div>
      <div class='formrow button'>
         <button class="button next upc_button2" id="commit" name="commit" type="submit"><span>Login</span></button>
      </div>
   </fieldset>
</form>
```

$('form').serializeArray() will give me:

> [ { name: 'utf8', value: '✓' },
>   { name: 'authenticity_token', value: 'somevalue } ]

As you can see, the input's which are "hidden" in sub-elements (fieldset/div) are not captured.

Is there a way I can get them within the .serializeArray(), or do I have to extract those myself?

**Comment by twang2218** [comment]
`serializeArray()` will include sub-elements `<input>`, except the `<input>` is `disabled` or a `button`. I just realize the `disabled` `<input>` will not be included.

**Comment by fb55** [comment]
The output for the example above is now identical to jQuery. Assuming this has been resolved.
