### ISSUE TITLE
Auto adds the end tags

### ISSUE THREAD

**Issue by kapilgarg1996** [cheeriojs/cheerio#859]
When i select an elements html using `.html()` function then it automatically adds the end tags in the html if there is missing. For example, if i have `<ul><li><code></li></ul>` and i select `li` html by `$('li').html()` then it will return me `<code></code>`. I think it should be good in case you have forgotten the end tags but in my case i don't want this behaviour.
Is there some tweak which can help me avoid this ?

**Comment by fb55** [comment]
Short (and late) answer: There isn't.
