### ISSUE TITLE
Keeps line and indentation on remove()

### ISSUE THREAD

**Issue by sindresorhus** [cheeriojs/cheerio#86]
When I remove an indented element that makes up the whole line it preserves the line and the indentation. This makes a document with many remove() look dirty, since it's filled with indented whitespace on empty lines.

``` html
    <span>lorem ipsum</span>
```

It should IMO remove the line if all the contents is gone.

**Comment by hanjo** [comment]
While this is quite an old issue, I just came across this facing the same situation. Beautification is obviously a possible way, but I didn't like the overhead, so I came up with the following solution, which is removing empty (whitespace only) lines. It is doing so by iterating over all nodes, selecting the text nodes and removing it if it only contains white spaces. Maybe it is helpful to anybody else:
```javascript
$("something").contents().filter(function() {
	var ns = this.nextSibling;
	if(ns != null) {
		return this.nodeType === 3 && ns.nodeType === 3 && /^\s+$/.test(this.nodeValue); // Node.TEXT_NODE
	}
	return false;
}).remove();
```
