### ISSUE TITLE
Greater than followed by equal sign is lost

### ISSUE THREAD

**Issue by godely** [cheeriojs/cheerio#860]
$.load('<=').html()
returns empty, instead of '<='

Now, this is important to me because I'm parsing html which can express "_A_ <= _B_" (A less or equal than B) as:
`<i>A</i><=<i>B</i>`

`$.load('<i>A</i><=<i>B</i>') == '<i>A</i><=<i>B</=<i>'`

This issue [#103](https://github.com/cheeriojs/cheerio/issues/103) had been issued for only greater sign. Can this be fixed too?

**Comment by AlynxZhou** [comment]
Why don't you escape `<=` into `&lt;=` by yourself? I think `&lt;` is better is this way instead of expecting parser to backtrack.

**Comment by fb55** [comment]
Fixed by #985
