### ISSUE TITLE
Update engine minimum to allow lodash removal

### ISSUE THREAD

**Issue by jsumners** [cheeriojs/cheerio#862]
Currently, cheerio's package.json says it works with node.js 0.6 and later:

1. 0.6 is long unsupported
2. 0.10 and 0.12 will be unsupported in a few short months -- https://github.com/nodejs/LTS#lts_schedule

If the supported engines were updated to `>= 4.0.0` then there is nothing in the code base, that I have seen in a cursory read, that depends on lodash that is not achievable with native JavaScript. Fewer dependencies, and native code, is a good thing.

**Comment by sotojuan** [comment]
Agreed—lodash makes up a big part of cheerio's filesize.

An alternative is to install the lodash functions from npm individually since cheerio only uses a few.

Would be more than happy to do a pull request for this.

**Comment by fb55** [comment]
Regarding newer node versions: node 0.6 already has array extras that could be used for the functionality, but lodash is simply faster, as it ignores eg. sparse arrays.

@sotojuan A PR would be great :)

**Comment by fb55** [comment]
Should be fixed with #864
