### ISSUE TITLE
Selector not building over context's selector when starting with operator

### ISSUE THREAD

**Issue by aaalsaleh** [cheeriojs/cheerio#867]
Take this simple example:

``` javascript
var $ = cheerio.load('<p>hello</p><p>cheerio</p>');
var firstP = $('p');
var nextP = $('+ p', firstP);
console.log(nextP.text());
```

The expected output according to jQuery is `cheerio`, but instead it is empty (no match) with Cheerio. Notice `nextP` selector using `firstP` as a context, and `nextP` selector building over `firstP` selector by starting with an operator (e.g. `+`, `~`, `>`).
While what I am trying above can be achieved by other means, there are other more complex scenarios where it is impossible to achieve things without it, not to mention that it is part of jQuery selector syntax.

**Comment by Delgan** [comment]
I am not sure this is related neither to context's selector nor to starting with an operator.

The following code seems to fail too:
```javascript
var $ = cheerio.load('<p>hello</p><p>cheerio</p>');
var p = $('p + p');
console.log(p.text());
```

But this one works as expected:
```javascript
var $ = cheerio.load('<div><p>hello</p><p>cheerio</p></div>');
var p = $('p + p');
console.log(p.text());
```

It appears it is more likely related to the selector being applied on a root object.

**Comment by aaalsaleh** [comment]
Not totally correct. The HTML example I used was a quick and random one. What you mentioned could be another factor (or a new issue altogether). The issue I mentioned is still to do with not supporting selectors starting with the operators `+`, `>`, and `~` in a context-based selection.

The issue is still there for this:
```javascript
var $ = cheerio.load('<div><p>hello</p><p>cheerio</p></div>');
var firstP = $('p');
var nextP = $('+ p', firstP);
console.log(nextP.text());
```
and even this:
```javascript
var $ = cheerio.load('<html><head></head><body><p>hello</p><p>cheerio</p></body></html>');
var firstP = $('p');
var nextP = $('+ p', firstP);
console.log(nextP.text());
```
I think it is a problem with the selector engine `css-select` not handling such case.

**Comment by fb55** [comment]
Fixed in css-select, will come to cheerio in the next release.
