### ISSUE TITLE
release 0.21.0 - Error: Cannot find module 'cheerio'

### ISSUE THREAD

**Issue by albertosantini** [cheeriojs/cheerio#872]
Requiring the module gives the error in the subject.

It seems there is not `index.js` in `node_modules/cheerio`.

**Comment by aivus** [comment]
Have the same issue

**Comment by RSPaul** [comment]
I have the same issue.

**Comment by madurmanov** [comment]
I have too.

**Comment by mikowiec** [comment]
+ issue

**Comment by fibo** [comment]
I also found this issue, I downgraded to 0.20 and it is ok there.

```bash
$ npm install cheerio
$ ls node_modules/cheerio/
History.md  lib  package.json  Readme.md
```

**Comment by wavelynn** [comment]
同样也遇到这个问题

后来看了一下npm install之后的目录以及package.json，其中指定的main文件为当前目录下的./index.js文件，但是当前目录下没有这个文件

解决方法：直接把git上的index.js文件拷贝一份即可解决

**Comment by krazyjakee** [comment]
the testing is strong with this one

**Comment by wyosean** [comment]
Oh，no index.js  ！！

**Comment by ewdave** [comment]
Same "Error" issue, downgrading may do for now

**Comment by mrjj** [comment]
Please, roll back the release.
It will be very nice to have release branches or tags to which developers could pin their requirements.

P.S. Thank you for the great work!

**Comment by ewdave** [comment]
seems branch with the issue's been deleted. Now back to Master

**Comment by clementallen** [comment]
The `0.21.0` release has been rolled back

**Comment by jakub-g** [comment]
@clementallen what do you mean with `The 0.21.0 release has been rolled back`?

When I do `npm show cheerio` it shows 0.21.0 as the latest release.

I think you should try to `npm unpublish` it (though I don't know if with recent changes to npm it's possible anymore), or `npm publish` a patch if possible

Thanks

**Comment by clementallen** [comment]
@jakub-g I'm not the dealer, just a user :)

When running `npm show cheerio` I get v0.20.0 which ties into the version listed on the [npm website](https://www.npmjs.com/package/cheerio) and the latest release in the [github repo](https://github.com/cheeriojs/cheerio/releases) so it very much appears that the buggy 0.21.0 has been rolled back.

**Comment by abhinavsingi** [comment]
@jakub-g @jakub-g  : Getting the same error, everytime I install `gulp-cheerio` it fetches the latest version of `cheerio` i.e. `0.21.0` instead of `0.20` Any help appreciated!

**Comment by jakub-g** [comment]
Turns out the issue was due to us having private npm instance (sinopia), I had to `npm unpublish cheerio@0.21.0` and `npm cache clean`

**Comment by abhinavsingi** [comment]
Yes this is what we figured and did, works like a charm :)

**Comment by dkadrioski13** [comment]
0.21.0 is missing ./index.js

**Comment by fb55** [comment]
Sorry for this everybody. I still haven't figured out why npm doesn't include the `index.js` file anymore in bundles, it is weird at least. I've unpublished `0.21.0` and will publish `0.21.1` as soon as I can get a complete package.

**Comment by albertosantini** [comment]
@fb55 see https://github.com/npm/npm/issues/5082

As workaround It seems it is highly recommend using Node.js 4 LTS to publish a package: https://github.com/npm/npm/issues/5082#issuecomment-220172560

**Comment by brandonwellsmmf** [comment]
this is still happening for me, i've tried rolling back without luck.  any advice?

**Comment by ewdave** [comment]
@brandonwellsmmf  you should use `npm install cheerio@0.20.0`

you can also use it with the `--save` flag to add it your package,json file -- `npm install cheerio@0.20.0`

**Comment by matthewmueller** [comment]
sorry for the headache, `0.22.0` is out now 🎉

**Comment by JamesRamm** [comment]
Still getting this issue with v1.0.0-rc.3:

```
~/>npm i -g cheerio
+ cheerio@1.0.0-rc.3
added 19 packages from 51 contributors in 11.371s

~/>node
Welcome to Node.js v12.14.1.
Type ".help" for more information.
> const cheerio = require('cheerio')
Thrown:
Error: Cannot find module 'cheerio'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
>
```

**Comment by tarateo78** [comment]
On my local machine Works fine... bat on heroku server... problem!
cheerio v.1.0.0-rc-3

```
 Error: Cannot find module 'cheerio'
 Require stack:
 - /app/connect.js
 - /app/controllers/todo.js
 - /app/index.js
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
     at Module.require (internal/modules/cjs/loader.js:1044:19)
     at require (internal/modules/cjs/helpers.js:77:18)
     at Object.<anonymous> (/app/connect.js:4:17)
     at Module._compile (internal/modules/cjs/loader.js:1158:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
     at Module.load (internal/modules/cjs/loader.js:1002:32)
     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
     at Module.require (internal/modules/cjs/loader.js:1044:19) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [ '/app/connect.js', '/app/controllers/todo.js', '/app/index.js' ]
 }

```
Thanks
