### ISSUE TITLE
[cheerio@0.20.0 ] it has problem when renaming img attribute src to alt_src 

### ISSUE THREAD

**Issue by chadlwm** [cheeriojs/cheerio#873]
I wants to rename the image attribute `src` to `alt_src`, for lazying load the image.
I add a attribute `alt_src`, then remove `src`, but it not works.

my code written as following:

``` javascript
- var cheerio = require('cheerio')
- var dom = cheerio.load(post.content);
each img in dom("img")
    - var url = dom(img).attr("src");
    - dom(img).removeAttr("src");
    - dom(img).attr("alt_src", url);
```

howerver, the result not like what i wanted:

``` html
<img alt="test.png" data-img-size-val="819,725" width="1311" 
alt_src="http://pic2.36krcnd.com/nil_class/14a48130-1cdc-428a-88e9-e4dcb7073330/____meitu_0.jpg!heading" 
src="http://pic2.36krcnd.com/nil_class/14a48130-1cdc-428a-88e9-e4dcb7073330/____meitu_0.jpg!heading">
```

it has both attributes `src` and `alt_src`.

when I change the `alt_src` to `alt-src`, `altsrc` or anything else, it works fine.

ps: the `alt-src` is  mandatory requirement attribute, I cannot chang it.

**Comment by fb55** [comment]
Unfortunately I'm unable to replicate this. I assume this has been resolved.
