### ISSUE TITLE
Add .ignore() traversal method.

### ISSUE THREAD

**Issue by djizco** [cheeriojs/cheerio#876]
I woud like to add a method for traversing to ignore the contents of a tag. Basically this function to the repo. http://stackoverflow.com/questions/11347779/jquery-exclude-children-from-text.  I have tested the code and it works.

**Comment by jugglinmike** [comment]
The goal of this project is API parity with jQuery, so methods not defined by that library are strictly out-of-scope. The good news is that, just like jQuery, Cheerio supports extensions, so it is safe to use the code you have submitted in gh-877 in your personal projects without explicit inclusion in Cheerio.
