### ISSUE TITLE
$.tidy() method missing docs

### ISSUE THREAD

**Issue by sindresorhus** [cheeriojs/cheerio#88]
[$tidy()](https://github.com/MatthewMueller/cheerio/blob/master/lib/api/manipulation.js#L177-179) method is missing docs.

What does it actually do? I ran it through some HTML and didn't really notice any difference.

It was added in ffb6f23cf9a482372c3f72e41f55ef621c2601c2

**Comment by coderingo** [comment]
Hi all, I don't wanna re-open the issue but I am getting this page again and again when searching for html standardizer/formatter along with cheerio. I found a package on npm which is inactive but can do the job. Maybe someone can use it , here is the link https://www.npmjs.com/package/htmltidy2

And its not mine :)
