### ISSUE TITLE
 error of self-closing tag

### ISSUE THREAD

**Issue by akuma** [cheeriojs/cheerio#885]
The test code:

```js
console.log(cheerio.load('<p>foo</p><hr><p>bar</p>', { xmlMode: true }).html())
```

The expect output:

```html
<p>foo</p><hr /><p>bar</p>
```

The actual output:

```html
<p>foo</p><hr><p>bar</p></hr>
```

Is this a bug or did I miss some options?

**Comment by fb55** [comment]
Self-closing tags aren't supported in HTML5. You can explicitly enable that functionality, have a look at the parser options in the README.

**Comment by akuma** [comment]
@fb55 , thank you.

```js
console.log(cheerio.load('<p>foo</p><hr><p>bar</p>').xml())
```

This code output the expect result:

```html
<p>foo</p><hr/><p>bar</p>
```
