### ISSUE TITLE
Security issue with text()?

### ISSUE THREAD

**Issue by ile** [cheeriojs/cheerio#886]
Does this seem like a security issue?

```
> c = require('cheerio');
> $ = c.load('<p>Hi ... &lt;script&gt;alert("hi"); &lt;/script&gt;</p>');
{ [Function]
  _root: 
   { type: 'root',
     name: 'root',
     parent: null,
     prev: null,
     next: null,
     children: [ [Object] ] } }
> $.root().text()
'Hi ... <script>alert("hi"); </script>'
```

If I output this text into the browser as it is now, unescaped, it will pop up an alert box, thus being html code in reality. Right?

**Comment by fb55** [comment]
Certainly something to be aware of, but this is how `.text` is supposed to work. You should always escape content you don't control, and this is no exception.

**Comment by ile** [comment]
Are you sure? Why does it turn &lt; into <?

**Comment by fb55** [comment]
Because `&lt;` is not the text representation of the character (and `.innerHTML` behaves this way).
