### ISSUE TITLE
Not working with Facebook

### ISSUE THREAD

**Issue by akashnimare** [cheeriojs/cheerio#889]
I am trying to scrape some basic user data on facebook. Here is the code -

``` javascript
'use strict';
const cheerio = require('cheerio');
const request = require('request');
const url = 'https://facebook.com/meakaakka';
request(url, function (error, response, html) {
	if (!error) {
		var $ = cheerio.load(html);
		let othersPeople;
		othersPeople = $('h4[class=uiHeaderTitle]').html(); 
		console.log(othersPeople);
	}
});

```
It's returning null. I don't know where I am going wrong.

**Comment by fb55** [comment]
Facebook uses ajax. Cheerio doesn't execute JS, so this doesn't work. Have a look at jsdom and PhantomJS for complete browser environments.
