### ISSUE TITLE
Build issue with ./package vs ./package.json 

### ISSUE THREAD

**Issue by peris** [cheeriojs/cheerio#891]
Hi,

We are experiencing build issues with the latest release 0.20.0 and the cause seems to be in the index.js;

Current: exports.version = require('./package').version;
Updated(fixed):  exports.version = require('./package.json').version;

It appears the master has the correction and we are wondering if there will be a release soon with the updated index.js

Thanks

**Comment by fb55** [comment]
This was recently released.

**Comment by ljharb** [comment]
@peris why would this matter? `.json` is implicit in node's require algorithm. What build  tool are you using?

**Comment by StrikeForceZero** [comment]
after reading @ljharb comment it made me realize it was webpack failing to resolve `package.json` automatically given just `./package`. Tested it in a vanilla node script and it worked fine as suggested.

a workaround for anyone using webpack before you run your tests or anything that depends on cheerio you need to add the '.json' extension to the resolve.extensions property

```js
resolve: {
    extensions: [
      // extensions
      '.json',
    ],
  //...
}
```
