### ISSUE TITLE
How to get raw html without parsing

### ISSUE THREAD

**Issue by Hurtak** [cheeriojs/cheerio#893]
Is there a way to get raw HTML from node before it gets parsed?

## Code
```js
> var $ = require('cheerio')
undefined
> $('<xmp><h2></xmp>').html()
'<h2></h2>'
```

## Current output
```js
'<h2></h2>'
```

## Wanted output
```js
'<h2>'
```

Some kind of rawHtml instead of html method?

**Comment by Hurtak** [comment]
On second look it seems like a parser issue, content of `<xmp>` tag should not be parsed at all. Take a look at http://codepen.io/anon/pen/VjyNQN inside console
But this seems like separate issue, should I create one for this?

**Comment by fb55** [comment]
There is not.
