### ISSUE TITLE
Does cheerio not work with public Instagram profiles?

### ISSUE THREAD

**Issue by ErraticFox** [cheeriojs/cheerio#896]
I keep trying with Instagram profiles and seem to not be able to pull stuff (specifically post count, follower count, etc.). I thought it was me just doing it wrong, but I've been able to pull from other websites without fail.

**Comment by fb55** [comment]
I would assume that Instagram doesn't have a static website. Cheerio doesn't evaluate JS, have a look at jsdom and Phantomjs for that.
