### ISSUE TITLE
passing null to .html() should not throw 

### ISSUE THREAD

**Issue by dhendo** [cheeriojs/cheerio#897]
Currently if you pass null to html, it throws:

```
     TypeError: Cannot read property 'cheerio' of null
      at null.<anonymous> (lib/api/manipulation.js:378:22)
      at exports.domEach (lib/utils.js:52:24)
      at exports.html (lib/api/manipulation.js:373:3)
      at Context.<anonymous> (test/api/manipulation.js:1350:15)
```

I believe it should empty the element, as jQuery does. PR to follow.

**Comment by jugglinmike** [comment]
The reported behavior in jQuery is neither [documented](https://api.jquery.com/html/) nor [explicitly tested](https://github.com/jquery/jquery/blob/3e3b09d68d317a3fe567e377e9032319ac5e0829/test/unit/manipulation.js) by that project. That means this isn't the kind of incompatability we're generally concerned with. If anyone would like to work with the jQuery project to make this behavior part of their formal API, then please report back here once you're done.

For now, though, the best practice (in Cheerio or jQuery) would be to use [the `empty` method](https://api.jquery.com/empty/) for this case.

**Comment by dhendo** [comment]
@jugglinmike  Sure, but jQuery doesn't throw if it receives this input. Surely cheerio should handle it gracefully?
