### ISSUE TITLE
$(document).ready functionality?

### ISSUE THREAD

**Issue by fenchu** [cheeriojs/cheerio#899]
Hi
I need to scrape some pictures in a nodejs module from a large family fileshare, but Cheerio loads the $("#dlbutton").attr('href') as '#' which is the default value before the simple javascript is applied.
This is probably to prevent people from curl/wget it easily.

In Jquery using the $(document).ready function just before querying this works. But how do it do it with Cheerio?

Thanks for a fantastic product.

--
MortenB, Oslo Norway

```
<div style="margin-left: -22px; margin-top: -5px; text-align: center;width: 303px">
  <a id="dlbutton"  href="#">
    <div class="download"></div>
  </a>
  <script type="text/javascript">
    var n = 2;
    var b = 2345678;
    document.getElementById('dlbutton').href = "/d/frAlZpYl/"+(n + n * 2 + b)+"%20MOBJ%20NIKON%20NEF%20DATE/2016/03/02/18.NEF";
    </script>
</div>
```

**Comment by fb55** [comment]
Cheerio doesn't evaluate JS. Please refer to jsdom and PhantomJS.
