### ISSUE TITLE
Retrieving the element type

### ISSUE THREAD

**Issue by ghost** [cheeriojs/cheerio#903]
How do I retrieve the element type?

```
> var u = cheerio.load('<html class="xxx"/>', {xmlMode: true, decodeEntities: false, recognizeCDATA: true});
undefined
> u.name
''
```

Shouldn't name come back as "html"? I need to programmatically retrieve the element type.

**Comment by noder45** [comment]
I was being a moron. $('.xxx')[0].name

**Comment by fb55** [comment]
`.prop('tagName')` and '.attr('class')` might be nice to have here.
