### ISSUE TITLE
Direct Child after body

### ISSUE THREAD

**Issue by h3nn3** [cheeriojs/cheerio#905]
Hey guys it seems like cheerio has a problem to select an element direct after the body tag.
For example if i want to select var myDivs = $("body > div:not(:first-of-type)").

After that i would like to iterate through each of them. But if i use the > selector myDivs is null. if i dont use the > selector every div except the first would be selected.

Help pls

**Comment by seanmars** [comment]
have the same issue, please help to fix that.

Thanks.

**Comment by fb55** [comment]
I would assume that your document omits the `body` tag, which currently isn't inserted by cheerio's HTML parser.

**Comment by fb55** [comment]
Fixed by #985
