### ISSUE TITLE
Fails to parse datauris properly

### ISSUE THREAD

**Issue by manast** [cheeriojs/cheerio#907]
If you have an element like this:

``` html
<div style='font-family:"butcherman-caps"; src:url(data:font/opentype;base64,AAEA...);'></div>
```

Parsing this element with cheerio will not return a correct value for the css property `src`:

```
$('div').css('src') -> url(data:font/opentype
```

I assume the css parser believes that the ; after opentype signals the end of the style property. The parser will need a special parser for handling datauris.

**Comment by fb55** [comment]
Closing in favour of #1134
