### ISSUE TITLE
General sibling selectors '~' not selecting element in 'doc' root

### ISSUE THREAD

**Issue by meeple142** [cheeriojs/cheerio#909]
First off not sure if this is cheerio's issue or css-select's issue but i'll start here.
Also it is similar to #890 
When I use `selector ~ selector` looking for root elements it does not find them. If they are deeper that root then they are found. An example follows.

With this html

``` html
<div>
    <p>in1</p>
    <p>in2</p>
</div>
<p>1</p>
<p>2</p>
```

and this code

``` javascript
var c = require('cheerio'),
    htmlText = "<div><p>in1</p><p>in2</p></div><p>1</p><p>2</p>",
    $ = c.load(htmlText);

console.log('1:', $.html($('p')));
console.log('2:', $.html($('p~p')));
console.log('3:', $.html($('div~p')));
```

 It finds all the paragraphs even the ones in the root with `p` selector but when I use `p~p` it only finds  `<p>in2</p>` in the `div` even though it should also find `<p>2</p>` in the root. Then I get nothing for `div~p` because all the matches are in the root.

This is the output:

```
1: <p>in1</p><p>in2</p><p>1</p><p>2</p>
2: <p>in2</p> 
3:
```

I think it should be:

```
1: <p>in1</p><p>in2</p><p>1</p><p>2</p>
2: <p>in2</p><p>2</p>
3: <p>1</p><p>2</p>
```

Thanks for such an awesome library! Its the perfect tool for many of my projects!

**Comment by fb55** [comment]
This should be fixed with the last release.
