### ISSUE TITLE
in php laravel blade have a little trouble

### ISSUE THREAD

**Issue by kyo4311** [cheeriojs/cheerio#914]
`var b = cheerio.load('<li @if($router_name=="index") class="curr" @endif><a href="/">home</a></li>');
console.log(b.html());`
=>
`<li @if($router_name="=&quot;index&quot;)" class="curr" @endif=""><a href="/">ho
me</a></li>`

**Comment by fb55** [comment]
Cheerio doesn't support extensions to HTML. I wouldn't even know what a good representation of your example in an HTML tree would look like. If you want to go through the hassle of reverting the parsing errors, you can still write your own serializer ([dom-serializer](https://github.com/cheeriojs/dom-serializer) should be a good starting point).
