### ISSUE TITLE
Incorrect innerHTML of <xmp> tag

### ISSUE THREAD

**Issue by Hurtak** [cheeriojs/cheerio#915]
It seems that content of `<xmp>` tag should not be parsed at all. 
## Code

``` js
> var $ = require('cheerio')
undefined
> $('<xmp><h2></xmp>').html()
'<h2></h2>'
```
## Current output

``` js
'<h2></h2>'
```
## Expected output

``` js
'<h2>'
```

In browser the output is `'<h2>'` (http://codepen.io/anon/pen/VjyNQN inside console)
Jsdom seems to also return this output (https://tonicdev.com/57c2990a1ac3301400487da5/57c2990a1ac3301400487da6)

**Comment by fb55** [comment]
Fixed by #985
