### ISSUE TITLE
Cheerio not finding all 'a' elements

### ISSUE THREAD

**Issue by Classy11** [cheeriojs/cheerio#916]
I have an example where Cheerio doesn't seem to select all 'a' elements when using a basic selector:

``` javascript
$('a')
```

I am not able to reproduce an example so I'll just put a link down to an existing production webpage where this issue occurs for me: http://www.vrs-uk.net/jobboard/list
After having parsed the page with Cheerio, it seems that the previously mentioned selector doesn't find the navigators at the bottom at all; eventhough they are 'a' elements and do not require client side javascript to get generated as try.jsoup.org seems to be able to find all 'a' elements just fine.

``` javascript
$('a').length // Returns the amount of hyper links available on the page minus the amount of navigator elements.
```

All help is appreciated.

**Comment by fb55** [comment]
Assuming this has been resolved!
