### ISSUE TITLE
Unexpected identifier on let statement

### ISSUE THREAD

**Issue by jordan314** [cheeriojs/cheerio#920]
In the demo code, I get unexpected identifier on the let statement. Using OS X 10.11.6 and npm 3.10.7.
`let cheerio = require('cheerio')  
SyntaxError: Unexpected identifier`

**Comment by fb55** [comment]
You are using an old version of node. Try to use `var` instead of `let`.

**Comment by ani-naslyan** [comment]
then it says require is not defined
