### ISSUE TITLE
Parsing of empty tags fails

### ISSUE THREAD

**Issue by jhbruhn** [cheeriojs/cheerio#921]
An empty tag (`<div class="peda" />`) gets transformed to just an opening tag, which completely messes up the underlying HTML.

**Comment by jhbruhn** [comment]
Fixed by using `xmlMode: true`.

**Comment by jhbruhn** [comment]
Okay, does not seem to work. This:
``` 
<p><div />peter</p>
```
automatically gets transformed to:
```
<p></p><div></div>peter<p></p>
```
which does not make any sense. Am I missing something?

**Comment by madelfresno** [comment]
Hi @jhbruhn. I had the same problem. By setting xmlMode:true, custom html elements are not opened but div element stays opened. I added a span element inside div. It worked.

**Comment by borislemke** [comment]
@madelfresno I currently need to workaround this with the same fix. But this is unacceptable as I'm building a CMS for many developers to use. It's not an option to explicitly tell people to insert a `span` element into empty `div`s.

**Comment by madelfresno** [comment]
@borislemke  I only suggested a solution that worked for me.

**Comment by fb55** [comment]
HTML doesn't support self-closing tags, XML does

**Comment by borislemke** [comment]
@fb55 what about empty tags like `<div></div>`? This also breaks the dom.

Example:
```
<div></div>
<div class="foo"></div>
```

Will be compiled to:
```
<div>
    <div class="foo"></div>
</div>
```

**Comment by meisl** [comment]
@borislemke  @fb55 That's right, empty tags like `<div></div>` are indeed rendered incorrectly by `.html()` namely as `<div/>`. This also seems to mess up the hierarchy somehow/sometimes.

`<div />` is not allowed in HTML. However, there *are* some tags that are allowed to be self-closing in HTML, e.g. `<link .../>`, `<meta .../>`, `<br/>`, ...

Hence the statement
>
> HTML doesn't support self-closing tags, XML does

is incorrect as such.

I think #1235 is related. I've posted a workaround for the false rendering of empty tags.
