### ISSUE TITLE
.append is inline - how can I get it on a new line

### ISSUE THREAD

**Issue by RonItelman** [cheeriojs/cheerio#922]
Hello, new to Cheerio, but so far it's great. I had a question about append() - whenever I use it the html is appended inline, and I'd like it to be on a new line. I've tried adding a +'\n' at the end but that hasn't worked. Any tips are appreciated. Thanks.

**Comment by fb55** [comment]
It's HTML, so try `<br>`

**Comment by RonItelman** [comment]
Adding a <br> tag would render a new line while viewing the html page in a browser. However, I want to add a new line within the html page itself. 

I would like to get (each append is a new line):
<div>appended content</div>
<div>appended content</div>
<div>appended content</div>

but I am currently getting (each append is inline):
<div>appended content</div><div>appended content</div><div>appended content</div>

**Comment by clitetailor** [comment]
May be you should try this:

```javascript
const carriageReturn = $('<text>\n</text>').contents();

$('parentNode').append([carriageReturn, yourNode]);
$('parentNode').append([carriageReturn, yourNode]);
$('parentNode').append([carriageReturn, yourNode]);

$('parentNode').append(carriageReturn);
```
