### ISSUE TITLE
Cannot read XML code with a tag name that contains a period

### ISSUE THREAD

**Issue by judocode** [cheeriojs/cheerio#925]
For example, `Web.Application` is a valid node name according to the XML spec, but `$("Web.Application")` will not return those nodes. I presume this is because the parser thinks it is html and thinks it is a tag name of `Web` with a class of `Application`.

Suggested fix: When `xmlMode: true`, do not parse as if it is html.

**Comment by fb55** [comment]
You can escape the dot: $("Web\\.Application")
