### ISSUE TITLE
[BUG], the css selector function may have somebug, anyone can explain it?

### ISSUE THREAD

**Issue by Remsh** [cheeriojs/cheerio#941]
### I want crawl some data and enncountered this problem。

Use this code:
```js
"use strict";
var cheerio = require('cheerio');
var superagent = require('superagent');
var url = "http://www.czrlzy.com.cn/aspx/htm/MarketJobs-2016111930.htm";
superagent.get(url)
    .end(function (err, sres) {
    if (err) {
        return err;
    }
    var $ = cheerio.load(sres.text, { decodeEntities: false });
    console.log($('#zph').find('#wrapper').children().length);
});
//25, totally wrong. Is it a bug?
```

### it outputs '25' definitely wrong, then I turned to use jsdom with this code :

```js
"use strict";
var cheerio = require('cheerio');
var superagent = require('superagent');
var jsdom = require("jsdom");  
var fs = require('fs');
var url = "http://www.czrlzy.com.cn/aspx/htm/MarketJobs-2016111930.htm";

jsdom.env(url, ["http://code.jquery.com/jquery.js"], function(errors, window){  
    var $ = window.$;
   	console.log($('#zph').find('#wrapper').children().length);
});`
```

### I don't know much about js and just use the functions of cheerio, is it a bug and how long can it be fixed?
best regards

**Comment by ignlg** [comment]
It seems related to #916

**Comment by bharatpatil** [comment]
For me when it loaded in browser $('a').length yielded 10 and when through cheerio, it yielded 6.
After carefully observing, I founds out that extra 4 links are added by a jquery slider plugin.

**Comment by fb55** [comment]
@bharatpatil Yes, cheerio does not execute javascript. Closing this as I assume the same is true for the original page.
