### ISSUE TITLE
Removing svg "stroke"-attributes removes "stroke-width"-attributes as well

### ISSUE THREAD

**Issue by christianvoigt** [cheeriojs/cheerio#942]
Hi,
I want to remove all stroke-attributes with "stroke=#000" from svg files. But the following line also removes all "stroke-width" attributes.

```javascript
 $('[stroke=#000]').removeAttr('stroke');
```

 Is this a bug?

**Comment by fb55** [comment]
I am unable to replicate this:

```js
const $ = cheerio.load(
  `<svg><path stroke="#000" stroke-width="2px"></path></svg>`
);
$('[stroke=#000]').removeAttr('stroke');
console.log($('svg').html());
```

**Comment by nicktoot** [comment]
I have the same bug with "stroke-linecap" and "stroke-linejoin" attributes. Is there any solution?

**Comment by 5saviahv** [comment]
I tried, but was also not able to replicate:

I took SVG exaple from [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin#miter-clip)

``` javascript
const cheerio = require('cheerio5');

const _svg = `
<svg viewBox="0 -1 10 7" xmlns="http://www.w3.org/2000/svg">
  <!-- Effect of the "miter-clip" value -->
  <path d="M1,5 l2,-3 l2,3" stroke="black" fill="none"
        stroke-linejoin="miter-clip" />

  <!-- Effect of the "miter-clip" value on a sharp angle
       where de default miter limit is exceeded -->
  <path d="M7,5 l0.75,-3 l0.75,3" stroke="black" fill="none"
        stroke-linejoin="miter-clip" />

  <!-- the following red dotted line show where the clip should happen -->
  <path d="M0,0 h10" stroke="red" stroke-dasharray="0.05"  stroke-width="0.025"/>

  <!-- the following pink lines highlight the position of the path for each stroke -->
  <g>
    <path d="M1,5 l2,-3 l2,3" stroke="pink" fill="none" stroke-width="0.025" />
    <circle cx="1" cy="5" r="0.05" fill="pink" />
    <circle cx="3" cy="2" r="0.05" fill="pink" />
    <circle cx="5" cy="5" r="0.05" fill="pink" />

    <path d="M7,5 l0.75,-3 l0.75,3" stroke="pink" fill="none" stroke-width="0.025" />
    <circle cx="7"    cy="5" r="0.05" fill="pink" />
    <circle cx="7.75" cy="2" r="0.05" fill="pink" />
    <circle cx="8.5"  cy="5" r="0.05" fill="pink" />
  </g>
</svg>`;

const $ = cheerio.load(_svg, { xmlMode: true });
console.log(`Cheerio: "v${cheerio.version}"\n`);

// Element 0
let path = $('path').eq(0);
console.log($.html(path));

path.removeAttr('stroke');
console.log($.html(path));

// Element 2
path = $('path').eq(2);
console.log($.html(path));

path.removeAttr('stroke');
console.log($.html(path));

var oo = 5;
```

results:

``` svg
Cheerio: "v1.0.0-rc.5"

<path d="M1,5 l2,-3 l2,3" stroke="black" fill="none" stroke-linejoin="miter-clip"/>
<path d="M1,5 l2,-3 l2,3" fill="none" stroke-linejoin="miter-clip"/>
<path d="M0,0 h10" stroke="red" stroke-dasharray="0.05" stroke-width="0.025"/>
<path d="M0,0 h10" stroke-dasharray="0.05" stroke-width="0.025"/>

```

**Comment by fb55** [comment]
@nicktoot Please post your code if you can!

**Comment by nicktoot** [comment]
I did logging after removing the attribute, the plugin only removes the stroke attribute, but probably there is a plugin in the task that optimizes the svg and when there is no stroke attribute it removes all dependent / children of it. So i just made it possible to edit the stroke color in css. Your plugin works well, i'm sorry :)


`
var gulp = require('gulp'),
    // svgmin = require('gulp-svgmin'),
    cheerio = require('gulp-cheerio'),
    replace = require('gulp-replace'),
    svgSprite = require('gulp-svg-sprites');


// Creating svg sprite
gulp.task('svgSprite', function () {
	return gulp.src('./src/images/svg/*.svg')
		// minify svg
		// .pipe(svgmin({
		// 	js2svg: {
		// 		pretty: true
		// 	}
		// }))
		// remove all fill and style declarations in out shapes
		.pipe(cheerio({
			run: function ($) {
        // $('[stroke]').removeAttr('stroke');
        $('[stroke]').attr('stroke', 'currentColor');
        $('[fill]').removeAttr('fill');
				$('[style]').removeAttr('style');
        $('[data-name]').removeAttr('data-name');
        $('[class]').removeAttr('class');
        $('style').remove();
        $('title').remove();
			},
			parserOptions: { xmlMode: true }
		}))
		// cheerio plugin create unnecessary string '>', so replace it.
		.pipe(replace('&gt;', '>'))
		// build svg sprite
    .pipe(svgSprite({
      mode: "symbols",
      preview: false,
      svg: {
        symbols: 'sprite.svg'
      }
    }))
    .pipe(gulp.dest('./assets/images'));
});
`

**Comment by fb55** [comment]
No worries, and thanks for confirming!
