### ISSUE TITLE
attr('attributeName',<number>) NOT WORKING...

### ISSUE THREAD

**Issue by davidhbigelow** [cheeriojs/cheerio#943]
This appears to be a very basic problem with passing numeric values to attributes.  Here is an example:

```

var $ = cheerio.load('<div>');

var myFloat = 99.99;
console.log('MY FLOAT: -->'+myFloat+'<--')
$('div').attr('shouldBeFloat',myFloat);

var myInt = 99;
console.log('MY INT: -->'+myInt+'<--')
$('div').attr('shouldBeInt',myInt);


console.log($.html());
```

RESULTS:

```
MY FLOAT: -->99.99<--
MY INT: -->99<--
<div shouldBeFloat="99.99" shouldBeInt="99"></div>

```

**Comment by fb55** [comment]
This is exactly what you'd expect from HTML; there aren't specific numeric types in HTML, so all attributes are represented the same way.

**Comment by davidhbigelow** [comment]
I will just leave this here:

http://api.jquery.com/attr/

```
**attributeName**
Type: String
The name of the attribute to set.

**value**
Type: **String** or **Number** or **Null**
```

**Comment by fb55** [comment]
That's the API's signature, but it all is rendered the same way later on :)

**Comment by davidhbigelow** [comment]
Well crap... ok I will close this out.
