### ISSUE TITLE
.prop('outerHTML') returns undefined

### ISSUE THREAD

**Issue by bill-bishop** [cheeriojs/cheerio#944]
cheerio:
`require('cheerio').load('<div></div>')('div').prop('outerHTML') // undefined`

jQuery:
`$('<div></div>').prop('outerHTML') // '<div></div>'`

i have implemented a fix which adds a switch case for 'outerHTML' in the exports.prop function within lib/attributes.js which uses the following implementation: `this.clone().wrap('<container />').parent().html()`

I will make a pull request, please let me know your thoughts.

**Comment by gajus** [comment]
> I will make a pull request, please let me know your thoughts.

Any updates on this?

**Comment by william-mcmillian** [comment]
I made the fix & PR back in November but it hasn't been pulled yet. it even raised code coverage...  you could point to a forked repo: `npm install cheerio@https://github.com/william-mcmillian/cheerio.git` until the fix is pulled into cheeriojs:master

**Comment by gajus** [comment]
This remains to be an issue.

**Comment by ash0080** [comment]
$(this).prop('outerHTML') return undefined also
