### ISSUE TITLE
Make cheerio objects monomorphic

### ISSUE THREAD

**Issue by fb55** [cheeriojs/cheerio#95]
cheerio objects are array-like objects. They have a `.length` property and hold the current set of elements as properties with numeric names.

This isn't ideal, as it's slowed down by the concept of [_hidden classes_](https://developers.google.com/v8/design#prop_access): V8 optimizes objects that have the same properties by assigning a _hidden class_ to them. When the number of properties differs, the object becomes _polymorphic_, which generally means slow(er).

The only exception are _real_ arrays, as they are expected to have varying numbers of arguments.

**Improvement**: Move the current set to a (real) array which then is assigned to a property. As a bonus, you can then use array methods inside cheerio without `.call`ing them.

**Comment by rightaway** [comment]
+1, having a regular array would be great

**Comment by fb55** [comment]
Extending arrays is pretty complicated, and would likely lead to all iteration methods returning cheerio instances again, without the options.

**Comment by rightaway** [comment]
@fb55 Would es6 proxies make it easier to implement?

**Comment by fb55** [comment]
I cannot think of a good way they can, but that doesn't mean there isn't one. Happy to hear suggestions!
