### ISSUE TITLE
setting data attributes in html not working

### ISSUE THREAD

**Issue by MiniXC** [cheeriojs/cheerio#950]
Setting a data attribute using `attr` throws `TypeError: Cannot read property 'test' of undefined`.

## Example
````
$('ul').attr('data-url', 'http://www.example.com');
````
<details><summary>Error Stack</summary>
<pre>
TypeError: Cannot read property 'test' of undefined
    at Object.$.each (D:\node\frix\lib\html-creator.js:141:39)
    at exports.each (D:\node\frix\node_modules\cheerio\lib\api\traversing.js:300:24)
    at HTMLCreator.insertContent (D:\node\frix\lib\html-creator.js:131:12)
    at HTMLCreator.resolveElements (D:\node\frix\lib\html-creator.js:56:10)
    at promises.push.access.readElement.then.template (D:\node\frix\lib\html-creator.js:113:23)
    at tryCallOne (D:\node\frix\node_modules\promise\lib\core.js:37:12)
    at D:\node\frix\node_modules\promise\lib\core.js:123:15
    at flush (D:\node\frix\node_modules\asap\raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
</pre>
</details>

**Comment by fb55** [comment]
Could you provide some more context?

```js
require('cheerio')('<div>').attr('data-url', 'http://www.example.com')
```

works as expected for me.

**Comment by weijarz** [comment]
@fb55 
```js
let cheerio = require('cheerio')
let $ = cheerio.load('<h2 class="title" data-foo=bar>Hello world</h2>')
$('h2').data('foo') // 'bar'
$('h2').data('foo', 'newbar')
$('h2').data('foo') // 'newbar'
$('h2').attr('data-a', 'b')
$.html() // '<h2 class="title" data-foo="bar" data-a="b">Hello world</h2>'
```

The `data-foo` attr in html() output is still the old value 'bar'.

**Comment by fb55** [comment]
@weijarz This is explicitly wanted. The data method does not interfere with data attributes, use attr to archieve that.

**Comment by jcrben** [comment]
@fb55 seems like you could close this issue?

**Comment by fb55** [comment]
@jcrben Thanks a lot for the offer! I agree that this can be closed, just wanted to wait for a possible answer.

We should definitely have an easier onramp for people that want to help. For now I've tagged some PRs with [Review](https://github.com/cheeriojs/cheerio/pulls?q=is%3Apr+label%3AReview+is%3Aopen), would be great if you could have a look at them. (Looking through the issues is also an immense help, but potentially not super exciting.) Happy to help if there is something else you would be interested in working on!

**Comment by drsnyder** [comment]
I was also tripped up by this. According to the [documentation](https://github.com/cheeriojs/cheerio#data-name-value-), one would think that setting data attributes is possible with `data`.

The snippet for `data()` reads:

> Method for getting and setting data attributes. Gets or sets the data attribute value for only the first element in the matched set.

So I was surprised when `element.data('key', 'value')` doesn't change the value.

**Comment by garyee** [comment]
@drsnyder even if it says something else in the documentation, it is standard jquery behavoir, took me some time to figure out.
