### ISSUE TITLE
decodeEntities will escape href's of a tags

### ISSUE THREAD

**Issue by wisko** [cheeriojs/cheerio#960]
If an A-tag href attribute includes parameter names that are valid, but with unfortunate names, they get html-decoded by cheerio.

Example:

```javascript
require('cheerio').load('<a href="/?param=value&reg_number=123">')('a').attr('href');
```
will output:
```javascript
/?param=value®number=123
```

Either the bug lies in `&reg_` getting the same treatment as `&reg;`, or perhaps the href attribute shouldn't be decoded at all.

If the load() option `decodeEntities` is set to `false` this does not happen, so perhaps this bug lies in a cheerio dependency?

**Comment by ioanb7** [comment]
https://github.com/cheeriojs/cheerio/issues/720
is this fixing it?

**Comment by fb55** [comment]
This is actually in-line with browser behavior 😄
