### ISSUE TITLE
Selector missing or skipping elements

### ISSUE THREAD

**Issue by ignlg** [cheeriojs/cheerio#963]
HTML
```html
<ul class="media-list">
  <li class="media">
    <span>
      <div class="inner">
        <ul class="item-singular">
          <li class="item">
           <div class="item-icon"></div>
           <span class="tag"><i class="fa fa-tag"></i> tag</span>
          </li>
        </ul>
      </div>
    </span>
    . . .
  </li>
</ul>

```
Cheerio:
`$(html).find('li.item').length` => `0`
`$(html).find('ul li.item').length` => `N`

It seems that it doesn't parse deeper if a parent element partially matches the selector, but it's just a guess.

**Comment by ignlg** [comment]
Could be related to #941 and #916

**Comment by MCTaylor17** [comment]
I couldn't replicate this.  

```js
var html = `<ul class="media-list">
  <li class="media">
    <span>
      <div class="inner">
        <ul class="item-singular">
          <li class="item">
           <div class="item-icon"></div>
           <span class="tag"><i class="fa fa-tag"></i> tag</span>
          </li>
        </ul>
      </div>
    </span>
  </li>
</ul>`;
console.log("test1:", $(html).find("li.item").length);   // test1: 1
console.log("test2:", $(html).find('ul li.item').length); // test2: 1
```

**Comment by ignlg** [comment]
The html code was a simplification of the original one, I'll try to clean it up a little less and paste/share it here again. Thanks for the feedback @MCTaylor17 :)

**Comment by jugglinmike** [comment]
@ignlg Any chance you could get us that sample HTML? I'd love to fix this problem, whatever it is.

**Comment by ignlg** [comment]
@jugglinmike Sorry for my late reply. I tried to reproduce it with a test but couldn't. The project I was working on is discontinued and I cannot run it again to watch the issue in production. As I use cheerio really often, I'll keep an eye on this issue. Thanks for your help :)
