### ISSUE TITLE
text function returns empty string when selector doesn't match any elements

### ISSUE THREAD

**Issue by rightaway** [cheeriojs/cheerio#965]
The `text` function returns empty string when selector doesn't match any elements. It should return `null` instead.

**Comment by jugglinmike** [comment]
This project tracks the behavior of the jQuery library, and [the functionality in this case is documented on that project's website](https://api.jquery.com/text/):

> The result of the `.text()` method is a string containing the combined text of all matched elements.

In the case of an empty selection, "a string containing the combined text of all matched elements," is the empty string, not the null value.
