### ISSUE TITLE
Way to get text without other elements

### ISSUE THREAD

**Issue by rightaway** [cheeriojs/cheerio#968]
There seems to be no way to get just the text `BEFORE` in this case. I tried `$('outer').not('inner').text()` but it returns all the text within `outer` and `inner` tags. It would be useful to support this case.

```html
<outer>
  BEFORE
  <inner>INNER</inner>
  AFTER
</outer>
```

**Comment by MCTaylor17** [comment]
I think it works pretty similar to [how you would do it in jQuery](https://api.jquery.com/contents/).  Try:

```js
	var $outer = $("outer").contents().filter(function() {
		return this.nodeType === 3;
	});
	
	$outer.each(function() {
		console.log($(this).text());
	});
```

**Comment by jugglinmike** [comment]
@MCTaylor17's suggestion looks good to me!
