### ISSUE TITLE
EQ in selector not working

### ISSUE THREAD

**Issue by TonySchu** [cheeriojs/cheerio#969]
I want to get this complex path:
`$("body > div#layout_main > div#layout_main_content_new > div#layout_content > div#layout_mid > div:eq(1) > div:eq(1) > div:eq(0) > table > tbody > tr:eq(0) > td:eq(2)").text()`

This will give me the error: "unmatched pseudo-class :eq".

I read that it is possible to use eq in another way, but I do not know how to use it in a complex path like this.

Any tips on this? I really like your packe and want to stick with it.
Thanks for the good work!

**Comment by fb55** [comment]
Just replace `:eq` with the `.eq` method and continue your path the same way using `.find`. (Selectors in cheerio can also start with `>`.

**Comment by TonySchu** [comment]
Thanks, and sorry for the redundant issue!
