### ISSUE TITLE
Cheerio on the client side

### ISSUE THREAD

**Issue by mitar** [cheeriojs/cheerio#974]
I would really love if Cheerio could work on the client side. Because parsing with jQuery has side effects. If I do `$('<img src="http://evil.com"/>')`, browser will make a request to `evil.com`. With Cheerio, I could parse this HTML string and this would not happen.

**Comment by fb55** [comment]
It does, just use a bundler like Browserify or Webpack :)

**Comment by skirankumar7** [comment]
are there any other packages work like cheerio on the client side?
