### ISSUE TITLE
SVG animate children are not rendered correctly

### ISSUE THREAD

**Issue by kraf** [cheeriojs/cheerio#975]
I want to create

```html
<circle ...>
  <animate ... />
</circle>
```

and I put it as a string into the $ function in cheerio, but when i call then `html` method on it, it places `<animate>` next to `<circle>`, not as a child. I guess it mistakenly assumes that `<circle>` can not have any children.

**Comment by inikulin** [comment]
Do you use `xmlMode` to parse these string. Note that HTML doesn't support self closing tags, unless they are not wrapped in `<svg>` or `<math>`.

**Comment by kraf** [comment]
I tried it with `xmlMode` but it breaks my html output. My elements are wrapped inside `<svg>` though, I really feel it should work. If I load a working svg animation and use `$.html()` to write it out, it's structure is changed and the animation is not working anymore.

It's changing

```html
<circle ... >
    <animate ... />
</circle>
```

to 

```html
<circle ... ></circle>
<animate ... ></animate>
```

**Comment by shunchen-yang** [comment]
I also met this issue. <rect ... ><animate ... /></rect> changed to <rect/><animate/>.
It should be a bug obviously.

**Comment by fb55** [comment]
This should be resolved with the latest release.
