### ISSUE TITLE
Builds succeed even if test don't pass

### ISSUE THREAD

**Issue by koenpunt** [cheeriojs/cheerio#977]
As can be seen at #976, where the commit is marked with a check. But if you follow the link to Travis, you'll see that the tests did not pass: https://travis-ci.org/cheeriojs/cheerio/jobs/200843828

**Comment by jugglinmike** [comment]
Nice catch, and thanks for the report! I've opened gh-978 to address the issue.

**Comment by fb55** [comment]
Fixed in #978
