### ISSUE TITLE
Error with pseudo-element

### ISSUE THREAD

**Issue by tscanlin** [cheeriojs/cheerio#979]
I get this error trying to parse normalize.css:

```
TypeError: Rules[rule.type] is not a function
    at /node_modules/css-select/lib/compile.js:101:26
    at Array.reduce (native)
    at compileRules (/node_modules/css-select/lib/compile.js
```

It seems that rule.type of `pseudo-element` isn't in the Rules map.

Love the library though, thanks for making cheerio!

**Comment by fb55** [comment]
Pseudo-elements aren't supported by the selector library. Do you have a specific use-case in mind?

**Comment by tscanlin** [comment]
No worries, I can work around this fairly easily.

I am currently working on a project called css-razor (https://github.com/tscanlin/css-razor) that uses cheerio and postcss to parse html strings and css files to find all of the used selectors so it can remove any unused selectors. It works pretty well except with normalize.css / tachyons that have some weird pseudo selector rules.

It seems like adding support for pseudo selectors wouldn't be too difficult but it also looks like it might actually be an issue with css-select and not cheerio directly. Feel free to close this issue, but I really appreciate your response. I can only imagine what its like trying to maintain a project with 11K+ stars on github. Thank you so much for creating cheerio! It's awesome and super fast :)

**Comment by fb55** [comment]
The way that jQuery supports it won't help you either here, as it will always return an empty set for pseudo-elements (which is jQuery's default behaviour for faulty selectors).

I've opened https://github.com/fb55/css-select/issues/82 to at least provide a more helpful error message regarding the lack of support for pseudo-elements.
