### ISSUE TITLE
Unable to iterate over elements returned by toArray()

### ISSUE THREAD

**Issue by callmekatootie** [cheeriojs/cheerio#981]
[Runkit link for testing the code](https://runkit.com/callmekatootie/testing-cheerio-xray)

After running a couple of functions namely `map()` and `filter()` I store the result in a variable and then use `toArray()` on that variable to get an array of the DOM elements.

Next, I try to loop over the elements but I find that the loop runs only once and not 300+ times, as expected from an array with over 300+ elements.

I have a feeling I am making a wrong assumption about the array properties of the return values from the earlier functions but I am not sure what it is. Any hints as to why the loop runs only once and not 300+ times, even though the length of the array is 300+

**Comment by jugglinmike** [comment]
Your code looks valid, and I've just run it locally and verified the expected
result--the string starting "I appear to" was printed to the screen the
appropriate number of times.

I recommend reducing this case further. First, capture the markup returned by
the `xray` library. Then begin paring it down to make it as simple as possible.
If you can share that, it will reduce the variability between our environments
and will give us a better chance of diagnosing the problem.

In addition, remember that some developer tools consolidate identical lines
when they are printed in rapid succession. To guard against this, try
concatenating the string with the value of the second parameter of the function
provided to `forEach`.

**Comment by callmekatootie** [comment]
Closing the ticket. The issue appeared to be the consolidation of the identical lines.
