### ISSUE TITLE
how to handle when someone searches page 1 and the current page goes to page2 and we wanna select items on page 2 ?

### ISSUE THREAD

**Issue by jpca999** [cheeriojs/cheerio#982]

**Comment by jugglinmike** [comment]
It sounds like you are working with a document that lists paginated results. If you'd like to work with the data on some other page, you can use Cheerio to scrape the current page for the appropriate URL, fetch the HTML for that document using the core `http` module (or a third-party  module like `request`), and then feed that into Cheerio via the `load` method. Good luck!
