### ISSUE TITLE
TypeError: $(...).click is not a function |    $('.btnPrimary').click();   doesnt work ?

### ISSUE THREAD

**Issue by jpca999** [cheeriojs/cheerio#983]
$('.btnPrimary').click();   doesnt work ?

can't it load second page after clicking on a button ?

**Comment by rickyblaha** [comment]
Cheerio is a parser, it won't actually execute any javascript. If you really need to do that try https://github.com/ariya/phantomjs/. Or you could use cheerio to scape the `href` (or similarly named) attribute on the button that might contain the second page's URL, then load the second page with a new cheerio.

**Comment by jugglinmike** [comment]
@rickyblaha is correct (thanks for helping out, Ricky).
