### ISSUE TITLE
can't i use simple jquery functions ?   like  phone   = $(".phone:first").html()

### ISSUE THREAD

**Issue by jpca999** [cheeriojs/cheerio#984]
why does it gives me an errror for this ?

![image](https://cloud.githubusercontent.com/assets/1026325/23173458/35c84dca-f827-11e6-9cab-42ce3776e138.png)

**Comment by regaw-leinad** [comment]
I'm sure the author would love it if you did a quick search first.  Please refer to https://github.com/cheeriojs/cheerio/issues/408

**Comment by fb55** [comment]
Thanks @regaw-leinad for the reference!
