### ISSUE TITLE
.text() includes text within <script> and <style>

### ISSUE THREAD

**Issue by Vittoriourzi** [cheeriojs/cheerio#986]
cheerio .text() not strip inline style and scripts.
If i perform a $("html").text() for strips all tags, the script include in text the textual content inside the inline script.

example of an html.

```html
<html><head></head><body>
<div>ciao</div>
<script>function(){blablabla}</script>
</body></html>
```

if a do: $("html").text() the ouput will be:
ciao function(){blablabla}

But in jQuery the inline tags were strip and removed too!

**Comment by henrix343** [comment]
@Vittoriourzi does cherio suport innerText ?

**Comment by matthewmueller** [comment]
This is currently implemented, but may be reverted. See: https://github.com/cheeriojs/cheerio/issues/1050
