### ISSUE TITLE
Question about Unit Test

### ISSUE THREAD

**Issue by zhenyulin** [cheeriojs/cheerio#989]
I'm relatively new to this, and currently using cheerio in the development of a scraper. Since I'm a big fan of TDD, I was wondering if there's any good framework/tool/method for creating unit test for cheerio or this kind of scraper? It looks like there will be a whole lot of stub/mockup. It would be great if someone can share some of the experience here. Thanks!

**Comment by jugglinmike** [comment]
Personally, I would recommend [Mocha](https://mochajs.org/). It has no Cheerio-specific functionality, but as a general-purpose JavaScript unit testing framework, it provides the features you would need to keep your tests concise (such as setup/teardown functions). Good luck!
