### ISSUE TITLE
prop('childNodes') returns undefined

### ISSUE THREAD

**Issue by gajus** [cheeriojs/cheerio#993]
`node.prop('childNodes')` returns `undefined`, though `node[0].childNodes` works as expected. Shouldn't the former just return the latter?

**Comment by jugglinmike** [comment]
It sure seems that way. Thanks for the report!

**Comment by wahajdar** [comment]
hi @jugglinmike, seems like getProp(...) in api/attributes.js validates if the element has a direct property, result in ignoring those inherited from prototype chain. 
![25ccceb17d8dbd1f5183e756a70dc768](https://user-images.githubusercontent.com/25760541/36563888-5455b886-183d-11e8-8481-aac6a439ab68.png)

Please check.
Thanks

**Comment by fb55** [comment]
Fixed in #1146
