### ISSUE TITLE
cheerio.load('<a href="foo"></a>').root().attr('href') gives undefined

### ISSUE THREAD

**Issue by gajus** [cheeriojs/cheerio#994]
I expect to get the "foo" value.

**Comment by gajus** [comment]
I see. For this to work I need to do:

```js
cheerio.load('<a href="foo"></a>').root().find('a').attr('href');

// or simply cheerio.load('<a href="foo"></a>').attr('href');
// though that creates other problems for me
```

**Comment by dbrezoev** [comment]
How would you do this if you have body loaded and css selector for the <a> tag. For example: 
`var $ = cheerio.load(body);
var selector = '#link';
var hrefValue = $(selector).attr('href');
`
I get undefined.

In the body I have the 'a' tag: <a id='link' href='http://facebook.com/'>Faceboook link</a> 
Thanks in advance.

**Comment by rohitnairtech** [comment]
> hrefValue

Same issue here

**Comment by hox** [comment]
Did this ever get fixed?
