### ISSUE TITLE
Wait for Loading Scripts

### ISSUE THREAD

**Issue by bifot** [cheeriojs/cheerio#996]
I have page, which content generating by JavaScript and cheerio can't display that content because it's didn't wait for loading JS scripts.

How I can fix it? Maybe something like in jQuery **$(document).ready()**?

Thanks a lot.

**Comment by jugglinmike** [comment]
Cheerio operates on static markup only, making it a poor choice for use cases that depend on dynamic script evaluation. See [the project's `Readme.md` file](https://github.com/cheeriojs/cheerio/blob/master/Readme.md) for more on the best uses of this library (and suggestions for alternatives).
